### PR TITLE
Correctly sort absurdly large numbers

### PR DESCRIPTION
**Pull request by AngryGamer**
@donho I see you enjoy sorting absurdly large numbers. 😜

This adds sorting support for numbers which are 18446744073709551615 characters long. 

----------------------------------------------
Input
```
192.00000000000
192.000000000000
192.380000000
192.283000000
192.2800000000
192.380000000000000000000000000000000000000000000000000000000000000000000000
192.283000000000000000000000000000000000000000000000000000000000000000000000
192.2800000000000000000000000000000000000000000000000000000000000000000000000
192.0000000000000000000000000000000000000000000000000000000000000000000000000000000000

192.00000000000
192.000000000000
192.0380000000
192.00283000000
192.002800000000
192.0380000000000000000000000000000000000000000000000000000000000000000000000
192.00283000000000000000000000000000000000000000000000000000000000000000000000
192.002800000000000000000000000000000000000000000000000000000000000000000000000
192.0000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
Now run _**Line Operations->Sort Lines As Integers Ascending**_

Patch Output _(correct)_
```

192.00000000000
192.000000000000
192.0000000000000000000000000000000000000000000000000000000000000000000000000000000000
192.00000000000
192.000000000000
192.0000000000000000000000000000000000000000000000000000000000000000000000000000000000
192.283000000
192.00283000000
192.380000000
192.0380000000
192.2800000000
192.002800000000
192.283000000000000000000000000000000000000000000000000000000000000000000000
192.00283000000000000000000000000000000000000000000000000000000000000000000000
192.380000000000000000000000000000000000000000000000000000000000000000000000
192.0380000000000000000000000000000000000000000000000000000000000000000000000
192.2800000000000000000000000000000000000000000000000000000000000000000000000
192.002800000000000000000000000000000000000000000000000000000000000000000000000
```

Latest Git Output _(incorrect: first 6 lines & last 6 lines)_

```

192.00000000000
192.000000000000
192.00000000000
192.000000000000
192.0000000000000000000000000000000000000000000000000000000000000000000000000000000000
192.0000000000000000000000000000000000000000000000000000000000000000000000000000000000
192.283000000
192.00283000000
192.380000000
192.0380000000
192.2800000000
192.002800000000
192.002800000000000000000000000000000000000000000000000000000000000000000000000
192.00283000000000000000000000000000000000000000000000000000000000000000000000
192.0380000000000000000000000000000000000000000000000000000000000000000000000
192.2800000000000000000000000000000000000000000000000000000000000000000000000
192.283000000000000000000000000000000000000000000000000000000000000000000000
192.380000000000000000000000000000000000000000000000000000000000000000000000
```

### CODE REVIEW

**Comment by AngryGamer** [comment]
Another test, which verifies it's working properly.

**_Test data_**
```
192.000000000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00000002812345678912345678912345678912345678912345678912345678912345678912345678
192.0000002812345678912345678912345678912345678912345678912345678912345678912345678
192.000002812345678912345678912345678912345678912345678912345678912345678912345678
192.00002812345678912345678912345678912345678912345678912345678912345678912345678
192.0002812345678912345678912345678912345678912345678912345678912345678912345678
192.002812345678912345678912345678912345678912345678912345678912345678912345678
192.02812345678912345678912345678912345678912345678912345678912345678912345678
192.2812345678912345678912345678912345678912345678912345678912345678912345678
```

Input into [https://www.random.org/lists/](https://www.random.org/lists/)

Take output and sort in Npp **_Line Operations->Sort Lines As Integers Ascending_**

Results should be unchanged, which shows proper equivalence despite using segments of 18.

**Comment by donho** [comment]
I've tried the following sequences:
```
192.00000000000
192.1000000000000
192.00000000000
```
and it doesn't sort.

**Comment by donho** [comment]
I thought about the bn (big number) library for accurate result, then I told my self why add an overhead and dependency for such rare used small feature?
So I guess the same argument for this pr - it doesn't worth to take risk of regression  for such rare used small feature. Let's keep the original implementation.

**Comment by AngryGamer** [comment]
@donho 

> I've tried the following sequences:

The bug was a basic unsigned to signed conversion mistake. compareResult is signed. compareResult was assigned the overflowed results of two unsigned variables being subtracted. This was [fixed](https://github.com/AngryGamer/notepad-plus-plus/commit/afeb97d5d37886b039a8c57124b09a9ea21fad1f#diff-4608be755b00f4ec444233203ee8eafcR188) by converting the variables to signed with static_cast prior to subtracting.

> So I guess the same argument for this pr - it doesn't worth to take risk of regression for such rare used small feature. Let's keep the original implementation.

I don't like leaving bugs for users to unexpectedly hit when basic fixes with negligible performance penalty are available.

I understand every change runs risks of regression, but at this point I think the risks with this PR are negligible.

With that said, whether to fix it or even how to fix it is your decision.

**Pull request closed without merging**
