### PR TITLE
Update Turkish translation

### PR DESCRIPTION
**Pull request by Tmp341**
- Trying to fix my errors made before #4336.

But tested directly, no luck. At least this fixes errors i've made.

### CODE REVIEW

**Comment by SinghRajenM** [comment]
Line [473](https://github.com/Tmp341/notepad-plus-plus/blob/016bb0adff49f82f6b7b2a93d1a597cef67e5b6d/PowerEditor/installer/nativeLang/turkish.xml#L473) also requires fix

```                <Item id="1" name=Tamam"/>```

**Comment by Tmp341** [comment]
Still not working. What is wrong with this?

**Comment by rddim** [comment]
Remove the space between `&amp;` and `Unix` at line 739 if you want to use <kbd>Alt</kbd>+<kbd>U</kbd> for enable/disable

**Comment by donho** [comment]
By using the following command, I've an error:
```
$ git checkout -b Tmp341-patch-1 master
fatal: A branch named 'Tmp341-patch-1' already exists.
```
You should create a new branch for a new PR instead of using the old branch.

**Pull request closed without merging**
