### PR TITLE
Update of Ukrainian lang

### PR DESCRIPTION
**Pull request by stenox**

### CODE REVIEW

**Comment by milipili** [comment]
Are you sure about the file encoding ?

**Comment by Croydon** [comment]
Unicode should be the way to go :)

**Comment by stenox** [comment]
Actually, unicode doesn't work.
But I've already done big update with encoding changing on my next pull request #231

**Comment by milipili** [comment]
UTF-8 should be used.

**Comment by stenox** [comment]
I know, but it doesn't...
Even if I change the locale in program settings - nothing's happened.
Ukrainian locale in the current version of Notepad ++ couldn't be activated.
Just try to do it and you'll see.

**Comment by milipili** [comment]
From now on, only utf-8 is accepted for translations (and for simple translation updates please provide a single commit). If it does not work for some reasons, please fill up a bug report

**Comment by Tmp341** [comment]
I've tried Russian language, it seems working for me. Want me to try Ukranian?

**Pull request closed without merging**
