### PR TITLE
Revert "Update uchardet to 0.0.6 to improve UTF-8 detection quality"

### PR DESCRIPTION
**Pull request by CookiePLMonster**
There are numerous issues (such as #5126) outlining that updating uchardet, although fixed numerous issues, has introduced new ones.

Since this seems to be a uchardet issue, I think it's safest to revert the update for the time being.

**DISCLAIMER: I have not tested if this revert fixes the regressions reported. I only verified that compilartion succeeds.**

### CODE REVIEW

**Comment by MetaChuh** [comment]
thanks @CookiePLMonster 

> DISCLAIMER: I have not tested if this revert fixes the regressions reported. I only verified that compilartion succeeds.

if this eases you: i have tested a few of the utf-8 files that have been submitted to us at community level as not being detected correctly since 7.6.
(selection of french, german, russian and japanese files)

all files i've tested so far are detected correctly as utf-8 in a 7.6.4 build with your regression.
i will test all of the submitted files and text fragments as soon as i have time.

ps: if you have any files that would not be detected correctly on the old code, please upload them here, or post them at the community. i'd appreciate as much as possible i can test with. 

@donho 

what is the reason for the suspension ?

**Comment by Faq** [comment]
I think thiss issue should be fixed with uchardet and therefore reported to them, but seeing that project looks abandoned, should be used some other "encoding detector library".

**Comment by MetaChuh** [comment]
@Faq 

> I think thiss issue should be fixed with uchardet and therefore reported to them, but seeing that project looks abandoned, should be used some other "encoding detector library".

it is more complicated.
submitting an issue about that at freedesktop.org will be to no avail, as their answer will be: "don't compile uchardet 0.0.6 on windows". 😉

uchardet 0.0.6 runs as perfect as it can get, when compiled and run in linux.
but the uchardet 0.0.6 code behaves **completely different and erratic**, when **compiled on windows**.

as a simple test we (me and other external devs) compiled the command line uchardet tool, using
the same, identical 0.0.6 source code on multiple platforms (mac, windows, linux).
we all got the same result, that it produces erratic results **only** when compiled on **windows**.
(in short words: it works as expected on all operating systems, except windows)

so far, no one of us, or others, have managed to adapt the 0.0.6 source code for windows, mainly because of lack of coding experience on windows platforms.

note: @vlakoff also played around with the nightly releases of uchardet, to try out if it gets any better, and his test results were even worse than 0.0.6, when compiled on windows ... **and only on windows !!!**

@donho 

thanks for the update of the conflict with nsUniversalDetector.cpp as reason for the suspending.
i have not yet been able to find any issue this rollback might cause.
can you be more specific, so that i can reproduce what you have found ?

in the meantime we will give the usual workaround answer (disable autodetect character encoding) to all users, at it is currently the only working way.
but i beg you to at least disable it as default setting, as requested before, as long as this issue is not solved.

ps: i guess you have a lot of other things to worry about at the moment, but keep in mind that you would help us a lot with this issue, as we at the community, are the ones who are answering probably most of all reports about this.

**Comment by MetaChuh** [comment]
@donho

here's another incident about the same issue from today.
do you see the need to prioritise this issue, or is it just us ?

https://notepad-plus-plus.org/community/topic/17298/problem-with-utf-files-with-polish-characters

ps: are my usual sentences too long ? 😉

**Comment by donho** [comment]
The newest release of uchardet fix some bugs
There is a new merge for fixing polish problem in this project, don't you think we can patch only this release @CookiePLMonster ?

@MetaChuh Do we know what are the regressions ?

**Comment by Faq** [comment]
Did anyone reported this to ucardet project? And can link it here?

**Comment by MetaChuh** [comment]
@donho 

> Do we know what are the regressions ?

yes. we have been submitted an elevated amount of issue reports since 7.6, that files are not correctly autodetected in notepad 7.6 and above.

all test files and text samples, that have been passed to us since then, are autodetected correctly on 7.5.9 or below, but not on 7.6 and above.

all test files we have been submitted by users at the issue tracker and at the community regarding this issue, are autodetected correctly on the old 7.5.9 autodetection code (but not on 7.6 and above)

note: this issue has leaded to corrupted files, on cases where the user was not aware of that,
because when they reopened a utf-8 file, with e.g. french, german, russian, or other localized characters, and the file was wrongly recognized as e.g. windows-1258 (vietnamese), any editing/adding of more text with special characters in that different encoding, had mixed up the original encoding.

please tell me if you want me to break down any further specific information from the issue tracker, the community, or the testing results, to your needs.
i will summarise everything you tell me to, in order to keep it as short as possible.

any further tests you want me or us to conduct, will be tested exactly to your specifications, and re-tested if we already have results on them.

many thanks and best regards.

**Comment by donho** [comment]
@MetaChuh 

Could you provide me ALL the files (one per language) which work in 7.5.9 but not in 7.6.4 please ?
If there's no sample file, the link of bug report is good as well.
My intention is to know how many languages are impacted by this issue.
Thank you.

**Comment by MetaChuh** [comment]
@donho 

here is the first set of submitted files and snippets for testing.
(french, german, polish, turkish)

all files are utf-8.
all files will be correctly detected as utf-8 in notepad++ 7.5.9.
all files will be incorrectly detected in notepad 7.6.x.

i have named the files, including the info `detected as [encoding]` in all names, for your convenience while testing and switching between 7.5.9 and 7.6.4:

```
06.01.2019  17:10        12 fra, utf-8, detected as windows-1258 (Réservation).txt
04.01.2019  20:13     1.844 fra, utf-8, detected as windows-1258 (paquet-111404).xml
06.01.2019  17:27         6 fra, utf-8, detected as windows-1258 (était).txt
18.03.2019  15:34        23 ger, utf-8, detected as iso 8859-7 (ü monika lobinger).txt
18.03.2019  15:43       136 tur, utf-8, detected as iso 8859-1 (Kullanılabilir).php
06.01.2019  17:27         9 fra, utf-8, detected as windows-1258 (mosaïque).txt
18.03.2019  14:59       233 pol, utf-8, detected as windows-1252 (DABBB).txt
13.02.2019  07:11        11 ger, utf-8, detected as windows-1250 (Österreich).txt
28.12.2018  11:20       894 fra, utf-8, detected as windows-1258 (paquet-1).xml
```

**important note:**
once the character encoding is incorrectly detected, the users also **can not** change the encoding at the menu `encoding > encode in utf-8` on any of these files, when using notepad++ 7.6 or above !
if tried to set the encoding to utf-8 or anything else, the encoding selection bullet will jump back to it's automatically detected, wrong encoding on notepad++ 7.6 or above.

[utf-8 test files for autodetect character encoding.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2978799/utf-8.test.files.for.autodetect.character.encoding.zip)

i will add more files if you need them, as soon as i have time to collect them from the issue tracker, the community forum and stack exchange/overflow.

**Comment by Ekopalypse** [comment]
Not sure if this helps identifying the culprit but after adding a second instance of the word containing
the unicode char every file, except the turkish one, has been reported as utf8 encoded. For the turkish
file it was needed to have a third instance of Kullanılabilir to be deteced as utf8.
Strange, that on windows there is a need to have more than one instance of unicode chars (at least for those examples) where as on linux and mac a single instance is detected correctly.

**Comment by MetaChuh** [comment]
we've just received the first **pure english** autodetect issue file today. ( https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5440 )
in this **english** .ini file, the presence of a single `¦` triggers a detection as iso 8859-9 (**turkish**).

i have named the file descriptive as:
`eng, utf-8, detected as iso 8859-9 (#5440 notepad++_.ini_bug).ini`
and attached it as a zip below. (zip to preserve full name and time stamp)

download: [eng, utf-8, detected as iso 8859-9 (#5440 notepad++_.ini_bug).ini.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2985429/eng.utf-8.detected.as.iso.8859-9.5440.notepad%2B%2B_.ini_bug.ini.zip)

i'm at your command if you need anything else (except if you need a [lamborghini urus](https://www.lamborghini.com/fr-en/modèles/urus) 😉)

**Reference Tags:** https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfb7e863cc6cd20f9f32389bee289607a212b12b , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5299 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5310 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5202 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5440

**Comment by MetaChuh** [comment]
@donho 

any short news ?

* [ ] accept
* [ ] close
* [ ] ignore/minor relevance
* [ ] need more time
* [ ] other

**Comment by donho** [comment]
@MetaChuh 
Sorry for not processing this issue earlier, I'm always racing with the time as you know already...
Thank you very much for your very detail report. It seems to me the reverting is inevitable.
The revert result will be in v7.6.5 for sure.
Thank you again for your help!

**Comment by MetaChuh** [comment]
@donho 
thank you a thousand times.
it's me who has to apologise for making so much pressure.

i was in panic, because my brain was imagining what could possibly happen if a user is careless.
e.g. editing mysql dumps and re-uploading them untested to the server, deploying possibly corrupted text, or worse unrecognisable custom separator characters.

much appreciated as always and sorry for producing so much additional stress.

**Comment by donho** [comment]
@MetaChuh 
Don't be sorry. You are the last person who should be sorry.

**Pull request closed without merging**
