### PR TITLE
function list: Perl function regex update

### PR DESCRIPTION
**Pull request by yuzhy8701**
Fixing the issue #4265

### CODE REVIEW

**Comment by donho** [comment]
We need uni-test for function list firstly.
I will make it happen as soon as I can.

**Comment by pryrt** [comment]
Hey, @donho : according to 3aaf083, you made the unit-test functionality in April of 2018.  Apparently, this still-open PR that was waiting for unit-test was lost in the shuffle.  Do you think you could incorporate it?

**Comment by donho** [comment]
@pryrt  Sure, the unit tests will be used manually in this PR. I've done a PR for the steps of its usage in npp-usermanual:
https://github.com/notepad-plus-plus/npp-usermanual/pull/106
If you could review this PR please.

**Comment by donho** [comment]
@yuzhy8701  I've got `unknown repository` so I can not test your code - could you fix that?

**Comment by chcg** [comment]
@donho unknown repository means the fork the PR was created from is deleted in the meantime.

**Comment by pryrt** [comment]
You can still get access to the whole file using the **Files changed > ... > View File > Raw** sequence, which leads to [this link](https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/4693efd722effe6afc5e9a7bc0940fa43506eb6d/PowerEditor/src/functionList.xml), so it could be manually checked.

But if you'd rather, I could grab a copy of the new regex from there, you could "reject" this PR, and tonight or this weekend I could submit a new PR which starts from the most recent functionList.xml but makes the same fix to the Perl function regex.

**Comment by donho** [comment]
@pryrt Thank you, it's OK. It's rather to keep the contributor's name in the repository.

**Pull request closed without merging**
