### PR TITLE
Read Windows environment variables correct also for unix-like shell

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10885.

@donho I accidentally created a [new branch](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/ArkadiuszMichalski-patch-1) in the main repo, can you delete it?
Edit: I found how to do it and remove it now.

### CODE REVIEW

**Comment by donho** [comment]
To build 32 bit under Git Bash, I've got indeed the following result: 
```
$ mingw32-make.exe
makefile:79: *** i686 build requires "%windir%/system32/SensApi.dll" to be present.  Stop.
```

However, after applying this PR, the result is:

```
$ mingw32-make.exe
bin.x86_64 bin.x86_64.build gcc-fixes.h makefile manifest.rc creating BUILD_DIRECTORY bin.i686.build
process_begin: CreateProcess(NULL, C:/ Files/Git/usr/bin/mkdir.exe -p bin.i686.build bin.i686.build/DarkMode bin.i686.build/MISC/Common bin.i686.build/MISC/Exception bin.i686.build/MISC/PluginsManager bin.i686.build/MISC/Process bin.i686.build/MISC/RegExt bin.i686.build/MISC/md5 bin.i686.build/MISC/sha2 bin.i686.build/ScintillaComponent bin.i686.build/TinyXml bin.i686.build/TinyXml/tinyXmlA bin.i686.build/WinControls/AboutDlg bin.i686.build/WinControls/AnsiCharPanel bin.i686.build/WinControls/ClipboardHistory bin.i686.build/WinControls/ColourPicker bin.i686.build/WinControls/ContextMenu bin.i686.build/WinControls/DockingWnd bin.i686.build/WinControls/DocumentMap bin.i686.build/WinControls/FileBrowser bin.i686.build/WinControls/FindCharsInRange bin.i686.build/WinControls/FunctionList bin.i686.build/WinControls/Grid bin.i686.build/WinControls/ImageListSet bin.i686.build/WinControls/OpenSaveFileDialog bin.i686.build/WinControls/PluginsAdmin bin.i686.build/WinControls/Preference bin.i686.build/WinControls/ProjectPanel bin.i686.build/WinControls/ReadDirectoryChanges bin.i686.build/WinControls/SplitterContainer bin.i686.build/WinControls/StaticDialog bin.i686.build/WinControls/StaticDialog/RunDlg bin.i686.build/WinControls/StatusBar bin.i686.build/WinControls/TabBar bin.i686.build/WinControls/TaskList bin.i686.build/WinControls/ToolBar bin.i686.build/WinControls/ToolTip bin.i686.build/WinControls/TrayIcon bin.i686.build/WinControls/TreeView bin.i686.build/WinControls/VerticalFileSwitcher bin.i686.build/WinControls/WindowsDlg bin.i686.build/WinControls/shortcut bin.i686.build/uchardet, ...) failed.
make (e=5): Access is denied.
mingw32-make: *** [makefile:193: bin.i686.build] Error 5
```

**Comment by ArkadiuszMichalski** [comment]
@donho 
How you run Git Bash? From `Git\bin` or `D:\WebTools\Git\usr\bin`? If from the latter location do you set access in the Path variable to this folder?

**Comment by ArkadiuszMichalski** [comment]
@donho 
I search about this and looks like make has problem with suporting space in path ([bug 712](http://savannah.gnu.org/bugs/?712)). It's best to just avoid it. The problem here is that `mkdir` (and the rest) sit on the folder `C:/Program Files/Git/usr/bin/` but `$(dir $(SHELL))` return `C:/ Files/Git/usr/bin/`. Strange because `$(SHELL)` is correct and return `C:/Program Files/Git/usr/bin/sh`.

I make some workround but only for tools folder. I have not checked a situation when someone puts the Notepad++ code into a folder with a space.

**Comment by donho** [comment]
@ArkadiuszMichalski 

image

**Comment by ArkadiuszMichalski** [comment]
@donho Can you check if the last revision makes any difference?

**Comment by donho** [comment]
32 build OK now.
But 64 build under Git Bash not OK:
```
bin.i686 bin.i686.build bin.x86_64 bin.x86_64.build gcc-fixes.h makefile manifest.rc linking bin.x86_64/notepad++.exe
C:/appz/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible bin.x86_64.build\libscilexer.a when searching for -lscilexer
C:/appz/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lscilexer
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [makefile:227: bin.x86_64/notepad++.exe] Error 1
mingw32-make: *** [makefile:186: all] Error 2
```

**Comment by ArkadiuszMichalski** [comment]
@donho Can you generate 64-bit with CMD? Because I have this error even in the case of CMD (even with a previous version of make).

**Comment by donho** [comment]
```
bin.i686 bin.i686.build bin.x86_64 bin.x86_64.build gcc-fixes.h makefile manifest.rc generating bin.i686.build/libsensapi.a
 * [C:\WINDOWS/syswow64/SensApi.dll] Found PE image
bin.i686.build bin.x86_64 bin.x86_64.build gcc-fixes.h makefile manifest.rc compiling ../src/winmain.cpp
bin.i686 bin.i686.build bin.x86_64 bin.x86_64.build gcc-fixes.h makefile manifest.rc linking bin.i686/notepad++.exe
bin.i686.build\libscilexer.a: error adding symbols: Archive has no index; run ranlib to add one
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [makefile:227: bin.i686/notepad++.exe] Error 1
mingw32-make: *** [makefile:186: all] Error 2

```

@ArkadiuszMichalski  Could you test under Git Bash with both 64 & 32 bit build to make sure it's OK?

**Comment by ArkadiuszMichalski** [comment]
@donho Yes, works without any problem for both build. I run Git Bash same as you with `Git\git-bash.exe` file. For 32-build without any steps because I have added MinGW 32-bit folder in `Path` variable. For 64-bit build firstly I run `mingw32-make clean` (to remove trash from 32-bit build), set `PATH` variable to include MinGW 64-bit folder (but before 32-bit variant) and run `mingw32-make`.

Can you additionally check the fresh repo with my changes? Build 32-bit, restore repo, and build 64-bit?

**Comment by donho** [comment]
@ArkadiuszMichalski 
Indeed, I didn't clean the 64 build before launching the 32 build.

**Review by donho — APPROVED** [review]

**Pull request closed without merging**
