### PR TITLE
Add options to control Go To behavior

### PR DESCRIPTION
**Pull request by Rikk**
Two new options (three in total):

1. *Remember last search*: will not clear the last typed value, after clicking Go.
2. *Use current position*: it will automatically update input box with the current line/offset.
3. *Clear after Go*: this is the current, now old, behavior.

Also:
* Turn "Remember last search" the default behavior. This gives the user more ease to go back to previous location.
* Make input text selected by default when dialog get focus. This improves usability when input is not empty.
* Add missing Alt-key shortcuts to the two buttons.

Todo: add these new options to translation files.

This close and improve https://github.com/notepad-plus-plus/notepad-plus-plus/issues/708.

goto

### CODE REVIEW

**Comment by donho** [comment]
I'm not for such "enhancement" due to the following reasons:
1. the added 3 radio buttons confuse users and they make the usage of gotoline dialog less intuitive.
2. The remembered number is not consistant - when you switch your document, the filed "you are here" and "you can't go further than" field are changed according the current document. Whereas "You want to go to" field are remain the old one - this is a bug.
To implement this feature properly, you should register the last search number in the current buffer, and get the number from the current buffer each time the field in question needs to be updated. That will make the code more complex for a small feature, therefore I won't implement it, and won't accept the PR for such feature.

**Comment by Rikk** [comment]
Lol Donho, you're crazy. That is exactly what it is supposed to do: keep the old number there, in other words, it remembers the number. If you don't like that option, you may want to set the default to another one.

**Comment by Rikk** [comment]
Lol Donho, you're crazy. That is exactly what it is supposed to do: keep the old number there, in other words, it remembers the number. If you don't like that option, you may want to set the default to another one.
About your number 1: Imo, it doesn't make the dialog confuse; if that was the case, Find & Replace dialog should be considered a disaster.

**Comment by Rikk** [comment]
I'm thinking in renaming "Options" to "Mode", to make it clear that the three are *modes of operation*, not really options.

**Comment by dail8859** [comment]
I understand the behavior behind it but it seems like alot of GUI real estate just to let the user keep a number in a box.  

Presenting the user with options can get confusing especially when going to a line seems like such a simple task. Half the battle of any new feature is making it intuitive and non-invasive.

**Comment by Rikk** [comment]
Any better place to put the options?
Dialog could be made larger, so claustrophobic people won't need to have a battle when that dialog is open.

**Comment by dail8859** [comment]
My thinking is that nobody will ever be like "ok good I have an option to not remember the last search".  One way is to not add any options but always remember the last search and if that line is not valid then just clear out the textbox. That's just off the top of my head would have to give it more thought when I have time.

**Comment by Rikk** [comment]
"ok good I have an option to not remember the last search"
Maybe Donho would like, because he didn't understand the new options.

But with 3 options, we need radio buttons, the last being the current one.
Imo, the current behavior is not really needed, because with the number being selected by default, the user needs simply to type a new number like it was always.

**Comment by Rikk** [comment]
For those interested in my work on Go To dialog, I announce two more interesting options
1. Keep window open
2. Keep window on top after Go
and some fixes. For an explanation, please read the description of the top commit here: https://github.com/Rikk/notepad-plus-plus/commits/GoToLineDlg

goto2

**Comment by donho** [comment]
@Rikk 
I agree totally with @dail8859 and the 3 huge radio buttons just make me think of a saying in French:
"crush a fly with a huge hammer" - totally pointless.

> Maybe Donho would like, because he didn't understand the new options...
Nice try but fail. Try harder.

**Comment by Rikk** [comment]
@donho Ask to this question: Have you read #708?

**Comment by Rikk** [comment]
@donho Answer this question: Have you read #708?

**Comment by donho** [comment]
yes, I did read it.

**Comment by Rikk** [comment]
Care to elaborate what you consider a bug and I don't?

**Comment by donho** [comment]
I said in my previous comment:
> 2. The remembered number is not consistant - when you switch your document, the filed "you are here" and "you can't go further than" field are changed according the current document. Whereas "You want to go to" field are remain the old one - this is a bug.

**Comment by Rikk** [comment]
What about this from #708:
> When I press Ctrl + G second time, I would expect that number "10" is already there and marked in gray. If I press only enter, then I jump on line 10. But if I press any other number (e.g. 15), 10 is deleted (besause is selected and grey) and number15 is there and I press enter and I am on line 15.

**Comment by donho** [comment]
I answered it as well in my previous comment:
> To implement this feature properly, you should register the last search number in the current buffer, and get the number from the current buffer each time the field in question needs to be updated. That will make the code more complex for a small feature, therefore I won't implement it, and won't accept the PR for such feature.

**Comment by Rikk** [comment]
Why, if it is doing what was proposed?
What matters if the number is kept when toggling between documents?

**Comment by donho** [comment]
Have you ever tested your pr?
Just test it with several documents please.

**Comment by Rikk** [comment]
Yes tested, dialog does not move and number does not change when using Remember Last Number.

**Comment by Rikk** [comment]
I think it would need a buffer or something alike if the dialog was totally destroyed when closed, but it is not, it is just hidden.

**Comment by Rikk** [comment]
I think it would need be registered in a buffer if the dialog was totally destroyed when closed, but it is not, it is just hidden. Is that what you were supposing?

**Comment by h-h-h-h** [comment]
@donho:
> To implement this feature properly, you should register the last search number in the current buffer, and get the number from the current buffer each time the field in question needs to be updated. That will make the code more complex for a small feature, therefore I won't implement it, and won't accept the PR for such feature.

If also find the feature potentially useful. But if @donho is not willing to accept it, what can we do about it?

May I suggest to implement a way for additional data fields of a buffer in general, so that this internal feature could be used for future issues, too, that need to remember a value per buffer?

**Pull request closed without merging**
