### PR TITLE
Increase untruncated Find-result window line length to 2048

### LINKED ISSUE #7723: DOUBLE (edit: was REMOVE) the line-length limit in Find-result window
### Description of the Issue

There has been a complaint about long lines not being "well-represented" in the `Find result` window.  See https://notepad-plus-plus.org/community/topic/18028/how-do-i-see-the-full-line-in-find-results-window.

Long lines are truncated and an ellipsis appended if the line is too long.  If the "hit" for the line occurs in the truncated part, the hit marking is either not present, or is sometimes put in a questionable location.

The line-length limit is represented by `SC_SEARCHRESULT_LINEBUFFERMAXLENGTH` which resolves to 1024.  This #define comes from a Scintilla #include but there doesn't seem to be any rationale for it; perhaps it is a vestige from the early days?

Removing the line-length limit would solve the problem, but would it create any new problems?

### Steps to Reproduce the Issue

See the Community issue linked earlier.

### Expected Behavior

Hits beyond column (roughly) 1024 should have their matched hit-text fully visible in the `Find-result` window.

### Actual Behavior

Lines with length greater than (roughly) 1024 are truncated and a `...` is appended to the end.  Thus, the true hit text is not knowable from simply looking at the line in `Find-result`.  Note that if one double-clicks the line in `Find-result`, the true hit-text will be revealed because the user's caret selection will indicate it in an editor tab.

### Debug Information
Notepad++ v7.8   (32-bit)
Build time : Oct  7 2019 - 00:58:16
Path : C:\........\npp.7.8.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1508
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll

### PR DESCRIPTION
**Pull request by sasumner**
Fixes #7723

### CODE REVIEW

**Comment by donho** [comment]
@sasumner I suppose you have check if it works and there's no regression?

**Comment by sasumner** [comment]
@donho said:

>I suppose you have check if it works and there's no regression?

Well, I test all of my PRs. :-)
I ran a few simple tests on this one, seemed to work.
I did not exhaustively test it as it is "only" a length change.
A recent PR changed hardcoded occurrences `1024` (the old value for this) to use the `#define` name, so that doesn't seem to be a concern.
Do you have some other concerns?
If so, can you be specific?
I am willing to run more tests, I'm just not sure what they should be.

**Comment by donho** [comment]
> Do you have some other concerns?
If so, can you be specific?

No no, I'm just lazy :)

> I am willing to run more tests, I'm just not sure what they should be.

I guess it's enough to test 1 or 2 case(s) to make sure it's working, and 1 or 2 usual case(s) to ensure there's no regression.

**Comment by sasumner** [comment]
BTW, for the testing I did do, I concentrated on lines with A-z0-9 data and line lengths slightly less than the new threshold (to NOT see the `...`) and lines lengths slightly more than the threshold (to definitely see the `...`).

**Pull request closed without merging**
