### PR TITLE
Upgrade Scintilla from 4.1.4 to 4.2.0

### PR DESCRIPTION
**Pull request by donho**

### CODE REVIEW

**Comment by GOLEM777** [comment]
I think this is a good idea.
Better to update than to edit.

**Comment by donho** [comment]
Please test both 32 and 64 build here:
https://notepad-plus-plus.org/temp/

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/92bad0a60ad606b30df9ed97aecf4ff27bb6e967

**Comment by GOLEM777** [comment]
Hello! ANSI feels good (typing and saving). At the moment everything is working and stable. FOR ME!!
Win10 (64).

**Pull request closed without merging**
