### PR TITLE
fill Replace field the same as Find field

### PR DESCRIPTION
**Pull request by xomx**
Implements #12122 . 

This option can increase productivity when one needs only to modify an already existing text.

### CODE REVIEW

**Comment by xomx** [comment]
setting:

fill_ReplaceField_same_as_FindField

**Comment by alankilborn** [comment]
@xomx 
Looks totally awesome; thank you for your efforts.

**Comment by Yaron10** [comment]
@xomx,

👍 
Thank you for your work.

What do you think of the following case?

For whatever reasons you uncheck "Fill Find Field with Selected Text".
You're working on a document containing multiple occurrences of the misspelled word "apreciate".
The correctly spelled "appreciate" is selected.
You might want to "Fill Replace Field with Selected Text".

How about the following two independent options?
1. "Fill Find Field with Selected Text".
2. "Fill Replace Field with Selected Text".

Disable "Select Word Under Caret..." only _if both options are unchecked_.

**Comment by xomx** [comment]
@Yaron10 

> For whatever reasons you uncheck "Fill Find Field with Selected Text".
> You're working on a document containing multiple occurrences of the misspelled word "apreciate".
> The correctly spelled "appreciate" is selected.
> You might want to "Fill Replace Field with Selected Text".

In your scenario you still need to fill the Find field of the Replace dlg with the misspelled "apreciate" somehow.

When I find such problem in my text written, I usually click on the relevant word or select some invalid text, press Ctrl+H, then Ctrl+C, move to the Replace field and Ctrl+V there, then edit... I have never done the opposite (filling the Replace field with the correct text, Ctrl+C there, then move to the Find field...), but maybe that is just my way how to accomplish this task.

IMO if we have separate independent "Fill Replace Field with Selected Text" checked and the "Fill Find Field with Selected Text" unchecked, we are in the same situation as before this productivity improvement PR but now from the Find field point of view.

**Comment by alankilborn** [comment]
@xomx 

IMO The logic of the PR is perfect the way it is.

**Comment by Yaron10** [comment]
@xomx,

> In your scenario you still need to fill the Find field of the Replace dlg with the misspelled "apreciate" somehow.

That is correct. But theoretically one might still prefer this configuration "For whatever reasons".

Let's analyze it from a broader design point of view.

1. "Fill Find Field with Selected Text" and "Fill Replace Field with Selected Text" are not "father and child".
2. You programmatically disable a setting only if it's absolutely contrary to the common sense to keep it enabled.
This is not the case here.
3. Why not implement it in a more flexible way? - You can still have your productivity improvement.

Thanks again.

**Comment by xomx** [comment]
@Yaron10 

Understood.

I do not promise anything, but I will try to look at it.

Is this conforming to what you are talking about?
FillReplaceField-Yaron10var
I just do not know if it will be clear that the "Select Word Under Caret ..." is for both Fill-checkboxes in case of such layout.

**Comment by Yaron10** [comment]
@xomx,

> I do not promise anything, but I will try to look at it.

👍 
Thank you very much.

> Is this conforming to what you are talking about?

Yes.

> I just do not know if it will be clear that the "Select Word Under Caret ..." is for both Fill-checkboxes in case of such layout.

Good point.

How about moving "Select Word Under Caret ..." to the right in the middle of the two other settings?

**Comment by alankilborn** [comment]
I said:

>IMO The logic of the PR is perfect the way it is.

I spoke too soon. :-(

With the new checkbox checked, invoking with Ctrl+h results in BOTH the _Find what_ and _Replace with_ text selected in their boxes:

image

This is likely confusing to a user because he doesn't really know where input focus is.  It's with _Find what_, but I don't think that is best.

In that situation, this is what I'd expect:

image

The reason for that is the supposition that the text from the document is what you want to replace most often, so the _Find what_ data is less likely to need changing than the _Replace with_ data.

Of course, that's my opinion only, so do what you like with it.

Since to this point, this issue/PR doesn't have @donho blessing at all, 
I think Don should take a look at it, and if the base idea is judged to be a smart one, then Don should direct any changes needed.

**Comment by Yaron10** [comment]
> With the new checkbox checked, invoking with Ctrl+h results in BOTH the Find what and Replace with text selected in their boxes:

👍

**Comment by donho** [comment]
@xomx 
Thank you for the PR.
However, the added option makes UI more confusing and I'm not sure this feature is really needed.
Let's see if the same request coming then I will consider this PR (and redo the UI eventually if this feature is useful for a lot of people).

**Comment by xomx** [comment]
@donho 
Ok

@alankilborn 
It was easy to adapt this PR for the replacing (Ctrl+H):
focus_on_Replace_field_(AK)
but it has to stay as it is for the FindInFiles, as there one cannot know in advance for what purposes a user triggered it:
FindInFiles_autofill

@Yaron10 
The above change in code logic together with a possible GUI ambiguity arising from a necessary changes (in case I implemented your version we discussed earlier) is for me a reason not to implement such version in case Don decides to accept this PR in future. Otherwise I have to cross-check that focus position (more code = chance to introduce a bug/regression...).

**Comment by alankilborn** [comment]
>but it has to stay as it is for the FindInFiles, as there one cannot know in advance for what purposes a user triggered it

I'd say that in this case it isn't a problem to have only  _Find what_ text selected.
But, as you like.

**Comment by donho** [comment]
Instead of adding the settings into Preferences dialog, I prefer to use the existent swap button in Find replace dialog - it makes more sense and better user experience. Please see #13332

**Comment by xomx** [comment]
@donho 

> I prefer to use the existent swap button in Find replace dialog

Thanks for a implementation of this, I got used to this feature (I used my own build of N++ with this PR before). Your variant is IMO better than my previous attempt.

What about a tooltip for the swap-button in the Find-dlg? (to help announce the rightclick functionality to the users...)

**Comment by donho** [comment]
@xomx 
Hope you and your family are well.

> What about a tooltip for the swap-button in the Find-dlg? (to help announce the rightclick functionality to the users...)

I have thought about tooltip, but it might be "too polluted" on a small button. In any way, it will be documented on Notepad++ User Manual, so I let user to discover it (or from Google, chatgpt...)

**Pull request closed without merging**
