### PR TITLE
Add setting for panels to ignore '-nosession'

### PR DESCRIPTION
**Pull request by ozone10**
<s>currently missing translation</s>

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9710

### CODE REVIEW

**Comment by ozone10** [comment]
rebase onto master to check something

**Comment by donho** [comment]
@ozone10 
What do you think `Remember Panel State in Multi-instance (-nosession) *` instead of   `Panel state ignore -nosession *` ?

**Comment by ozone10** [comment]
@donho 
`-nosession` can be used even in mono-instance. And unfortunately there is no space for such long title.
There might be problem with translations, text running out of space.

Maybe adding [?] button or static text with more description.

**Comment by donho** [comment]
@ozone10 
> `-nosession` can be used even in mono-instance. And unfortunately there is no space for such long title.

Yes, indeed.
What I think about is people who know nothing about Notepad++ command line arguments. 

> Maybe adding [?] button or static text with more description.

That's a good idea, so that will give the full explanation to the both sides of people.

Do you mind that I join this PR to finish that, or do you prefer to take care of it by yourself?

**Comment by ozone10** [comment]
@donho 
I've added description (static text), if you want [?] button instead I will leave that to you.
image
image

**Comment by ozone10** [comment]
Maybe keep only `Panel State *` for title

**Comment by donho** [comment]
@ozone10 
It's much clear. Thank you!

**Pull request closed without merging**
