### PR TITLE
update korean 7.8.3

### PR DESCRIPTION
**Pull request by yunbj**
Update korean

### CODE REVIEW

**Comment by donho** [comment]
Please add this one:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f44c3579994e0259c2f5ce24cf41555b92a0d005

**Comment by yunbj** [comment]
It is already added.

https://github.com/yunbj/notepad-plus-plus/blob/29e26231992888cc20ff236296fcee86176e0fa0/PowerEditor/installer/nativeLang/korean.xml#L1202

**Comment by xylographe** [comment]
Perhaps, Don meant these 2 missing items?
```xml
<Item id="6314" name="Use monospaced font in Find dialog (Need to restart Notepad++)"/>

<cloud-select-folder value="Select a folder from/to where Notepad++ reads/writes its settings"/>
```

**Comment by yunbj** [comment]
@xylographe  Thank you. I will update.

**Pull request closed without merging**
