### PR TITLE
update english and french translations

### LINKED ISSUE #2293: Update english and french translation
### Description of the Issue

translation of ID 43033 -> 43037 and 43039 -> 43043 are wrong
The shortcut mapper is very confusing
bugtranslation
### Steps to Reproduce the Issue

1. check the name in the shortcut mapper : main menu line 124 to 140
### Expected Behavior

```
<Item id="43033" name="Go to next 1st style"/>
<Item id="43034" name="Go to next 2nd style"/>
<Item id="43035" name="Go to next 3rd style"/>
<Item id="43036" name="Go to next 4th style"/>
<Item id="43037" name="Go to next 5th style"/>

<Item id="43039" name="Go to previous 1st style"/>
<Item id="43040" name="Go to previous 2nd style"/>
<Item id="43041" name="Go to previous 3rd style"/>
<Item id="43042" name="Go to previous 4th style"/>
<Item id="43043" name="Go to previous 5th style"/>
```
### Actual Behavior

```
<Item id="43033" name="1st style"/>
<Item id="43034" name="2nd style"/>
<Item id="43035" name="3rd style"/>
<Item id="43036" name="4th style"/>
<Item id="43037" name="5th style"/>

<Item id="43039" name="1st style"/>
<Item id="43040" name="2nd style"/>
<Item id="43041" name="3rd style"/>
<Item id="43042" name="4th style"/>
<Item id="43043" name="5th style"/>
<Item id="43044" name="Find style"/>
```
### Debug Information

Notepad++ v6.9.2   (32-bit)
Build time : Aug 24 2016 - 05:43:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : LightExplorer.dll linefilter2.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll PluginManager.dll PythonScript.dll

### PR DESCRIPTION
**Pull request by cmeriaux**
update english and french translations without any Tab/space replacement
Fixed #2293

### CODE REVIEW

**Comment by donho** [comment]
As my comment in the previous PR: "Go to next" and "Recherche le... suivant" is not necessary at all. Therefore this PR won't be accepted.

**Comment by cmeriaux** [comment]
@donho I got your point. Menus are clear and "Recherche le suivant" is not necessary. You are right.
My point is :  "Recherche le suivant" is mandatory in the Shortcut Mapper. As my screenshot shows, it's very confusing
bugtranslation

More generally, a translationcan't rely on a sub-menu translation or you'll have a problem in the shortcut mapper.

So can you consider my point of view and reopen the ticket ?
Thanks

**Comment by donho** [comment]
@cmeriaux I see your point, but my choice remines the same.

**Comment by cmeriaux** [comment]
@donho so you are OK that I add in shortcutMapper.cpp some check to prepend the submenu ID to the translate ID  ?

**Comment by donmontmartre** [comment]
@cmeriaux I don't think it's a good idea. The coding effort (and side effect of making maintenance harder) is necessary (to me) in the case of more important issue.
I would keep the items display as it is.

**Comment by donho** [comment]
@cmeriaux I don't think it's a good idea. The coding effort (and side effect of making maintenance harder) is necessary (to me) in the case of more important issue.
I would keep the items display as it is.

**Comment by cmeriaux** [comment]
@donho 
You don't want to complicate the "shortcut mapper" code.
You don't want redundant translation with a sub-menu translation.
So you don't care that Shortcut Mapper" GUI prompt an incomprehensible message.

There are some contradiction in what you says and what is implemented. Sometime you repeat the sub-menu message, some time you don't

"mark all"/"Using 1st style"
"mark all"/"Using 2st style"
"unmark all"/"clear 1st style"
"unmark all"/"clear 2st style"
"jump up"/"1st style"
"jump up"/"2st style"
"jump down"/"1st style"
"jump down"/"2st style"
"EOL Conversion"/"convert ...."
"close more"/"close but ...."
"project"/"project pannel ....3


I suggest you to make every body happy ( user of the GUI, user of the Shortcut Mapper, Developer of Shortcut mapper) : 
**write a translation that doesn't rely on a sub-menu message**

So please accept my PR

**Pull request closed without merging**
