### PR TITLE
Update code in FileManager::reloadBuffer to correctly detect line endings and encoding

### LINKED ISSUE #2637: NP++ has issue changing status bar from ANSI to UTF-8 when the file is changed externally
### Description of the Issue
In notepad++ when a comma separated text files encoding changes from ANSI to UTF-8 with no byte order marker the status bar does not reflect the change.  The file needs to be closed and reopened for the status bar to reflect the change.

### Steps to Reproduce the Issue
1. Load the ANSI file into NP++
2. Use a text editor, other than NP++, that can save an ANSI file as UTF-8 with no BOM
3. Go back to NP++ and allow it to reload the externally change file and note that the encoding doesn't change from ANSI to UTF-8

### Expected Behavior
I expected the status bar to change from ANSI to UTF-8

### Actual Behavior
The status bar stayed displaying ANSI

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

### PR DESCRIPTION
**Pull request by CookiePLMonster**
Fixes #2637, #2843, #3557 and #4033 (maybe more?)

PR seems nearly identical to rejected #2633, however I have actually compiled and tested this and all test cases work fine.

This PR mirrors encoding/EOL detection present in `FileManager::loadFile` to `FileManager::reloadBuffer`. As a result, I observed following issues when reloading files modified outside of Notepad++ are fixed:

- EOF changes get detected and reflected in the GUI
- If default encoding is set as UTF-8, yet a modified file is a valid ANSI file then encoding gets set as UTF-8 (just like when opening) as opposed to ANSI - that is, default settings are now respected

### CODE REVIEW

**Comment by donho** [comment]
@CookiePLMonster The following PR will be chosen for the fix of https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4034 due to its simplicity:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4034

Please redo another PR for the other issues.
Sorry for the inconvenience, thank you for your contribution.

**Comment by CookiePLMonster** [comment]
Sure! I'll wait until the other PR is merged and re-submit, so it'll be of narrower scope.

**Comment by donho** [comment]
@CookiePLMonster Done: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/46d0f12c3e687c83efbaa04f7ebd95616678226c

**Comment by CookiePLMonster** [comment]
@donho PR reissued as #4124

**Pull request closed without merging**
