### PR TITLE
update galician.xml

### LINKED ISSUE #10742: Spanish and Galician translations for v8.1.9
Hi, I'm new here.

I bring the updated Spanish and Galician language files to be included in the new version of Notepad++, if you consider it appropriate.

Sorry if I do something wrong.

Greetings from Spain

Translated by deepl.com

[Notepad++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7456667/Notepad%2B%2B.zip)

Hola, soy nuevo por aquí.

Aporto los ficheros actualizados de idioma español y gallego para, si lo consideran oportuno, incluirlos en la nueva versión de Notepad++.

Perdón por si hago algo mal.

Saludos desde España

### PR DESCRIPTION
**Pull request by conky77**
fix #10742 for Galician

### CODE REVIEW

**Comment by conky77** [comment]
@P0rsche-911 
* I created this "Pull Request" with your Galician translation. If it is accepted, It will be included in the next version. 
* In order to compare your translation (version 8.1.5) with the last English.xml, I added English strings untranslated.
* I deleted items 6214, 6901 (they are not present in the last English version). 
* I corrected Item 6408, 6409 (they were inverted).  I integrated "files-filter-tip".
Once it is updated, you can create a new ticket with the last translation. 
About Spanish translation: please check it with the last translators, and in case, open a new ticket only for Spanish.

* Creé este "Pull Request" con tu traducción al gallego. Si se acepta, se incluirá en la próxima versión.
* Para comparar su traducción (versión 8.1.5) con el último English.xml, agregué cadenas en inglés sin traducir.
* Eliminé los elementos 6214, 6901 (no están presentes en la última versión en inglés).
* Corregí el Item 6408, 6409 (estaban invertidos). Integré "files-filter-tip".
Una vez actualizado, puede crear un nuevo ticket con la última traducción.
Sobre la traducción al español: por favor verifíquelo con los últimos traductores, y en su caso, abra un nuevo ticket solo para español.

**Comment by conky77** [comment]
@P0rsche-911 The author of Notepad++ has modified again "english.xml", so maybe it is better to wait for the new version before starting the Galician translation. For Spanish, there are already translators, so please write them (or wait their translation).

**Comment by P0rsche-911** [comment]
Hi, I have finished reviewing the file. I attach it to you.

 

Thank you very much for all your help. My work is of some use.

 

 


Hola, he terminado de revisar el archivo. Te lo adjunto.

 

Muchas gracias por toda tu ayuda. Mi trabajo sirve para algo.



 
 

Enviar: martes 25 de octubre de 2022 a las 0:44
De: "Matteo Concato" ***@***.***>
Para: "notepad-plus-plus/notepad-plus-plus" ***@***.***>
CC: "P0rsche-911" ***@***.***>, "Mention" ***@***.***>
Asunto: Re: [notepad-plus-plus/notepad-plus-plus] update galician.xml (PR #12336)


 

@P0rsche-911 The author of Notepad++ has modified again "english.xml", so maybe it is better to wait for the new version before starting the Galician translation. For Spanish, there are already translators, so please write them (or wait their translation).

**Comment by conky77** [comment]
@P0rsche-911 I can't see any attachments (when you answer, I can see your comment in this "Pull Request").
So please open a new issue with the attachment. Remember to mention my user with (at) (arroba), so I receive a notification.

**Comment by P0rsche-911** [comment]
Sorry
 

Enviar: miércoles 26 de octubre de 2022 a las 7:18
De: "Matteo Concato" ***@***.***>
Para: "notepad-plus-plus/notepad-plus-plus" ***@***.***>
CC: "P0rsche-911" ***@***.***>, "Mention" ***@***.***>
Asunto: Re: [notepad-plus-plus/notepad-plus-plus] update galician.xml (PR #12336)


 

@P0rsche-911 I can't see any attachments (when you answer, I can see your comment in this "Pull Request").
So please open a new issue with the attachment. Remember to mention my user with (at) (arroba), so I receive a notification.

**Comment by P0rsche-911** [comment]
> @P0rsche-911 I can't see any attachments (when you answer, I can see your comment in this "Pull Request"). So please open a new issue with the attachment. Remember to mention my user with (at) (arroba), so I receive a notification.

@conky77 edited

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Comment by P0rsche-911** [comment]
Hi, I am obviously inexperienced in these matters.

I would be grateful if you could tell me where I have gone wrong. I have only changed the language displayed in the program using the last file "english.xml" for reference and "french.xml" for help.

@donho redirects me to a page for making mistakes.

It is a big file where I save every correction and there are many. It is very likely that something could be modified without realizing it.
I appreciate any help you can give me.

Thank you very much and apologies

Translated with www.DeepL.com/Translator (free version)

Hola, es evidente que soy inexperto en estos temas.

Agradecería que me dijeran en qué he fallado. Solo he cambiado el idioma que se muestra en el programa usando el último archivo "english.xml" como referencia  y "french.xml" como ayuda.

@donho me redirige a una página por cometer errores.

Es un archivo grande donde guardo cada corrección y son muchas. Es muy probable que algo se pudiera modificar sin darme cuenta.
Agradezco toda ayuda que me puedan dar.

Muchas gracias y disculpas

**Comment by conky77** [comment]
> Hi, I am obviously inexperienced in these matters.
> 
> I would be grateful if you could tell me where I have gone wrong. I have only changed the language displayed in the program using the last file "english.xml" for reference and "french.xml" for help.
> 
> @donho redirects me to a page for making mistakes.
> 
> It is a big file where I save every correction and there are many. It is very likely that something could be modified without realizing it. I appreciate any help you can give me.
> 
> Thank you very much and apologies
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)
> 
> Hola, es evidente que soy inexperto en estos temas.
> 
> Agradecería que me dijeran en qué he fallado. Solo he cambiado el idioma que se muestra en el programa usando el último archivo "english.xml" como referencia y "french.xml" como ayuda.
> 
> @donho me redirige a una página por cometer errores.
> 
> Es un archivo grande donde guardo cada corrección y son muchas. Es muy probable que algo se pudiera modificar sin darme cuenta. Agradezco toda ayuda que me puedan dar.
> 
> Muchas gracias y disculpas

Hi @P0rsche-911, it is my fault because I tried too many things with a pull request, and unfortunely Do-Ho doesn't like that ;-)
At your file I added some missing strings for the next version and mainly I converted TAB with spaces. That is more difficult for who wants to check differencies. We have to check if your original galician.xml would pass the rules. I'm afraid not: I remember that the previous version used both Tab and Spaces to identate the code. If what I remember is true, before creating a new Pull Request, we have to ask to Don-Ho if it is possible to normalize the file in advance(for example using only tab like what you did. I try to do this checks as soon as possible, but could be next week.

**Pull request closed without merging**
