### PR TITLE
[XML] Update brazilian_portuguese.xml

### PR DESCRIPTION
**Pull request by Marcellomco**
Added fix for "Make english language text with colon (':') consistent"

### CODE REVIEW

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Update English translation for v8.6.8 (indentation setting)"

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Add message box with information about disabled backward regex searching"

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Add Backspace unident option"

**Comment by myTempTemp** [comment]
340082238-bd0869f0-a8c0-4d0a-9663-dee784d9c1bb

**Pull request closed without merging**
