### PR TITLE
11501 - Current Line Frame with a simpler Preferences UI

### PR DESCRIPTION
**Pull request by shriprem**
New Feature: #11501

The Preferences GUI with this PR is much simpler as compared to PR #11526.

Due to the elimination of the _Enable current line frame_  checkbox, the GUI will be simpler for the end users to comprehend and use. Instead of the checkbox, user guidance is provided in the feedback text next to the slider (now with a range from **_0_** to 6).

While evaluating the two PRs, please see @Yaron10's analysis [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11501#issuecomment-1094116463).

image

image

### CODE REVIEW

**Comment by shriprem** [comment]
>Testing https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11532 and also https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fe810cea31cdacdd1c7a2fa765fd734d11be65b2, the border/edge disappears on checking/sliding.
This issue did not exist with the earlier commits.

Could you please have a look?

@Yaron10, I noticed that too. The edge shows up only at slider position 1. It goes away at all other positions. Can you please confirm this more specific finding? Thanks!

I was initially suspecting Scintilla for this. But that is not the case since when I execute either of `editor.setCaretLineFrame(1)` in PythonScript or `sci_sendmsg 2705 1` in NPPExec, the edge toggling is not happening.

So, yes. I will review my code changes again for this PR again to see what makes the execution for slider position at '1' to be causing this edge toggling.

**Comment by Yaron10** [comment]
@shriprem,

> The edge shows up only at slider position 1. It goes away at all other positions. Can you please confirm this more specific finding?

Yes, that seems correct.

You're doing a great job. 👍 
Thank you.

**Comment by Yaron10** [comment]
@shriprem,

Thank you for the quick fix. 👍

**Comment by shriprem** [comment]
Thanks @Yaron10. It turned out be a very simple fix. So the credit belongs to you for spotting the issue.

**Comment by shriprem** [comment]
@donho, I did not fully read your [review request](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11526#pullrequestreview-941150124) at the now closed PR #11501 since I was immersed in coding at that time. I just now did. I am sorry I couldn't do so earlier.

Do you want me to implement the GUI per your design?

**Comment by donho** [comment]
> Due to the elimination of the Enable current line frame checkbox, the GUI will be simpler for the end users to comprehend and use. Instead of the checkbox, user guidance is provided in the feedback text next to the slider (now with a range from 0 to 6).

I have to say that the simpler way you found is pretty good. However, with the global view, I prefer to provide to user a cleaner GUI and clear logic. So please consider what I have requested in #11526.

Please create a new branch for a new PR. I'm preparing the RC of next release so this feature won't be in the next release - Take your time for the implementation and please make sure what you have commit. Thank you.

**Comment by alankilborn** [comment]
At this point I wish I had @Yaron10 's email address for some private messaging. :-)

**Comment by Yaron10** [comment]
@alankilborn,

It would be a pleasure. :)
Would you like to post your Email here?

**Pull request closed without merging**
