### PR TITLE
Context menu with "Copy link" option.

### PR DESCRIPTION
**Pull request by Uhf7**
Implements #2435.

### CODE REVIEW

**Comment by Yaron10** [comment]
@Uhf7,

Thank you for another great PR. :+1: 

NPP enables the user to customize the context-menu (Menu -> Settings -> Edit Context Menu).
Would it be possible to control *both* the appearance and position of "Copy Link" via `contextMenu.xml`?

If NOT, I think the "Copy Link" addition should be optional.
And regarding the position: IMO it would be better to add a separator + "Copy Link" to the end instead of replacing "Copy".
(For my personal use it's even more important: I use the "MenuIcons" plugin and it works in the context-menu only if "Copy" is there). 

Should it require a lot of extra work?

**Comment by Uhf7** [comment]
@Yaron10, thank you for the feedback.

I intentionally tried it this way to avoid too much impact on the infrastructure. The basic idea is, that "Copy" is useless without selection, disabled anyway in this case, so simply make it to "Copy link", if appropriate.

_Configuration:_ Since it replaces "Copy", "Copy link" appears instead of "Copy" where ever you configure it in the `contextMenu.xml`. If there is no "Copy" command in the `contextMenu.xml`, then no "Copy link" appears. If there are no clickable links enable in Settings->MISC, no "Copy link" appears either. That is the plan and seems enough configuration for me.

_MenuIcons plugin:_ I just tried the `MenuIcons_dll_1v22_x32.zip` from the GitHub repository (https://github.com/francostellari/NppPlugins), and it worked perfect. The icons seem to be identified by the file names, and if I copy a `Copy Link.ico` file in the `MenuIcons\!` folder of this plugin, then this icon gets displayed beside the "Copy link" menu entry.

**Comment by Yaron10** [comment]
@Uhf7,

> I intentionally tried it this way to avoid too much impact on the infrastructure.

That's a good point.

> Since it replaces "Copy", "Copy link" appears instead of "Copy" where ever you configure it in the contextMenu.xml.

*So, the "MenuIcons" plugin shouldn't be a consideration at all.* Thank you for trying it.
(It does work with the original `contextMenu.xml`, but doesn't with some [customization](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5542897/contextMenu.zip)).

**Comment by donho** [comment]
I love how it changes dynamically - high value on the usability. Bravo @Uhf7 !

**Pull request closed without merging**
