### PR TITLE
Add new explorer context menu entry "Edit with Notepad++" for Windows 11

### LINKED ISSUE #92: Use registry for Explorer context menu instead of NppShell
Instead of NppShell, you can set some values in registry for Explorer context menu:

```
[HKCR\*\shell\EditWithNpp]
@="Edit with Notepad++"
[HKCR\*\shell\EditWithNpp\command]
@="\"C:\\Program Files (x86)\\Notepad++\\notepad++.exe\" "%1" %*"
```

### LINKED ISSUE #4368: ShellExecute failed error when using "Edit with Notepad++" R-click context menu option
### Description of the Issue
I wanted Notepad++ to always "run as administrator", so I found the .exe and checked that option on the compatibility tab, but now whenever I try to open a file with the right-click > Edit with Notepad++ option I get the error message "Notepad++ Extension: Error", "ShellExecute Failed (2): Is this command correct?" with the path to the Notepad++ exe on the next line followed by the path to the file I was trying to open...

### Steps to Reproduce the Issue

1. Check the "Run this program as an administrator" option in the exe properties menu
2. try to open any file using the "Edit with Notepad++" option in the windows right-click context menu.

### Expected Behavior

The file opens, with notepad++ in administrator mode

### Actual Behavior

I get the following and the program does not open.
screenshot of error

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

### LINKED ISSUE #6169: Translate context menu "Edit with Notepad++"
Can context menu be translated somehow?
I know context menu is programed in:  **NppShell_06.dll**
translation

### LINKED ISSUE #7747: Not localized context menu entry "Edit with Notepad++"
### Description of the Issue

Regardless of the language selected during installation, the context menu is always "Edit with Notepad++"

Аннотация 2019-12-16 195538

### Steps to Reproduce the Issue

1. Run installer in non-english language (eg russian)
2. Install Notepad++ (eg x64) with context menu entry and non-english localization file (eg russian)
3. You will see in the context menu (RMB on a text file) "Edit with Notepad++"

### Expected Behavior

When I choose Russian localization I want get "Изменить в Notepad++" in context menu entry

### Actual Behavior

I always get "Edit with Notepad++" in context menu entry

### Debug Information

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 (64-bit) 
OS Version : 1909
OS Build : 18363.535
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

### LINKED ISSUE #8786: Error (shellExecute) when trying to open files from context menu
### Description of the Issue
If you run Notepad++ in compatibility mode ("Run as Administrator"), you may get the following error when you try to open files using the Windows context menu (that is, right click the file and select "Edit with Notepad++"):

ShellExecute failed (2): Is this command correct?
"C:\Program Files\Notepad++\notepad++.exe"
"C:\Users\Username\Desktop\textfile.txt"

The window name is "Notepad++ Extension: Error" and the window icon is Windows Explorer icon. Even though this happens for me with a clean installation of Notepad++, so without any non-standard extensions or plugins.

Screenshot of the error:
error

### Steps to Reproduce the Issue

1. Install Notepad++ 7.8.9 (x64)
2. Go to Notepad++ install folder and right click notepad++.exe file > properties > compatibility > enable "Run this program as Administrator"
3. Right-click any file on your hard disk that Notepad++ can open, and select "Edit with Notepad++"
4. Observe error

### Expected Behavior
Notepad++ should be able to open files in this manner despite running itself as Administrator. Some people intuitively want to run editors like Notepad++ as admin, to avoid errors of a lack of file access or locked files for which Notepad++ asks the user to restart with administrator privileges, in order to be able to save it. These advanced users might enable this setting in compatibility tab, no matter how effective it is, and will now run into this unnecesary error, and will probably have a hard time figuring out the reason for their error.

### Actual Behavior
Notepad++ couldn't open a file using the context menu

### LINKED ISSUE #10320: [Feature Request] Update Context Menu for Windows 11
Microsoft have changed the default context menu in Windows 11 (https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/) and therefore the "Edit with Notepad++" context menu entry is no longer present on the main menu and you need to go to the overflow. 

It'd be nice to be able to get the context menu entry again. Unfortunately it looks like you need a packaged identity to use the Windows 11 menu so you'd need to deploy a manifest with the application, but I guess you have a signing key so it might not be that big an issue. Also maybe it's something to wait for closer to a final release as Microsoft could easily change things if enough people complain.

### LINKED ISSUE #10565: Windows 11 Context Menu
### Description of the Issue
Windows 11 context menu for "Edit with Notepad++" is buried within the new context menu

### Steps to Reproduce the Issue

1. Download windows 11 beta (or dev)
2. Install NPP
3. Right click a file to "edit with notepad++"

### Expected Behavior
"Edit with notepad++" should be on the first context menu, not buried.

### Actual Behavior
Normally "Edit with Notepad++" is in the context menu when right clicking a file within windows. With windows 11 build 21H2 you now have to Right click a file > Show more options > Edit with notepad++

Its far easier to just have it in the first context menu, not buried within the menu

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\my-st\Desktop\Arma\AltisLife.Altis\ZDGaming.Altis\initPlayerServer.sqf"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 22000.194
Current ANSI codepage : 1252

Current Windows version is 
https://gyazo.com/dc1d62060a2ed340fbe09fc8f17b7ff7

### LINKED ISSUE #10640: Shell doesn't register on ARM based systems
### Description of the Issue
The provided shell file NppShell_06.dll in the ARM package fails to register with Windows on ARM. The end result is the same using both the installer or registering it by hand.

### Steps to Reproduce the Issue

1. Install Notepad++ using the installer.
2. Try to open any file using the context menu
2. Notice missing "Edit with Notepad++" in context menu
3. Open CMD with elevated privileges
4. Navigate to the folder Notepad++ is installed at
5. Try to register the NppShell_6.dll with "regsvr32 /i NppShell_6.dll"

### Actual Behavior

Error2

### Debug Information

Notepad++ v8.1.5   (ARM 64-bit)
Build time : Sep 26 2021 - 15:10:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (Unknown-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : HexEditor.dll

### LINKED ISSUE #10653: Open With dialog for all files should include N++ in Windows 11
### Description of the Issue
Windows 11 provides new UWP Notepad app.
Hack replacing notepad.exe via Debugger registry value does not work anymore here.
OFC you can set assocate all required file extensions.

Sadly Notepad++ is not seen in suggested app list for not known files.
Notepad UWP is.

### Steps to Reproduce the Issue

1. Install Notepad++
2. Try open editable file not registered with Notepad++ for seen Open with dialog.
3. Notepad++ it is not listed here. 

### Expected Behavior
Open With dialog for all files should include N++

### Actual Behavior
Notepad++ is missed in Open With dialog for not registered files. 

### Debug Information
Notepad++ v8.1.6   (64-bit)
Build time : Oct 10 2021 - 14:10:29
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 22000.194
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Screenshot

s

### Reference

- https://community.notepad-plus-plus.org/topic/21570/open-with-dialog-for-all-files-should-include-n?_=1634017402297

### LINKED ISSUE #10856: Enabling "Edit with Notepad++" context menu for OneDrive OnDemand files which are yet to download
The context menu option needs to be available for "Edit with Notepad++" for the files which are yet not downloaded in the OneDrive OnDemand.

### Description of the Issue

The unavailability of the option of "Edit with Notepad++" and us not to be able to directly trigger the downloading of the content of the files via choosing the option from the context menu of explorer to "Edit with Notepad++" is very annoying. 

### Steps to Reproduce the Issue

1. Locate any file which is one the OneDrive in the Explorer. It must have empty blue cloud symbol.(which means that the contents of the files aren't downloaded yet to the local system)
2. Right click that file in order to see the option to edit with notepad++. (which you will not be able to see)
3. After selecting the option of "Always keep this on this device" the file contents will be downloaded and then only in the context menu option we will be able to see that option of "Edit with Notepad++" in the context menu. 

### Expected Behavior

Whenever we are right clicking the file there are 2 cases.
1. **Normal File** : We can see the "Edit with Notepad++" ----> **Fine**
2. **OneDrive OnDemand Not Downloaded File** : There needs to be the context menu option entry, which will trigger the explorer or OneDrive to download the file context first and then open the file in edit mode in Notepad++

### Actual Behavior

Currently when we right click a file which is in the OneDrive of the explorer and it's contents are not available then the option to "Edit with Notepad++" isn't visible. 
We need to force download first from some other workaround and once the file is available in the system then only right-click context menu shows us the option of "Edit with Notepad++"

### Debug Information

Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Education (64-bit) 
OS Version : 2009
OS Build : 19043.1387
Current ANSI codepage : 1252
Plugins : AutoSave.dll mimeTools.dll NppConverter.dll NppExport.dll 

### Before
image

### After 
image

### PR DESCRIPTION
**Pull request by donho**
Windows 11 has its new interface for its explorer context menu. It makes the old "Edit with Notepad++" command less accessible. This commit improves the accessibility and also fix issue of run as an administrator (Properties set in Compatibility) in the new context menu command.
I believe it fixes also the context menu command issue under ARM64 architecture (fixed only under Windows 11).

The localization of "Edit with Notepad++" is also possible in this commit.

Note that if the command place of "Edit with Notepad++" context menu command is taken by other application ("\HKEY_CLASSES_ROOT\*\shell\pintohome"), the new context menu "Edit with Notepad++" won't be installed. User should install it him/herself.

For people want to test, 3 signed installers are available for downloading:
http://download.notepad-plus-plus.org/repository/MISC/newCM4Testing/

For people have got problem to download, you can grab them here:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13170#issuecomment-1438731043

Fix #10320, fix #10565, fix #4368, fix #8786, fix #10320, fix #10640, fix #10856, fix #10653, fix #7747, fix #6169, fix #92

### CODE REVIEW

**Comment by neonoxd** [comment]
Great intermediate fix, would be super nice if you could implement it like NanaZip or Sandboxie where it resides in the proper area on the context menu and can also use the proper icon for the tool

Haven't investigated further but this might give you some directions
- https://github.com/M2Team/NanaZip/tree/main/NanaZipShellExtension

Or Sandboxie's implementation:
- https://github.com/sandboxie-plus/Sandboxie/tree/master/SandboxiePlus/SbieShell/SbieShellExt
- https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/Windows/SettingsWindow.cpp#L523

Until then this is already much appreciated 🙏

**Comment by FadeMind** [comment]
@donho sir `DNS_PROBE_FINISHED_NXDOMAIN` when open `http://download.notepad-plus-plus.org/repository/MISC/newCM4Testing/` 

DNS Google (8.8.8.8)

**Comment by donho** [comment]
@FadeMind 
Does that mean that you cannot download them?

**Comment by FadeMind** [comment]
@donho yes, site is not available. Unable to download.

**Comment by donho** [comment]
For ppl have got problem to download, you can grab them here:

[npp.8.4.9.Installer.arm64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10795272/npp.8.4.9.Installer.arm64.zip)
[npp.8.4.9.Installer.x64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10795295/npp.8.4.9.Installer.x64.zip)
[npp.8.4.9.Installer.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10795297/npp.8.4.9.Installer.zip)

**Comment by ten2120** [comment]
What about the Mini-portable version? I use it for years and I was waiting for this feature (Adding NP++ to Windows 11 Menu). Any chance to get it on portable version (like the classic menu)?

**Comment by TiranSpierer** [comment]
when will this be available to install?

**Comment by mariobesen** [comment]
This feature implementation messesd up with native OS context menu entry instead of proper and supported way to add entries to new XAML context menu.

This hack replaces "Pin to Quick Access" option in menu which is not good. It also shows up as an option for non-editable files (like DLLs, binaries).

Even worse, this is NOT reversed after uninstalling NP++ from system.

Because of this we're not deploying new version of NP++ in our env until this is fixed. Thank you

**Comment by donho** [comment]
@mariobesen 
> This feature implementation messesd up with native OS context menu entry instead of proper and supported way to add entries to new XAML context menu.

If you have a better solution, you're welcome to do your contribution.

> Even worse, this is NOT reversed after uninstalling NP++ from system.

It's not true - Before releasing this feature has been tested - the entry is removed after uninstalling Notepad++.

**Comment by firestarter7924** [comment]
Hello. I have "edit with notepad++' option in the FULL contex menu using 8.4.7 version. Tried the latest and this feature is broken. hope it'll be fixed.

**Comment by modz2014** [comment]
hey question about the context menu there is duplicated in both im guessing thats not possible to fix

**Pull request closed without merging**
