### PR TITLE
Use custom draw for main toolbar in dark mode

### LINKED ISSUE #15225: [Feature request][Dark Mode] Custom draw for main toolbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Panels with toolbar already use custom draw. Main toolbar doesn't, and is using workaround for visual glitch in dark mode on Windows 11. 

### Describe the solution you'd like.

Main toolbar should use custom draw.

### Debug Information

```shell
Notepad++ v8.6.7
```

### Anything else?

related #10510

### PR DESCRIPTION
**Pull request by ozone10**
image

fix #15225

### CODE REVIEW

**Comment by donho** [comment]
@ozone10 
Is the above image the glitch one? If it is, what's the pic of fixed one?

**Comment by ozone10** [comment]
@donho 
the fixed one. This is from current release Notepad++ v8.6.7
image

Document map is pressed.

**Comment by donho** [comment]
@ozone10 
It crashes in x64 Release mode. It doesn't crash in x64 Debug mode (Dark Mode eabled).

**Comment by ozone10** [comment]
@donho 
I cannot reproduce it.

**Comment by donho** [comment]
Hmm...
It could be my config.xml.
I'll try to provide step by step instructions.

**Comment by donho** [comment]
culprit identified: it's the icons from Explorer plugin:

[Explorer.zip](https://github.com/user-attachments/files/15517212/Explorer.zip)

Unzip it into your plugin folder, then you should be able to reproduce the crash.

**Comment by ozone10** [comment]
@donho 
could you test, it should work now.

**Comment by donho** [comment]
@ozone10 
No more crash now.

Tested a lot of plugins as well, it seems no issue:

image

Thank you for fixing it!

**Pull request closed without merging**
