### PR TITLE
Swap errant tooltip text for function list sort and reload buttons

### LINKED ISSUE #9804: Function List button tool tips are mixed up
### Description of the Issue

image
image

### Steps to Reproduce the Issue

1. View > Function List
2. Hover a cursor over the buttons in the Function List panel

### Expected Behavior

1st button shows a tool tip "Reload" and 2nd button shows "Sort".

### Actual Behavior

Should be vice versa.

### Debug Information
```
Notepad++ v7.9.5   (64-bit)
Build time : Apr 24 2021 - 12:11:48
Path : E:\Development\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe
Command Line : -nosession -multiInst
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : none
```

### PR DESCRIPTION
**Pull request by sasumner**
Fix #9804

### CODE REVIEW

**Review by mere-human — APPROVED** [review]
By the way, is it not localized?

**Comment by sasumner** [comment]
>is it not localized?

Oddly, function list controls don't seem to be localized.
The code makes it look like they *should* be localized....hmmm.
Even in light of that, this PR is still valid.

**Comment by vinsworldcom** [comment]
> Oddly, function list controls don't seem to be localized.

Aren't they localized in the cpp file:

```
Search "_sortTipStr" (4 hits in 2 files of 500 searched)
  C:\Users\mvincent\src\personal\notepad-plus-plus\PowerEditor\src\WinControls\FunctionList\functionListPanel.cpp (3 hits)
	 539: 			wcscpy_s(lpttt->szText, _sortTipStr.c_str());
	 812: 			_sortTipStr = pNativeSpeaker->getAttrNameStr(_sortTipStr.c_str(), FL_FUCTIONLISTROOTNODE, FL_SORTLOCALNODENAME);
	 812: 			_sortTipStr = pNativeSpeaker->getAttrNameStr(_sortTipStr.c_str(), FL_FUCTIONLISTROOTNODE, FL_SORTLOCALNODENAME);
  C:\Users\mvincent\src\personal\notepad-plus-plus\PowerEditor\src\WinControls\FunctionList\functionListPanel.h (1 hits)
	 116: 	generic_string _sortTipStr = TEXT("Reload");
```

Cheers.

**Comment by sasumner** [comment]
>Aren't they localized in the cpp file

Well...yes...but it doesn't seem to be working.  :-)
I tried a fresh portable 7.9.5, turn Function List on, change language to anything, see that Function List components remain in English.

**Pull request closed without merging**
