### PR TITLE
Finder window. "One result per line"\"Results in line" option.

### PR DESCRIPTION
**Pull request by vitali-kurylovich**
"Results in line" feature is useful for tables and logs analysis.

Indirectly partially softens the problem #9879

notepad++ Finder _One_result_per_line

### CODE REVIEW

**Review by donho — CHANGES_REQUESTED** [review]
The formatting of 4 files FindReplaceDlg.h, FindReplaceDlg.cpp, resource.h and Scintilla.h has been changed - not only it's hard for the code review, but also formatting change should not go into the repository. Please restore the 4 files for the code review.

**Comment by vitali-kurylovich** [comment]
I deleted a branch and recreated it with the same name. Is it possible to reopen this PR again?

**Comment by alankilborn** [comment]
>Is it possible to reopen this PR again?

Why not just create a new PR?

**Comment by vitali-kurylovich** [comment]
There is "Reopen and comment" button but it is not active. I probably have no permits.
@donho Could you reopen this PR, please.

**Comment by donho** [comment]
@vitali-kurylovich 
Please create a new PR with a different branch name.

**Pull request closed without merging**
