### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Omcsesz**
The older, cmd method has been replaced with Visual Studio-based method, hence the update.

### CODE REVIEW

**Comment by donho** [comment]
The readme has been updated recently and as fas as I know, nobody has the problem with it.

**Comment by Omcsesz** [comment]
Actually, it has been suggested to me here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5958

**Comment by donho** [comment]
The suggestion told you if you find any inaccurate description, you're free to do a PR to correct it.
Not erase the whole section to put a link for people who have never done dev.

**Comment by sasumner** [comment]
> it has been suggested to me here

It would have been more appropriate to take any clarifying points you found at that external link and integrate them into readme.md to make it a more accurate and cohesive document.

**Comment by Omcsesz** [comment]
> 
> 
> > it has been suggested to me here
> 
> It would have been more appropriate to take any clarifying points you found at that external link and integrate them into readme.md to make it a more accurate and cohesive document.

True, I will do that.

**Comment by sasumner** [comment]
@Omcsesz You are very agreeable; hopefully if you put the effort in, it will be accepted and all will benefit if the way it is now is deficient.  But, I for one have no control over whether or not that will happen.

**Pull request closed without merging**
