### PR TITLE
Add navigation to the 1st & last tab abilities

### LINKED ISSUE #14416: [Request] Add "Last Tab" as kb shortcut option
### Description of the Issue
Right now shortcuts exist for 1st to 9th tab (189-197), like most tabbed program. What would be great is if there was also an option to go to the last tab. In firefox as an example, ctrl+9 goes to the last tab in the window. It would be nice to set that to match, or set it to ctrl+0

See related issue #14240

### PR DESCRIPTION
**Pull request by donho**
Fix #14416

### CODE REVIEW

**Comment by xomx** [comment]
@donho 
Please add also the following two items for the [TabBar](https://github.com/donho/notepad-plus-plus/blob/24d7777e5aff039c9423989d1c39d4d984b2536c/PowerEditor/installer/nativeLang/english.xml#L417):
```
<Item CMDID="10005" name="Move to Start"/>
<Item CMDID="10006" name="Move to End"/>
```

This for the:

npp-TabBar-MoveToStart End

**Comment by donho** [comment]
@xomx 
Strangely, in my v8.6.1 RC, I don't have these 2 items. Are you using the v8.6.1 RC for taking the screenshot?

**Comment by donho** [comment]
@xomx 
Just realized it's due to the presence of tabContextMenu.xml in my %APPDATA%\Notepad++. I will update tabContextMenu_example.xml.
Thank you for your heads up.
I'll do it in about 8 hours.

**Comment by donho** [comment]
@xomx 
Done: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d039eaa9009e3561589cb3b5e9849ab9aefa3e02

**Pull request closed without merging**
