### PR TITLE
Change foreground color for ERROR in JSON to be more readable

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8715. The red background for the ERROR is sufficient. I check also other themes and looks like they are readable enough. The only exception is `Solarized-light.xml` but here selected text is quite dark so setting black color for ERROR wouldn't look good.

### CODE REVIEW

**Comment by donho** [comment]
@ArkadiuszMichalski 
Do you mind to provide screenshot "Before" and "After" please?

**Comment by donho** [comment]
@ArkadiuszMichalski 
Thank you for providing the screenshots.
The middle line of "BEFORE" is improved indeed in "NOW", but the 1st line in NOW is less readable.
I have tried several colors, but cannot find a suitable foreground color.
Do you have a better suggestion other than black?

**Comment by ArkadiuszMichalski** [comment]
@donho
Maybe instead of the typical red background, use something brighter?
image

**Comment by donho** [comment]
@ArkadiuszMichalski 
OK for Orange variant.
Thank you

**Comment by ArkadiuszMichalski** [comment]
@donho 
Do you have any specific color value? Above is #FFA448 (255, 164, 72).

**Comment by donho** [comment]
@ArkadiuszMichalski 
No, I don't have any specific value.
The one you show me is perfect - you can just use it:
image

**Pull request closed without merging**
