### PR TITLE
Enable edit control highlight on focus

### PR DESCRIPTION
**Pull request by ozone10**
for incremental search and function panel
add initializers

image

Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13187

### CODE REVIEW

**Comment by donho** [comment]
The result looks nice in dark mode, but not in light mode:

image

Is it possible to be like comboboxes in Find in files while the edit control being on focus?

**Comment by Yaron10** [comment]
The result is fine with 96 DPI.
תמונה

**Comment by ozone10** [comment]
@donho 
unfortunately this is how Windows 11 highlight edit control.
To use "Windows 10" style, same as in dark mode, I would need to rewrite custom border subclass to allow light mode to use custom border. Also the same Windows 11 style  is already used in e.g. preference dlg, plugin admin dlg, ...

@Yaron10 
you have Windows 10

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2bf50bc191a580c4f57e90bddc8277a33ad03618

**Pull request closed without merging**
