### PR TITLE
Update german.xml to 7.7.2

### PR DESCRIPTION
**Pull request by schnurlos**
Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3f7956dc1bd16445f031a38bca8aa9e72806a408

### CODE REVIEW

**Comment by donho** [comment]
duplicated

**Comment by schnurlos** [comment]
Hi donho, why did you close both? This one should be merged ...

**Comment by schnurlos** [comment]
Not easy when the master file is changed before the commit is included ...

**Comment by donho** [comment]
Thank you for the update.
Sorry, I didn't check if your PR contain all the new added entries.  Could you check the file in the following issue : 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5962
and confirm me your PR contain all the new added entries, please?
If not, please add another commit to include all of them.
Thank you.

**Comment by schnurlos** [comment]
@donho, confirmed.

**Comment by donho** [comment]
@schnurlos 
After merging your PR into my local master, there are some repeated commits displayed by using `git log`. Apparently  your branch is not updated totaly with origin/master.

Could you redo your PR by following the following steps:
1. Force update your master by using the commands below: 
```
git fetch --all
git reset --hard origin/master
```
2. Create a new branch with a new name.
3. Make your modification and redo a PR.

Sorry for the inconvenience.

**Pull request closed without merging**
