### PR TITLE
Fixes for multi-line feature

### PR DESCRIPTION
**Pull request by AngryGamer**
Changes:

1. Text on tabs with multi-line are no longer clipped (g, y, etc).
2. Fix tab switching hotkeys  (**shift+MW**, **ctrl+MW**, **shift+ctrl+MW**)
3. Hijack **shift+MW** hotkey to move tabs rather than switch to them (while drag and drop enabled)
4. Fix drag and dropping tabs with multi-line enabled.

### CODE REVIEW

**Comment by donho** [comment]
Hi @AngryGamer Thank you for the patch.
> Text on tabs with multi-line are no longer clipped (g, y, etc).

I have never seen text clipped. Could you provide the instructions to reproduce it?

> Fix tab switching hotkeys (shift+MW, ctrl+MW, shift+ctrl+MW)

What do you mean by "MW" ?

> Fix drag and dropping tabs with multi-line enabled.

This is good definitely!

BTW, it'll be good have 4 commits for each enhancements.

**Comment by donho** [comment]
@AngryGamer 
Please do another PR which contains 4 commits for each enhancements.
It's just difficult to review your PR.

**Comment by bahusoid** [comment]
@donho Text is clipped for active tab. I've already uploaded example here:

**Comment by AngryGamer** [comment]
@donho 
MW = mousewheel

The hotkeys are used by clicking a tab and then holding ctrl and/or shift and scrolling the mousewheel.

**Comment by donho** [comment]
@AngryGamer I just cannot open the branch of this PR in Github desktop.
Could you open an another PR ?

**Comment by AngryGamer** [comment]
OK, re-opening PR.

**Pull request closed without merging**
