### PR TITLE
[XML] Update brazilian_portuguese.xml

### PR DESCRIPTION
**Pull request by Marcellomco**
Added translation for "Add Pin/Unpin Tab context menu item" and "Rename an option in Preferences dialog to fit other settings"

### CODE REVIEW

**Review by Marcellomco — COMMENTED** [review]
Synchronizing lines between this file and English.

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Update localization files to v8.7.3"

**Review by donho — CHANGES_REQUESTED** [review]
Please add a new entry also in Tabbar context menu, as latest commit in english.xml:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f18d99e24cb3609f912e7c7bf0f1d3de2b48268f

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Add a missing line to english.xml"

**Review by donho — APPROVED** [review]

**Pull request closed without merging**
