### PR TITLE
Updated piglatin file

### PR DESCRIPTION
**Pull request by bubbajdf**

### CODE REVIEW

**Comment by donho** [comment]
@bubbajdf  Could you translate new added SHA-256 feature (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/953919c4067c6ccbc3003adaad90074d621b0580) and plugin Admin (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5080fdf2d869db0138693965c8f546964917941f#diff-2a8496e2537c34b95cbeca007cd2346b) please?

**Comment by bubbajdf** [comment]
Ok will not be til next Wed,  I wrote a pho program to do it.

**Comment by bubbajdf** [comment]
Php not pho

**Comment by donho** [comment]
Please reopen it or redo a new PR when you rework on it.

**Pull request closed without merging**
