### PR TITLE
Update ukrainian.xml

### PR DESCRIPTION
**Pull request by a-polivanchuk**

### CODE REVIEW

**Comment by a-polivanchuk** [comment]
New translations for 7.8.6 included.

**Comment by donho** [comment]
Thank you @a-polivanchuk

**Comment by donho** [comment]
For the sake of workflow, you should create a new branch with a different name for per PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Comment by a-polivanchuk** [comment]
Ok, I created new PR #8114 from a new branch with the same changes in 1 commit.

**Pull request closed without merging**
