### PR TITLE
Message box on bad_alloc

### PR DESCRIPTION
**Pull request by tonyk24**
Handle bad_alloc in two places during find

### CODE REVIEW

**Comment by donho** [comment]
Please provide more description to explanation.
More accurate and detailed your explanation (with screenshots BEFORE/AFTER if possible), more chance that I take my time to review your PR.

**Comment by tonyk24** [comment]
For example when a allocation is failed on the following lines occur, a bad_alloc is thrown, due to heap allocation failed.
`		_pOldFoundInfos->insert(_pOldFoundInfos->begin(), _pMainFoundInfos->begin(), _pMainFoundInfos->end());
		_pOldMarkings->insert(_pOldMarkings->begin(), _pMainMarkings->begin(), _pMainMarkings->end());`

Before:
Search result is not displayed.

After
screenshot_bad_alloc1

**Comment by donho** [comment]
@tonyk24 Thank you for the explanation.
Could you please indicate me how to reproduce the bad allocation?

**Comment by bahusoid** [comment]
@donho You just need to open some really big binaryfile and try to find all spaces in it.

Here is I prepared 120Mb zip bomb :) . You can try to unzip it and open BigFile.txt and try to find all "1" in it.
[120MbBigFile.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1162113/120MbBigFile.zip)

**Comment by donho** [comment]
@bahusoid 
Thank you for the file. I have tried to produce the exception/crash with it but without success. It just hang and after applying this PR it's still the same result.

@tonyk24 You should provide the steps to reproduce the bug to prove that your PR fix the bug. Otherwise your PR won't be accepted.

**Comment by bahusoid** [comment]
@donho Have you tried with x86 build?

**Comment by donho** [comment]
Hmm... @bahusoid indeed for 32 bits it crashes (hang and disappear) for both builds before and after applying this PR.

**Pull request closed without merging**
