### PR TITLE
update chineseSimplied.xml

### PR DESCRIPTION
**Pull request by wwj402**
update chinese Simplied language

### CODE REVIEW

**Comment by popcorner** [comment]
I guess that you want to reorder the item in the xml file according to the english.xml, and fix some issues, right?
I checked the modification in your commit, and wrote some suggestions(in Chinese). You may consider about them.

**Comment by donho** [comment]
@wwj402  Could you take consideration of @popcorner suggestions please?

**Comment by donho** [comment]
@wwj402 Please reopen this PR while you do a new commit to reply @popcorner

**Comment by popcorner** [comment]
@donho this translation is already outdated. I'll make a new one which is up to date.

**Pull request closed without merging**
