### PR TITLE
Update ReadMe and Remove V2013 project

### PR DESCRIPTION
**Pull request by SinghRajenM**
1. Update readme.md
Now Notepad++ is built with VS2015 and **can't be built with VS2013** because JSON.hpp needs VS2015 or higher. So updated ReadMe, to reflect the same.

2. VS2013 is no longer needed
As Notepad can't be built with VS2013 anymore and to avoid confusion, VS2013 should be removed.

Reported Bug: #4008

### CODE REVIEW

**Comment by donho** [comment]
@SinghRajenM Have you tried to build Scintilla with PCRE support under VS2015 ?

**Comment by SinghRajenM** [comment]
@donho No, I just tried without PCRE support and it worked fine. Now, I downloaded boost1.55 and it looks like VS2105 is not supported for Boost1.55. So let's drop idea to update readme. We can update it later when we move to latest scintilla.

**Comment by donho** [comment]
Please reopen it when boost support VS2015

**Comment by CookiePLMonster** [comment]
VS2015 is supported since a while - but boost 1.55.0 is too old to support it. 1.66.0 supports even VS2017.

**Pull request closed without merging**
