### PR TITLE
[xml] Update polish.xml to 8.6.9

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Update polish.xml to 8.6.9 according to the last commit.

### CODE REVIEW

**Comment by GOLEM777** [comment]
New lines in darkMode block:
```
<Item id="7136" name="Red"/>
<Item id="7137" name="Green"/>
<Item id="7138" name="Blue"/>
<Item id="7139" name="Purple"/>
<Item id="7140" name="Cyan"/>
<Item id="7141" name="Olive"/>
```

**Comment by ArkadiuszMichalski** [comment]
@GOLEM777 I don't really understand, I don't see anything like that in the current code:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml#L1015

**Comment by GOLEM777** [comment]
Last acept Pull
[preference_rc.h](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5501485c0bce1f5f8e3402374d96e5b830ef413e#diff-f437a14797d62f457784fb0f442a504d95d081379968c32837dd0d0d98e33dab)

**Comment by ArkadiuszMichalski** [comment]
The reference for translations is the file:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

If something is missing, please open a new issue. However, in this case, the translations for these reset fields are dynamically retrieved based on already existing entries, so additional elements in the xml file are not needed.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5501485c0bce1f5f8e3402374d96e5b830ef413e#diff-686f6d3c1ec15b51f312bb5a68130dfa62292a8d19594fb0f3621c179970fa1fR1699

**Comment by GOLEM777** [comment]
You're right, my bad!

**Pull request closed without merging**
