### PR TITLE
Fix bug recording find dialog text.

### LINKED ISSUE #13565: Regression: macro is not saved properly
**STR:**
Open a file containing the word `cpp`.
Start recording a macro.
Open the Find dialog.
Search for `cpp` in the current document.
Stop recording the macro.
Save the macro.
Run the saved macro.

**Result:**
A search for `c` is executed.

***
Current master: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0457a112c76ddc883a99074cf459a970741cf5b6.

### PR DESCRIPTION
**Pull request by doug1234**
Fixes #13565.

### CODE REVIEW

**Comment by Yaron10** [comment]
@doug1234,

👍 
Thank you for looking into it and fixing the issue.

1. I should have mentioned that the problem exists in other Find/Replace operations as well (e.g. Find in Files).
2. Can't you use `wstring2string()`?

**Comment by donho** [comment]
> 1. I should have mentioned that the problem exists in other Find/Replace operations as well (e.g. Find in Files).

@Yaron10 
Could you provide scenario for the bug reproduction here please?

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13565#issuecomment-1519059105.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c76f178534bba518f263c8120b732801e13c4916

**Pull request closed without merging**
