### PR TITLE
Reword command name of Run menu's Open file in new instance

### LINKED ISSUE #9724: Cannot spawn another instance of Notepad++ for an empty non-saved document tab
### Description of the Issue
Cannot spawn another instance for a new document tab that have never been saved.

### Steps to Reproduce the Issue
1. Open Notepad++ with other documents open in tabs.
2. Click "File -> New".
3. Drag the new tab off Notepad++ to spawn another shell.  It doesn't work.

Workaround is to type something, save the document as new.txt or whatever, and drag that tab off Notepad++.   Then, a new notepad++ will be spawned but the document had to be saved first.

### Expected Behavior
A new spawned Notepad++ with new empty non-saved tab.

Alternatively, the File menu could have a menu option to spawn a new Notepad++ with an empty non-saved tab.

### Actual Behavior
Notepad++ does not allow spawning another Notepad++ for a non-saved new document tab.

### PR DESCRIPTION
**Pull request by sasumner**
Fix #9724

...at least the really broken part.

@donho I saw no reason for `$(CURRENT_WORD)` to be a parameter to the command, so this PR removes it -- do you see any reason for it to be there?  I suspect a copy-paste-forgetToRemove bug from the previous command when this one was created.

### CODE REVIEW

**Comment by donho** [comment]
`$(CURRENT_WORD)` should be kept and "Open file in another instance" should be "Open file in another instance via selected file path". However, it's too long as menu entry name. If you have any suggestion for a better menu entry name, please let me know.

**Comment by mere-human** [comment]
Maybe, show a tooltip that says the selected word will be used as a file path?

> `$(CURRENT_WORD)` should be kept and "Open file in another instance" should be "Open file in another instance via selected file path". However, it's too long as menu entry name. If you have any suggestion for a better menu entry name, please let me know.

**Comment by sasumner** [comment]
How about ""Open selected file path in new instance?"

**Comment by donho** [comment]
@sasumner 
OK for me.

**Comment by sasumner** [comment]
@mere-human said

>Maybe, show a tooltip that says the selected word will be used as a file path?

I don't think tool tips are supported on menu items, but that might be a useful thing for the future.

**Pull request closed without merging**
