### PR TITLE
Update czech.xml

### PR DESCRIPTION
**Pull request by xomx**
Fixes for the Dark Mode panel new options.

### CODE REVIEW

**Comment by donho** [comment]
Here is the diff between v8.1.2 & v8.1.3:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10297

Could you check it and confirm me it's all done (or you prefer do it later in the next release)?
Thank you.

**Comment by xomx** [comment]
@donho 
It is done.

**Comment by donho** [comment]
@xomx 
Could you resolve the conflict?

**Comment by xomx** [comment]
@donho 
It should be resolved now.

**Comment by donho** [comment]
@xomx
While doing rebase, I've got the following message: 
```
$ git rebase -i
error: could not apply 6009e93e... Update czech.xml to v 8.1.3
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 6009e93e... Update czech.xml to v 8.1.3
Auto-merging PowerEditor/installer/nativeLang/czech.xml
CONFLICT (content): Merge conflict in PowerEditor/installer/nativeLang/czech.xml
```
This PR won't be merged.
Please do a new PR with a new branch from the current master.

**Pull request closed without merging**
