### PR TITLE
Improve Copy-Selected-Lines

### LINKED ISSUE #15803: [BUG] "Copy Selected Line(s)" in Search-results sometimes has unexpected behavior
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

(Some would see this as a Feature Request; I see it as a Bug because unexpected behavior is obtained)

---

Sometimes I am sloppy with selecting text when using _Copy Selected Lines_, example:

image

My intent here is to put exactly this into the clipboard:

```txt
01 : The quick brown fox jumped over the lazy dogs.
01a : The quick brown dog jumped over the lazy foxes.
```

But after I execute _Copy Selected Line(s)_ I obtain (in the clipboard):

```txt
01 : The quick brown fox jumped over the lazy dogs.
01a : The quick brown dog jumped over the lazy foxes.
02 : The quick brown fox jumped over the lazy dogs.
02a : The quick brown dog jumped over the lazy foxes.
```

### Steps To Reproduce

1.  See Description above
2.  
3.  

### Current Behavior

Less than obvious copying behavior.

### Expected Behavior

Better behavior would be to only copy the "Line" data from lines touched by the stream selection the user has made.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (3.0.16)
```

### Anything else?

As a convenience functionality, if there is no selected text at time of right-click, and...
* ... the line right-clicked is a Pathname line, copy the data for all Line text hierarchically below that Pathname (until either the following Pathname -- or Search line -- is encountered)
* ... the line right-clicked is a Search line, copy the data for all Line text hierarchically below that Search line, for all Pathnames (until the following Search line is encountered)

### PR DESCRIPTION
**Pull request by alankilborn**
Fix #15803

### CODE REVIEW

**Comment by alankilborn** [comment]
Closed due to "please don't" comment here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15803#issuecomment-2499289745

**Comment by alankilborn** [comment]
Reopened due to request here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15803#issuecomment-2525825647

**Comment by donho** [comment]
@alankilborn 

Here's my test:

image

The result of my test:
```
B.1 yellow bird & blue rain & purple ribbon
B.2 yellow bird & blue rain & purple ribbon
B.3 yellow bird & blue rain & purple ribbon
B.4 yellow bird & blue rain & purple ribbon
C.1 purple bird & yellow rain & blue ribbon
C.2 purple bird & yellow rain & blue ribbon
C.3 purple bird & yellow rain & blue ribbon
C.4 purple bird & yellow rain & blue ribbon
```

Shouldn't it be rather : 
```
B.1 yellow bird & blue rain & purple ribbon
B.2 yellow bird & blue rain & purple ribbon
B.3 yellow bird & blue rain & purple ribbon
B.4 yellow bird & blue rain & purple ribbon
```
according the spec as we both agreeed?

**Comment by donho** [comment]
@alankilborn 
Please ignore my previous message: that was my bad - I switched the wrong PR (that is also your PR).

**Pull request closed without merging**
