### PR TITLE
GUI Enhancement: Plugins Admin dlg

### LINKED ISSUE #13622: [GUI] Plugins Admin dlg key accelerators
### Description of the Issue

image
Missing key accelerators.
### Steps to Reproduce the Issue

1. Open Plugins Admin via keyboard

### Expected Behavior

Key accelerators
### Actual Behavior

No key accelerators
### Debug Information

Notepad++ v8.5.2

### PR DESCRIPTION
**Pull request by ozone10**
add key accelerators
remove unused define
add initializers
fix override warnings
optimize dark mode
resize listview controls based on other child controls
image

fix #13622

### CODE REVIEW

**Comment by Yaron10** [comment]
@ozone10,

Great. 👍 
Thank you for that too.

Personally I'd prefer a much smaller width.
What do you (and @donho) think?

**Comment by donho** [comment]
@Yaron10 
> Personally I'd prefer a much smaller width.

Do you mean smaller height? The width of dialog in this PR has not changed, but its height is reduced.

**Comment by ozone10** [comment]
Fix merge conflict

**Comment by ozone10** [comment]
@Yaron10 
>Personally I'd prefer a much smaller width.

You mean like this
image

**Comment by Yaron10** [comment]
@donho,

The height was reduced. I thought that it would be nicer and more proportional if the width should be reduced as well.

Thank you.

@ozone10,

Your new design is much nicer IMO.

`const long margeX = ::GetSystemMetrics(SM_CXEDGE);`
Great. 👍 

Thank you.

***

Perhaps even narrower?

תמונה

**Comment by donho** [comment]
@Yaron10 
> The height was reduced. I thought that it would be nicer and more proportional if the width should be reduced as well.

Please create an issue and ping me - I will see what I can do about it.
Or, @ozone10 you may do a PR, if you are interested in doing it.

**Comment by Yaron10** [comment]
@donho,

@ozone10 did a great job, and I'd rather not open an issue for a minor visual preference.

Thank you!

**Pull request closed without merging**
