### PR TITLE
Update Corsican translation for Notepad++ 7.8.9

### PR DESCRIPTION
**Pull request by Patriccollu**
Same changes as PR #8492 but using a brand new branch (after deleting my local NPP repository)

### CODE REVIEW

**Comment by Patriccollu** [comment]
Added changes for these latest commits: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7d289139e8d370da422bd4a74f8c878e537db172, https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84ea510b67dec193eee605a1cca723151ef80448, https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5ba7f99590b6ade8a5fb13edc7cb9f9f0981e18f

**Comment by Patriccollu** [comment]
Added change for latest commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f1b059414b95fa49c164adaa3cca4e11691bf789

**Comment by Patriccollu** [comment]
Added change for latest commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ca3d5147228b351b66b6af410faec195fdc9b938

**Comment by Patriccollu** [comment]
Added change for recent commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/33f042932f0b9faf4b1fe899a6b76c6bfaa25f41

**Comment by Patriccollu** [comment]
Added change for recent commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3a2edb99c40f5577a29307f1321d9a3cbe2a69cb

**Comment by Patriccollu** [comment]
Added change for these recent commits: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ddd2e5fd23412d5e8410c2a821461f1f578bca0f and https://github.com/notepad-plus-plus/notepad-plus-plus/commit/209ccb97ecaf3c16a66b8401d4c2a594576b0c66

**Comment by Patriccollu** [comment]
Added change for commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0fe971ca8888f97f17381d1a5520a7b383eac617

**Comment by Patriccollu** [comment]
Added change for commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84430809df2f6607a3bc5b9f05866149842f2bd9

**Comment by donho** [comment]
@Patriccollu 
Thank you for your update. 
Could you check the diff from 7.8.9 to the newest `english.xml` to make sure there's nothing's missing?
http://download.notepad-plus-plus.org/repository/MISC/diff/english.diff.htm

**Comment by Patriccollu** [comment]
@donho 
Hi Don,

I just double checked the WinMerge comparison and can confirm the Corsican file contains all the changes. I also modified some keyboard shortcuts on the Replace dialog.

Cheers,
Patriccollu.

**Pull request closed without merging**
