### PR TITLE
Update dutch.xml

### PR DESCRIPTION
**Pull request by rvangeijtenbeek**
Please don't translate 'Fluent UI', this is the name of a Microsoft UI library.

### CODE REVIEW

**Comment by donho** [comment]
Thank you for the localization file update.
Please check the newest localization file update: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10160 and confirm me your update is updated.

**Comment by RockyTDR** [comment]
Please cancel this pull request. I incorporated the changes from this PR into my own (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10105)

@rvangeijtenbeek please don't create pull requests for Dutch, but contact me directly when you have feedback, so I can apply your edits myself. This will make it easier for me to manage the translations in the future. Thanks!

**Comment by rvangeijtenbeek** [comment]
> Please cancel this pull request. I incorporated the changes from this PR into my own (#10105)
> 
> @rvangeijtenbeek please don't create pull requests for Dutch, but contact me directly when you have feedback, so I can apply your edits myself. This will make it easier for me to manage the translations in the future. Thanks!

Thanks. This is new for me, didn't see an easy way to contact you.

**Comment by RockyTDR** [comment]
> Thanks. This is new for me, didn't see an easy way to contact you.

I'll add an email address to the next version of the translation file 😉

**Pull request closed without merging**
