### PR TITLE
Fix for PERL parser Regression of Function List Update 2.

### LINKED ISSUE #2963: Function list doesn't work with Perl since 7.3.2
### Description of the Issue
On perl-code the function list is empty
This doesnt't work for .pm and .pl files. 
On v7.3.1 of npp the recognition works fine.

### Steps to Reproduce the Issue
Open a file (.pl or .pm) with functions included

### Expected Behavior
List of function and classes

### Actual Behavior
Empty function list

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\editor\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 8.1 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll FingerText.dll jN.dll MathPad.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppQCP.dll NppSnippets.dll NppTextFX.dll PluginManager.dll PythonScript.dll RunMe.dll SourceCookifier.dll SpellChecker.dll

### PR DESCRIPTION
**Pull request by MAPJe71**
This fixes #2963.

### CODE REVIEW

**Comment by donho** [comment]
@MAPJe71 Thank you for the PR. Have you reversed this part to v7.3.1 ?
I have checked in v7.3.1, it seems Perl parser doesn't work neither.
I will check more in detail - if it has never worked, it'll be better to remove this parser.

**Comment by MAPJe71** [comment]
@donho Yes I reversed the PERL parser to the one of v7.3.1 after checking it does list subroutines.
The following image shows the result of this PR's `functionList.xml` active in Notepad++ v7.3.2.

capture-2017-03-02-09 42 30


[example.2.pl](https://github.com/notepad-plus-plus/notepad-plus-plus/files/813178/example.2.pl.txt)

**Comment by ldavoine** [comment]
It does not work for me on Notepad++ v7.3.2. The general form of a subroutine definition in Perl programming language is :

```
sub subroutine_name{
   body of the subroutine
}
```

not 

```
sub subroutine_name**()** {
   body of the subroutine
}
```

and the parser does not recognize this syntax. In previous versions it worked :(

Thanks.

**Comment by MAPJe71** [comment]
@Idavoine
> It does not work for me on Notepad++ v7.3.2.

Presuming you installed the patch, did you update the right `functionList.xml` as there might be more then one on your system?
Both subroutines show up just fine ...

capture-2017-04-04-17 18 24

**Comment by KptainBiwouak** [comment]
I have just updated Perl & Python parsers from previous FunctionsList.xml (7.3.2) and it works.
Consider it as a workaround until FunctionsList.xml provided with official delivery will support these 2 languages.

**Comment by akela68** [comment]
This bug comes up with every update of npp. The xml-file not updates in the releases. Please can any developer do this in the next release?
Thank's

**Comment by akela68** [comment]
This solution doesn't work for npp 7.4.1

**Comment by ldavoine** [comment]
Hi,

I've just installed the 7.4.1 version from the [website](https://notepad-plus-plus.org/repository/7.x/7.4.1/npp.7.4.1.Installer.exe) and it still does not work for me. 

To be sure, i have also downloaded the last "FunctionList.xml" from the [GitHub repository](https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/PowerEditor/src/functionList.xml). I have exactly the same on my PC ("C:\Program Files (x86)\Notepad++\functionList.xml")

You can see the problem [here](http://ludoda.free.fr/NOTEPAD.jpg). The PERL functions are still not recognized but in old versions of Notepad++ it worked perfectly :(

Do i have to do something else ? Is the right "FunctionList.xml" file on another repository ?

Thanks.

I'm sorry to bother you...

**Comment by akela68** [comment]
Hi Idavoine,

this file doesn't work for me too. Use the file from the developer. This works for me.
https://github.com/MAPJe71/Notepad-Plus-Plus_Fork/blob/f227ba20dfdbcad26dc803f959c9ec985f3ceff0/PowerEditor/src/functionList.xml

**Comment by MAPJe71** [comment]
Superseded by #3393

**Comment by akela68** [comment]
Hi,

on every update npp lost the functionlist-functionality for perl. Why?
Is there a persistent solution without permanently override the functionList.xml ?

Bye Andreas

**Pull request closed without merging**
