### PR TITLE
Unify line ending terminology

### LINKED ISSUE #2038: Line ending encoding sounds like a Mexican restaurant
On a Windows installation, in the status bar, the defaults encoding shows `Dos\Windows`. At least it's a well-lit restaurant with good views. :-) Still, the text would be better as `DOS/Windows`, or still better, given that its 2016, just `Windows`. A side benefit is that the slash grammar police won't get you.

There's also the issue that the encoding names displayed on the status bar don't match the ones in the context menu. They should be harmonized.

### PR DESCRIPTION
**Pull request by dail8859**
Closes #2038 

Currently there are inconsistencies when using EOL terminology. I have changed occurrences to use (and maintain this order):

- `Windows (CR LF)`
- `Unix (LF)`
- `Macintosh (CR)`

I am open to suggestions but I feel this is fairly straight forward, unambiguous, and this is exactly how MSVC displays them in their menu.

Before:

menu
settings
bar

---

After:
menu_after
settings_after
after_bar

### CODE REVIEW

**Comment by vlakoff** [comment]
We should emphasize that Macintosh actually uses LF.

Maybe we could just drop the CR option?

**Comment by Eldaw** [comment]
I submitted an excellent pull request some time back to address this issue, which also addressed the fact that Macintosh uses LF (by calling the CR one 'Classic Mac'). Unfortunately it was rejected by Don Ho for a reason that made no sense.
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/787

**Comment by vlakoff** [comment]
How about this?

Windows (CR LF)
Unix / Mac (LF)
Old Mac (CR)

The important part is to not trick Mac users into using CR.
Also, many Mac users probably don't know they are using a Unix system.

**Comment by dail8859** [comment]
@Eldaw Interesting...never realized there was a PR so similar.

I'm not attached to the terminology I used, it's what Visual Studio used so figured it was an OK way of doing it. I understand that VS is targeted to a more technical audience than N++ is. Presumably in the majority of cases (not all) if a user is converting line endings they have some idea what line endings they want even without terminology.

I think it is important to keep the CR/LF/CRLF terminology that way if someone disagrees with the naming scheme they can at least know exactly what line endings they are converting to.

> The important part is to not trick Mac users into using CR.
Also, many Mac users probably don't know they are using a Unix system.

I totally agree, however most Mac users probably don't know the difference between "Mac" vs "Old Mac" (although maybe they do? I'm not a Mac person :) ).

**Comment by vlakoff** [comment]
> I totally agree, however most Mac users probably don't know the difference between "Mac" vs "Old Mac" (although maybe they do? I'm not a Mac person :) ).

Agree, I just tried to get a concise result, and I got not satisfying result using "Mac OS X" or "OS X".

That's why I suggested above to remove the CR mode.
Useless (unless proven otherwise), no more confusion to worry about.

**Pull request closed without merging**
