### PR TITLE
Update hungarian.xml file

### PR DESCRIPTION
**Pull request by montlikadani**
What we talked about at Crowdin is here now.

**If possible, in the coming days when texts are given to the program, be sure to insert the language into the file.**

### CODE REVIEW

**Comment by batagy** [comment]
Hi!

This is not proper translation request.
I'm the Hungarian language translator of Notepad++ since 2004 (14 years now). 
This Pull request contains several changes of old strings, without any explanation. At least I was not informed or nobody looked for me. Even though I always appreciate improvements in my translation work.

The official Hungarian translation update is done now in PR #4308 .
This current request should be rejected. At least user should discuss with me.

Regards
György

**Comment by a-polivanchuk** [comment]
Hi @batagy,

I propose you to join and lead Hungarian team on Crowdin.
https://crowdin.com/project/notepadpp
You'll be able to maintain your translations easily.
There are also other translators so you can collaborate together in a centralized way.

Thanks,
Artem

**Comment by a-polivanchuk** [comment]
Hi @batagy 

Please join Hungarian on Crowdin. I'll grant you the proofreader permission and update the locale with the latest strings from GitHub, so you can continue work together with other localizers.

**Comment by batagy** [comment]
@a-polivanchuk 
Hi Artem, I've registered now and asked for join for Notepad++ team.
But actually I don't understand the purpose of that whole Crowdin project. Is that approved by Don? Why do we need another repository or place for translation work? György

**Comment by a-polivanchuk** [comment]
The purpose is to have a centralized resource for work with more than one translator as well as powerful translation workflow.

**Comment by a-polivanchuk** [comment]
@batagy Hello,
Could you please review the  new translations and prepare an update for your locale:
https://crowdin.com/project/notepadpp

**Comment by batagy** [comment]
@a-polivanchuk Hi. OK, I'll check.

**Pull request closed without merging**
