### PR TITLE
Corrected order for "(\r, \n, \t, \x…, \0)" for all languages

### PR DESCRIPTION
**Pull request by h-h-h-h**
- Corrected language files that were not already adhereing to the reorder of `\r, \n, \t, \x…, \0` (find-and-replace dialog)
- Used Unicode ellipsis character
- I don't know where `danish.xml` got its `\u` from, but I think it's safe so remove it: `"Udvidet (\n, \r, \t, \0, \u, \x...)"`
- `turkish.xml` proves that there has been misunderstanding with `\x...` at the end of the list: `"&amp;Genişletilmiş (\n, \r, \t, \0, \x, …)"`

### CODE REVIEW

**Comment by donho** [comment]
What's the reason for such order?

**Comment by h-h-h-h** [comment]
It was already accepted: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/574. This is just for the remaining languages.

**Comment by donho** [comment]
Please check the comment of this commit:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c2eb1e191970efcd4891455d8865a0f035440325

**Comment by h-h-h-h** [comment]
See also there. (Are you subscribed to commit discussion?)

**Pull request closed without merging**
