### PR TITLE
Update ukrainian.xml

### PR DESCRIPTION
**Pull request by a-polivanchuk**
This is the next update of Ukrainian translation.

### CODE REVIEW

**Comment by popcorner** [comment]
There is another translation #2764

**Comment by a-polivanchuk** [comment]
Yes I sow it. There is a bunch of corrections for current translation and I asked the author to join our team on Crowdin.

Anyway, I would suggest to merge this PR first and wait for the reply from other PR.

Is it possible?

Thanks!

**Comment by donho** [comment]
@a-polivanchuk I just add a new feature and several new translations:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6a05bedd05cbfce40106aa464e43448639d1913b#diff-2a8496e2537c34b95cbeca007cd2346b

Could you update the PR please? (so I can include it in new release)

And also please consider #2703 : `<Item id="44097" name="Моніторинг (слідом -f)"/>` is just wrong.

**Comment by donho** [comment]
thank you @a-polivanchuk

**Pull request closed without merging**
