### PR TITLE
Create ISSUE_TEMPLATE.md

### LINKED ISSUE #1496: Template for New Issues
@donho [Issue templates](https://github.com/blog/2111-issue-and-pull-request-templates)!!!!

Would be very useful to have!

### PR DESCRIPTION
**Pull request by dail8859**
Since alot of people create really unhelpful issues...hopefully this will help. Feel free to add/remove to this as you see fit. Closes #1496

### CODE REVIEW

**Comment by milipili** [comment]
Maybe we should add something about plugins ? :)

**Comment by dail8859** [comment]
I just threw this together real quick so I'm open to suggestions! :)

**Comment by dail8859** [comment]
@donho ping

**Comment by donho** [comment]
@dail8859 Generally I'm not for such procedure - too many procedures make no procedure.
But let's give it a try.

**Comment by donho** [comment]
@milipili  What do you mean by "add something about plugins" here?

**Comment by dail8859** [comment]
Fair enough. If you feel it does not turn out to be beneficial we can always remove it.

**Comment by milipili** [comment]
I like this. It is not really a procedure, but an helpful guide to help people to fill bug reports.

**Comment by milipili** [comment]
@donho Something like "please report your plugin list" or "is the problem reproductible without plugins ?". Something like that. The idea is to limit the bug reports linked to problem, or to help to solve them if some well-known buggy plugin appears.

**Comment by donho** [comment]
@milipili In `### Debug Information`
There'll contain the list plugin user has installed.

**Pull request closed without merging**
