### PR TITLE
[Fixed issue] - Detect Line ending changes on Reload

### PR DESCRIPTION
**Pull request by SinghRajenM**
Fixed issue #4033

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Ouch, haven't noticed your pull request before submitting #4077... not sure what to do now, since I also corrected detecting encoding on reload (so default encoding for ANSI files is respected when reloading) :/

**Comment by SinghRajenM** [comment]
> Ouch, haven't noticed your pull request before submitting #4077... not sure what to do now

No problem. I feel it is ok to keep the both PR active and let @donho decide which/how to merge.

**Comment by CookiePLMonster** [comment]
That's cool then =) I guess if your PR gets merged first then mine will throw some merge issues, which actually won't be merge issues (as it's 1:1 code), and thus both can work together just fine.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/46d0f12c3e687c83efbaa04f7ebd95616678226c

**Pull request closed without merging**
