### PR TITLE
langs.model.xml: Additions to PHP highlight

### PR DESCRIPTION
**Pull request by Rikk**
+ Add some extensions.
+ Additions to PHP highlight:
  * Added/updated huge amount of PHP Functions of several categories: Filesystem, Directory, Program execution, Fileinfo, Date/Time Functions, Calendar, Variable handling, Function handling, Array, Filter, Classes/Object, String, POSIX Regex, Output Control, Password Hashing, OpenSSL, Mcrypt, Mhash, Hash, FTP, SSH2, cURL, LDAP, IMAP, Network, JSON, URL, Stream, XML Parser, Misc., GD and Image, Exif, Zip, Zlib, Apache, PHP Options/Info, Error Handling, Semaphore.
  * Update functions related to databases (*sql_ ; sqlite_ ; odbc_ ; dba_), also adding MySQLi and MaxDB procedural style commands.
  * Added/updated PHP Reserved Words, Control Structures, and Predefined Constants from these categories: Network, Core, Magic constants, Arrays, Filter, URLs, Streams, Strings, Output Control.
  * Removed duplicates and sorted.
  * Break too long lines (>10k chars) so the entire file display properly in SmartGit.

### CODE REVIEW

**Comment by Rikk** [comment]
Closes https://github.com/notepad-plus-plus/notepad-plus-plus/issues/459

**Comment by milipili** [comment]
For the next time please create several PR (or at least several commits) since it involves different kind of fixes (php, bash...)  :)

**Comment by Rikk** [comment]
>For the next time please create several PR (or at least several commits) since it involves different kind of fixes (php, bash...) :)
Okay... I made only one commit just because another time you asked me to do so...

*(anyway, I think it was a bit more easy to keep adding things into just one commit than would be into two)*

**Comment by milipili** [comment]
Sorry if it seems inconsistent. For commits, the rule that I would like to follow is "a commit for a single thing", so that the history can be read easily. As a second though, since it can be difficult sometimes to choose, several commits should always be fine now since the merge from github will be no longer used and it is easy to squash the commits if needed.

**Comment by milipili** [comment]
(and I agree with you, most of the time it is easier with one single commit ^^)

**Pull request closed without merging**
