### PR TITLE
Restore commit history prior to 2009-04-24

### PR DESCRIPTION
**Pull request by azabluda**
Hello @donho 

Glad to see that the project has finally moved to Github. My congratulations!

I just noticed that for some strange reason the [old history](https://github.com/azabluda/notepad-plus-plus/commits/6b0cfa6bb62f0106603a4eb3c32d2e9209793093) (before 2009-04-24) hasn't been imported. So I made a couple of trivial manipulations in Git to bring it back. Unfortunately we can't append it to the bottom of the new history (2009-04-25 and after) without rewriting all further commit hashes, but I suggest at least to merge it into the master tip as a zero-change branch.

Regards,
AZ

### CODE REVIEW

**Comment by ariccio** [comment]
Huh, this is interesting. How'd you do it?

**Comment by azabluda** [comment]
Hi @ariccio, I just used to keep the old SVN history in my local Git repo (fetched some time ago from svn://svn.tuxfamily.org/svnroot/notepadplus/repository). The exact technique of integrating it into the current 'master' is simple, and the easiest for you would be to just fetch my branch and study (e.g. in TortoiseGit or SmartGit) the two commits e10294a and 7af2cc5. Once this PR is accepted 7af2cc5 can be seamlessly merged into the official 'master' as it doesn't carry any actual modifications (see "Files changed: 0" in GitHub UI)

**Comment by Croydon** [comment]
Why are there PRs which don't get any official reaction in 8 months?

**Comment by donho** [comment]
@azabluda Thank you: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/24bb021d711b64aa845da564cb7dfdcf26d1a19d

**Pull request merged**
