### PR TITLE
Update czech.xml translation

### PR DESCRIPTION
**Pull request by darBis**
save changes dialog - added missing accelerator keys for buttons

### CODE REVIEW

**Comment by xylographe** [comment]
@darBis
 Could you also add _SHA256FromFilesDlg_ and _SHA256FromTextDlg_.
 They are ver similar to _MD5FromFilesDlg_ and _MD5FromTextDlg_, respectively.
```
	<SHA256FromFilesDlg title="Generate SHA-256 digest from files">
		<Item id="1922" name="Choose files to generate SHA-256..."/>
		<Item id="1924" name="Copy to Clipboard"/>
		<Item id="2"    name="Close"/>
	</SHA256FromFilesDlg>

	<SHA256FromTextDlg title="Generate SHA-256 digest">
		<Item id="1932" name="Treat each line as a separate string"/>
		<Item id="1934" name="Copy to Clipboard"/>
		<Item id="2"    name="Close"/>
	</SHA256FromTextDlg>
```
```
	<MD5FromFilesDlg title = "Generování unikátního MD5 klíče ze souborů">
		<Item id = "1922" name = "Vyberte soubory pro generování MD5..."/>
		<Item id = "1924" name = "Kopírovat do Schránky"/>
		<Item id = "2"    name = "Zavřít"/>
	</MD5FromFilesDlg>

	<MD5FromTextDlg title = "Generování unikátního MD5 klíče">
		<Item id = "1932" name = "Brát každý řádek jako separátní textový řetězec"/>
		<Item id = "1934" name = "Kopírovat do Schránky"/>
		<Item id = "2"    name = "Zavřít"/>
	</MD5FromTextDlg>
```

**Comment by darBis** [comment]
ok, I will add those.

**Comment by darBis** [comment]
I have noticed an issue with translation of "from files" dialog. The button for selecting input files if fixed width and its text is getting clipped.
I have checked other translations and for example a french translation experiences the same issue.
obrazek

**Comment by xylographe** [comment]
Thank you, @darBis. Looking good,

SHA256

I increased the width of the button from 131 to 190. This will also be useful for some other languages. I will create a PR later this week (the CheckBox in FromTextDlg also should be a little wider for some languages). I've also noticed another problem that can be easily fixed.

**Pull request closed without merging**
