### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
Add new section missing
Revise some strings.

### CODE REVIEW

**Comment by bovirus** [comment]
@donho 

Could you please check, and apply these language check?

Could you please check (and apply if you can) several pending request about other languages?

Thanks.

**Comment by donho** [comment]
Thank you for the update.
Sorry, I didn't check if your PR contain all the new added entries.  Could you check the file in the following issue : 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5962
and confirm me your PR contain all the new added entries, please?
If not, please add another commit to include all of them.
Thank you.

**Comment by bovirus** [comment]
@donho 

Probably I will make another PR for a Italian language update.
About post https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5962 in the text

<Item id="1721" name="â–²"/> 
<Item id="1723" name="â–¼ Find Next"/> 

I just have a doubt of character  â.

**Comment by donho** [comment]
Use the same PR please.
No need to recreate another one.

**Comment by bovirus** [comment]
Update Italian language

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5977

tested as comparison with English one.

**Comment by donho** [comment]
@bovirus 
Please close this one then.
Keeping both opened will make both closed by team, because we don't know which one we should merge.

**Comment by bovirus** [comment]
Done. Thanks.

**Pull request closed without merging**
