### PR TITLE
Resolve issue for create another tab with name new0 after closing first one

### PR DESCRIPTION
**Pull request by ibesedin**

### CODE REVIEW

**Comment by Rikk** [comment]
What if someone saves "new 0.txt", closes it, he will start another "new 0" one? He would need to rename it on save...
Looks a bad change, imo.

**Comment by ibesedin** [comment]
This situation can be with any file of name "new ##" (both on my and master version), it depends on amount of created unsaved tabs. I doesnt create new functionality, I try to fix different behaviour of creating new tabs.

**Comment by Eldaw** [comment]
Does this resolve issue #182 I created some time ago?

**Comment by ibesedin** [comment]
yes. i hope

**Comment by Rikk** [comment]
Maybe the fix here should be a single variable change, so it always start in "new 1" instead of "new 0". This looks a traditional behavior in many programs, eg. Photoshop starts with "Untitled-1".

[Buffer.cpp line 1109](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1109)
```diff
-	wsprintf(nb, TEXT("%d"), 0);
+	wsprintf(nb, TEXT("%d"), 1);
```
(Not sure if this one also needs change in this case: `_pscratchTilla->execute(SCI_ADDREFDOCUMENT, 0, doc);`)

**Comment by ibesedin** [comment]
if you want to start counting unsaved files from 1 i think its need to create another issue and close #182 in same time. imo initial number isn't matter

**Comment by donho** [comment]
This PR fixes the bug partially.

**Pull request closed without merging**
