### PR TITLE
Scintilla 5.4.1 and Lexilla 5.3.0

### PR DESCRIPTION
**Pull request by chcg**
Scintilla https://www.scintilla.org/scintilla540.zip

Release 5.4.0

    Released 18 November 2023.
    Fix crashes on macOS 12 and older when built with Xcode 15.0.

Lexilla https://www.scintilla.org/lexilla529.zip

Release 5.2.9

    Released 18 November 2023.
    Xcode build settings changed to avoid problems with Xcode 15.0.

### CODE REVIEW

**Comment by Yaron10** [comment]
@chcg,

You've reverted https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4ff9d77d2bfbb323e2fcba10f02570710872db94#diff-20e695d3c03a3258299dab9fc6a0684b04dcb9f0d12d8893f8d19f273ae6c453. :)

Thank you.

**Comment by rdipardo** [comment]
> ```
> ...
> Fix crashes on macOS 12 and older when built with Xcode 15.0.
> ```
> ...
> You've reverted [4ff9d77#diff-20e695d3c03a3258299dab9fc6a0684b04dcb9f0d12d8893f8d19f273ae6c453](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4ff9d77d2bfbb323e2fcba10f02570710872db94#diff-20e695d3c03a3258299dab9fc6a0684b04dcb9f0d12d8893f8d19f273ae6c453). :)
> 

Surely this release can be skipped? The upstream changes have nothing to do with Notepad++ or even Windows.

**Comment by chcg** [comment]
@Yaron10 Thanks for heads up on this merge issue.
Indeed there seems to be no N++ relevant fix within this release of scintilla/lexilla.

**Comment by Yaron10** [comment]
@chcg,

👍 
Thank you.

**Comment by chcg** [comment]
Updated to Scintilla

[Release 5.4.1](https://www.scintilla.org/scintilla541.zip)

    Released 27 December 2023.
    Add IDocumentEditable interface to allow efficient interaction with document objects which may not be visible in a Scintilla instance. This feature is provisonal and may change before being declared stable. For better type-safety, the ScintillaCall C++ API uses IDocumentEditable* where void* was used before which may require changes to client code that uses document pointer APIs DocPointer, SetDocPointer, CreateDocument, AddRefDocument, and ReleaseDocument.
    Ctrl-click on a selection deselects it in multiple selection mode.
    Add SCI_SELECTIONFROMPOINT for modifying multiple selections.
    Add SCI_SETMOVEEXTENDSSELECTION and SCI_CHANGESELECTIONMODE to simplify selection mode manipulation.
    Improve performance of global replace by reducing cache invalidation overhead. [Feature #1502](https://sourceforge.net/p/scintilla/feature-requests/1502/).
    Fix regular expression search for "\<" matching beginning of search when not beginning of word and for "\>" not matching line end. [Bug #2157](https://sourceforge.net/p/scintilla/bugs/2157/).
    Fix regular expression search failure when search for "\<" followed by search for "\>". [Bug #2413](https://sourceforge.net/p/scintilla/bugs/2413/).
    Fix regular expression assertion (^, $, \b. \B) failures when using SCFIND_CXX11REGEX. [Bug #2405](https://sourceforge.net/p/scintilla/bugs/2405/).
    Fix regular expression bug in reverse direction where shortened match returned. [Bug #2405](https://sourceforge.net/p/scintilla/bugs/2405/).
    Avoid character fragments in regular expression search results. [Bug #2405](https://sourceforge.net/p/scintilla/bugs/2405/).
    With a document that does not have the SC_DOCUMENTOPTION_TEXT_LARGE option set, allocating more than 2G (calling SCI_ALLOCATE or similar) will now fail with SC_STATUS_FAILURE.
    Protect SCI_REPLACETARGET, SCI_REPLACETARGETMINIMAL, and SCI_REPLACETARGETRE from application changing target in notification handlers. [Bug #2289](https://sourceforge.net/p/scintilla/bugs/2289/).

and lexilla

[Release 5.3.0](https://www.scintilla.org/lexilla530.zip)

    Released 27 December 2023.
    Fix calling AddStaticLexerModule by defining as C++ instead of C which matches header. [Bug #2421](https://sourceforge.net/p/scintilla/bugs/2421/).
    Bash: Fix shift operator << incorrectly recognized as here-doc. [Issue #215](https://github.com/ScintillaOrg/lexilla/issues/215).
    Bash: Fix termination of '${' with first unquoted '}' instead of nesting. [Issue #216](https://github.com/ScintillaOrg/lexilla/issues/216).
    HTML: JavaScript double-quoted strings may escape line end with '\'. [Issue #214](https://github.com/ScintillaOrg/lexilla/issues/214).
    Lua: recognize --- doc comments. Defined by [LDoc](https://github.com/lunarmodules/ldoc). Does not recognize --[[-- doc comments which seem less common.

**Pull request closed without merging**
