### PR TITLE
 #862 - Allow plugins to retrieve settings directory.

### PR DESCRIPTION
**Pull request by sanastasiou**
Added some sample implementation.

### CODE REVIEW

**Comment by sanastasiou** [comment]
Hi, is there any chance that this will be committed in the foreseeable future? :) Without this "feature" cloud settings cannot be used from any plugin.

**Comment by dail8859** [comment]
I'd suggest splitting this into two pull requests since it addresses two totally separate issues; one being a bug, and one a feature.

Assuming this ever gets merged :)

**Comment by sanastasiou** [comment]
Reverted last fix. I will created a new pull request about that. 

Btw - this here is also a bug.

NPPM_GETPLUGINSCONFIGDIR is giving back wrong results in case cloud settings are active.

**Comment by donho** [comment]
@sanastasiou Why do you need to have this infotmation?

**Comment by sanastasiou** [comment]
@donho 

Because in order for my plugin to correctly format it's text, I have to know it's respective tab settings. Currently this is impossible for plugins since the settings directory cannot be retrieved.

**Comment by dail8859** [comment]
@sanastasiou 

I'm curious what is different about your use case that `NPPM_GETPLUGINSCONFIGDIR` is not sufficient. As far as I know this is how all plugins store their settings. 

Or is it just simply that you "want" (rather than need) your settings stored in the cloud settings directory?

**Comment by sanastasiou** [comment]
@dail8859 Not really, I want my plugin to integrate flawlessly with Npp. This is not possible because if the user chooses cloud settings, then the settings will not be retrievable. So if we are using cloud settings - for language specific settings e.g. Tabs which is part of the Notepad++ itself and therefore is not saved under the plugins directory, rather the Notepad++ ( user defined ) directory, then this will not work and the plugin will have no way to retrieve the settings.

Why should the plugin author have to implement a Tab settings from scratch when this setting already exists per language in the plugin itself?

In my opinion you will have to either "removed" any and all tab settings for plugins, or allow the plugin to retrieve these settings ( why have a setting when you cannot read it? )

Sure, I could have implemented this in my plugin itself, but since the mechanism is already there, why not reuse it?

**Comment by donho** [comment]
@sanastasiou The correct way to get the info (TAB setting) you want is ask Notepad++ via API but not read from Notepad++. For the sake of security plugins can access to their space. 
OTOH, it's harder (and less reliable - since they could be changed in Notepad++) for plugins author to retrieve info from xml file than using API.
I would say you need rather **NPPM_GETTABSETTING** than **NPPM_GETSETTINGSDIR**.

**Pull request closed without merging**
