### PR TITLE
Allows user defined extension to associate workspace files

### PR DESCRIPTION
**Pull request by dail8859**
As I suggested in #169. Files ending in the defined extension will be opened in the project panel, instead of as a normal file to edit (much like how the session file extension works).

Adds a new settings option as shown: 
workspaceext

### CODE REVIEW

**Comment by donho** [comment]
@dail8859 It cannot be compiled due to missing ```const TCHAR* val = n->Value();``` line.
Could you check it again?

**Comment by dail8859** [comment]
Will check on it later today. No surprise there are problems. Sure a lot has changed since the original PR.

**Comment by donho** [comment]
Thank you @dail8859

**Comment by dail8859** [comment]
@donho Commit has been fixed and rebased onto the current master.

**Pull request closed without merging**
