### PR TITLE
update themes to v7.9.1

### LINKED ISSUE #9071: Themes are out of sync for global styles
All themes are currently, as of 7.9.1 out of sync concerning their global styles configuration

### PR DESCRIPTION
**Pull request by Ekopalypse**
Missing global style attributes were added to all themes and attempts were made to ensure that it did not collide with the previous setup by using previously used colors.
fixes #9071

### CODE REVIEW

**Comment by sasumner** [comment]
Nice.

I noticed:
image
Give us more! :-)

**Comment by donho** [comment]
I'm quite surprised there's no conflict with what I've committed:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/13d2fdadb050026b67b2fdca53493083cff50feb

I guess it's because the content of this PR contains the identical modification of my PR.

**Comment by Ekopalypse** [comment]
@donho 
> I'm quite surprised there's no conflict with what I've committed:
Great minds think alike - but I like the German saying better: Zwei Dumme ein Gedanke :-D
(Note, the German phrase is used  rather teasingly)

**Comment by donho** [comment]
That ("Two stupid one thought") WAS in my mind when I read "Great minds think alike" : "Why not shit minds" :D

**Pull request closed without merging**
