### PR TITLE
Update Turkish localizaton

### PR DESCRIPTION
**Pull request by Tmp341**
* According to 27524e1, 80c285e, a0472fd and 599f185 commits.

### CODE REVIEW

**Comment by donho** [comment]
Here is the diff between v8.1.2 & v8.1.3:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10297

Could you check it and confirm me it's all done (or you prefer do it later in the next release)?
Thank you.

**Comment by Tmp341** [comment]
@donho I think it is done this time.

**Comment by donho** [comment]
@Tmp341 
Could you resolve the conflict?

**Comment by donho** [comment]
@Tmp341 
While doing the integration of your PR, I've got the following error message:
```
$ git rebase -i
error: could not apply e9db0a2c... Update again
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply e9db0a2c... Update again
Auto-merging PowerEditor/installer/nativeLang/turkish.xml
CONFLICT (content): Merge conflict in PowerEditor/installer/nativeLang/turkish.xml

```

This PR won't be merged.
Could you create a new PR from a new branch based on the current master?

**Pull request closed without merging**
