### PR TITLE
Fix clickable link bad display regression

### LINKED ISSUE #12219: Scintilla 5.3.0: "URL Hovered" only affects links' underline
**STR:**
"Preferences -> Cloud & Link -> Clickable Link Settings": check only "Enable".
Paste https://github.com/notepad-plus-plus/notepad-plus-plus.
Hover over the link.

**Result:**
Only the link underline changes color.
תמונה

**Preferred:**
Both link and underline change color.
(The behavior prior to Scintilla 5.3.0).
תמונה

***

Notepad++ v8.4.5   (64-bit)
Build time : Sep 12 2022 - 18:38:40
Path : C:---\Notepad++.x64.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1)
    HTMLTag (1.3.2)
    MenuIcons (1.2.5)
    PythonScript (2)
    _CustomizeToolbar (4.2)

### PR DESCRIPTION
**Pull request by donho**
Fix #12219

### CODE REVIEW

**Comment by donho** [comment]
@Yaron10
Please check if this PR fix the problem.
Thank you for your patience and thank you again for the catch.

**Comment by Yaron10** [comment]
@donho,

Thank *you* for your work and for this PR. 👍 

I'd like to point out again what I mentioned in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12219#issuecomment-1256536491 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12219#issuecomment-1256814479:

> NOTE: if you check "No Underline", there's no underline in normal state but it does appear on hover.
IMO it's actually better.

In previous versions there was no underline in both normal and hover states.
If you prefer that behavior:

> MOTE: if you only change that line, you get the exact behavior as in previous NPP versions.

**Comment by donho** [comment]
@Yaron10 
> In previous versions there was no underline in both normal and hover states.

**Normal:**

image

**Hovered:**

image

I'm quite confused. Tested with v8.4.3

**Comment by donho** [comment]
@Yaron10 
Just checked in v8.4.5

The hovered link displays also the underline with even "no underline" is checked.

image

**Comment by ArkadiuszMichalski** [comment]
Yes, previous behavior was as @donho describe.

**Comment by Yaron10** [comment]
@donho,

You're right. Sorry about the confusion.

Instead of testing it with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9455684b429449f668c1aedb77ec9dcb1642c244, I tried it with an outdated backup binary.

_Normal:_
תמונה

_Hovered:_
תמונה

Well, you seem to prefer that behavior. :)

Thanks again.

**Comment by donho** [comment]
@Yaron10 @ArkadiuszMichalski 
Thank you for your confirmation.
So this PR will restore the clickable link's behaviour of previous version.

**Comment by Yaron10** [comment]
@donho,

👍 
Great!

**Pull request closed without merging**
