### PR TITLE
Issue #2179 fixed: No notification for not installed software

### PR DESCRIPTION
**Pull request by SinghRajenM**
Though, this is plain solution. It is not localized. This change can be replaced with similar localized item.

### CODE REVIEW

**Comment by dail8859** [comment]
I second @MAPJe71's suggestion of at least showing the command it is attempting to run. That way the user can at least try to identify a problem...such as using the wrong keyword or missing a backslash, etc.

**Comment by A-R-C-A** [comment]
Here's a way to go. First lets shift this to RunDlg.cpp to get access to the expanded strings. In RunDlg.cpp on line 195 do something like this:
```cpp
HINSTANCE res = ::ShellExecute(hWnd, TEXT("open"), cmd2Exec, args2Exec, TEXT("."), SW_SHOW);

// As per MSDN (https://msdn.microsoft.com/en-us/library/windows/desktop/bb762153(v=vs.85).aspx) 
// If the function succeeds, it returns a value greater than 32.  
// If the function fails, it returns an error value that indicates the cause of the failure.  

int retResult = reinterpret_cast<int>(res);
if (retResult <= 32)
{
	generic_string errorMsg;
	errorMsg += TEXT("Open\n------\n");
	errorMsg += cmd2Exec;
	errorMsg += TEXT(" ");
	errorMsg += args2Exec;
	errorMsg += TEXT("\n------\nfailed : ");

	switch (retResult)
	{
		case NULL:
			errorMsg += TEXT("NULL");
			break;
		case ERROR_FILE_NOT_FOUND: // same as SE_ERR_FNF
			errorMsg += TEXT("ERROR_FILE_NOT_FOUND");
			break;

		// ... some more error codes ...

		case SE_ERR_SHARE:
			errorMsg += TEXT("SE_ERR_SHARE");
			break;
		default:
			errorMsg += TEXT("UNKNOWN ERROR");
			break;
	}

	::MessageBox(hWnd, errorMsg.c_str(), TEXT("ShellExecute - ERROR"), MB_ICONERROR);
}
return res;
```
You can open a new clean PR for this and close this one if you like.

**Comment by MAPJe71** [comment]
Or use the [FormatMessage function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679351(v=vs.85).aspx) to automatically convert error codes into error text.
Something like this:
```
// TortoiseGit - a Windows shell extension for easy version control

// Copyright (C) 2009-2010, 2014 - TortoiseSVN

// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software Foundation,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
#pragma once

/**
 * A wrapper class for calling the FormatMessage() Win32 function and controlling
 * the lifetime of the allocated error message buffer.
 */

class CFormatMessageWrapper
{
private:
    LPTSTR buffer;
    DWORD result;
    void release();
    void obtainMessage() { obtainMessage(::GetLastError()); }
    void obtainMessage(DWORD errorCode);

public:
    CFormatMessageWrapper() : buffer(0), result(0) {obtainMessage();}
    CFormatMessageWrapper(DWORD lastError) : buffer(0), result(0) {obtainMessage(lastError);}
    ~CFormatMessageWrapper() { release(); }
    operator LPCTSTR() const { return buffer; }
    operator bool() const { return result != 0; }
    bool operator!() const { return result == 0; }
};

inline void CFormatMessageWrapper::obtainMessage(DWORD errorCode)
{
    // First of all release the buffer to make it possible to call this
    // method more than once on the same object.
    release();
    result = FormatMessage (FORMAT_MESSAGE_ALLOCATE_BUFFER |
                            FORMAT_MESSAGE_FROM_SYSTEM |
                            FORMAT_MESSAGE_IGNORE_INSERTS,
                            NULL,
                            errorCode,
                            MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), // Default language
                            (LPTSTR) &buffer,
                            0,
                            NULL
                            );
}

inline void CFormatMessageWrapper::release()
{
    if(buffer != 0)
    {
        LocalFree(buffer);
        buffer = 0;
    }

    result = 0;
}
```

**Comment by SinghRajenM** [comment]
As suggested by A-R-C-A Closing this. Creating new request

**Comment by donho** [comment]
Please redo your pr then

**Comment by SinghRajenM** [comment]
@donho 
I have prepared fresh PR #2626 .

**Pull request closed without merging**
