### PR TITLE
Fix leading & tailling spaces being allowed after renaming tab issue

### LINKED ISSUE #13967: Leading & tailling spaces should not be allowed after renaming tab
### Description of the Issue
Leading & tailling spaces should not be allowed after renaming tab

### Steps to Reproduce the Issue

1. Renaming a tab by right clicking on a "new 1" tab for having the context menu
2. Choose "Rename"
3. In "New Name" field, type `   whatever   `, then  click OK button

### Expected Behavior
`whatever` as tab new name

### Actual Behavior
`   whatever   ` as tab new name

### Debug Information
```
Notepad++ v8.5.5   (64-bit)
Build time : Aug  2 2023 - 23:40:03
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2070
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

### PR DESCRIPTION
**Pull request by donho**
Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13344#issuecomment-1665687932

Fix #13967

### CODE REVIEW

**Comment by Yaron10** [comment]
@donho,

Great. 👍 
Thank you for the quick fix.

Change a new tab name to "" (empty).
Open the Find dialog and "Find All in Current Document".
Double-click an entry in the Search Results window.

Result:
An error message: _Cannot open file ""_.

So an empty title (after trimming) should not be allowed either. :)

**Comment by Yaron10** [comment]
@donho,

👍 
Thank you again for your time and work.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/391f4281efac81649a02aa8cdd4e765fa76d1237

**Comment by alankilborn** [comment]
@donho @Yaron10 

Try this STR:

* Edit a localization file, e.g. `English_customizable.xml`
* Set this tag/value pair: `<tab-untitled-string value="         new "/>`
* Save the file
* Activate this Localization
* Press Ctrl+n a few times to create new tabs
* See that the new tabs have leading spaces

**Comment by Yaron10** [comment]
@alankilborn,

Do you consider those spaces an issue? Consistency?
If we didn't have the _Cannot open file_ error, why shouldn't spaces be allowed?
(Now that an empty tab-title is not allowed, `std::wstring newTitle` could _theoretically_ be empty for NonMainEdit Scintillas and we shouldn't have any collisions).  

And even if spaces should not be allowed, is it worth the extra trimming? - Translators shoudn't add spaces to that string. :)
IIRC, NPP can crash if you manually edit config.xml with some wrong/unexpected values.

**Comment by alankilborn** [comment]
>Do you consider those spaces an issue? Consistency?

Using the string I supplied, user could have a tab with name `         new 2`.  If they then rename the tab with intention on having `         new 2a`, result will be `new 2a`.  Confusing for user as to why that happened?  I'd say yes.  I think it is better to enforce consistency.

>Translators shoudn't add spaces to that string.

I suppose not, but I've long used english_customizable for my own purposes.

---------------------

My thoughts were:  After forming a potential new tab name via `tab-untitled-string`'s value, the result should be subjected to the same trimming as if a user renamed a tab.

Perhaps it isn't worthy of consideration.

**Comment by Yaron10** [comment]
>  I think it is better to enforce consistency.
...
After forming a potential new tab name via tab-untitled-string's value, the result should be subjected to the same trimming as if a user renamed a tab.

I "love" consistency, and it's certainly a nice case.
@donho might agree with you that it IS worth the extra trimming.

**Pull request closed without merging**
