### PR TITLE
a bug about monitoring(tail -f) 

### PR DESCRIPTION
**Pull request by willdevgh**
when I use the monitoring(tail -f), a message box pop up : "This file has been modified by another program. Do you want to reload it?".
so, I find the bug and fix it.
this is my first time to use GitHub, and writing in English, if there has been some mistakes, please correct me.
Thanks!!

### CODE REVIEW

**Comment by donho** [comment]
@willdevgh  Could you tell me what have you fixed?

**Comment by willdevgh** [comment]
@donho 
In file  PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChangesPrivate.cpp line 152:
The statement "if"'s condition is 'wstrFilename.Right(1) != L"\\"', so the "false" branch never executed and after this, the wstrFilename is some string like L"E:\\\\test_20160715_0001.log" which has 4 backslashes.
In file  PowerEditor/src/NppIO.cpp  line 90:
In this line, the variable "fullFileName" has 2 backslashes, so it is never equal to variable "wstrFilename" in this statement.
These would lead to the situation that when I use the monitoring(tail -f), a message box named "Reload" pop up("This file has been modified by another program. Do you want to reload it?").

Thanks!!

**Comment by donho** [comment]
@willdevgh I meant how can I reproduced the bug?

**Comment by willdevgh** [comment]
@donho 
To reproduce the bug, you can open a text file and use the "Monitoring (tail -f)", every time the file appended by other application, the message box will pop up, you must close the message box to see the appended text, that is the problem.

P.S. If you don't close the file that already opened in other app, the message box doesn't pop up and the appended text doesn't display too. It can not display the appended text in real-time. To reproduce the bug, you must write the file and close it in a single operation. I think the feature about "Monitoring (tail -f)" should worked on the situation that a file is still opened by other app and it should displayed the appended text in real-time.
Sorry, my English is terrible. ):

**Comment by donho** [comment]
@willdevgh I open a text file in monitoring mode in Notepad++, and I open the same text in Notepad.exe, append any text in Notepad.exe and save it.
The modified text has been shown in Notepad++ correctely, without any popup messagebox.
What appication do you use for modify the text?

**Comment by donho** [comment]
@willdevgh  BTW, what is the full file path of your file?

**Comment by willdevgh** [comment]
@donho 
Earlier, I writen a tool to test my log class, so I use the Monitoring mode to debug.
full path is "E:\\test_20160719_0001.log"

I had just did the same thing(use notepad.exe), and the message box still pop up.
full path is "E:\\test.txt"

I sent you an email about this.

It is so weird...

**Comment by donho** [comment]
@willdevgh Your patch is correct.
To reproduce such bug, the file foo.txt to monitor should be under the root (ie. `c:\\foo.txt`).
The algorithm is check if folder path has '\\' at the end, if no, then add a '\\' then append file name.
In the original code, instead of checking folder path, the file name is checked. Since file name doesn't contain '\\',  a '\\' is always added on folder path which has no '\\' at the end, except root folder `C:\\`, `E:\\` or `F:\\`.

**Pull request closed without merging**
