### PR TITLE
Updated some strings in romanian.xml

### PR DESCRIPTION
**Pull request by TigerxWood**

### CODE REVIEW

**Comment by donho** [comment]
Is there any Romanian speaker can validate this PR?

**Comment by Dambuster88** [comment]
No, it is not ok. Not all the changes.
Some of the verbs, like "Open" and "Close" are at the long infinitive form and sounds very bad.
https://en.wikipedia.org/wiki/Infinitive#Latin_and_Romance_languages

**Comment by Dambuster88** [comment]
Check lines 911, 912, 914 and 919.
Why space before question mark?

**Comment by simioff** [comment]
I'm not sure about the spaces before the question marks, but the rest looks good. At least other tools like Microsoft Office are using the same wording.

**Comment by TigerxWood** [comment]
Hi guys, maybe you didn't notice but I redid the entire translation of this program. This last changes was some minor mistakes that I missed when I proofread it. This is the best translation you could have, instead of the old one that was imposible to use. Even this is not 100% according to romanian language rules. For example I didn't translate words like Clipboard or Cloud because I considered that because this program is used mainly by programmers they will understand better this english version instead of some crappy translation that noone could guess what it is, like Clipplanșetă for Clipboard.
About that infinitive stuff this is the right way to translate, for the consisystency with the rest of the translation: Salvare, Tipărire, etc.
About the spaces before question marks it was not intentional. I corrected them.

**Comment by donho** [comment]
@TigerxWood  Could you check the newest updated english.xml here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

which has been updated by this commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bd0867ee62b115b5f485abd8791da775c001ff8d

**Comment by pfparesseux000** [comment]
In the file english.xml, because of issue 4040, items id="45005, id="45008, id="45010" and id="45011" changed. In the file romanian.xml, the sentences seem confused. These sentences should be updated too.

**Pull request closed without merging**
