### PR TITLE
[xml] Update portuguese.xml

### PR DESCRIPTION
**Pull request by hugok79**
* Following commits: 07924528c4407f0d99f8ac01862e2d21dcc69899 aaab190763b720e2eed6495d8508b970d09ad39c dc99ce103550a3441f474b44c0a4075af3ed41ba 43d9f0d665248e252642e3f8cd4c2a8b9b1370e5 9eab1f566d59c08e9f30d6faa2e4d6f56f05edc0 3f13957f69738670a39fd589fe3cd85de1b307f8 f7fcab4c219b7187ce9d6ca300c96f06f8f2e877 0c704fd66b12170c17ccd97c6b5f3d72e40e241c 37963ea21ad7876903c669e2190e6f2b2dde7e39 f403b1226471370ab203bc66a313fc976e626cd2 9627494043d3ace4d4b5ab04b85fbdd0bd5a87a5
* Other minor corrections

### CODE REVIEW

**Comment by conky77** [comment]
@dail8859 you could be interested in creating [Wingup translation](https://github.com/notepad-plus-plus/wingup/tree/master/src/translations)
see also [the announcement](https://community.notepad-plus-plus.org/topic/24125/wingup-for-notepad-s-been-translatable-since-long-time-ago)

**Comment by dail8859** [comment]
@conky77 I just label the PRs. I don't actually do any of the translation.

**Comment by donho** [comment]
Could you please check the following announcement for completing your localization file if it's not done?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13209

Thank you @hugok79

**Comment by hugok79** [comment]
@donho All done.

**Comment by hugok79** [comment]
> @dail8859 you could be interested in creating [Wingup translation](https://github.com/notepad-plus-plus/wingup/tree/master/src/translations) see also [the announcement](https://community.notepad-plus-plus.org/topic/24125/wingup-for-notepad-s-been-translatable-since-long-time-ago)

Done https://github.com/notepad-plus-plus/wingup/pull/42

**Comment by hugok79** [comment]
> @conky77 I just label the PRs. I don't actually do any of the translation.

Done. https://github.com/notepad-plus-plus/wingup/pull/42

**Pull request closed without merging**
