### PR TITLE
[xml] update japanese.xml

### PR DESCRIPTION
**Pull request by yasmise**
Add translations for these commits:
* Add Begin/End Select in Column Mode command (0792452)
* Add show non-printable characters command (aaab190)
* Make Non-Print Characters show by default (dc99ce1)
* Translate 'Compact Language Menu' popup dialog (43d9f0d)
* Add option to make auto-completion list brief (9eab1f5)
* Make two items in progress dialog translatable (3f13957)
* Make categories in the Shortcut Mapper dialog translatable (f7fcab4)
* Make theme warning message translatable (switching unsaved theme to another) (0c704fd)
* Apply tab colors to document list items and add groups to document list. (37963ea)
* Make Context menu in Shortcut Mapper (Modify, Delete, Clear) translatable (f403b12)
* Fix translation issue for Dock/Undock label in User-Defined dialog (9627494)
* GUI enhancement: replace auto-complete link mini dlg with slider (caff51c)
* Rename commanfd "Remove Unmarked Lines" to "Remove Non-Bookmarked Lines" (3f3aed4)
* Make "Cannot open file" message translatable (a689635)
* GUI enhancement: use edit field instead of tab size link + mini dlg (8b3f072)
* Set english.xml version right (99e7c5a)

### CODE REVIEW

**Comment by donho** [comment]
Could you please check the following announcement for completing your localization file if it's not done?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13209

Thank you @yasmise

**Comment by yasmise** [comment]
@donho 
I've updated and now it's ready. This also contains "Edit with Notepad++" translation.
Thank you.

**Comment by donho** [comment]
@yasmise 
Could you exclude explorerContextMenuEntryLocal.ini from this PR please?
I will merge the translation "Edit with Notepad++" myself. Thank you.

**Comment by yasmise** [comment]
Hi @donho 
Sorry to bother you. I've excluded `explorerContextMenuEntryLocal.ini`.
Could you merge following translation to it? Thanks a lot.
```
[japanese.xml]
Edit_with_Notepad++=Notepad++ で編集
```

**Pull request closed without merging**
