### PR TITLE
[xml][force xml] Handle md/txt/log by appveyor in a special way

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Ref https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12587.

### CODE REVIEW

**Comment by donho** [comment]
@ArkadiuszMichalski 
Please ping me when it's ready to be merged.

**Comment by donho** [comment]
@ArkadiuszMichalski 
BTW, please apply to master also.

**Comment by ArkadiuszMichalski** [comment]
@donho 
More file can be add here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c468f84865c77baa7663cd33642bf0f36eea3a97/appveyor.yml#L40

With or without Master is controlled by:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c468f84865c77baa7663cd33642bf0f36eea3a97/appveyor.yml#L38

PR is ready.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Thank you for this enhancement. Not only it saves devs' precious time, but also makes our environment greener!

**Pull request closed without merging**
