### PR TITLE
Reduce AppVeyor build time

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Detail https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12457.

### CODE REVIEW

**Comment by donho** [comment]
@ArkadiuszMichalski 
Have you any conclusion via this PR?
If no, could we close it? Or you need more try?

**Comment by ArkadiuszMichalski** [comment]
@donho 
I've made some potential improvements but I don't know if you want to include any of them. I will summarize them in
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12457.

**Comment by donho** [comment]
Please close this one then.

**Comment by ArkadiuszMichalski** [comment]
@donho But https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12457 is issue for discussing (not PR). I need some PR for test or show code example. I can close this PR, but I will probably reopen it again to do some testing until we determine whether we will adopt or not any changes from this PR.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Please ping me when the PR is ready.

**Comment by ArkadiuszMichalski** [comment]
@donho 

It's basically ready. I can run a full build (10 jobs) to be sure, but it's rather unnecessary (last commit pass `Win32 Debug`). When you merge you can open some PR for test and play with it. f necessary we can change later the syntax of annotations or message descriptions.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Thank you. It's merged.
Let's just see what happens without any `[FLAG]`.
Regarding `[xml]`, I am thinking about `[Translation]` - which might more explicit for the translators. What do you think?

**Comment by ArkadiuszMichalski** [comment]
@donho
This validation actually could be applies to all `xml` files (localization, themes, autoCompletion, functionList), generally those covered by [validator_xml.py](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/Test/xmlValidator/validator_xml.py). So `[Translation]` is too narrow and it's longer (with one upper case). On the other hand, if you prefer this form, we can change it. We can even use both `[xml]` or `[Translation]`, which will mean the same.

In my opinion `[xml]` fits best because it's short (easy to remember and little typing) and indicates that PR/commit only modified XML files and is expected to pass validation.

**Comment by donho** [comment]
OK, let's stay with only [xml].

**Pull request closed without merging**
