### PR TITLE
Reduce CI build time

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14942 (I put the description in the issue).

### CODE REVIEW

**Comment by ArkadiuszMichalski** [comment]
@donho We can temporarily disable filtering for the `master` (so all jobs will always be run regardless of the files being changed), and do filtering only for PR. 
Just change `$allowMaster` var to `$false`:
```
$allowMaster = $false
```
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14943/files#diff-f1f3205c400170ee27a9f6cce59215a9cb0179d6491af8fd3942dcf40fb238ffR21

If after some time it turns out that everything is working properly and you decide that it is worth doing it for the `master`, just change the value of the variable back to `$true`.

**Comment by donho** [comment]
@ArkadiuszMichalski 
It's nice the suggestion/solution of #14942 (the filter).
My question is: how can we test all the offered features by this PR before merging it?

**Comment by ArkadiuszMichalski** [comment]
@donho Maybe this way:

1. Create new fresh repo on GitHub page (like testCI)
2. Clone this repo locally
3. Copy to locally testCI all actual Notepad++ repo
4. Change on master `CI_build.ym` file to my code and commit this change 
5. Push locally testCI to origin

Or make a new fork directly from the main repo and change `CI_build.ym`.

Now you have a separate repo for testing. You can change master or create and change new branches.

You can also create PR to this repo directly via the website (no need to create an additional fork). Just make change to some file and when press:
image
choose:
image

Once you have a new branch (and PR) for it, you can change other files and observe the behavior. Finally, do a merge to master to see if this also works properly.

You can also create different PRs on this way by changing different files and see if everything works as it should. If something requires clarification, please provide a link to the PR and we will discuss it there.

One note: when we make PRs from origin repo to origin (not from fork) then two `push` and `pull_request` events will be fired in PR. This is normal, don't pay attention to the `push`.

image

You can also make a new PR with my code directly into the main repo, but then we change one file `CI_build.ym`, so by default it will run all jobs (this file is not filtered). To force different behavior we can use the flags: [force all], [force one], [force none] and [force xml] on next commits to simulate different behavior. But the above solution seems to be the most convenient.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Sounds great.
We need a table of test like:
|   test \ build    |FILTER|VR64 | VR32 |VRA64|VD64 |VD32 |VDA64|CMAKE| MR64 | MR32 | MD64 | MD32 |
|---------------|------|-----|------|-------|-----|-----|-------|-----|------|------|------|------|
|1 *.h / *.cpp   |  RUN | RUN | RUN  | RUN   | RUN | RUN |  RUN  | RUN | RUN  |  RUN | RUN  | RUN  |
|2      *.xml    |  RUN |     |      |       |     |     |       |     |      |      |      |      |
|3 *.MD / *.txt  |  RUN |     |      |       |     |     |       |     |      |      |      |      |
|4     cpp.xml   |  RUN |     |      |       |     | RUN |       |     |      |      |      |      |
|5 *.xml + *.cpp |  RUN | RUN | RUN  | RUN   | RUN | RUN |  RUN  | RUN | RUN  |  RUN | RUN  | RUN  |
|6   More test?|  RUN |     |      |       |     |     |       |     |      |      |      |      |
|7    ...        |      |     |      |       |     |     |       |     |      |      |      |      |

### Legend: 
**FILTER**: the task added by this PR 
**V**: **V**isual Studio
**R**: **R**elease
**D**: **D**ebug
**A**: **A**RM
**64**: **64** bits
**32**: **32** bits
**CMAKE**: **CMAKE** build
**M**: **M**sys

Once the table of test is defined in this PR, please follow your suggestion to clone the current PR and push the test PRs, with prefix **CI_Reduce_Test0#** where **#** is number of test which is correspondent to the defined table. The title could be more explicit like: **CI_Reduce_Test02 xml validation test**. Of course, each number of test could have 2 or more PRs if it's necessary, but every number of test should have at least 1 PR.

While the results of test PRs match with defined table of tests, this PR can be merged.

**Comment by ArkadiuszMichalski** [comment]
@donho OK, I setup two repos:
- [NPP_CI](https://github.com/ArkadiuszMichalski/NPP_CI) (main repo, will accept PR)
- [NPP_CI2](https://github.com/ArkadiuszMichalski/NPP_CI2) (other repo, will create PR)

Thanks to this only the `pull_request` event will be fired for PR (simulating the identical behavior as in the main Notepad++ repo). I've started doing tests for the table above, I'll let you know when they're ready.

**Comment by ArkadiuszMichalski** [comment]
@donho Do we also need such tests?
- *.MD / *.cpp << all jobs
- *.MD / *.xml << xml validation
- *.MD / cpp.xml << one VD32 job

**Comment by ArkadiuszMichalski** [comment]
@donho Update here because I don't want to accidentally delete the original table. 

|   test \ build    |FILTER|VR64 | VR32 |VRA64|VD64 |VD32 |VDA64|CMAKE| MR64 | MR32 | MD64 | MD32 |
|---------------|------|-----|------|-------|-----|-----|-------|-----|------|------|------|------|
|1 *.h / *.cpp   |  RUN | RUN | RUN  | RUN   | RUN | RUN |  RUN  | RUN | RUN  |  RUN | RUN  | RUN  |
|2      *.xml    |  RUN |     |      |       |     |     |       |     |      |      |      |      |
|3 *.MD / *.txt  |  RUN |     |      |       |     |     |       |     |      |      |      |      |
|4     cpp.xml   |  RUN |     |      |       |     | RUN |       |     |      |      |      |      |
|5 *.xml + *.cpp |  RUN | RUN | RUN  | RUN   | RUN | RUN |  RUN  | RUN | RUN  |  RUN | RUN  | RUN  |
|6 *.MD + *.xml  |  RUN |     |      |       |     |     |       |     |      |      |      |      |
|7 *.MD + cpp.xml  |  RUN |     |      |       |     | RUN |       |     |      |      |      |      |
|8 *.MD + *.cpp |  RUN | RUN | RUN  | RUN   | RUN | RUN |  RUN  | RUN | RUN  |  RUN | RUN  | RUN  |
|9   More test?|  RUN |     |      |       |     |     |       |     |      |      |      |      |
|10    ...        |      |     |      |       |     |     |       |     |      |      |      |      |

@donho There is always a risk that the files below may affect the builds:
`$files_nowork = "md|txt|log|ini"`
especially `.ini`, but from what I understand, changing `CMakeFileList.txt` should also trigger CMAKE compilation? I don't know all the relevant configuration files in the project.

I will simply create an additional variable where such cases can be defined:
`$files_needwork = "CMakeFileList\.txt"`

Currently changing build configuration files triggers all builds. We can try to break it down into smaller ones, e.g. changing the `makefile` will run everything only for `msys2`, but this will cause larger modifications (additional conditions/variables and other things) so I'm skipping it for now.

**Comment by donho** [comment]
@ArkadiuszMichalski 

Nice job!
However, [the PRs in your repo](https://github.com/ArkadiuszMichalski/NPP_CI2/pulls) , the jobs are rue double: besides **(pull request)** there are also **(push)** - is it normal?

I notice that you have pushed 2 more commits in this PR.
Are they included in your cloned test PRs as well?

**Comment by ArkadiuszMichalski** [comment]
@donho https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14943#issuecomment-2041116985

> One note: when we make PRs to the same repo (not from other) then two push and pull_request events will be fired in PR. This is normal, don't pay attention to the push.

In the standard order (PR from another repo) there will be only one `pull_request` event, like here.

>I notice that you have pushed 2 more commits in this PR.
>Are they included in your cloned test PRs as well?

The first one was added, the second one wasn't, but it's just a performance improvement (does the same thing). I will try to update the master there, do a rebase and start the action again.

**Comment by donho** [comment]
@ArkadiuszMichalski 

There's an issue in the PR:

image

https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/8675235878/job/23788441957

Could you check it please?

**Comment by ozone10** [comment]
This is due to double quotes in commit message.
Until @ArkadiuszMichalski fix it, pushing next commit should fix failing build.

**Comment by ArkadiuszMichalski** [comment]
@donho @ozone10 OK, I'll see what I can do, I forgot that there may be double quotes in commit message.

**Pull request closed without merging**
