### PR TITLE
Support selection for Blank Operations

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12602.

### CODE REVIEW

**Comment by Yaron10** [comment]
What about the "built-in" macro `Trim Trailing Spaces and Save`?
Those who are used to saving via that command might want to *trim all* even if there's a selection.

**Comment by alankilborn** [comment]
> What about the "built-in" macro `Trim Trailing Spaces and Save`?
> Those who are used to saving via that command might want to _trim all_ even if there's a selection.

Indeed.
Maybe a new sample macro that "cancels" any active selection(s) before trim-trailing?  Is there a simple way to cancel such selections?

Side note:  Users might be better off to turn control of this (meaning the trim-trailing + save action) over to the editorconfig plugin.

**Comment by ArkadiuszMichalski** [comment]
>Is there a simple way to cancel such selections?

Press right arrow key? 

If the selection bothers someone, they can always create a new macro without it.

**Comment by alankilborn** [comment]
>>Is there a simple way to cancel such selections?

>Press left or right arrow key?

Well, yes, but I was considering a more-automated way, e.g. a Scintilla command.
If one wanted to create a macro (like we are discussing), putting a "press right arrow" command in it, requires also a "press left arrow" to restore original position, and perhaps some side effects from this, I don't know...

--------------------------------

>If the selection bothers someone, they can always create a new macro without it.

Right, but one would have to make sure there is no selection somehow (and maybe that is the "press right" + "press left" before the trim operation).

**Comment by ArkadiuszMichalski** [comment]
> Well, yes, but I was considering a more-automated way, e.g. a Scintilla command.
SCI_CLEARSELECTIONS
https://www.scintilla.org/ScintillaDoc.html#SCI_CLEARSELECTIONS

We can also read the current cursor position in the selection and set it without selection.

**Comment by alankilborn** [comment]
>SCI_CLEARSELECTIONS

>We can also read the current cursor position in the selection and set it without selection.

Please consider what a user can do in a macro in your responses, as that is the point Yaron10 made and I've been responding to.
User can't (easily) do SCI_CLEARSELECTIONS or your other point.

**Comment by ArkadiuszMichalski** [comment]
You asked about Scintilla's commands (although not everyone can have shortcuts).

The easiest way is record macro with press up+down (or reverse) keys before other command.  This causes that whether there was a selection or not, the cursor will remain in the same place.

**Comment by alankilborn** [comment]
>You asked about Scintilla's commands (although not everyone can have shortcuts).

I was asking in the context of what user can do, i.e., what appears in ShortcutMapper.  But I should have been more specific.

"Press left and right" or "press down and up" is okay, but it just feels unclean and hacky.  :-)

But OK, so the suggestion then is:
Add "press left and right" to the _Trim Trailing and Save_ macro, to preserve its existing functionality of trimming from the entire file.

Or maybe that upsets purists?

**Comment by ArkadiuszMichalski** [comment]
You can open a new issue for clearing selections command. Currently there is no such direct command. Even `Esc` is mapped to:
https://www.scintilla.org/ScintillaDoc.html#SCI_CANCEL
but that also leaves the main selection.

**Comment by alankilborn** [comment]
>You can open a new issue for clearing selections command

I don't know that it is worth it.  What felt hacky to me is probably ok with others. :-)

**Comment by Yaron10** [comment]
Another point:
some of the "Blank Operations" still do not work on selection only. This might be confusing.
Looking briefly at the relevant code, the implementation seems to be more complex.

Adding a menu-setting `Apply Commands to Selection Only` (and arrange the menu so that it's clear what those commands are) to "Blank Operations" and "Line Operations" should solve both issues.

But we have all learned quite recently not to engage in futile long discussions. :)

**Comment by ArkadiuszMichalski** [comment]
@Yaron10 

Anyway something needs to be done here because `doTrim()` is also used in `IDM_EDIT_TRIMALL`, and the second part of this command operates on the entire document.

I think that the first 5 commands can operate on selection (it's easy to achieve), but another 3 (after separator) use more complex `wsTabConvert()`.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> Anyway something needs to be done here because doTrim() is also used in IDM_EDIT_TRIMALL...

`EOL to Space` (`IDM_EDIT_EOL2WS`) also operates on the entire document.

> I think that the first 5 commands can operate on selection (it's easy to achieve), but another 3 (after separator)...

That would be better, but still somewhat confusing IMO.

**Comment by ArkadiuszMichalski** [comment]
>EOL to Space (IDM_EDIT_EOL2WS) also operates on the entire document. Yes, but it doesn't use `doTrim()`, just its own method that can be handled separately.

I have a dilemma how to process selections because the default behavior is inconsistent https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12648. We can autoexpand to full lines, but I don't know if that's desirable. The best selection is the one made by the user, but it doesn't work properly.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> Yes, but it doesn't use doTrim(), just its own method that can be handled separately.

If I understand you correctly, the problem is not with `doTrim()` - which apparently can easily be modified to work on selection only - but with `_findReplaceDlg.processAll()`.

> I have a dilemma how to process selections because the default behavior is inconsistent https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12648. We can autoexpand to full lines, but I don't know if that's desirable. The best selection is the one made by the user, but it doesn't work properly.

Unfortunately I don't know anything about RegEx.
Could you give me an example with the first 3 "Blank Operations" that are supposed to work properly at this stage?

If you mean the following case: 
תמונה

`Trim Trailing` removes the selection. - This is correct because the selected chars are indeed "trailing".
`Trim Leading` does not remove the selection. - This is correct because the selected chars are not "leading".

**Comment by ArkadiuszMichalski** [comment]
I open issue for this:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12648

**Pull request closed without merging**
