### PR TITLE
Upgrade Scintilla from v4.2.0 to v4.4.6

### LINKED ISSUE #8900: Notes for updating N++'s Scintilla beyond 4.2.0
Notepad++ 7.8.9 (current version as of this writing) uses Scintilla version 4.2.0.

Yesterday, I build Scintilla 4.4.4 for Notepad++.
4.4.4 was chosen as it is one version behind current Scintilla release (as of this writing), to avoid possible unknown issues with the very latest release.

Also yesterday, @donho hinted that Scintilla might be updated (for real) in Notepad++ soon; see here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8110#issuecomment-698698135

This issue is being opened to document some discoveries I made in my trial migration of N++'s Scintilla from 4.2.0 to 4.4.4.  This info may be useful when the real migration is conducted, to whatever version of Scintilla is decided upon to move to.

------------------------------------------

In the `nppSpecifics.mak` file :

* Need to change `SOBJS` to `SRC_OBJS`
* Need to change `INCLUDEDIRS` to `INCLUDES`

### PR DESCRIPTION
**Pull request by donho**
Close #8900

### CODE REVIEW

**Comment by sasumner** [comment]
@donho From the Scintilla project's history page, I see a version 4.**4**.6 as the latest, I think your use of 4.**6**.6 was a typo!

**Comment by donho** [comment]
@sasumner 
You're right. I'll stop working in the night :)

**Comment by GOLEM777** [comment]
Are you sure?!  Last update caused a lot of problems with Cyrillic ANSI (save, work and display), and much more other bugs.
I remember you did your own updates for Silintila!

**Comment by donho** [comment]
@GOLEM777 

I think I have integrated the needed modification into this release.
You can check this signed Scilexer.dll (in release mode):
[SciLexer.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6018233/SciLexer.zip)

Open the issue with the title [Scintilla 446 bug: ...] if you see any problem. I will treat it in high priority.

**Comment by GOLEM777** [comment]
Do you have versions for x64 SciLexer? ))

**Comment by donho** [comment]
@GOLEM777 
SciLexer x64 here:

[SciLexer64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6037751/SciLexer64.zip)

**Pull request closed without merging**
