### PR TITLE
Fix crash on unhiding lines

### LINKED ISSUE #12184: NPP crashes on hiding lines
**STR:**
Paste the following lines in a new document.
```
Test
Test
Test
Test
Test
```
Place the caret at line 3.
View -> Hide Lines.
Place the caret at line 2.
View -> Hide Lines.
Click on the show-lines markers.
You should get this:
תמונה
Click on the single show-lines marker.

**Result:**
NPP crashes.

***

Notepad++ v8.4.5   (64-bit)
Build time : Sep 16 2022 - 07:53:18
Path : C:\***Notepad++ Original.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1)
    HTMLTag (1.3.2)
    MenuIcons (1.2.5)
    PythonScript (2)
    _CustomizeToolbar (4.2)

### PR DESCRIPTION
**Pull request by donho**
Fix #12184

### CODE REVIEW

**Comment by donho** [comment]
Notepad++ stops hanging while clicking inconsistent symbol with the current state of PR.
I am working on PR to prevent from inconsistent situation.

**Comment by donho** [comment]
It should better now.

**Comment by Yaron10** [comment]
@donho,

The crash seems to have been fixed. 👍 
Thank you for your work.

Is this PR ready? - There still are some inconsistent cases.

I'm not really familiar with this feature.
It would be nice if @alankilborn could test it too.

**Comment by Adrian104** [comment]
Hello, @donho and @Yaron10

I have also tested this code. Program didn't crash (so issue seems resolved), but lines can sometimes disappear:

Animation

I have fixed this issue in my own fork but in a different way (without disappearing lines). I was about to make PR, but I was too late. Could you please take a look at my fork, on branch fix-line-hiding? I have never contributed to Notepad++ source and I would be grateful for your feedback on my code.

Link to my commit:
https://github.com/Adrian104/notepad-plus-plus/commit/0bceaf64c0323035f02e8388b328cb669ab83ff5

**Comment by Yaron10** [comment]
@Adrian104,

Thank you for your work. 👍 
Could you please build it with appveyor?

@donho,

You are the master.
Still, allow me to ask: disabling the command is a nice idea, but is it really worth calling `canHideLines()` on `SCN_UPDATEUI`?

**Comment by Adrian104** [comment]
Thank you for your reply, @Yaron10
Unfortunately, I have no experience in continuous integration (sorry for the problem, I am still learning GitHub).
Should I make a pull request and it will automatically test this code?

**Comment by Yaron10** [comment]
@Adrian104,

I'm not a GitHub expert either.
If you submit a PR, appveyor should start build it.

**Comment by donho** [comment]
@Adrian104 
Thank you for your test and bug report.
I can reproduce it.

You can do a PR from the master and if it's good enough, it will be used instead of this one.
Please consider the rule of creating a PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Comment by Adrian104** [comment]
@donho 
Thank you for your reply. I carefully read the contribution guidelines beforehand and I have just submitted a PR.

**Comment by donho** [comment]
@Yaron10 
> Still, allow me to ask: disabling the command is a nice idea, but is it really worth calling `canHideLines()` on `SCN_UPDATEUI`?

Indeed. The PR provided by @Adrian104 (#12250) is much better.

**Comment by Yaron10** [comment]
@donho,

> Indeed. The PR provided by @Adrian104 (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12250) is much better.

I respect you for that sentence.

**Comment by Adrian104** [comment]
@donho,
Once again, thank you very much! I'm very happy that I can support Notepad++ development.

**Pull request closed without merging**
