### PR TITLE
Update Bulgarian localization

### PR DESCRIPTION
**Pull request by rddim**
* Add localization for Length label in the Customize Maximum Length popup · notepad-plus-plus/notepad-plus-plus@bc14878
* Update localization files · notepad-plus-plus/notepad-plus-plus@11ccc41 / Fix localization files · notepad-plus-plus/notepad-plus-plus@3fcad98
* Fix inconsistencies at OS-forced Notepad++ (v8.4.7) exit · notepad-plus-plus/notepad-plus-plus@bd4c323
* Make tab context menu customizable · notepad-plus-plus/notepad-plus-plus@aa8ae48
* other fixes

### CODE REVIEW

**Comment by donho** [comment]
@rddim 
Please add `[xml]` on the beginning of title next time, if the PR is about translation, and only xml file(s) is (are) modified.
Ex: `[xml] Update Bulgarian localization`

**Comment by rddim** [comment]
@donho 
Could you add this instructions to the `CONTRIBUTING.md`

**Comment by ArkadiuszMichalski** [comment]
I add instruction to FAQ:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#how-to-create-a-non-blocking-pull-request-pr

**Comment by donho** [comment]
@rddim 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

**Pull request closed without merging**
