### PR TITLE
Add autocompletion file for AutoIt

### PR DESCRIPTION
**Pull request by vlakoff**
Add autocompletion file for the amazing [AutoIt](https://www.autoitscript.com/site/) software, which is already supported in syntax highlighting.

File directly taken from directory `Extras\Editors\Notepad++` of their release package. I only replaced the single quotes by double quotes for consistency with the other autocompletion files, and made sure this change didn't break anything.

I searched the author of this substantial file for proper credit, but I couldn't find it.

### CODE REVIEW

**Comment by donho** [comment]
autoit.xml is not in the repository.
As a result your patch will make NSIS build fail.

**Comment by vlakoff** [comment]
I didn't understand, what do you mean by "autoit.xml is not in the repository"?

**Comment by A-R-C-A** [comment]
This is probably closed by mistake. Any plans for redoing this PR? Or should I make a new PR for this?

**Comment by vlakoff** [comment]
Maybe Don HO looked too fast and didn't notice I'm *adding* the file :-)

By the way, the file is a bit large (just below 1 MB), but:
* It's very acceptable considering today's drives, and compared to the size of the bloat added by almost all softwares nowadays.
* It's tiny once compressed (84 KB), thanks to #2175 :-)

**Comment by A-R-C-A** [comment]
Yeah, this file is a bit larger than the others but it is also the most completed one. Most included API files are by far not completed, thus not as useful as this one. Also it's much easier to delete unneeded files afterwards than searching for missing ones. The installer has some options to exclude unwanted files and those who don't need all the extra files can simply download the minimalist version.

I wanted to do the same PR independently, have mostly the same changes as you did except some minor differences like converting to Unix endings to release some more kB. So I wonder if you plan to redo your PR? If not I can submit a fresh PR for this and see what happens.

**Comment by vlakoff** [comment]
* My PR is still up-to-date and could be reopened. But if you have ideas for improvements, don't hesitate to open another PR.
* -1 for the LF endings. Sounded great at first glance, but inconsistent with all other *.xml files and more importantly it's not compatible with classic Notepad.

**Comment by A-R-C-A** [comment]
> My PR is still up-to-date and could be reopened. But if you have ideas for improvements...

Remove the following `&#x0a;` and `CR` on line 22426. There are also some more wrongly placed `&#x0a;` pattern across this file, some of them can be removed. So it's your turn to reopen this PR or better open a new one on the top of the PR stack.

> -1 for the LF endings...

Accepted, but you cannot take Notepad really seriously ;)

**Pull request closed without merging**
