### PR TITLE
Support both MinGW multilib versions 

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10941.

### CODE REVIEW

**Comment by donho** [comment]
@ArkadiuszMichalski 
So the indicated package on build.md:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
is not MinGW multilib package?

If not, it will better to use this link:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z
to replace the original one, for putting the advantage of this PR. What do you think?

**Comment by ArkadiuszMichalski** [comment]
@donho
I checked MinGW  8.1.0 packages and only `sjlj` variant is multilib (for both case, 32/64 bit). I would not change the recommended versions in `build.md` because these are the same ones that `appveyor` uses. It will be easier to manage any error in the future (if someone reports them). so better to encourage testing in the same version.

Until now, the makefile had MinGW 64-bit multilib support, but the 32-bit variant was missing. so I added it (since it already partially exists). The additional information in `build.md` may be useful for people who have and using such versions permanently in the `Path` env. 

If in the future problems arise from using different versions (I mean onelib vs multilib) it is best not to support multilib at all. Well, I have not seen such a report yet, so it does not bother me. Sometimes it's easier and faster to generate a second version of Notepad++ without changing the `Path` to other MinGW variant. Personally, I have permanently added MinGW 32-bit sjlj to system `Path` and generation of 64-bit Notepad++ works fine.

**Comment by donho** [comment]
@chcg 
Is it hard to change to MinGW sjlj W64 in our build system so we don't have to deal with 2 packages of MinGW ?
What's your opinion on it?

**Comment by chcg** [comment]
At least there seems to be a performance penalty with sjlj compared to seh, see
https://stackoverflow.com/questions/30739099/what-is-the-difference-between-mingw-seh-and-mingw-sjlj/30739394.
I'm not sure how complicated it is to install the sjlj package on appveyor. Timing might be also of interest then and maybe caching.

**Comment by ArkadiuszMichalski** [comment]
@donho 

I'm not sure if single package multilib will always work the same as 2 separate ones. Generally I'm not working on Notepad++ generated from MinGW. Separate versions MinGW are probably more promoted (more popular and available), especially in the new versions of MinGW.

This got me interested when I started analyzing the makefile from Notepad++. Multilib support has arrived in this new makefile that was made quite recently. Maybe Ivan U7n had some experience with it and wanted to be able to handle them as well (well, at least 64-bit packages), but only through `TARGET_CPU` variable.

**Comment by donho** [comment]
@ArkadiuszMichalski @chcg 
OK, I see your points. Thank you for your answers.

**Pull request closed without merging**
