### PR TITLE
Remember each individual show characters setting after toggling "Show All Characters" OFF

### PR DESCRIPTION
**Pull request by molsonkiko**
Would address #13734

When the user selects "Show all characters", their previous character showing settings (e.g., show nonprinting and control chars but not EOL or whitespace) will be saved so that when they toggle "Show all characters" OFF it reverts to their previous settings.

TO TEST:
1. Add this text to a document (UTF-8 bytes are `[0xc2, 0xa0, 0x20, 0x9, 0x5, 0xd, 0xa]`):
image
2. Turn on "Show all characters"
3. Turn off "Show non-printing characters" so that the `NBSP` is no longer visible.
4. Turn on "Show all characters"
5. Turn off "Show all characters" again.
RESULT: You should now be able to see all characters except the `NBSP` at the beginning.

### CODE REVIEW

**Comment by donho** [comment]
@molsonkiko 
You should always create an issue (bug) then create PR to link with the issue.
See:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md

**Comment by molsonkiko** [comment]
Just realized my PR doesn't cover an edge case where the previous settings had all checked (by checking each box individually) and the user tries to uncheck `Show All Characters`. I need to make another commit to cover this, but don't have time to recompile and test now. Will be able to later today.

**Comment by donho** [comment]
So this PR is making each individual show characters setting remembered after switching "Show All Characters" OFF.
It change the current behaviour and could bring the confusion.
Any thought about this PR? @ozone10 ? Anyone?

**Comment by molsonkiko** [comment]
If someone wanted to turn off all special char showing, maybe add another
button to turn everything off?

**Comment by Yaron10** [comment]
@donho & @molsonkiko,

If "Show all characters" is checked, all symbols are displayed.
Doesn't that mean the opposite on unchecking it - _Hide all characters_?

But even if we don't interpret it so literally...

Manually check the the first 4 _Show_ commands (-> "Show all characters" is auto-checked).
Uncheck "Show all characters".

Result:
No change at all.
Isn't that highly confusing?

**Comment by molsonkiko** [comment]
> Manually check the first 4 _Show_ commands (-> "Show all characters" is auto-checked). Uncheck "Show all characters".
> 
> Result: No change at all.

Yeah, that was a deliberate choice on my part. The alternative was to make a special case to turn everything off when all settings were checked manually. I agree that it's somewhat confusing, but it's completely self-consistent (remember exactly what the settings were before hitting `Show all characters`), unlike the alternative.

I really do understand your objections, @Yaron10 and @donho. I can totally see a case for doing things your way. But making it easy to see non-printing characters is one of the things that I like most about Notepad++ compared to, say, VSCode. From my perspective, making it so that one of my favorite buttons causes NPP to permanently forget all of the settings I had specifically chosen feels like a regression.

**Comment by molsonkiko** [comment]
> If "Show all characters" is checked, all symbols are displayed.
> Doesn't that mean the opposite on unchecking it - _Hide all characters_?

I'd also just observe that no, that's not the case. `not (A and B) != (not A) and (not B)`

**Comment by molsonkiko** [comment]
Is there any way to make the button tri-modal? Like make it so that it has three settings, `show no special characters`, `show user-chosen characters`, `show all characters`? Maybe the button would begin each session in the `show user-chosen` setting, then clicking once would go to the `show all` setting, and then clicking again would go to the `show none` setting?

**Comment by donho** [comment]
@Yaron10 
> Manually check the first 4 _Show_ commands (-> "Show all characters" is auto-checked). Uncheck "Show all characters".
> 
> Result: No change at all. Isn't that highly confusing?

Yes, "Show all characters" cannot be unchecked. It makes this option pointless - users cannot hide all characters by one click.

@molsonkiko 
> Is there any way to make the button tri-modal (and have the text change to reflect that)? Like make it so that it has three settings, show no special characters, show user-chosen characters, show all characters? 

I don't think such control does exist.

> Maybe the button would begin each session in the show user-chosen setting, then clicking once would go to the show all setting, and then clicking again would go to the show none setting?
 
Even it does exist, we should keep our GUI as straightforward as possible. Change the current behaviour is not only pointless, but also confusing for the users.

The current behaviour will be kept.

**Comment by Yaron10** [comment]
@molsonkiko,

I've never used Non-Printing/Control characters in real life.

Reading https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13734#issuecomment-1575171074 - would one toggleable "Show Non-Printing and Control Characters" command solve your issue?

@donho wants to improve NPP, and I'm sure he'd be willing to consider a good alternative solution.

**Comment by molsonkiko** [comment]
@Yaron10
Thanks for asking! I'm not sure what would be the most satisfactory solution aside from the one I put forward. Maybe somebody else who talked in the #13734 discussion could come up with a good idea that would satisfy everyone.

> would one toggleable "Show Non-Printing and Control Characters" command solve your issue?

That would definitely help.

**Comment by Yaron10** [comment]
@molsonkiko,

Thank _you_ for your work.

> would one toggleable "Show Non-Printing and Control Characters" command solve your issue?
>> That would definitely help.

I wasn't following the implementation of "Show Control Characters & Unicode EOL", and I don't know why it had to be separated from "Show NPC".

> Maybe somebody else who talked in the https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13734 discussion could come up with a good idea that would satisfy everyone.

That would be great. Best of luck.

**Pull request closed without merging**
