### PR TITLE
Update russian.xml to v7.9.3

### PR DESCRIPTION
**Pull request by GOLEM777**

### CODE REVIEW

**Comment by donho** [comment]
Please solve the conflict and check [v7.9.3 translation diff comparing with v7.9.2](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9455). If nothing is missed, please confirm it with me, so I will include this PR in the next release. Thank you!

**Comment by donho** [comment]
Please try to not move xml nodes around - let's modify the content only where it needs.
Next time it will be rejected.

**Comment by donho** [comment]
@GOLEM777 Could you confirm there's nothing missing please?

**Comment by GOLEM777** [comment]
Yes, all good!

**Comment by GOLEM777** [comment]
> @GOLEM777 Could you confirm there's nothing missing please?

Yes, all good!

**Comment by donho** [comment]
When I rebase after merging your PR, I've got the following message:
```
donh@XXXXXX MINGW64 /c/sources/notepad-plus-plus (master)
$ git rebase -i
Auto-merging PowerEditor/installer/nativeLang/russian.xml
CONFLICT (content): Merge conflict in PowerEditor/installer/nativeLang/russian.xml
error: could not apply ee17ce8e... Update russian.xml to v7.9.3

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

Could not apply ee17ce8e... Update russian.xml to v7.9.3

donh@XXXXXX MINGW64 /c/sources/notepad-plus-plus (master|REBASE-i 1/4)
```
So I revert the change you made from my local master. I'm gonna close this PR. Please make a new PR based on current state of russian.xml, and change only where you need to change.

**Comment by GOLEM777** [comment]
> When I rebase after merging your PR, I've got the following message:
I have similar after deleting line id6430 i got conflict of file.  Therefore I tryed merged into patch-29.
Strange error!

**Pull request closed without merging**
