### PR TITLE
TiXmlBase::StringEqual: ignoreCase parameter is mistreated

### PR DESCRIPTION
**Pull request by QoL15155**
[Issue #9545](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9545)

### CODE REVIEW

**Review by mere-human — COMMENTED** [review]
The PR itself looks good.

But on a side note, I've just discovered that the version used in this project had been discontinued https://sourceforge.net/projects/tinyxml/

> *Please Note* that TinyXML development has stopped and all development has moved to TinyXML-2. TinyXML-2 is available at https://github.com/leethomason/tinyxml2

Should we consider an upgrade in the future?

**Comment by sasumner** [comment]
>Should we consider an upgrade in the future?

It's truly a question for @donho but IMO if it isn't broken, don't fix it.

**Comment by donho** [comment]
@QoL15155 
As I said,  you have to report the bug in the [issue tracker](https://github.com/notepad-plus-plus/notepad-plus-plus/issues), provide the description of bug and instructions to reproduce the bug. Then create a PR to refer the bug fixed in this PR.

Here is an example of valid issue you should create: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9556 for your fix (commit) https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9543/commits/9a97163940fefa085a4735fc10d9b1558066089b

**Comment by donho** [comment]
@QoL15155 
FYI:
I did a cherry pick on your commit regarding issue #9556. 
I let you create a (or 2, for the remain commits) bug to prove your commit does fix bug in the binary.
On the meantime, this PR is suspended.

**Comment by donho** [comment]
@mere-human 
> Should we consider an upgrade in the future?

I don't update because there is one available. Tiny XML works quite well in Notepad++ project, so as @sasumner said: "if it isn't broken, don't *update it".

**Comment by QoL15155** [comment]
@donho 
I did create an issue : [issue 9545](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9545)
I guess in my initial descrpition I put the wrong link (sorry :)) Fixed it now.

**Comment by donho** [comment]
As the bug issue cannot be provided, this PR is rejected & closed.

**Pull request closed without merging**
