### PR TITLE
Update ukrainian.xml

### PR DESCRIPTION
**Pull request by bigvovan**
new file

### CODE REVIEW

**Comment by a-polivanchuk** [comment]
Hi @bigvovan 

Ukrainian translators of Notepad++ are working on https://crowdin.com/project/notepadpp
There is a simple while powerful localization workflow.
Please join our team and help us with translation :)

**Comment by a-polivanchuk** [comment]
@bigvovan I've just created new PR #4198 with a bunch of new translations and some corrections.
I would propose to close this PR and join our team on Crowdin to help us make further improvements :)

**Comment by donho** [comment]
@a-polivanchuk Can I let you take in charge of this PR?

**Comment by a-polivanchuk** [comment]
@donho I see neither any crucial corrections nor fixed mistakes in this PR, only changes for several strings.
The requestor is not responding, so I propose to close it.

**Pull request closed without merging**
