### PR TITLE
Improvements for JSON highlighting

### PR DESCRIPTION
**Pull request by vlakoff**
Note: I haven't tested the changes of cd2f5ba86af6705cf26a0e37117ba5b98bd05400, there might be errors.

Refs #1303

### CODE REVIEW

**Comment by vgturtle127** [comment]
@vlakoff @donho JSON is only supported via a plugin currently, I thought?

**Comment by dail8859** [comment]
JSON support is in v6.8.4

**Comment by vgturtle127** [comment]
@dail8859 Thanks. :wink: 

Time to remove JSON Viewer, then. :smile:

**Comment by thedarkfalcon** [comment]
I know that this issue has been closed, but I can't find anywhere more appropriate, and I didn't want to create a new issue as this one seemed to describe my issue.

JSON syntax highlighting doesn't appear to be working for me. I have tried NPP 6.9.X and also 7.1 (with regular plugins, also with plugins disabled), also with the basic theme and other themes. I also tried on multiple machines, same behaviour on all.

I have starting using VSCode due to this issue, but would like to use NPP.

How JSON looks in NPP:
json_npp
How JSON looks in VSCode:
json_vscode

The [release notes for 6.8.5](https://notepad-plus-plus.org/download/v6.8.5.html) says "Add JSON language support.", which appears partially correct, NPP knows how to collapse JSON, but there is no highlighting?

**Comment by dail8859** [comment]
Assuming you are using the default theme, try deleting (or moving if you want to save it) your `stylers.xml` (probably located under your appdata folder). This should reset all the language styling.

**Comment by thedarkfalcon** [comment]
That did indeed regenerate the stylers.xml, but that did not fix the JSON highlighting.
Just checking, does JSON highlighting actually work for you (i.e. this is a localised issue for me only)?

**Comment by dail8859** [comment]
It works for me. What does the bottom left of N++ say? It should say "JSON file" when you open it. There isn't a lot of highlighting to JSON.

**Comment by thedarkfalcon** [comment]
Yes it shows its a JSON file, but there is no syntax highlighting difference in the JSON files between keys and values.  I would expect something like VSCode in my earlier post.
___npp

**Comment by dail8859** [comment]
`Notepad++ != VSCode`

Internally there is not a dedicated lexer to JSON. It reuses the C++ lexer, so it just sees them as strings. When Scintilla is upgraded eventually there is a dedicated JSON lexer that has **much** better support.

**Comment by thedarkfalcon** [comment]
Okay thanks, that's all I wanted.

**Pull request closed without merging**
