### PR TITLE
Don't halt find/replace operation because of large file

### PR DESCRIPTION
**Pull request by SinghRajenM**
Fixes defect: #4131 ,  #1889 and #2072

Many times, we get multiple logs (specially from server/production server) to analyze reported issues. Sometimes, these logs are more in number whereas few logs are huge in size. Notepad++ is very useful to find special keywords such as ERROR. **But sometimes the complete process gets stuck due to big file. Unless we kill the messagebox it does not proceed further**.

-----------------------------
### Update
~~I have two proposals to deal with this.~~
~~1. By default ignore large files for search/replace and once operation is complete show the ignore file details. This message box can be shown/hidden using setting.~~
~~2. Provide a setting to exclude large files. Once operation is complete show the ignore file details. If exclude file setting is disabled, then keep the existing behavior.~~

~~This PR implements the second approach. If the proposal sounds good, I'll will improve it by moving strings to localization files.~~

In this PR, I tried to solve the above issue. When "Find in Files" or "Replace in Files" operation is performed and npp is unable to open a file, then skip that file and continue with rest of the files. In the end of operation, show the details of skipped file(s) if any.

image

-----------------------------

## Further ToDo##
If the solution sounds good, I will update the PR to support localization.

## ##
Accidentally closed previous PR #4140 while resolving conflict. So opening again.

### CODE REVIEW

**Comment by kevinf28** [comment]
Does this scale with 100s of too large files? I see that Ok button being buried quick. Scrollbars or ... after X entries ?

**Comment by bladeoflight16** [comment]
Might I suggest taking a look at [my comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1889#issuecomment-374430377) in #1889? It should deal with the scaling problem more smoothly and negate the need for a setting.

**Comment by SinghRajenM** [comment]
Improved it as suggested by @bladeoflight16.

**Comment by xantari** [comment]
This hasn't been merged yet? Why not?

**Comment by SinghRajenM** [comment]
>This hasn't been merged yet? 

No, it is not merged yet.

>Why not?

Only @donho knows. 😉

**Comment by informatorius** [comment]
Would like to see this merged too :-)

**Comment by SinghRajenM** [comment]
@donho Did you get time to review this PR?

**Comment by SinghRajenM** [comment]
> 
> 
> @donho Did you get time to review this PR?

@donho still waiting for your response.

**Comment by grantmatheny** [comment]
Please merge this as soon as possible! Still an issue in 7.8.5!

**Comment by wonkawilly** [comment]
I'm really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and ask others to. More opinion are welcome. Thank you all.

**Comment by RobertTanenbaum** [comment]
@donho - This may not be a "bug", but it is definitely a feature that many people have requested. 
It is quite painful when I am searching a repository of thousands of .txt files and I have to monitor the search and click on the error popup whenever it occurs.
Being able to specify that the popup regarding too big files be suppressed, is sorely needed.
Is there any way to make an equivalent change in the current code base, so that this feature can be added?

**Comment by SinghRajenM** [comment]
Good to see this PR reopened.
@donho , should I resolve conflicts if you want to take it further?

**Comment by alankilborn** [comment]
@SinghRajenM 

I like your GUI approach to this at the very top.
I was curious if read-only files as well as files too large to open would be included in this?

**Comment by donho** [comment]
@SinghRajenM 
Thank you for your feedback.
As you might notice, v8.2.2 release candidate is out, and in this version (for x64 build) the 2GB restriction will be removed. So normally it should work with v8.2.2 x64 binary (or with a minimum tuning). 
I opened it as a reminder, so it's not necessary do anything for this PR, at least not before the official release of v8.2.2.

**Comment by donho** [comment]
@SinghRajenM @RobertTanenbaum 

After some testing, I confirm you that large file searching restriction has been removed. There is a large file opening confirmation which may be not expected, but it's working.

**Pull request closed without merging**
