### PR TITLE
Fix unsupported language set to english

### LINKED ISSUE #3844: 7.5.1 Only installs as "Afrikaans"
### Description of the Issue
Installing ver 7.5.1, 32 or 64 on MS Server 2012 R2 Standard. I get (Dutch) as the language. My servers are set to English. Previous versions all installed as English. 
Attached screenshot is first screen after launching installer.  It does not matter what login is used, or if you choose Install as Administrator.
Last version I have loaded was 7.4.2

### Steps to Reproduce the Issue

1. download 7.5.1 32 or 64bit
2. try to install on MS Server 2012 R2 Standard
3. 

### Expected Behavior
Install in english or prompt for language

### Actual Behavior
starts install in Dutch, 

### Debug Information

notepad_dutch

### LINKED ISSUE #7574: Installer language is Afrikaans instead of English on Windows Server 2016.
### Description of the Issue

The Notepad++ installer instead of English is shown in Afrikaans. Afterwards also the notepad++ is shown in this language.
Language and regional settings on Windows 2016 OS are set to US (English).

Found similar closed bug: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3844
and 
https://community.notepad-plus-plus.org/topic/14564/dutch-as-install-language-instead-of-english

### Steps to Reproduce the Issue

1. Double click  on the "npp.7.8.1.Installer.x64.exe".
2. Confirm UAC.
3. Installer is shown in Afrikaans.
4. After installation the Notepad++ application is also in Afrikaans.

### Expected Behavior

Installer is shown in English (like other installers on US/English OS).
### Actual Behavior

Installer is shown in Afrikaans, also the installed application defaults to it.

### Debug Information

Windows Device Guard is active on this system.

2019-11-14 10_21_25-NotepadPP
2019-11-14 10_30_37-Windows-Regional1
2019-11-14 10_31_00-Windows-Regional2
2019-11-14 10_31_00-Windows-Regional3
2019-11-14 10_31_00-Windows-Regional4
2019-11-14 10_37_09-notepadpp-gui

### PR DESCRIPTION
**Pull request by mpheath**
Fix #3844
Fix #7574

### CODE REVIEW

**Comment by mpheath** [comment]
I reviewed again and amended the commit so that `1033` is replaced with `${LANG_ENGLISH}` .

**Comment by schnurlos** [comment]
Would be nice to see languages sorted in alphabetic order.

**Comment by mpheath** [comment]
@schnurlos Sorted in alphabetic order as you requested.

**Comment by donho** [comment]
The installer x86 & x64 of this PR which contain the fix of the issue (#3844 & #7574) are available here:
http://download.notepad-plus-plus.org/repository/MISC/fixInstallLangIssue/

They are the latest version 8.5.7 and binaries are signed.
Please test the installer of your choice, and confirm me if this issue has been fixed.

**Comment by donho** [comment]
The PR doesn't seems work:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3844#issuecomment-1729507977

OTOH, the problem could be caused by McAfee: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1487933838

So the PR is closed.

**Pull request closed without merging**
