### PR TITLE
Add confirmation dialog for "Replace All in All Opened Documents"

### PR DESCRIPTION
**Pull request by Myrcellion**
The issue #5253 states that a user can accidentally replace all occurrences of a string in all opened documents rather than in a single document. When it happens, the user needs to undo in every opened document, one after another. In order to prevent this, I thought that adding a confirmation dialog before executing the replace could be a solution.

replace

The code behind the dialog is inspired from the doCloseOrNot function from Notepad_plus.cpp
code

### CODE REVIEW

**Comment by vlakoff** [comment]
This would be consistent with "Find in Files > Replace in Files" which already has a confirmation dialog.

On the other hand, a mistake with "Replace All in All Opened Documents" is not a disaster (you can undo the changes and the files are not saved) whereas "Find in Files > Replace in Files" is quite dangerous (not undoable, files saved in the process).

Also, maybe the two dialogs could be uniformized a bit (for example one has Yes/No the other has OK/Cancel).

**Comment by Myrcellion** [comment]
I updated the options to OK/Cancel and modified the text of the dialog to match the "Find in Files > Replace in Files" dialog.
npp03
A mistake with "Replace All in All Opened Documents" is indeed not a disaster, it is simply annoying and potentially time-consuming as it has to be undone for every opened document, which may be a boring operation if there are many. This additional dialog is certainly not vital, but as you said, it would be consistent with "Find in Files > Replace in Files" and prevent some mistakes.

**Comment by vlakoff** [comment]
I'd tend to agree with the addition of this dialog.

I use a lot the "Replace All" feature, but much less the "Replace All in All Opened Documents" feature, and when I do it's for "large works" (refactoring, etc) where an additional prompt doesn't add much time to the total time spent on the task.

**Comment by sasumner** [comment]
I would have thought that "Yes/No" is better than "OK/Cancel" to an "Are you...?" question.  Meh.

**Comment by vlakoff** [comment]
Personally I'd vote for OK/Cancel, because Yes/No is a choice between two options, whereas OK is for confirming ("go forward") and Cancel is a "do nothing, panic escape" action.

But this could be debated for ages, let's be happy as long as the two dialogs are consistent :)

**Comment by Myrcellion** [comment]
Well, the "Find in Files > Replace in Files" already exists and uses Ok/Cancel, the changes to the text of "Replace All in All Opened Documents" are also based on this already existing dialog, for consistency purpose.

**Comment by donho** [comment]
As @sasumner said:
> It's possible to undo, you just have to move to each document and execute Undo. Not great, but not catastrophic either.

**Pull request closed without merging**
