### PR TITLE
Update portuguese.xml

### PR DESCRIPTION
**Pull request by hugok79**
For commit: 7d5516e0a8ef69d04165926255828cc70c0c3811

Other minor corrections/improvements

### CODE REVIEW

**Comment by donho** [comment]
Thank you for the update of localization file.

Could you check the following announce and confirm that your localization is updated?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12058

In case that you are not on time to do your update or confirmation, this PR will be merged for the release v8.4.5.
Your next PR will be merged in the future release.

**Comment by hugok79** [comment]
@donho Done! **portuguese.xml** fully updated

**Comment by Mateos81** [comment]
Hmm, there's an extra portuguese.xml file at the root of the project now ^^'

**Comment by hugok79** [comment]
@donho  Can you re-open the pull? The file was in a wrong location!

**Comment by hugok79** [comment]
Fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12065

**Pull request closed without merging**
