### PR TITLE
Add capability to find-all in selected text of current document

### LINKED ISSUE #7927: Grouping box wrapping 'In-Selection' and 'Count' is misplaced
### Steps to Reproduce the Issue

0. (Added post-issue creation).  Start Windows with your primary display one that is greater than 96 d.p.i.  I started mine with my laptop's screen (120 d.p.i) as my primary (and only) display.

1.  Invoke `Replace` window; note positioning of grouping box around `In selection` and `Replace All` controls:  

image

2.  Invoke `Find` window; note positioning of grouping box around `In selection` and `Count` controls:

image

3.  Compare the results of 1 and 2 and notice that while 1 looks nice and is well-placed; 2 looks bad and is mis-aligned.  For 2, the grouping box needs to be repositioned "upward" a few pixels.

### Expected Behavior
I expect the UI to look nice in this regard. :-)

### Actual Behavior
The UI does not look nice in this regard. :-( 

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\.........\npp.7.8.4.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1565
Plugins : mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll

### PR DESCRIPTION
**Pull request by sasumner**
Implements #8133 , #8213 
Fixes #7927
Perhaps implements some of the spirit of #5089 
Perhaps implements some of the spirit of  this Community [THREAD](https://community.notepad-plus-plus.org/topic/17802/block-commands)

--------------------------------------------------

The implementation is to make _Find All in Current Document_ respect the _In Selection_ checkbox, and to change the text in the _Find result_ window to reflect that a search was done at the "selection" scope:

image

In the _Find_ window, to emphasize that _In Selection_  can apply to _Find All in Current Document_ , the groupbox UI element that contained _In Selection_ and _Count_ buttons is changed to contain all three of _In Selection_ and _Count_ and  _Find All in Current Document_ :

image

To make the containing groupbox approach feasible, it was needed to swap the positions of _Find All in Current Document_ and _Find All in All Opened Documents_ buttons.  While I don't like to change the user interface, it makes sense to do so in this case, with additional argument for doing it provided in #8123 .

--------------------------------------------------

The subject of this PR previously had two submitter-aborted tries (sorry for the noise on this):  #8207 and #8140

### CODE REVIEW

**Comment by GOLEM777** [comment]
Does this really work with separate selection? 
Оr $INT_REPLACE3$ rudimentary and show number of files?

**Comment by sasumner** [comment]
@GOLEM777 I have no idea what you are trying to ask with that.

**Comment by Uhf7** [comment]
Only a suggestion, but I think, that the _Find_ dialog looks too much different compared to the _Replace_ dialog. My preferred look would still be as said in #8213 (_Find_ on the left side, _Replace_ on the right side):

FindDlg001

This would not change functionality, but the dialogues would fit much nicer together, because:

- The **Find next** buttons are the same and look the same, they are good as they are.
- The **Replace** button exists only in the _Replace_ dialog, naturally.
- The **Find all** button is the equivalent to the **Replace all** button and could look similar.
- The **... in all Documents** buttons and the **Close** buttons already look similar as they should.
- The **Count** button in the _Find_ dialog is a special function. It needs the **In selection** frame around it, so it could be placed like shown. PRO: The **In selection** frame remains much more compact.

And, since we swap the **Find all in Current Document** and **Find all in All Opened Document** buttons anyway, the slim design could help the users to adopt to the new button order, instead of accidentally hitting the wrong of the equal sized **Find all in ...** buttons, because they changed places.

**Comment by donho** [comment]
I guess that's is what @GOLEM777 is talking about:
image
If my guess is right, it should not work with separate selection (like `Count` behaviour) and 
`N hits in 1 file of 1 searched` format should be kept as it is.

**Comment by GOLEM777** [comment]
capture_06152020_195338

**Comment by donho** [comment]
@Uhf7 Though I don't like the UI of this PR, at least it keeps the same logic (all the commands are in the same column on the right) IMO.

**Comment by sasumner** [comment]
@Uhf7 I _did_ note your comments on UI.  However, I don't like to change existing UI except when absolutely necessary, because it is an unpopular thing to do (with users and author), even when it makes things better.  This PR changes UI only because I felt it had to.  Because it "had to", I took the suggestion in #8213 and that only in its minimal sense.

**Comment by sasumner** [comment]
@donho said:

>I guess that's is what @GOLEM777 is talking about ,,, If my guess is right, it should not work with separate selection (like Count behaviour) 

Existing released Notepad++ behavior:  _In Selection_ is greyed when more than one selection is active.  Thus it is not possible to _Count_ in more than one selection, nor do the subject of this PR in more than one selection, no do _any_ Find/Replace/Mark operation when more than one selection is active.  

Doing what @GOLEM777 suggests is beyond the scope of the current PR, because it opens the door to having _Count_ handle multiple selections as well.  That functionality would be fine, except it should have its own issue, suggest: "Find/Replace/Mark functions should work on multiple selections".

>and `N hits in 1 file of 1 searched` format should be kept as it is.

Wouldn't that be misleading?  You could do two searches back-to-back, one with entire file scope, the other with selection scope, and they would look the same except for a different number of hits:

`Search "foo" (5 hits in 1 file of 1 searched)`
`Search "foo" (2 hits in 1 file of 1 searched)`

>Though I don't like the UI of this PR

What specifically bothers you here?
We can fix it, whatever it is.  :-)

**Comment by Uhf7** [comment]
> at least it keeps the same logic (all the commands are in the same column on the right)

Yes, but one could say that **Count** is a special command here, the only one which does not do real action, except of displaying the number of results. It is a kind of preview of what is to expect when the **Find all** function beside it is executed. And, one could say, we have a huge empty white space wasted below the **Find what** input box anyway, why not use it? 

And, as I cannot say often enough (sorry for repeating), the _Find_ dialog and the _Replace_ dialog look like made by different persons on different days. It's like a car with a green door on the left and a blue door on the right, for me.

**Comment by Uhf7** [comment]
>  I don't like to change existing UI except when absolutely necessary.

Yes, this strategy works if no UI change at all is necessary. Then one can say, I leave it (as bad) as it is, no harm done. 

But here, 
- the UI is changed anyway, 
- two nearly equal looking buttons are swapped,
- the _Find_ dialog is designed different to the _Replace_ dialog, optically even more after this PR than before,

so, why not try to pull it straight. Of course, its all subjective ...

**Comment by sasumner** [comment]
So is there value in the scope of this PR, aside from the UI?
If the answer is No, we close it.
If the answer is Yes, then @donho tells me how to resolve this concern:

>Though I don't like the UI of this PR

It really is _that_ simple. :-)

**Comment by donho** [comment]
@sasumner 
> What specifically bothers you here?

I just feel it's not pretty, but I have no better solution, so let's keep it as it is in PR.

>> and N hits in 1 file of 1 searched format should be kept as it is.

> Wouldn't that be misleading? You could do two searches back-to-back, one with entire file scope, the other with selection scope, and they would look the same except for a different number of hits:...

Not sure what you mean, but I what I meant for the expected result is what you have implemented.

**Comment by sasumner** [comment]
@donho said:

>I just feel it's not pretty, but...

Maybe you mean the big groupbox with a lot of open space around _In selection_, and the checkbox being uncentered vertically?
Well, if you'll notice, what I did was made it so _In selection_ never moves on the three of four tabs that implement it.  For some reason, for me that is satisfying. :-)

Thank you for valuing the content of the PR, even if not the UI.  At work, we have to do a lot of searches of this type.  At least weekly some colleague will ask me how to search only within selected text with Notepad++.  Soon I will be able to tell them how to do this.

**Pull request closed without merging**
