### PR TITLE
Issue 804 open new tab next to active tab

### PR DESCRIPTION
**Pull request by irgendsontyp**
Implements an option to open new tabs next to the active tab (#804).

### CODE REVIEW

**Comment by irgendsontyp** [comment]
I was not able to remove those other two commits from the PR. I haven't worked much with git yet. Can someone tell me how to get rid of those commits (c403a06 and 9d40290)?

**Comment by tarung65** [comment]
You have made changes In 2015 project file due to which it won't compile on visual studio 2015 I think correct way of doing it to create a new project file for 2017 instead of changing 2015 file as done by me in pull request #3484

**Comment by irgendsontyp** [comment]
So should I delete this PR and create a new one, only containing the commit required for the feature?

**Comment by donho** [comment]
@irgendsontyp Thank you for your contribution.
However, it's a small feature need a lot of change in codes, not mention to additional option to make UI more complicated. 
As a result, this feature won't be included in the official release.

**Pull request closed without merging**
