### PR TITLE
Improve "Close all BUT This" functionality

### PR DESCRIPTION
**Pull request by SinghRajenM**
Fixes: #7553

In continuation to previous PR #7502, this PR improves user experience for "Close all But This" feature. Moreover, this PR makes "Close All BUT this" feature consistent with "Close All to the left/right".

### CODE REVIEW

**Comment by donho** [comment]
@SinghRajenM 

Your branch  `src_forcedJunkCodeToFix7553` contains a bug, I cannot reproduce steadily though.
But you can try it several times in the case of a dirty document in a view and its cloned document in another view, 80% you can produce it :

1. Open an existing file in Notepad++, clone it to the 2nd view.
2. Make this file dirty.
3. create several new documents in both view (2 - 5 in each), make them dirty.
4. Right click on the opened existing file's tab to have the context menu, run "Close All BUT This" command.
5. answer "No" for each dirty file to save, except the last one.
6. answer "No to all" for the last dirty file to save.

Now you can see not there are few files left.

**Comment by donho** [comment]
Is it the "Junk Code" code which makes the bug mentioned above?
Nope. "Junk Code" works with some unexpected behaviour, but the bug is inserted by your code.

If I were you, I would do 2 commits for it - one for the fix and one for refactoring, so the project maintainer has the option.
It's not necessary to explain why I want minimum lines of code for the fixes. The following page explains well:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md

As project maintainer, I have my way to get jobs done. Feel free to fork Notepad++ to do thing in your way.

**Comment by SinghRajenM** [comment]
@donho 
1. >I cannot reproduce steadily though.

    But I can reproduce easily. You need not to have cloned view. Just create 2~3 dirty tabs and click on "No to All" as soon save dialog appear. Boom, you will see the defect. And the root cause it flag `noSaveToAll` in both the `for` loops at lines [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7559/files#diff-76c62ef652708b4b7b02f049a16b0629R1209) and [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7559/files#diff-76c62ef652708b4b7b02f049a16b0629R1272). 

    This is where code review comes into the picture, not for the number of lines changed. **FYI, I didn't change these lines, but these lines should be part of code review, shouldn't it?**


2. >If I were you, I would do 2 commits for it - one for the fix and one for refactoring, so the project maintainer has the option.

    But this goes against the policy (Make single commit per PR.) which is **clearly defined by you**. So, don't know when do you expect single commit and when 2 or more. 
    BTW, I have done 2~3 commit in single PR in past which were straight forward rejected.


3. >Feel free to fork Notepad++ to do thing in your way.

    It is not required @donho. You are going good job and keep doing it.

_Anyway, it is time to say thank you now. I will no longer trouble you. You will not receive any further PR from me. I had a great experience while working with Notepad++ community. I have learnt a lot from here. Thank you!_

**Comment by AngryGamer** [comment]
@SinghRajenM
> _Anyway, it is time to say thank you now. I will no longer trouble you. You will not receive any further PR from me. I had a great experience while working with Notepad++ community. I have learnt a lot from here. Thank you!_

I'm also no longer contributing patches for similar reasons. Don Ho treats his regular contributors with apathy. There's been more than a few PRs rejected or outright ignored for the most arbitrary reasons. I've even seen a couple straightforward patches with backing from like 5+ [regular contributors](https://github.com/notepad-plus-plus/notepad-plus-plus/graphs/contributors) that ended up arbitrarily rejected with all dissent completely ignored. I don't think he cares about his userbase. This project is nothing more and nothing less than a means for him to score social & political points within his social circles.

**Comment by AngryGamer** [comment]
@SinghRajenM
> _Anyway, it is time to say thank you now. I will no longer trouble you. You will not receive any further PR from me. I had a great experience while working with Notepad++ community. I have learnt a lot from here. Thank you!_

I'm also no longer contributing patches for similar reasons. Don Ho treats his regular contributors with apathy. There's been dozens of PRs rejected or outright ignored for the most arbitrary reasons. I've even seen a couple straightforward patches with backing from like 5+ [regular contributors](https://github.com/notepad-plus-plus/notepad-plus-plus/graphs/contributors) that ended up arbitrarily rejected with all dissent completely ignored. I don't think he cares about his userbase. This project is nothing more and nothing less than a means for him to score social & political points within his social circles.

**Comment by AngryGamer** [comment]
@SinghRajenM
> _Anyway, it is time to say thank you now. I will no longer trouble you. You will not receive any further PR from me. I had a great experience while working with Notepad++ community. I have learnt a lot from here. Thank you!_

I'm also no longer contributing patches for similar reasons. Don Ho treats his regular contributors with contempt. There's been dozens of PRs rejected or outright ignored for the most arbitrary reasons. I've even seen a couple straightforward patches with backing from like 5+ [regular contributors](https://github.com/notepad-plus-plus/notepad-plus-plus/graphs/contributors) that ended up arbitrarily rejected with all dissent completely ignored. I don't think he cares about his userbase. This project is nothing more and nothing less than a means for him to score social & political points within his social circles.

**Comment by AngryGamer** [comment]
@SinghRajenM
> _Anyway, it is time to say thank you now. I will no longer trouble you. You will not receive any further PR from me. I had a great experience while working with Notepad++ community. I have learnt a lot from here. Thank you!_

I'm also no longer contributing patches for similar reasons. Don Ho treats his regular contributors with contempt. There's been dozens of PRs rejected or outright ignored for the most arbitrary reasons. I've even seen a couple straightforward patches with backing from like 5+ [regular contributors](https://github.com/notepad-plus-plus/notepad-plus-plus/graphs/contributors) that ended up arbitrarily rejected with all dissent completely ignored. I don't think he cares about his userbase. This project is nothing more than a means for him to score social & political points within his social circles.

**Comment by donho** [comment]
@AngryGamer Thank you for your remark. I took note of it, and I will pay more attention about my attitude next time.
Anyway, thank you and thank @SinghRajenM for your contribution. It's sham that Notepad++ won't get your contribution any more and I apology if my attitude offended you.

**Comment by SinghRajenM** [comment]
@AngryGamer it is not only you and me. There are many in the list who fed up. 

Look at the attitude. 
1. As per him whatever he writes is **`unexpected behaviour`**, but same is bug if written by others.
2. More than software, many political agendas were spread (like Yellow vest, Free Uyghur, Taiwan LGBT, and so on).
3. Branding text of installer (`BrandingText "Software is like sex: It's better when it's free"`). One day, I was mentoring my junior colleagues about nsis installer and I took the npp installer for explanation. I ashamed when I touched `BrandingText` topic.

But yes, if I leave all these things apart. I enjoyed my 3 years of journey here.

**Comment by bahusoid** [comment]
@SinghRajenM You've actually been very patient. Kudos to you :)  I've stopped contributing very quickly - PRs too often are closed with so silly remarks. It seems time to create donho free version of notepad  - angry contributors fork :)

**Comment by AngryGamer** [comment]
@bahusoid 
> @SinghRajenM You've actually been very patient. Kudos to you :) I've stopped contributing very quickly

Haha, yeah. I guess you were the smart one there.

On that note, @sasumner is doing a great job of instilling realistic expectations into new contributors. 

I've been watching him alienate them in real-time with strict discourteous responses. I had mixed feelings about it at first, but it's better they get a good grasp of what they're up against now rather than months down the road. FYI @sasumner, I'm not hating on you, I understand the difficult position you're in.

> PRs too often are closed with so silly remarks. It seems time to create donho free version of notepad - angry contributors edition :)

That would be entertaining. The _BrandingText_ could be quotes of the various reject reasons with a  translation of their _true meaning_.

**Comment by AngryGamer** [comment]
@chcg @CookiePLMonster @pnedev @vlakoff @xylographe @cmeriaux

How are you guys feeling about contributions?

**Comment by cmeriaux** [comment]
@AngryGamer @donho 

I feel the same way as you guys. 
Lot's of PR are rejected even when they are accepted by top contributors. totally demotivating !!!

@SinghRajenM big kudos for you. Your contributions is so impressive in only 3 years, your motivation is so strong !!! I hope the community won't loose you.

I was so sad when we lost contributore @bruderstein with its famous "plugin admin" plugin. The new system is still far from the old one. I tried to add a tiny field (relesae date) => rejected. I'm trying to add a UI resizing feature => not yet rejected but still waiting for 6 months
I also have a filtering feature in addition of search feature but I'm pretty sure it will be rejected !

I don't know why I'm still trying to contribute. Maybe because I love Npp since 13 years.

Big thanks for every contributors of the repository, and every user of the community forum like   [guy038](https://community.notepad-plus-plus.org/user/guy038) who are devoted to help users.

**Comment by CookiePLMonster** [comment]
@AngryGamer @SinghRajenM @cmeriaux 

It's sad to see things evolve this way. Now without @SinghRajenM contributing further, this project can focus on truly important changes, like [more easter eggs](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/72168497232290a697cc499326a351b405084f59)!

Snarky comments aside, I've been on and off contributing to N++ and even though apparently a vast majority of my contributions were not rejected, I can see a disappointing trend - every time I browse PR's or issues here, I see @SinghRajenM successfully trying to sort out the mess of the code causing obscure failures people report. I cannot grasp how can those be shot down under an excuse of making diffs too big and instead directing to forks (which sounds an awful lot like a programming equivalent of "_I don't want you in my sandbox, go play on your own_"). This is a very dangerous attitude to take towards people who **willingly** and **voluntarily** work on things.

Truth is, this project seems unfriendly for most of the newcomers not only because of policies and unclear reasoning behind rejecting contributions, but also because of how stale the code is - it's painfully obvious it dates back to early 2000s and has not evolved much since. While I understand concerns about stability and not regressing changes (_Tests? Hello?_), attempts to tame and reduce the technical debt this codebase has should be encouraged, not rejected because they are big or do not tie to any specific issue report (seriously?). At some point, nobody is going to want to touch the codebase because of how convoluted and outdated it becomes. Then, somebody who wants to make the change will quickly be discouraged when they get changes rejected due to arbitrary reasons such as "no memory allocations" - even if it means compromising resilience against edge cases.


Like I said, I've been off and on with the project - but seeing how it's been doing lately, I see even less reason to further lurk around issue reports. But hey, at least they've halved in volume, which is commendable.

**Comment by donho** [comment]
> I just noticed another disappointing behaviour - what's with rejecting enhancements (#7566) and then commiting them either way without any notice (30e545a), effectively removing authorship from the original contributor? This change might be tiny, but it's still not very polite, @donho

The PR has been closed and branch has been deleted so there's no way to keep the authorship.

**Comment by CookiePLMonster** [comment]
> The PR has been closed and branch has been deleted so there's no way to me to keep the authorship.

I guess asking to reinstate the PR would also be a possibility but that's fair enough nonetheless, okay.

**Comment by AngryGamer** [comment]
@CookiePLMonster
> > The PR has been closed and branch has been deleted so there's no way to me to keep the authorship.
> 
> I guess asking to reinstate the PR would also be a possibility but that's fair enough nonetheless, okay.

Too late for that. The courteous thing at present is replying to PRs with a commit message (so author knows his patches were acknowledged) and then change label to "approved". What I find funny is @donho put a reject label on some of @bobsayshilol's PRs, but he ended up incorporating them anyway. lol

> I cannot grasp how can those be shot down under an excuse of making diffs too big and instead directing to forks (which sounds an awful lot like a programming equivalent of "_I don't want you in my sandbox, go play on your own_"). This is a very dangerous attitude to take towards people who **willingly** and **voluntarily** work on things.

I'm in total agreement.

> because of policies and unclear reasoning behind rejecting contributions ... While I understand concerns about stability and not regressing changes **(_Tests? Hello?_)**

The reject reasons are both baffling and ironic at times. He's rejected more than a few patches because _they **might** regress or contain bugs_ (_what's the point of code review and release candidates?_) at the same time he's skipping code review entirely for his rushed patches and committing them directly into the repository while ignoring concerns about them (arrogance? hypocrisy?). This often [leaves me speechless](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fce74dd894a33bc169d0be75b789a0606aae8474). There's been dozens of his patches which were riddled with typos, unexpected behavior changes, regressions, and bugs which even a half-assed review by anyone would have caught.

**Comment by AngryGamer** [comment]
@CookiePLMonster
> > The PR has been closed and branch has been deleted so there's no way to me to keep the authorship.
> 
> I guess asking to reinstate the PR would also be a possibility but that's fair enough nonetheless, okay.

Too late for that. The courteous thing at present is replying to PRs with a commit message (so author knows his patches were acknowledged) and then change label to "approved". What I find funny is @donho put a reject label on some of @bobsayshilol's PRs, but he ended up incorporating them anyway. lol

> I cannot grasp how can those be shot down under an excuse of making diffs too big and instead directing to forks (which sounds an awful lot like a programming equivalent of "_I don't want you in my sandbox, go play on your own_"). This is a very dangerous attitude to take towards people who **willingly** and **voluntarily** work on things.

I'm in total agreement.

> because of policies and unclear reasoning behind rejecting contributions ... While I understand concerns about stability and not regressing changes **(_Tests? Hello?_)**

The reject reasons are both baffling and ironic at times. He's rejected more than a few patches because _they **might** regress or contain bugs_ (_what's the point of code review, testing, and release candidates?_) at the same time he's skipping code review entirely for his rushed patches and committing them directly into the repository while ignoring concerns about them (arrogance? hypocrisy?). This often [leaves me speechless](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fce74dd894a33bc169d0be75b789a0606aae8474). There's been dozens of his patches which were riddled with typos, unexpected behavior changes, regressions, and bugs which even a half-assed review by anyone would have caught.

**Pull request closed without merging**
