### PR TITLE
Use small size icon (16x16) for tray icon

### PR DESCRIPTION
**Pull request by ozone10**
fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8971

### CODE REVIEW

**Comment by ozone10** [comment]
@Yaron10
could you test?

**Comment by Yaron10** [comment]
@ozone10,

👍 
I've tested the binary from your repo.
It works like a charm.

Thank you.

**Comment by donho** [comment]
Below the comparison of try icon image before the PR and after the PR:

image

I don't see the difference.

**Comment by ozone10** [comment]
@donho 
for me the after icon is more sharper.

@Yaron10 
could you provide before/after example?

**Comment by Mateos81** [comment]
Beyond being sharper, the lines above the animal can be seen, and the holes above are more obvious too

**Comment by donho** [comment]
@ozone10 @Yaron10 @Mateos81 
Thank you for the information you provided.

**Comment by ArkadiuszMichalski** [comment]
@ozone10 Any tips why my compilation is failing? WinLibs doesn't support `LoadIconWithScaleDown`?
```
$ mingw32-make SHELL=cmd
mingw32-make[1]: '../../PowerEditor/gcc/bin.x86_64.build/libscintilla.a' is up to date.
mingw32-make[1]: '../../PowerEditor/gcc/bin.x86_64.build/liblexilla.a' is up to date.
+ linking bin.x86_64/notepad++.exe
d:/webtools/winlibs_x64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.x86_64.build/Notepad_plus.o:Notepad_plus.c:(.text+0x1d3b2): undefined reference to `__imp_LoadIconWithScaleDown'
d:/webtools/winlibs_x64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.x86_64.build/Notepad_plus_Window.o:Notepad_plus_Window.cpp:(.text+0x2a48): undefined reference to `__imp_LoadIconWithScaleDown'
d:/webtools/winlibs_x64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.x86_64.build/NppBigSwitch.o:NppBigSwitch.c:(.text+0x8e5f): undefined reference to `__imp_LoadIconWithScaleDown'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [makefile:259: bin.x86_64/notepad++.exe] Error 1
mingw32-make: *** [makefile:208: all] Error 2
```

**Comment by ozone10** [comment]
@ArkadiuszMichalski 
no idea, maybe because it is supported from Vista.
try adding `-Wl,--major-os-version,6 -Wl,--minor-os-version,0 -Wl,--subsystem,windows` to `LDFLAGS` in makefile

**Comment by ArkadiuszMichalski** [comment]
@ozone10 

Did not help, but we set `_WIN32_WINNT=_WIN32_WINNT_VISTA` in makefile. I tried manually setting other macros and specifying libraries but no effect.

Some search inside mingw:
https://github.com/ArkadiuszMichalski/mingw/search?q=LoadIconWithScaleDown

https://github.com/ArkadiuszMichalski/mingw/blob/9b64c5c337d42a05c050f5fd3f28a6f505a8c284/mingw-w64-headers/include/commctrl.h#L5533
```
#if NTDDI_VERSION >= 0x06000000
  enum _LI_METRIC {
    LIM_SMALL,
    LIM_LARGE,
  };

  WINCOMMCTRLAPI HRESULT WINAPI LoadIconMetric (HINSTANCE hinst, PCWSTR pszName, int lims, HICON *phico);
  WINCOMMCTRLAPI HRESULT WINAPI LoadIconWithScaleDown (HINSTANCE hinst, PCWSTR pszName, int cx, int cy, HICON *phico);
#endif
```

In WinLibs I have this `commctrl.h` file, but it's probably not a problem with include, but with linking? I also opened a bug for WinLibs, maybe they will write some hint:
https://github.com/brechtsanders/winlibs_mingw/issues/139

**Pull request closed without merging**
