### PR TITLE
Update Powershell Lexer

### PR DESCRIPTION
**Pull request by adipiciu**
PowerShell Lexer doesn't recognize escaped quotes within quotes.
#4000 
#3598 
#1394

### CODE REVIEW

**Comment by MAPJe71** [comment]
Or maybe better update to Scintilla 3.7.6 as this issue has been fixed in Scintilla 3.7.5 ([bug 1929](https://sourceforge.net/p/scintilla/bugs/1929/)).

**Comment by donho** [comment]
Will to update Scintilla in the future.

**Comment by passboltUser** [comment]
Why is this still not fixed?

**Comment by DavidHansen-0x454d43** [comment]
@passboltUser, the issue has been fixed in version 3.7.5 of the underlying scintilla component, and it looks like Don Ho has committed to pulling in this version to a future Notepad++ release.

**Comment by passboltUser** [comment]
Let's hope @donho accepts @adipiciu's patch (if it's that easy).

**Comment by ygoe** [comment]
Strange way of using an issue tracker, closing unresolved issues to want to resolve them in the future. Is there a second, hidden tracker that is going to remind him not to forget?

**Pull request closed without merging**
