### PR TITLE
add zulu.xml (given chnages done) 

### PR DESCRIPTION
**Pull request by rra0137**
given changes is done this new pull request

### CODE REVIEW

**Comment by rra0137** [comment]
@chcg your and Don HO given changes done please update him for new binary translation

**Comment by rra0137** [comment]
@donho  Would you please merge pull request.

**Comment by donho** [comment]
@RoshanRathod0137  There are 2 PR opened currently.
Please close 1 of these 2 so I know which one I should check.

**Comment by rra0137** [comment]
@donho i am close 1 pull request   would you please check with this pull request as i am done changes which you told me  thanks

**Comment by rra0137** [comment]
@donho i am close 1 pull request would you please check with this pull request as i am done changes which you told me thanks

**Pull request closed without merging**
