### PR TITLE
contextMenu: Add Sort Lines Lexicographically Ascending/Descending by default

### PR DESCRIPTION
**Pull request by JoseGalRe**
this is really very helpful! xD

### CODE REVIEW

**Comment by cmeriaux** [comment]
you know that you can do those modification in your own notepad++ configuration without committing anything ?

**Comment by JoseGalRe** [comment]
of course, but I thought it would be good to add, many people use these options but don't think everyone knows how to add

**Comment by NN---** [comment]
+1

**Comment by donho** [comment]
It's a very useful feature for some, but I believe not for all.
For the sake of keeping context menu brief and concise, these 2 commands won't be added in default context menu. Please modify your own "contextMenu.xml" instead.

**Pull request closed without merging**
