### PR TITLE
Make Notepad++ color customizable

### PR DESCRIPTION
**Pull request by donho**
Notepad++ is dark-modable now, but why not in green/purple/yellow/red/blue/etc... mode?
This PR is try to make Notepad++ color customizable.
image

### CODE REVIEW

**Comment by donho** [comment]
@ozone10 
I made all members in `darkColors` structure more blue to see the result:

image

As you can see in the screenshot, there are at least 3 places remain unchanged, and it seems the 3 API are the undocumented ones, controlled by WDM. Do you know how to change the colors?

**Comment by ozone10** [comment]
Unfortunately, unless we owner draw it, it is not possible. And for title I don't think it's possible.

**Comment by donho** [comment]
@ozone10 
Then these colors won't be changed and I will make only dark mode but with the different colors for choice.
Thank you for your reply.

**Comment by mere-human** [comment]
> This PR is try to make Notepad++ color customizable.

This looks nice even though other areas aren't customizable!

**Comment by donho** [comment]
@mere-human 
More color tones supported. Check it out ;)

**Comment by mere-human** [comment]
@donho 
> @mere-human
> More color tones supported. Check it out ;)

I checked it out. Looks good!
image

However, for some reason, when I switched from default Black (Dark mode) to e.g. Red tone, the editor style became default white as you can see above.

**Comment by mere-human** [comment]
Also, how about to show small color swatches near each tone here?
image
For example, like here in the Style Configurator:
image

**Comment by GOLEM777** [comment]
Also, how about to show add color picker for custom customizing self color?

**Pull request closed without merging**
