### PR TITLE
[xml] Update brazilian_portuguese.xml

### PR DESCRIPTION
**Pull request by Marcellomco**
Added translation for "Add Begin/End Select in Column Mode command"

### CODE REVIEW

**Review by Marcellomco — COMMENTED** [review]
Add translation for "Translate 'Compact Language Menu' popup dialog".

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Make two items in progress dialog translatable".

**Review by Marcellomco — COMMENTED** [review]
Updating translation for changes in "Make Context menu in Shortcut Mapper (Modify, Delete, Clear) translatable"

**Review by Marcellomco — COMMENTED** [review]
Adding translation for "Fix translation issue for Dock/Undock label in User-Defined dialog"

**Comment by donho** [comment]
Could you please check the following announcement for completing your localization file if it's not done?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13209

Thank you @rddim

**Review by Marcellomco — COMMENTED** [review]
Final revision for V8.5

**Pull request closed without merging**
