### PR TITLE
Followup on issue #3467

### PR DESCRIPTION
**Pull request by chcg**
- update toolset from v140_xp -> v141_xp
- removed outdated VS2013 project file

### CODE REVIEW

**Comment by SinghRajenM** [comment]
@chcg  the build is failing and reason is explained in PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5306. But unfortunately, it was not accepted.

@donho  you may need to look into PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5306 again or @chcg include the changes here.

**Comment by donho** [comment]
@SinghRajenM  There's never problem for me to build under VS2017 with the current code, so I don't see the reason to change it.

**Comment by SinghRajenM** [comment]
> restore all v140_xp instead of v141_xp

@donho ,
Didn't get the context why you want to keep the toolset from VS2015 while both projects (npp and scintilla) have already been migrated to VS2017?

Just for reference from [MS Doc](https://docs.microsoft.com/en-us/cpp/build/how-to-modify-the-target-framework-and-platform-toolset?view=vs-2019)
>**Note**
**To change the target platform toolset, you must have the associated version of Visual Studio or the Windows Platform SDK installed.** For example, to target the Itanium platform with the Windows7.1SDK platform toolset, you must have Microsoft Windows SDK for Windows 7 and .NET Framework 4 SP1 installed; however, you could use another compatible version of Visual Studio to do your development work, provided that you target the correct Framework version and platform toolset.

Currently to build npp, it is required to install toolset of VS2015. Fortunately, MS made it easy to install different versions of toolsets using "Visual studio Installer", but it comes with additional cost. In VS2019 it cost around 3GB extra space.
**Additionally, v140 can be installed, but v140_xp can't be installed using "Visual studio Installer 2019". Not sure about "Visual studio Installer 2017". Hopefully, "Visual studio Installer 2017" should allow to install v140_xp. If not, then VS2015 must be installed separately to build npp.**

image

**P.S. Just curious to know why do you want to keep VS2015 toolset at all instead of VS2017 toolset?**

**Comment by chcg** [comment]
@SinghRajenM You are right, I have local modification for the v141_xp build issues. 
@donho I will update the PR to avoid the compiler issues. Ok?

**Comment by donho** [comment]
@chcg As I said, please restore all v140_xp instead of v141_xp to make PR accept.
@SinghRajenM Yes, I saw that v141_xp come with VS2017. Strangely, it's not installed on my PC.
Since all the releases are built from my PC, I try to keep the build environment as stable as possible.

**Comment by chcg** [comment]
@donho As you want to stay at older VS2015 toolchain the only thing what was left is the removal of the outdate vs2013 project file you did already.
But still unclear as @SinghRajenM pointed out why you want to stick to vs140_xp instead of vs141_xp. See also https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/SciLexer.vcxproj#L30 , so scintilla is also using vs141.

**Pull request closed without merging**
