### PR TITLE
Russian Localization: Rename Encodings in Main menu to reflect consistently line endlings (CR/CR LF/LF)

### PR DESCRIPTION
**Pull request by milbrandt**
In Russian and German language in menu Encoding and in Settings/Preferences/NewDocument the items were partly named "UTF-8/UTF-8 without BOM" and partly "UTF-8 with BOM/UTF-8".

 
notepad-plus-plus/notepad-plus-plus#3926

### CODE REVIEW

**Comment by SinghRajenM** [comment]
Add localization or something similar in the title or PR to get spotted that this is only locale change (no code change) which will increase the change of getting PR accepted sooner.

**Comment by chcg** [comment]
@schnurlos You may want to check the german changes.

**Comment by schnurlos** [comment]
Done, merged here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5101

**Comment by milbrandt** [comment]
German language was merged, Russian changes still open

**Comment by MetaChuh** [comment]
i believe this is deprecated, as the russian utf-8 translation was already changed, as seen at the 7.6.6 screenshot below.

please verify if it can be closed.

**Comment by milbrandt** [comment]
In the Settings - Preferences New Document the Format (Line ending) the line endings are still not explained in Russian, whereas in English and German CR LF/LF/CR are added to the operating system names. Therefore I still propose to merge.

Settings-NewDocuments

**Comment by GOLEM777** [comment]
Made a long time ago.
 Close PLZ!
-
capture_07292019_222101

**Pull request closed without merging**
