### PR TITLE
Appveyor artifacts debug and release

### LINKED ISSUE #1942: Appveyor artifacts debug and release
Fix the Appveyor artifacts configuration.

Also generate the release configuration

### PR DESCRIPTION
**Pull request by cmeriaux**
Fixes #1942

### CODE REVIEW

**Comment by cmeriaux** [comment]
@donho  ping

**Comment by cmeriaux** [comment]
@donho ping. please, it's been a while you agreed my PR but asked to squash 2 commites
thanks

**Comment by donho** [comment]
@cmeriaux Sorry for the delay.
Could you add also for x64 build?
Thanks

**Comment by donho** [comment]
@cmeriaux 
I've got several error messages from Appveyor, one of them is

> Build notepad-plus-plus 1.0.195 failed
> 
> Commit 1df0250795 by Christophe Meriaux on 5/22/2016 3:54 PM: 
> Appveyor artifacts debug and release
> 
> Configure your notification preferences

Any idea about that?

**Comment by cmeriaux** [comment]
@donho 
I'm still working on it but I need help from you because I'm not an expert of Visual Studio Build.

What do I have to use : 
Microsoft Visual Studio 12.0\VC\bin\vcvars32.bat ?
Microsoft Visual Studio 12.0\VC\vcvarsall.bat amd64 ? amd64_x86 ?

I would be more convenient to use only vcvarsall.bat whatever the platform. Is it possible ?

Thanks for the help

**Comment by donho** [comment]
@cmeriaux 
It's due to the boost debug lib - I'll see what can I do about it.

**Comment by chcg** [comment]
See x64 release boost path:

link -OPT:REF -LTCG -DEBUG -LIBPATH:C:\projects\notepad-plus-plus\boost_1_55_0\bin.v2\libs\regex\build\msvc-12.0\release\architecture-ia64\link-static\runtime-link-static\threading-multi -DEF:Scintilla.def ...

vs: x64 debug:

link  -OPT:REF -LTCG -DEBUG -LIBPATH:C:\projects\notepad-plus-plus\boost_1_55_0\bin.v2\libs\regex\build\msvc-12.0\debug\link-static\runtime-link-static\threading-multi -DEF:Scintilla.def ...

, so architecture-ia64 is missing

**Comment by donho** [comment]
@cmeriaux Can't you make sure it works on your side before doing your PR?

**Comment by cmeriaux** [comment]
@donho As I commit with --amend option, the PR is automatically updated. I supposed your are spammed with my tests. So I close it, and will submit against when it works.

In another side, have you read the @chcg  comment ? Will you fix it in another ticket ?

**Comment by cmeriaux** [comment]
It's seems that AppVeyor has serious trouble with their storage. Cache management and artifacts storage throws exceptions

**Comment by donho** [comment]
I'm thinking WITHOUT Boost part - since it generates a lot of problem.
What do you think?

**Comment by cmeriaux** [comment]
Do you mean remove totally boost from NPP ?

**Comment by donho** [comment]
I mean to build in Appveyor without building boost:
https://github.com/notepad-plus-plus/notepad-plus-plus#to-build-scilexerdll-without-boost

**Comment by cmeriaux** [comment]
I think Appveyor must be in the final configuration. If you deliver Npp with Boost support, AppVeyor must build with Boost support.
In that way, appveyor could be our official builder, and deliver automatically "official version" and "nightly build version"

@chcg may found the solution, see his comments in 5a5582b97286678cce7a98eb0810efea38607d7e

**Comment by donho** [comment]
> appveyor could be our official builder
It can't be.
There's a signing procedure to sign all binary.
appveyor will be only the block which check the pr & commit.

**Comment by cmeriaux** [comment]
Ok, nevermind for the official builder.
What about "nightly build version" non signed ? Are you interested ?

**Comment by donho** [comment]
I don't see the advantage of nightly build neither - without boost PCRE, some of features in Notepad++ will broken.
If people need last snapshot, they can pull from master and build their version themselves.

**Comment by cmeriaux** [comment]
If people need last snapshot, it can be a nightmare to build. We are developper, so its easy for use to compile. 
There are so much version of visual studio (community, enterprise, 2012 2013 2015) ... People don't have to official version of npp.

It's so easy for appVeyor to propose the nightly build.

**Comment by chcg** [comment]
added PR #2062 to fix the x64 debug build

**Comment by donho** [comment]
@cmeriaux 
> Ok, we keep boost.

You miss my point. I don't want to keep boost. 
It takes time for each build and could be failed due to boost.

The part of boost will be removed. OTOH, the part of x64 will be added.
AppVeyor will be used only for checking of coherence of x64 and x86 notepad++.exe/scilexer.dll build.

For whom needs Nighty build, they can check out notepad++.exe from the latest build artifacts.

**Comment by cmeriaux** [comment]
fixed in #2079

**Pull request closed without merging**
