### PR TITLE
Update shortcuts.xml

### PR DESCRIPTION
**Pull request by janschreiber**
This pull request addresses issue #471 ("Send via Outlook" > "Send via e-mail"). It is more of a workaround, not a real solution.

### CODE REVIEW

**Comment by Rikk** [comment]
Obs:
- It regresses https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e58ae03897aae88cb8c925b9b659581efb9e5b3d and https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c6f206082e7a23b62d894b0ad8888c9e7c4b0c8a
- Adds "&" for creating menu shortcuts, that doesn't exist in original
- Adds some other custom commands

**Comment by Rikk** [comment]
Have you studied the possibility of using `mailto` links so the system uses the default email program? I'm not sure if `attachment` will work properly for all programs; but, if attachment is not needed `mailto` seems a better option.
Eg:
```
mailto:?subject=$(FILE_NAME)&body=Attachment: $(FILE_NAME)&attachment=$(FULL_CURRENT_PATH)

mailto:?subject=$(FILE_NAME)&amp;body=Attachment:%20$(FILE_NAME)&amp;attachment=$(FULL_CURRENT_PATH)
```

**Comment by janschreiber** [comment]
@Rikk, thanks for pointing out the regressions and for your attachment suggestion. I tried it but Thunderbird ignores the attachment.

**Comment by Rikk** [comment]
1. Now you removed a needed "$" in php line...
2. I see no need to have two commands for the same thing, one specific to Tb (`Send ... as email body text` and `Send ... as email body with Thunderbird`) -- if one has Thunderbird set as default, this may be the only email client in his machine, else he doesn't have Tb.
3. Should not quote the entire `mailto` command. It uses URL syntax.

This is my suggestion:
```diff
-        <Command name="Send selected text as &amp;email body text" Ctrl="no" Alt="no" Shift="no" Key="0">&quot;mailto:?&amp;subject=$(NAME_PART)&amp;body=$(CURRENT_WORD)&quot;</Command>
-        <Command name="Send selected text as email body with Thunder&amp;bird" Ctrl="no" Alt="no" Shift="no" Key="0">thunderbird.exe -compose &quot;to=,subject=$(FILE_NAME),body=$(CURRENT_WORD)&quot;</Command>
-        <Command name="Send current file as attachment with Thunder&amp;bird" Ctrl="no" Alt="no" Shift="no" Key="0">thunderbird.exe -compose &quot;to=,subject=$(FILE_NAME),body=Attachment: $(FILE_NAME),attachment=&apos;file:$(FULL_CURRENT_PATH)&apos;&quot;</Command>
-        <Command name="Send current file as attachment with Out&amp;look" Ctrl="yes" Alt="yes" Shift="yes" Key="79">outlook /a &quot;$(FULL_CURRENT_PATH)&quot;</Command>
-        <Command name="Get &amp;php help" Ctrl="no" Alt="yes" Shift="no" Key="112">http://www.php.net/(CURRENT_WORD)</Command>

+        <Command name="Send selected text as &amp;email body text" Ctrl="no" Alt="no" Shift="no" Key="0">mailto:?subject=$(FILE_NAME)&amp;body=$(CURRENT_WORD)</Command>
+        <Command name="Send current file as attachment with Thunder&amp;bird" Ctrl="no" Alt="no" Shift="no" Key="0">thunderbird.exe -compose &quot;subject=$(FILE_NAME),body=Attachment:%20$(FILE_NAME),attachment=&apos;file:$(FULL_CURRENT_PATH)&apos;&quot;</Command>
+        <Command name="Send current file as attachment with Out&amp;look" Ctrl="yes" Alt="yes" Shift="yes" Key="79">outlook /a &quot;$(FULL_CURRENT_PATH)&quot;</Command>
+        <Command name="Get &amp;php help" Ctrl="no" Alt="yes" Shift="no" Key="112">http://php.net/$(CURRENT_WORD)</Command>
```
Obs: I haven't test if thunderbird command is working.

**Comment by janschreiber** [comment]
@Rikk Thanks for your suggestions, they make perfect sense. But I think I will withdraw this pull request. When doing some more tests I discovered that CURRENT_WORD or the body argument is truncated after 202 characters. By far not as useful as I thought it was.

**Pull request closed without merging**
