### PR TITLE
Add warnings keyword for Perl to langs.model.xml

### LINKED ISSUE #11369: Perl langs.model.xml does not include warnings keyword
### Description of the Issue
The 'langs.model.xml' does not include for Perl the keyword `warnings` as in:

```Perl
use warnings;
```

It does however include `strict` which is used generally in the same case and in conjunction with `warnings` to start most Perl scripts.

```Perl
#! /usr/bin/perl

use strict;
use warnings;
```

This leads to incorrect lexing:

image

When it should be:

image

@pryrt :  as a fellow Perl user, would you agree?

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 11 2022 - 03:16:47
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : -noPlugin
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : none

### PR DESCRIPTION
**Pull request by vinsworldcom**
Fix #11369

Updates keywords for Perl in langs.model.xml to include core pragmas.
Updates those same new keywords in autoCompletion\perl.xml for autocomplete.

Example of new keywords highlighting and showing in AutoComplete:
image

### CODE REVIEW

**Comment by vinsworldcom** [comment]
@pryrt The ones with `::` don't seem to work for me:

image


Cheers.

**Comment by vinsworldcom** [comment]
> Think it could be the Scintilla lexer stopping at the `::`? I so, we can still add the single words `autodie` and `skip` instead of `autodie::skip` together?

Resolved in [issue conversation](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11369#issuecomment-1065192890), we remove the `::` "compound" pragmas.

Cheers.

**Review by pryrt — COMMENTED** [review]
With those changes, it's all working now, and has all the missing pragma keywords that meet the lexer's definition of a keyword.  I'd say it's ready for merging, whenever the Developers are ready to merge it.

**Comment by double-standard-you** [comment]
> Fix #11369
> 
> Updates keywords for Perl in langs.model.xml to include core pragmas. Updates those same new keywords in autoCompletion\perl.xml for autocomplete.
> 
> Example of new keywords highlighting and showing in AutoComplete: image

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

**Comment by donho** [comment]
@vinsworldcom 
Will you keep working on this PR or I can merge it now?

**Comment by vinsworldcom** [comment]
@donho

I think it's good.  Collaborated with @pryrt (Perl expert) and we updated both the keywords in 'langs.model.xml' and the keywords in 'autoCompletion/perl.xml'.

I tested with typing a few of the old and new keywords and they all lexed properly and also tried autocomplete with new keywords way down the list to ensure I put them in 'autoCompletion/perl.xml' in proper alphabetical order.

I think @pryrt comment above signs off from his perspective and I'm happy with it as well.  Nice to give Perl some love!

Cheers.

**Pull request closed without merging**
