### PR TITLE
No toolbar tooltip - fixed

### LINKED ISSUE #10355: Issue: No Toolbar Tooltips
After commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/733c7e73de6d5dece3bcd9eb8784fd2bf61da359 main toolbar tooltips are not showing

### PR DESCRIPTION
**Pull request by Ashfaaq18**
Fix #10355

@Yaron10 and @ozone10 , can you guys give this a thorough check. RTL and LTR tooltips should be working accordingly. 
Check the drag and drop as well.

### CODE REVIEW

**Comment by Yaron10** [comment]
@Ashfaaq18,

It's working perfectly on my machine. 👍 
Thanks again for your time and work.

**Comment by donho** [comment]
@Ashfaaq18 
Do you mind to explain why the change made the regression and why this PR solve the regression?

**Comment by Ashfaaq18** [comment]
Hi @donho, Initially I thought the problem was with only using ScreenToClient, since in this [winapi](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-screentoclient) documentation they suggest using MapWindowPoints for RTL application. But just using that did not work.

So I guessed maybe something should be wrong with the handle "_pPublicInterface->getHSelf()". Therefore, I tried to replicate the problem by returning the handle at the cursor point through WindowFromPoint, this fixed the problem (my previous PR). But I did not realize that the toolbar tips will stop working.

After, @ozone10 brought up the toolbar tip issue, looks like returning the handle through WindowFromPoint is bringing up another problem. This is where I realized the exact problem. 

In both of these scenarios (the initial RTL issue and the recent toolbar tip issue) the program was incorrectly executed at the if else conditions (line 919 in NppNotifications.cpp), this condition works with the handles returned by the ::RealChildWindowFromPoint() function, after further testing there seemed to be something wrong with the handles returned by this function. 

So, after taking a look at the documentations, I used the function ChildWindowFromPointEx to get further control of the handle returned at the cursor point. By skipping the invisible child windows (RealChild skips transparent), I got the problem fixed.

The problem seemed to lie only at the "RealChildWindowFromPoint" statement, nothing to do with the handles I talked about initially, the "_pPublicInterface->getHSelf()" and "WindowFromPoint". So i reverted it back to what it was before since i didn't want to break anything which was already working.

**Comment by donho** [comment]
Thank you @Ashfaaq18  for the very detailed explanation!

**Comment by Ashfaaq18** [comment]
You're welcome @donho, Happy to help and be a part of this project.

**Pull request closed without merging**
