### PR TITLE
Update Inno Setup keyword list

### PR DESCRIPTION
**Pull request by sssousa**

### CODE REVIEW

**Comment by donho** [comment]
@sssousa 
I didn't find any info by googling on it: 
Is Inno Setup case-sensitive?

**Comment by sssousa** [comment]
@donho 
It's not.

**Comment by donho** [comment]
@sssousa 
> It's not.

Any ref from the official description? 
And even though, people use Camel case or Pascal case conventionally, don't they?

**Comment by sssousa** [comment]
@donho 
> Any ref from the official description? And even though, people use Camel case or Pascal case conventionally, don't they?

I couldn't find it on the official documentation either, so I tested at my owns scripts to be sure. But you are correct, the common use is Pascal Case.

**Comment by donho** [comment]
@sssousa 
Thank you for your info.
I will take the PR as it is.
If you wanna transform all inno setup autocompletion keywords to Pascal Case afterward, you're welcome.

**Pull request closed without merging**
