### PR TITLE
Add .gitattributes file

### PR DESCRIPTION
**Pull request by rcdailey**
Only adding `.gitattributes` file this time. Note that you should highly consider normalizing line endings one way or another before you commit this to your repo publicly, otherwise EOL hell will ensue.

### CODE REVIEW

**Comment by Rikk** [comment]
Why the need to explicitly set `eol=crlf` for some files?
Local repositories in Windows will have CRLF automatically, because `core.autocrlf = true` is default.
`*	 text=auto` normalizes eol, making it LF in remote.

**Comment by milipili** [comment]
It depends of the client configuration. `core.autocrlf` is not always set. I disagree on using gitattributes for that. For me the default configuration should `checkout as-is, commit as-is` from Windows Git. Unfortunately this is not the case for most users...
Making LF in remote should not be bad anyway since all source code will be converted that way.

**Comment by Rikk** [comment]
My question is: why *.bat, *.sln, *.vcxproj need `eol=crlf` on remote=github?

**Comment by milipili** [comment]
I don't understand `on remote=github`. Git attributes are used on checkout.
https://help.github.com/articles/dealing-with-line-endings/#platform-all

**Comment by Rikk** [comment]
>text
This attribute enables and controls end-of-line normalization. When a text file is normalized, its line endings are converted to LF in the repository. To control what line ending style is used in the working directory, use the eol attribute for a single file and the core.eol configuration variable for all text files.
[Src](http://git-scm.com/docs/gitattributes#__code_text_code)

Suppose one's working directory uses LF, we need to force .bat, .sln, .vcxproj files into CRLF because:
VC++ has problem with LF? or,
Git does not detect it as text in `* text=auto`?

**Comment by milipili** [comment]
You're right. It already annoys me. We will see later once all files have proper line endings.

**Comment by Rikk** [comment]
Imo only 3 had errors (mixed eol), see #508.
Oh why you reverted? `* text=auto` seemed a good thing :cry:

**Comment by milipili** [comment]
It is just temporary :)

**Pull request closed without merging**
