### PR TITLE
add support for GB18030

### PR DESCRIPTION
**Pull request by qxo**
ref: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2105

54936 is GB18030

and current GB2312 should change to  GBK ( 936 means GBK after Window 95)

### CODE REVIEW

**Comment by popcorner** [comment]
GB18030...

**Comment by donho** [comment]
The Scintilla part should do the PR on Scintilla project.

**Comment by qxo** [comment]
OK 
https://sourceforge.net/p/scintilla/feature-requests/1257/

**Comment by chcg** [comment]
@donho See:

>  The patch is against an old 3.x version of Scintilla so will not apply. For example, Platform::DBCSCharLength no longer exists. The patch does not add GB18030 cases to 4.x methods like IsDBCSLeadByteInvalid and IsDBCSTrailByteInvalid.
> 
> The patch does not appear to handle all GB18030 cases. GB18030 includes 4-byte characters and Scintilla's DBCS support includes code where only 1 or 2-byte characters will work, such as in SafeSegment:
> 
> 

So it seems to be unlikely that this change will ever appear on a 3.x branch. If this would be added to scintilla how to you plan to backport this for N++?

**Pull request closed without merging**
