### PR TITLE
Change dialog extyles

### PR DESCRIPTION
**Pull request by ozone10**
Apply `WS_EX_DLGMODALFRAME` instead of `WS_EX_TOOLWINDOW` on non-docking dialog window

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10384

image

This will also make close button bigger and more consistent.
so maybe it also fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5847

### CODE REVIEW

**Comment by donho** [comment]
👍

**Comment by donho** [comment]
👍

**Comment by mere-human** [comment]
Can this PR cause the appearance of a thin grey border around the document area?
Left: 8.1.2, right: 8.1.3 (built from the latest master)
image

**Comment by ozone10** [comment]
@mere-human 
this was added in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8bf11be0b581f919d9918c055507a6e497c42f7f

image

**Pull request closed without merging**
