### PR TITLE
Xml syntax check failing

### PR DESCRIPTION
**Pull request by chcg**
checked all files of the APIs dir for xml syntax issues and corrected the invalid files

Tested with plugin tools and checked also against https://www.xmlvalidation.com/

The current invalid xml syntax seems to have no bad influence on the functionality of the files.

### CODE REVIEW

**Comment by donho** [comment]
@chcg  I let you commit your pr directly. Thank you.

**Comment by donho** [comment]
@chcg Any problem for you to merge your PR into master?

**Comment by donho** [comment]
BTW, it'll be good to check XML syntax for every build - is it possible?

**Comment by chcg** [comment]
@donho 
I think I did:
b. copy 2 commands "git checkout -b USER-BRANCH_NAME master" and "git pull https://github.com/USER/nppPluginList.git USER-BRANCH_NAME" to execute on your local git repository with git command.
c. copy 2 commands "git checkout master" and "git merge --no-ff USER-BRANCH_NAME" from the github PR page then execute on your local git repository with git command.
skipped as I thought that is not needed as there were no conflicts:
d. execute "git rebase -i" on your local git repository with git command to fix up if needs.
e. execute "git commit --amend" on my local git repository with git command to make a more pertinent commit comment if needs.
and then:
f. "git push"

, but it seems the history look different from your merges. Is point d. needed therefore?

**Comment by chcg** [comment]
I think it should be possible to do a similar check as for the json format via python at https://github.com/notepad-plus-plus/nppPluginList/blob/master/validator.py also for the xmls under ...\notepad-plus-plus\PowerEditor\installer\APIs and ...\notepad-plus-plus\PowerEditor\installer\nativeLang. Maybe even add an xml schema to even better check the content of the xmls.

I will take a look at that.

**Comment by MAPJe71** [comment]
> Maybe even add an xml schema to even better check the content of the xmls.

IMO that's the right way (e.g. see [functionList.xsd](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/Test/FunctionList/functionList.xsd)).

**Pull request merged**
