### PR TITLE
Fix Context menu not shown regression bug [fixes issue #383]

### PR DESCRIPTION
**Pull request by pnedev**
After FindInFiles operation context menu was no longer accessible.
This patch fixes this regression.

### CODE REVIEW

**Comment by cmeriaux** [comment]
:+1:

**Comment by milipili** [comment]
#383

**Comment by Rikk** [comment]
What was the (unnecessary) job of `flushCallerUserInput` function?

**Comment by pnedev** [comment]
FlushCallerUserInput() wasn't exactly unnecessary - its purpose was to flush the user input queue of main N++ window while FindInFiles was taking place and immediately after it finished. Without it if the user clicks in the main N++ window while the find operation is running the user input is not processed immediately because the user thread is busy searching but is put in the queue. After search finishes the stacked user input takes place which is undesirable.

The context menu actually gets corrupted because of DSpellCheck plugin which hooks to it to add spelling suggestions. It interfered with flushCallerUserInput() for some reason and became irresponsive making the Context menu inaccessible too.
The new version of the plugin doesn't have this problem even without this patch.

This patch was released just as a quick solution to the issue

**Comment by Rikk** [comment]
Thanks for clear explanation

**Pull request closed without merging**
