### PR TITLE
Add confirmation preference for Replace All in All Opened Documents operation

### PR DESCRIPTION
**Pull request by sasumner**
Implements #8527

Here is sample of new UI.
I anticipate maybe some desired changes to it? :-)

**_Edit: Removed image of initial UI to avoid future confusion_**

### CODE REVIEW

**Comment by sasumner** [comment]
@Yaron10 Sorry, I didn't implement your RTL or quoting suggestions in this. :-(

**Comment by donho** [comment]
I think the following layout has more advantage:
image
for some reasons:
1. It's prettier :) 
2. More space for the translation.

Here's code:
```
IDD_PREFERENCE_SEARCHINGSETTINGS_BOX DIALOGEX 0, 0, 455, 185
STYLE DS_SETFONT | DS_FIXEDSYS | DS_CONTROL | WS_CHILD
FONT 8, "MS Shell Dlg", 0, 0, 0x1
BEGIN
	CONTROL         "Don't fill find field in Find dialog with selected word", IDC_CHECK_STOPFILLINGFINDFIELD,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 10, 350, 10
	CONTROL         "Use Monospaced font in Find dialog (Need to restart Notepad++)", IDC_CHECK_MONOSPACEDFONT_FINDDLG,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 25, 350, 10
	CONTROL         "Find dialog remains open after search that outputs to results window", IDC_CHECK_FINDDLG_ALWAYS_VISIBLE,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 40, 350, 10
	GROUPBOX        "Replace Confirmations", IDC_SEARCH_CONFIRMATIONS_STATIC, 30, 66, 279, 84, BS_CENTER
	CONTROL         "Confirm interactive Replace-All-in-All-Opened-Documents", IDC_CHECK_CONFIRMREPLOPENDOCS,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 80, 265, 10
	CONTROL         "Confirm Replace-All-in-All-Opened-Documents in macro", IDC_CHECK_CONFIRMMACROREPLOPENDOCS,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 95, 263, 10
	CONTROL         "Confirm interactive Replace-in-Files", IDC_CHECK_CONFIRMREPLFILES,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 111, 224, 10
	CONTROL         "Confirm Replace-in-Files in macro", IDC_CHECK_CONFIRMMACROREPLFILES,"Button", BS_AUTOCHECKBOX | WS_TABSTOP, 37, 126, 196, 10
END
```

BTW, I don't think it's a good idea to make confirm dialog disable optional. I can imagine that the user disable it by ignorance, then he/she hits the Replace in Files button accidentally. It's not like Replace in all Opened files (all the modified files are kept in the editor, so user can undo them file by file.

**Comment by sasumner** [comment]
@donho

It's prettier, but it takes up a lot more of the available space that way. :-(
We have many more "Searching" preferences to come, so where will they fit? :-)

Should I remove both of the _Replace in Files_ items?
I do recall someone asking for it to be removed during macro execution, but I can't find the reference on that right now.
Is it reasonable to remove the interactive one, leaving 3 new checkboxes with this?

**Comment by donho** [comment]
> Should I remove both of the Replace in Files items?

User should not be able to disable the confirmation of Replace in File both button/macro action for me.


OTOH, the confirmation of Replace all in All opened document macro action should be always absence  - if user recorded such macro and run it by error, it's not our problem but PEBKAC.


> I do recall someone asking for it (the confirmation) to be removed during macro execution, but I can't find the reference on that right now.

There are always people who ask somethings. It doesn't mean what they ask is pertinent and we  should implement the feature they ask. But if you see a feature is request more than 3 times, it may need to be implemented.

> Is it reasonable to remove the interactive one, leaving 3 new checkboxes with this?

So we keep only one checkbox "Confirm Replace All in All Opened Documents action". No word "interactive", neither the "-". And we can remove the groupbox as well.

**Comment by sasumner** [comment]
>There are always people who ask somethings. It doesn't mean what they ask is pertinent and we should implement the feature they ask

Right, but when you're implementing something related, it doesn't hurt to also do a related request that you remember.

>So we keep only one checkbox "Confirm Replace All in All Opened Documents action". No word "interactive", neither the "-". And we can remove the groupbox as well.

I agree that this makes sense.  My main reason for agreeing is that it saves space on the page. :-)

I will do it.

**Comment by donho** [comment]
> but when you're implementing something related, it doesn't hurt to also do a related request that you remember.

Hmm... It could hurt. I do believe KISS - too many options kill application. Users prefer a simple, easy to use program.

**Comment by sasumner** [comment]
>too many options kill application

I really do hate preference settings for things, so, yes, total agreement

**Comment by sasumner** [comment]
Revised UI:

image

**Pull request closed without merging**
