### PR TITLE
Hindi Translation for V7.0

### PR DESCRIPTION
**Pull request by SinghRajenM**
- Corrected/updated whole translation (used user friendly words)
- Synced with english.xml (easy to compare with diff tool such as Beyond compare)
- Update for v7.0 (added missing strings)
- Added/updated translation in such a way so that it should not run out of space for the control which has limited width

### CODE REVIEW

**Comment by donho** [comment]
So which one should I take? #2304 or this one?

**Comment by SinghRajenM** [comment]
Please consider this one.

**Comment by SinghRajenM** [comment]
Any reason for suspension? Does it require any input from my side?

**Comment by donho** [comment]
`991 additions, 598 deletions not shown because the diff is too large. Please use a local Git client to view these changes.`
I don't trust when there are too many modifications, especially on translation.
Avoiding reformatting is one of tips.

**Comment by SinghRajenM** [comment]
There were multiple reason for many changes - 
1. Many translation were wrong and not user friendly.
2. There were many translation missing as it was not updated parallel to notepad release for long time.
3. It was tough to translate as it was not sync with English xml. It was taking too much time to translate one by one therefore I synced with english xml. So whenever a new items is added to english, it can be easy translated without any issue.

**Comment by SinghRajenM** [comment]
@donho I have question about the PR process. Once a PR is accepted (not merged), can we update a PR?
I'm asking because, this PR is accepted but I would like to update for new strings which were recently added to English String.

**Comment by donho** [comment]
@SinghRajenM English.xml has been updated. Could you update your translation please?
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

**Comment by SinghRajenM** [comment]
@donho I have updated the translation now.

**Pull request closed without merging**
