### PR TITLE
[XML] Update brazilian_portuguese.xml

### PR DESCRIPTION
**Pull request by Marcellomco**
Added translation for "Fix menu Tools contains 2 SHA-256 item while using localization"

### CODE REVIEW

**Review by Marcellomco — COMMENTED** [review]
Added translation for "Add change history navigation commands"

**Review by Marcellomco — COMMENTED** [review]
Translation for "Fix inaccurate find/replace in files result while using invalid regexp"

**Review by Marcellomco — COMMENTED** [review]
Translation for 'Remove "Temporary doc site:" from localization files'

**Comment by donho** [comment]
Please merge https://github.com/notepad-plus-plus/notepad-plus-plus/commit/50a15f2e59fac6350d6011b2201eab5f0b3e892a for fixing build error.

**Pull request closed without merging**
