### PR TITLE
Update dutch.xml

### PR DESCRIPTION
**Pull request by RockyTDR**
Last attempt...

### CODE REVIEW

**Comment by donho** [comment]
@RockyTDR Looks much better. Thank you very much for your effort. There is still some reformatting but I think it's OK. However, since I know nothing about Dutch, and the modification is important, I will ask community to review it. Hope you don't mind.

Could @xylographe or any Dutch speaker validates this PR?

**Comment by RockyTDR** [comment]
@donho I tried to contact @xylographe by mail on January the 6th but I didn't receive an answer. That's why did a complete translation review on my own.

Maybe this also helps to validate the pull request (see attachment):

I created a short list of 30 translations I changed, in 4 columns:
- English source string
- Old Dutch translation + literal English translation
- Corrected Dutch translation 

This should make it possible (even for people who don't understand Dutch) to verify some of my changes (e.g. by using Google Translate or, my favourite: DeepL)

[Notepad ++ Dutch translation correction examples.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5895656/Notepad.%2B%2B.Dutch.translation.correction.examples.pdf)

**Comment by donho** [comment]
@RockyTDR 

Sincerely, I hope everything is OK for @xylographe 

OK. If you want to reformate the current dutch.xml, I can understand. 
I'll merge this one. You can do another PR with a new reformatting if you want.

**Comment by RockyTDR** [comment]
@donho I'm so sorry! I just read your mail, and I pushed the changed formatting in this pull request. Can the last one be stopped? I'll create a new one for the formatting.

**Comment by donho** [comment]
@RockyTDR 
Does this one need reformatting ?

**Comment by RockyTDR** [comment]
@donho The current "dutch.xml" in master is fine. Formatting is exactly like in "English.xml". No further changes are needed. Thanks!

**Pull request closed without merging**
