### PR TITLE
make URL highlighting/formatting unicode aware

### LINKED ISSUE #2798: [Improvement/Fix] - Make URL highlighting/formatting unicode aware by changing regex
Current situation is that urls which contain unicode character aren't highlighted or formatted correctly.
The reason for that is the current regex used to identify urls.

Current regex: [A-Za-z]+://[A-Za-z0-9_\-\+~.:?&@=/%#,;\{\}\(\)\[\]\|\*\!\]+

To support urls containing unicode chars it would be needed to change the regex to e.g.

(?-s)[A-Za-z][A-Za-z0-9+.-]+://.*?(?=\s|$)

With this new regex a test has been done to check if urls containing any code point within the 
range 0x0 - 0x10FFFF would match - most of them did.

Tested scenarios:
start of file tests
-url at start of file (no additional text) (also end of file test)
-url at start of file (followed by tab)
-url at start of file (followed by space)
-url at start of file (followed by eol)
-url at start of file (followed by tab and text)
-url at start of file (followed by space and text)
-url at start of file (followed by eol and text)

end of file tests
-url at end of file (preceded by tab)
-url at end of file (preceded by space)
-url at end of file (preceded by eol)
-url at end of file (preceded by text and tab)
-url at end of file (preceded by text and space)
-url at end of file (preceded by text and eol)

in the middle of a file tests
-url in the middle of a file (preceded and followed by tab)
-url in the middle of a file (preceded and followed by space)
-url in the middle of a file (preceded and followed by eol)
-url in the middle of a file (preceded and followed by text and tab)
-url in the middle of a file (preceded and followed by text and space)
-url in the middle of a file (preceded and followed by text and eol)

Chars which "broke" (broke in terms of the match was reported until this char (char excluded)),
the tests are:

(the obvious ones)
0x0    = NULL
0x9    = TAB
0xA    = LineFeed
0xB    = VerticalTab
0xC    = FormatFeed
0xD    = CarriageRetrun
0x20   = Space
0x85   = Next Line 
0xa0   = No-Break Space
0x1680 = Ogham Space Makr
0x2000 = En Quad 
0x2001 = Em Quad 
0x2002 = En Space
0x2003 = Em Space 
0x2004 = Three-Per-Em Space 
0x2005 = Four-Per-Em Space 
0x2006 = Six-Per-Em Space 
0x2007 = Figure Space
0x2008 = Punctuation Space
0x2009 = Thin Space 
0x200A = Hair Space
0x200C = Zero Width Non-Joiner
0x200D = Zero Width Joiner
0x200E = Left-To-Right Mark
0x200F = Right-To-Left Mark
0x2028 = Line Separator
0x2029 = Paragraph Separator 
0x202f = Narrow No-Break Space
0x205f = Medium Mathematical Space 
0x3000 = Ideographic Space

and some unusual ones
(see the pattern 0x?0085, 0x?2028 and 0x?2029 !! ??)

0x10085 LINEAR B IDEOGRAM B105M STALLION
0x12028 Cuneiform Sign Al Times Ush     
0x12029 Cuneiform Sign Alan             

0x20085 CJK UNIFIED IDEOGRAPH
0x22028 CJK UNIFIED IDEOGRAPH
0x22029 CJK UNIFIED IDEOGRAPH

(code points are reported as unknown-unknown script by unicode.org,
which I guess means, valid but unused code point)
0x30085, 0x32028, 0x32029, 
0x40085, 0x42028, 0x42029,
0x50085, 0x52028, 0x52029,
0x60085, 0x62028, 0x62029,
0x70085, 0x72028, 0x72029,
0x80085, 0x82028, 0x82029,
0x90085, 0x92028, 0x92029,
0xa0085, 0xa2028, 0xa2029,
0xb0085, 0xb2028, 0xb2029,
0xc0085, 0xc2028, 0xc2029,
0xd0085, 0xd2028, 0xd2029,
0xe0085, 0xe2028, 0xe2029,
0xf0085, 0xf2028, 0xf2029,
0x100085, 0x102028, 0x102029

Nevertheless I think it is worth to change the regex.

Thank you
Claudia

### PR DESCRIPTION
**Pull request by ClaudiaFrank**
fixes #2798

### CODE REVIEW

**Comment by donho** [comment]
@ClaudiaFrank  We need unit test for this commit.
Any idea about unit test for this part?

**Comment by ClaudiaFrank** [comment]
@donho - What I did was using python script plugin and checking under the following conditions

validity check tests
    start of file tests
        url at start of file (no additional text) (acts also as end of file test)
        url at start of file (followed by tab)
        url at start of file (followed by space)
        url at start of file (followed by eol)
        url at start of file (followed by tab and text)
        url at start of file (followed by space and text)
        url at start of file (followed by eol and text)
       
    end of file tests
        url at end of file (preceded by tab)
        url at end of file (preceded by space)
        url at end of file (preceded by eol)
        url at end of file (preceded by text and tab)
        url at end of file (preceded by text and space)
        url at end of file (preceded by text and eol)
       
    in the middle of a file tests
        url in the middle of a file (preceded and followed by tab)
        url in the middle of a file (preceded and followed by space)
        url in the middle of a file (preceded and followed by eol)
        url in the middle of a file (preceded and followed by text and tab)
        url in the middle of a file (preceded and followed by text and space)
        url in the middle of a file (preceded and followed by text and eol)

invalidity check tests
    same tests as before but url contains "invalid" unicode points like nbsp etc...

The tests created urls by looping through unicode points which were added to
a fix scheme (http) and authority part (://wikipedia.org/) and checking the returned length
from the proposed regex.

Do you think this is sufficient? Any additional ideas?

I assume you like to have c++ unit tests, correct?
If so, do you already have some ideas how those should be build/created?
I don't have any experience in c++ unit test but willing to learn and creating/providing them.

**Comment by donho** [comment]
@ClaudiaFrank  C++ Unit test could be useful, but it cannot be used to test PCRE, which is not included in continuous integration due do the need of Boost for PCRE part.

What I talked about unit test could be similar to the unit test I committed several days ago: 
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3aaf083c1d2480b2a16998eb2f7495708807caeb
(By using powershell)

Do you think it can be done to unit-test this part?

**Comment by ClaudiaFrank** [comment]
requirements cannot be fullfilled

**Pull request closed without merging**
