### PR TITLE
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/817/ --…

### PR DESCRIPTION
**Pull request by sanastasiou**
… Allow plugins to save any opened file without activating the buffer.

Let me know if anything needs to be improved/changed.

### CODE REVIEW

**Comment by dail8859** [comment]
Just curious, is there a reason you pass the file name instead of the buffer id? I have no objection to the way it is now, maybe it is just easier to do it this way...either way it is up to Don.

Also, according to the [CONTRIBUTING.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#use-tabs-instead-of-white-spaces-we-usually-set-our-editors-to-4-white-spaces-for-1-tab-but-the-choice-is-up-to-you) file, it is recommended to use tabs instead of spaces.

**Comment by sanastasiou** [comment]
@dail8859 Regarding the buffer id, I think it's more intuitive to just pass the file name, but I could change that no problem. Tab vs spaces :) sorry my IDE was adjusted to use spaces. I'll fix this.

**Comment by sanastasiou** [comment]
OK Tabs fixed.

**Comment by Rikk** [comment]
```cpp
bool Notepad_plus::fileSaveSpecific(const generic_string& fileNameToSave)
{
	BufferID idToSave = _mainDocTab.findBufferByName(fileNameToSave.c_str());
	if (idToSave == BUFFER_INVALID)
		idToSave = _subDocTab.findBufferByName(fileNameToSave.c_str());
	else
	{
		fileSave(idToSave);
		checkDocState();
		return true;
	}

	return false;
}
```

**Comment by sanastasiou** [comment]
@Rikk Thanks :) I guess coding at 2 AM has its drawbacks :dancer:

**Comment by sanastasiou** [comment]
@Rikk I've "fixed" the issue and added a comment for clarification.

**Comment by donho** [comment]
Any issue related with this PR?

**Comment by cmeriaux** [comment]
what about merging all your commit to avoid overload of "git log" ?

**Comment by sanastasiou** [comment]
@cmeriaux You mean squash? Or how do I do this ?

**Comment by Croydon** [comment]
Btw, next time just write #817 in the title instead of the whole URL. In the comments it gets shortened automatically by GitHub, but that's not working in titles.

**Comment by sanastasiou** [comment]
@Croydon Thanks for the tip.

**Comment by Rikk** [comment]
Looks an odd logic.
The new `else` means `(idToSave == BUFFER_INVALID)` that is already checked above.
Perhaps a better logic is verifying whether `_subDocTab` or `_mainDocTab` exist prior to defining the variable. I'm testing this, hold on.

**Comment by cmeriaux** [comment]
Yes, I mean squash : [link](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by sanastasiou** [comment]
@cmeriaux I think it's too later for that, I've already pushed the changes and @Rikk  has already merged them, except the last one.

**Comment by cmeriaux** [comment]
@sanastasiou , no it's not to late. Your 6 commits have been pushed to your branch FeatureSetup. They have not been merged in your remote master or in the notepad++ master. 
So you can rebase and squash your local branch FeatureSetup, Push your local FeatureSetup to your remote FeatureSetup (you may need a -force option). Then submit again your PR if needed.

**Comment by sanastasiou** [comment]
@cmeriaux OK, I'll try this and then close this pull request and open another one if the commit number is smaller.

**Pull request closed without merging**
