### PR TITLE
Check if URL is enclosed in apostrophes

### LINKED ISSUE #14212: Extra Underline When Pasting a URL between two ' characters
### Description of the Issue
When you put a URL inside of two single quotes, the right most tickmark gets underlined which makes it appear as if its part of the URL. This behavior is different when you enclose a URL inside of two double quotes -- the right most double quote does not get underlined which seems normal to me.

### Steps to Reproduce the Issue

1.  Start with a signle quote '
2. Type the rest of the url, followed by a second single quote like this: 'http://example.com'
3. Auto formating takes over and underlines the url and the last single quote.

### Expected Behavior
I dont expect the last single quote to be underlined as its not part of the URL. When you enclose a URL in double quotes, the application behaves correctly and doesnt underline the double quote.

### Actual Behavior
The right most ' character gets underlined which is misleading. See the attached screenshot.

### Debug Information
Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\MY_USER\MY_FOLDER\Desktop\scripts\MY_PROJECT\MY_FILEt.xt" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3324
Current ANSI codepage : 1252
Plugins : 
    JsonTools (5.4)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

image

### LINKED ISSUE #14323: open link when double click include ' of end tag in html
open link when double click include ' of end tag in html
### Description of the Issue

I have same code in html:
<li class='menu-item-has-children menu-item-type-label menu-item' data-class='' data-enable_mega='' data-icon=''>
        <a data-href-default='#' data-text-default='' href='/#Label2'>Quà tặng Doanh Nghiệp</a>
        <ul class='sub-menu'>
          <li class='menu-item-type-post menu-item-type-label menu-item' data-class='menu-item-type-post' data-enable_mega='' data-icon=''>
            <a data-href-default='/' data-text-default='' href='https://gifthouse.jwvietnam.vn/p/gioi-thieu.html'>Giới thiệu JW Gifthouse</a></li>
          <li class='menu-item-type-post menu-item-type-label menu-item' data-class='menu-item-type-post' data-enable_mega='' data-icon=''>
            <a data-href-default='/' data-text-default='' href='https://luxgift.jwvietnam.vn/p/gioi-thieu.html'>Giới thiệu JW Luxgift</a></li>
          <li class='menu-item-type-post menu-item-type-label menu-item' data-class='menu-item-type-post' data-enable_mega='' data-icon=''>
            <a data-href-default='/' data-text-default='' href='https://gift.jwvietnam.vn/p/gioi-thieu.html'>Giới thiệu JW Gift</a></li>
        </ul>
      </li>
But when double click the link it will open with the ' at end of the link
### Steps to Reproduce the Issue

1. Copy the code as same or write your html code with link in the apostrophe. The link will have hyperlink with underscore but it include the apostrophe at the end.
2. Click on that link will open in default browser the link have apostrophe at the end of link.

### Expected Behavior

Open the webpage correct
### Actual Behavior

It open wrong webpages or have 404 error page
### Debug Information

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Temp\Xiaomi_Global_Debloater_v1.9\Debloat-16-Duo.bat" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home Single Language (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2205)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppTextFX (1.4.1)
    XMLTools (3.1.1.13)

### LINKED ISSUE #14978: hyperlink [bug]
### Description of the Issue
The hyperlink bug in Notepad++ version 8.6.5 causes URLs to contain the ' symbol when you double-click with the left mouse button after entering 'https://www.google.com/' in a text file. This results in the URL becoming 'https://www.google.com'/'.

### Steps to Reproduce the Issue

1. open notepadd++  input  'https://www.google.com' 
2. Double-click the URL with the left mouse button.

QQ截图20240411203655

### PR DESCRIPTION
**Pull request by MarkusBodensee**
Fix #14978, fix #14323, fix #14212.
Check if URL is enclosed in apostrophes. Only if URL is directly preceded by apostrophe and URL ends with apostrophe.

### CODE REVIEW

**Comment by MarkusBodensee** [comment]
Hmm, is it worth to separate the code of this PR into a method and add some more checks of characters with similar issue like ´ and `?
Or even add this kind of check for the parathesis instead of the current algo? Opinions, please.

**Comment by donho** [comment]
> Hmm, is it worth to separate the code of this PR into a method and add some more checks of characters with similar issue like ´ and `?
> Or even add this kind of check for the parathesis instead of the current algo? Opinions, please.

@MarkusBodensee 
Could you provide the URL samples for the above mentioned symbols?

**Comment by MarkusBodensee** [comment]
This PR fixes the following:
`'https://www.google.de/'`

In #14978, there is an example of a URL enclosed in diacritical accents, means, my question is, if the code should be enhanced to handle also these cases:
```
´https://www.google.de/´
`https://www.google.de/`
´https://www.google.de/`
`https://www.google.de/´
```

With the second sentence, I meant, if even the way how parenthesis are handled should be adapted in this direction. Means instead of trimming trailing closing parenthesis, if there is no symmetrical number of parenthesis pairs in the URL, better check if URL is enclosed in parenthesis. But if so, it should better be a task for separate PR.

**Comment by donho** [comment]
@MarkusBodensee 
> In https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14978, there is an example of a URL enclosed in diacritical accents, means, my question is, if the code should be enhanced to handle also these cases:

Good thinking. IMO, only the following case need to be enhanced: 
```
`https://www.google.de/`
```

**Review by donho — CHANGES_REQUESTED** [review]
Please add the enhancement of the following case:
```
`https://www.google.de/`
```

**Comment by donho** [comment]
@MarkusBodensee 
> With the second sentence, I meant, if even the way how parenthesis are handled should be adapted in this direction. Means instead of trimming trailing closing parenthesis, if there is no symmetrical number of parenthesis pairs in the URL, better check if URL is enclosed in parenthesis. But if so, it should better be a task for separate PR.

Are you talking about refactoring? If you are, what's the point of the refactoring?

**Comment by MarkusBodensee** [comment]
> Please add the enhancement of the following case:
> 
> ```
> `https://www.google.de/`
> ```

Done. Enclosure with apostrophes or grave accents are working. See result with the modification:
```
'https://www.google.de/'
`https://www.google.de/`
´https://www.google.de/´
`https://www.google.de/´
´https://www.google.de/`
```
grafik

You are right, enhancement of the algo with acute accent would not be such simple, since it is a non-ASCII char. So it is enough for this PR and all points of #14978 are completely fullfilled now anyway.

**Comment by MarkusBodensee** [comment]
> Are you talking about refactoring? If you are, what's the point of the refactoring?

Yes, talking about refactoring, but should not be part of this PR. It was just a though which came to my mind and I am not sure if there would be also downsides.

With the current algo of counting parenthesis within the URL, there could be some cases in which the user could expect a different result. E.g. if the URL does not contain symmetric pairs of parenthesis, preceded char is irrelevant.
```
https://www.google.de/)      <<< gets trimmed
https://www.google.de/))     <<< not gets trimmed
https://www.google.de/)))    <<< not gets trimmed
(https://www.google.de/)      <<< gets trimmed
(https://www.google.de/))     <<< not gets trimmed
(https://www.google.de/)))    <<< not gets trimmed
(https://www.google.de/())()) <<< not gets trimmed
```
See also #9781 (but this could also not be solved by checking preceded char).

**Review by donho — APPROVED** [review]

**Comment by MarkusBodensee** [comment]
Note: Date in branch name was wrong and misleading.

**Pull request closed without merging**
