### PR TITLE
Fix crash during Search result

### LINKED ISSUE #11883: [Regression] Wrong lexing in Search Results
**STR:**
Find in Files -> Search All.
Again, Find in Files -> Search All.

**Result:**
The second search-results are not lexed properly, and NPP may even crash.

תמונה

**Caused by:** https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88.

### PR DESCRIPTION
**Pull request by donho**
Fix #11883 partially.

### CODE REVIEW

**Comment by Yaron10** [comment]
@donho,

The crash was not consistent (about 1 of 10 NPP startups).
Unfortunately I've just encountered a crash with the new binary. 

Thank you for looking into it.

**Comment by Yaron10** [comment]
> Unfortunately I've just encountered a crash with the new binary.

Positive.

I might be wrong, but the crash seems to happen more frequently in NPP x32 (in x64 system).

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

Could you please try reproducing the crash on your machine?

**Comment by ArkadiuszMichalski** [comment]
Crash still exist:
```
Notepad++ v8.4.3   (32-bit)
Build time : Jul  8 2022 - 15:52:51
Path : E:\Download\_chrome\npp.8.4.3.portable\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.778
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

```

**Comment by donho** [comment]
@Yaron10 @Yaron10 
I cannot reproduce the crash at all with v8.4.3 x32 official portable version (neither with x32 Debug mode)

Could you provide a way to reproduce crash steadily please?

**Comment by ArkadiuszMichalski** [comment]
@donho 
1. Open Notepad++
2. Open some file, like `license.txt`
3. Go to Find in Files (Ctrl+Shift+F) and mark `Follow current doc.`
4. Find some text.

If crash not happend after two searches close and run NPP again and repeat above steps. Currently I get crash after first run.

**Comment by xomx** [comment]
@ArkadiuszMichalski 
I can reproduce the crash with your steps, but on the 32-bit N++ only, x64 does not crash.

**Comment by ArkadiuszMichalski** [comment]
@xomx Try with version from this PR (looks like it breaks more often than the official one). If after catching a crash and after a few attempts, there is still no crash, try run system again (in the past I had a case  that after a few crashes in NPP they stopped appearing until the system restarted).

**Comment by Yaron10** [comment]
@donho,

> Could you provide a way to reproduce crash steadily please?

That's the problem: it's inconsistent and can not be reproduced steadily.

You're trying to separate the crash from the wrong lexing. - Your knowledge and understanding are better than mine. 
Still, allow me to ask: did you find out why in "Find in Files" the lexing breaks after the first search? Perhaps it IS related to the random illusive crash?

@ArkadiuszMichalski has mentioned an important point:
> If crash not happend after two searches close and run NPP again and repeat above steps.

And also, try it with the x32 build.

Thank you.

**Comment by donho** [comment]
> Try with version from this PR (looks like it breaks more often than the official one). 

It should be more stable though. In anyway, I believe it doesn't contribute to the crash.

> * Open Notepad++
> 
> * Open some file, like `license.txt`
> 
> * Go to Find in Files (Ctrl+Shift+F) and mark `Follow current doc.`
> 
> * Find some text.

Yes, now I can reproduce the crash with x86 official release. However, in debug mode (the same source code) I can see the syntax highlighting is lost, but no crash at all. 

It seems it's rather the race condition on Scintilla - the execution on debug binary is much slower; since Scintilla is not thread safe, when the execution speeds up, there might be several accesses to Scintilla, which lead crash.

Since I cannot find the crash reason from the debug, I'll revert  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88 to see if the crash still happens.

**Comment by Yaron10** [comment]
> I'll revert https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88 to see if the crash still happens.

We can all try it now with the previous commit.

Would you mind waiting a couple of days?
You or @xomx might still come up with a solution. :)

**Comment by donho** [comment]
Found it!
I'll do a commit in 30 minutes!

**Comment by donho** [comment]
The crash should be fixed in the latest commit.
There is still the colorizing problem though.
Once the crash-fix is confirmed, I will revert https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88 to fix the rest of problem.

**Comment by Yaron10** [comment]
@donho,

The crash seems to be fixed. 👍 
Thank you.

I suppose you've noticed that with the recent commit the results in "Find in Files" _are lexed_ but wrongly.

> I will revert https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88 to fix the rest of problem.

Do you mean back to "no folding"?

**Comment by Yaron10** [comment]
And the lexing in "Find All in Current Document" is broken.

**Comment by donho** [comment]
@Yaron10 
Sorry my bad. I was too excited to commit the correct fix.
I just commit the correct fix. Please check the latest commit. Sorry again for the error.

**Comment by ArkadiuszMichalski** [comment]
Crash was fixed.

**Comment by Yaron10** [comment]
@donho,

Perfect! 👍 
Thank you for you time and work. 

I'm sharing your excitement. :)

So there's no need to revert https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88, correct?

**Comment by donho** [comment]
@ArkadiuszMichalski  @Yaron10 
Thank you for the confirmation!

> So there's no need to revert https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0b5785cbecf82e5889f6e8680aeed85305b5fe88, correct?

Yes it's not necessary to revert this PR.
OTOH, I remark there's still the folding performance issue (on the 2nd search) when "color" is searched in all file from root of Notepad++ project. 
I may try to improve the method `ScintillaEditView::collapse()` in another PR.

**Comment by Yaron10** [comment]
> Indeed, it's not necessary to revert this PR.

That's great.

> OTOH, I remark there's still the folding performance issue (on the 2nd search) when "color" is searched in all file from root of Notepad++ project.

There's a performance issue in the _first_ search too. :)
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11774.

> I may try to improve the method ScintillaEditView::collapse() in another PR.

👍 
Thank you and best of luck.

**Pull request closed without merging**
