### PR TITLE
Allow selected text foreground color to be changed

### LINKED ISSUE #3397: Foreground Color of selected text cannot be changed
### Description of the Issue

Notepad++ does not use the standard selected text colors of white text on blue background. Because of this, the user should be able to change both the foreground and background colors of selected text. However, using the Style Configurator  and changing the Foreground Color of selected text does nothing and the color is always black. 

### Steps to Reproduce the Issue

1. Click "Settings" 
2. Click "Style Configurator"
3. Select "Global Style" 
4. Select "Selected text colour"
5. Change the foreground color and save the changes.

### Expected Behavior

The foreground text color of selected text should  change. Alternatively, the default secret text color should be the Windows standard OD white text on blue background. 
 
### Actual Behavior

The foreground text color of selected text does not change.

### Debug Information

Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 

The color of the selected text in the npp dialog boxes as shown below is the windows standard and should be available in the npp editor.

### PR DESCRIPTION
**Pull request by sasumner**
Fix #3397 #1314

I really don't know the history (if there is any) on why this wasn't fixed long ago...
Maybe there is some good reason for it?

### CODE REVIEW

**Comment by donho** [comment]
It doesn't be done because it's cool to select text w/o losing the syntax highlighting.
I would say "why not" if it's optional that user can change back to keep syntax highlighting on selection...

But no. I prefer to keep the current behaviour.

**Comment by sasumner** [comment]
@donho

OK.  Sure.
At least we have documented the "why" of it.

I (with the gracious help of another person) spent some time yesterday trying to research the "why" and we couldn't find anything.  (Later edit: we should have read issue 3397 comments closer!)
Certainly more time was spent on the research than coding a change!
The "best" (most entertaining) thing that was found was something from 2004 that didn't even seem to answer the question asked:  https://sourceforge.net/p/notepad-plus/discussion/331754/thread/40dc962c/

For myself, I've had this code in place in my `startup.py` for probably 5 years:

```
        for e in (editor1, editor2):
            # set foreground text for selections to be white instead of the default black:
            e.setSelFore(1, (255, 255, 255))
```

My point in mentioning my 5-year-workaround is that I have never -- ever, not one single time -- noticed that while I was selecting text, the lexing colors/styles are not retained on the text that is selected.
Sure enough, if I evaluate it now, they are not retained (surprise!)
If I had noticed this, I likely wouldn't have cared, because IMO it simply isn't that big of a deal.
(But, aha, there are some hints of this behavior if one reads the comments closely in #3397 )

So we have multiple user complaints over the years about not being able to set selected text foreground color; here are only some that I could find:

- https://community.notepad-plus-plus.org/topic/11039/foreground-options-for-selected-text
- https://community.notepad-plus-plus.org/topic/12578/can-t-change-foreground-color-of-selected-text
- https://community.notepad-plus-plus.org/topic/20156/how-to-change-color-of-letters-of-highlighted-text

I have no reason to believe that people are going to stop requesting this, nor stop denegrating Notepad++ because it doesn't support it.

So what are we left with?
FAQ?
Does our FAQ maintainer @ArkadiuszMichalski want to take care of that?

**Comment by donho** [comment]
@sasumner 
The fact that everyone is doing it doesn't mean it's right.

Selecting text without losing the syntax highlighting is advanced feature for Notepad++ certainly, though for some it's not. 
We see some people complain for such behaviour which's come from its 1st release, but if we apply the PR you provided - there will be much more complain (even the insult) coming.

The only way to satisfy both sides is make it as a hidden option - if users want to modify the current behaviour with the foreground colour, they have to put an empty xml file named `enableSelectForegroundColour.xml` beside of `config.xml`. We active this option in the code only if `enableSelectForegroundColour.xml` exists. What do you think?

**Comment by sasumner** [comment]
@donho

>The only way to satisfy both sides is make it as a hidden option - if users want to modify the current behaviour with the foreground colour, they have to put an empty xml file named enableSelectForegroundColour.xml beside of config.xml. We active this option in the code only if enableSelectForegroundColour.xml exists.

How about a different "hidden" option that isn't so development intensive?
What about:

* if user sets selected-text foreground color to the same as selected-text background color, we preserve existing behavior (respect background choice only)
* if user sets foreground different from background, we respect both settings (no lexing in selected text)

**Comment by mere-human** [comment]
> they have to put an empty xml file named `enableSelectForegroundColour.xml` beside of `config.xml`. We active this option in the code only if `enableSelectForegroundColour.xml` exists.

Just a suggestion: what if the option would still be in `config.xml` but won't be exposed in the Preferences UI?
Probably, we have some similar pro-users options.

**Comment by donho** [comment]
@sasumner 
> How about a different "hidden" option that isn't so development intensive?

It's not intensive at all, and it's quite easy to do - otherwise I wouldn't suggest.


> What about:
> * if user sets selected-text foreground color to the same as selected-text background color, we preserve existing behavior (respect background choice only, lexing in selected text)
> * if user sets foreground different from background, we respect both settings (therefore no lexing in selected text)

It could be a way for a power user who has RTFM, but the average users (including me)  will be lost.
If an user change one of these 2 colour by accident, how can he/she knows to set both the same colour to get back the current settings? Not mention that the foreground colour should be always disabled.

Users know what they are doing by adding this empty file, so the other the users who want the current behaviour have no risk to be bothered.

@mere-human 
> Just a suggestion: what if the option would still be in config.xml but won't be exposed in the Preferences UI?

I still think adding an empty file `enableSelectForegroundColour.xml` explicitly to enable this feature is a better solution. The advantage is easier to add (no need to hack config.xml).

**Comment by donho** [comment]
@sasumner 
I will reopen this PR and push some commits into your branch, so you has nothing to do but validate my commits.

**Comment by e-t-l** [comment]
I created enableSelectForegroundColour.xml and the Foreground Color option for Selected Text is still disabled. I am on version 8.6.4. Is there something else I need to do to enable this feature?

**Pull request closed without merging**
