### PR TITLE
Make CURRENT_LINE and CURRENT_COLUMN expansions one-based

### LINKED ISSUE #8679: CURRENT_LINE and CURRENT_COLUMN should be one-based not zero-based
### Description of the Issue

To be user-useful, the `$(CURRENT_LINE)` and `$(CURRENT_COLUMN)` expansions offered in the _Run_ menu's _Run..._ > _The Program to Run_ box should be "one-based" and not "zero-based".

### Steps to Reproduce (STR) the Issue

1. In a Notepad++ tab, move your caret to line 1, column 1 (start of document)
2. Invoke the _Run_ menu's _Run..._ command.
3. Put this text in the input combobox underneath _The Program to Run_ :  
`cmd /c echo CURRENT_LINE=$(CURRENT_LINE) CURRENT_COLUMN=$(CURRENT_COLUMN) && pause`:

image

4. Press the `Run` button.

### Expected Behavior

A CMD window opens with `CURRENT_LINE=1 CURRENT_COLUMN=1` in it.

### Actual Behavior

A CMD window opens with `CURRENT_LINE=0 CURRENT_COLUMN=0` in it:

image

The line and column data is always "one less" than it should be, for any line and any column the caret is on.

### Additional

1. If it is thought that users are using these commands as they are, the "fix" could be to implement new expansion variables, suggest: `$(CURRENT_LINE1)` and `$(CURRENT_COLUMN1)`

2. See also https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8629#issuecomment-667582029

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\.............\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

### PR DESCRIPTION
**Pull request by sasumner**
Fixes #8679

### CODE REVIEW

**Comment by dail8859** [comment]
Couldn't this potentially break plugins that are expecting it to be zero based? Not saying it is correct, just that the behavior will change.

**Comment by sasumner** [comment]
>Couldn't this potentially break plugins that are expecting it to be zero based?

It could.  Perhaps plugins was its primary use?
I can't see this at a user-level at all, as all other tools I've seen that deal with line and column numbers deal with "user" concepts of one-based numbers.

Should I back off and create `$(CURRENT_LINE1)` and `$(CURRENT_COLUMN1)` ?

**Comment by dail8859** [comment]
I guess that would be Don's call. That suggestion would ensure compatibility and would be my preference.

**Comment by sasumner** [comment]
>I guess that would be Don's call. That suggestion would ensure compatibility and would be my preference.

Let's just go with that, then.
No need to wait for Don on it.
I'll rework it...

**Comment by Yaron10** [comment]
Do plugin use `$(CURRENT_LINE)` or `NPPM_GETCURRENTLINE`?

If the latter is correct, how about changing `wsprintf(expandedStr, TEXT("%d"), lineNumber);` to `wsprintf(expandedStr, TEXT("%d"), lineNumber + 1);` instead of the current change?

(In `RunDlg/RunDlg.cpp`).

**Pull request closed without merging**
