### PR TITLE
give FileLockedWarning when file could not be saved

### LINKED ISSUE #9994: No error message when locked file could not be saved
### Description of the Issue

No error message when file could not be saved.

### Steps to Reproduce the Issue

1. have file which is locked by another program
2. start notepad++ in admin mode
3.  open the file and edit
4. save with Ctrl + S or the Symbol bar
5. => no error that the file was not saved (because it is locked by another process)

### Expected Behavior

An Error message, that there was a sharing violation or the file was locked, or whatever Windows gives as error 

### Actual Behavior
File is not saved, no error message.
File still shows as edited (what is OK).

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows Server 2016 Standard (64-bit) 
OS Version : 1607
OS Build : 14393.4467
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

### PR DESCRIPTION
**Pull request by chund**
fix #9994
replace #9995
when file was locked and could not be saved, no error message was given.
Now the error message is given. The else with an obviously already existing error message was inserted.
All nativeLang files were enhanced with the $STR_REPLACE$\r to insert the actual error message from Windows.
changed some of the errors in the function to have the ERROR icon.

### CODE REVIEW

**Comment by chund** [comment]
@mere-human @chcg
this is just a little enhancement, improving an error message or rather reactivating an already existing one.
Could you please merge? Or otherwise tell me what has to be done?
I would appreciate to have this in the release.
Thanks :)

**Comment by mere-human** [comment]
For me it looks fine. I even tried it locally.
What I did:
- create a CSV file
- open the file in Open Office or MS Excel (it becomes locked)
- open the file in Notepad++
- modify the file and try to save it
- Notepad++ suggests you to switch to Admin mode, agree
- try saving again
- the warning in question is shown
image

One note, is that we usually change text only in `english.xml`. Other localizations are usually handled by translators.
But since it is just a $STR_REPLACE + LF, it looks acceptable for me.

**Comment by mere-human** [comment]
@donho What do you think? I see this as a nice improvement.

**Comment by donho** [comment]
Due to lack of reply & actions, this PR will be closed.

@mere-human 
You may be interested in doing a PR for #9994 ?

**Comment by mere-human** [comment]
> You may be interested in doing a PR for #9994 ?

Yes, I can do that.

**Pull request closed without merging**
