### PR TITLE
Update german.xml v7.9.2

### PR DESCRIPTION
**Pull request by schnurlos**
Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f5dcfc196aff5b41bb6db6e4b3044c26ab57cdf3#diff-a6ac7ceba70d88bf1547fd1defd760bd55052dcdb78c44f9d46d99ef1f450472

### CODE REVIEW

**Comment by Henry2o1o** [comment]
hier meine aktuelle funktionierende germn.xml

https://github.com/Henry2o1o/notepad-plus-plus-de/blob/main/PowerEditor/installer/nativeLang/german.xml

**Comment by Henry2o1o** [comment]
https://github.com/Henry2o1o/notepad-plus-plus-de/commit/094322d74eb9a63a6da1e95a1597d337858dec05

**Comment by donho** [comment]
@schnurlos 
Thank you for the updated translation. Could you complete your update according:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9293

**Comment by Henry2o1o** [comment]
> @schnurlos
> Thank you for the updated translation. Could you complete your update according:
> #9293

https://github.com/Henry2o1o/notepad-plus-plus-de/commit/b51f307d4054687336843f29afe33e951a021945#commitcomment-45348431

**Comment by schnurlos** [comment]
@donho: compleded, ready to merge.

**Pull request closed without merging**
