### PR TITLE
[xml] Update german.xml to v8.4.8

### PR DESCRIPTION
**Pull request by schnurlos**

### CODE REVIEW

**Comment by schnurlos** [comment]
OK, done

**Comment by donho** [comment]
@schnurlos 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

**Comment by schnurlos** [comment]
@donho all changes are included.

**Comment by donho** [comment]
Thank you @schnurlos !

**Pull request closed without merging**
