### PR TITLE
Update Corsican translation for Notepad++ 7.8.7

### PR DESCRIPTION
**Pull request by Patriccollu**
Translation of new strings related to changes since January 8th and modification of existing strings.

### CODE REVIEW

**Comment by Patriccollu** [comment]
@donho 
Hi Don,

This is an update of corsican.xml containing the translation of new strings related to latest changes since January 8th as well as a modification of some existing strings.

Thanks,
Patriccollu.

**Comment by donho** [comment]
@Patriccollu 
Please also add the following change:
93f7853

Thank you

**Comment by Patriccollu** [comment]
@donho 
Already done in latest commit ;-)
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8138/commits/811a1dc274e2b20b4c7d062495e2b079e64a3162
Cheers,
Patriccollu.

**Comment by Patriccollu** [comment]
@donho 
Actually this PR includes 6 commits which respectively take into account the following changes:

- Apr 19, 2020: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/eb6da8195b67a3077310a4d787fd4ac37cd21c76 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5483ad13d0d580b7858176032819582d9daccc10 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8a37faa7046169e4f8b675671e384ade1c9b57a6 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ffda03c41c660d255bffb0488cfaf8af4ea7fd46 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3474b8b11ed2aab10bec8e72e277705a66eef141 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/78d42fbd2d0e13b7b4d3773f609152b879c4ffc3
- May 1, 2020: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/924e4b23fe1c3f20a65282022c81fba082cfcd47
- May 5, 2020: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2b345c8f39310a921fc90ae38196ed323cb1a66a
- May 7, 2020: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f637901db5426c53ad6fa5def6a008e24a8f967c
- May 12, 2020: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c4851a49ab63f49092dce158b55f348dc84081d8 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2b713fb75b5f72f2d3e53a1a70a9d59b2124f830 , https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5a951531ad440c0080880b5ddcfda76f28071455
- May 26, 2020: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/93f78533334bb11af006e1171cc45d42848346ef

Patriccollu.

**Comment by donho** [comment]
I've got the conflict by merging your commit:
```
$ git merge --no-ff Patriccollu-patch-3
Auto-merging PowerEditor/installer/nativeLang/corsican.xml
CONFLICT (content): Merge conflict in PowerEditor/installer/nativeLang/corsican.xml
Automatic merge failed; fix conflicts and then commit the result.
```
Could you update your master, create a new branch and redo your PR based on this new branch?

**Pull request closed without merging**
