### PR TITLE
[xml] Restore accelerators for Incr Search to english.xml

### LINKED ISSUE #14500: Incremental Search inconsistent captioning for English controls
### Steps to Reproduce the Issue

1. Fresh extract of N++ 8.6 portable
2. Invoke _Incremental search_ window with Ctrl+Alt+i
3. Click in the edit box for _Find:_
4. Press and release Alt
5. Note the captions on the controls that have them (`&` represents that the following letter is underlined):
```
Find:
Match &case
&Highlight all
```
6. Set the _Localization_ setting to "English"
7. Click in the edit box for _Find:_ in the Incremental Wearch window
8. Press and release Alt
9. Observe the captions are now:
```
Find
Match case
Highlight all
```

### Expected Behavior
No change in captions after a fresh-extract to English localization change.

### Actual Behavior
_Find_ lost its colon, _Match case_ and _Highlight all_ no longer have underlined accelerators.

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6\test\npp.8.6.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

### PR DESCRIPTION
**Pull request by alankilborn**
Fix #14500

### CODE REVIEW

**Comment by alankilborn** [comment]
Oops, didn't do the right thing to keep CI_build from doing a build... :-(

**Comment by chcg** [comment]
> Start syntax check for xml files.
> {'category': 'error',
>  'details': '',
>  'message': 'PowerEditor/installer/nativeLang\\english.xml: '
>             'PowerEditor/installer/nativeLang/english.xml:516:38:FATAL:PARSER:ERR_ENTITYREF_SEMICOL_MISSING: '
>             "EntityRef: expecting ';'\n"
>             'PowerEditor/installer/nativeLang/english.xml:517:37:FATAL:PARSER:ERR_ENTITYREF_SEMICOL_MISSING: '
>             "EntityRef: expecting ';': XMLSyntaxError Invalid File"}
> Done.
> 

@alankilborn You missed the xml escaping of &

With the switch from appveyor to github action the optimization for xml file changes was not ported yet

**Comment by alankilborn** [comment]
>You missed the xml escaping of &

Yea, wow, that WAS a pretty big miss.  :-(

**Comment by donho** [comment]
Just change the title even
1. the changing of title after pushing has no effet
2. github action of the optimization for xml file changes has not done yet

but let's keep the habit for the day that github action for xml is done.

**Pull request closed without merging**
