### PR TITLE
Updated UI appearance of About dialog and Debug (#2151)

### PR DESCRIPTION
**Pull request by SinghRajenM**
Fixed reported issue  for UI consistency on About and Debug Info Dialog #2151

### CODE REVIEW

**Comment by SinghRajenM** [comment]
Fixed issue

**Comment by SinghRajenM** [comment]
Fixed issue

**Comment by dail8859** [comment]
Screenshot?

**Comment by SinghRajenM** [comment]
comparision
comparison screenshot is added!!!

**Comment by SinghRajenM** [comment]
Hi
I'm new to github and this is my first contribution. So I would like to
know who will merge this change and when?

**Comment by A-R-C-A** [comment]
By looking around here, the time ranges for merging reach from a couple of days to a couple of months and some even more. So take a break, relax. Don HO is busy. It will take some time.

**Pull request closed without merging**
