### PR TITLE
Update french.xml

### PR DESCRIPTION
**Pull request by Mateos81**
Recent commits + one typo fix

### CODE REVIEW

**Comment by donho** [comment]
@Mateos81 
Please add `[xml]` on the beginning of title next time, if the PR is about translation, and only xml file(s) is (are) modified.
Ex: `[xml] Update french.xml`

**Comment by donho** [comment]
@Mateos81 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

**Comment by Mateos81** [comment]
@donho Retrieved latest english.sml and compared to this PR french.xml, it's correct as far as I can see

**Comment by donho** [comment]
Thank you @Mateos81 !

**Pull request closed without merging**
