### PR TITLE
Update sql.xml

### PR DESCRIPTION
**Pull request by malix0**
### Description of the Issue
SQL functionList does not catch all procedure and function signatures

### Steps to Reproduce the Issue
Open an sql file and check that functionList contains all the signatures

### Solution
I change the sql.xml attached here and this one seems to work better than the one provided with Notepad++. Evaluate yourself if you want to use my version.

### CODE REVIEW

**Comment by Mateos81** [comment]
I believe an example script will be asked by the maintainer to check a before/after behaviour, so if you can provide one

**Comment by ArkadiuszMichalski** [comment]
@donho We have the first case of new build:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45530859

Here `sql.xml` from `functionList` was changed so compilation + full test was done in `MSC Win32/Debug`, and other 9 jobs was terminated. This case will takes ~21min.

**Comment by malix0** [comment]
Attached a source for a Oracle PL/SQL package with heterogeneous code formatting

[test_re.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10122119/test_re.txt)

**Comment by malix0** [comment]
> Attached a source for a Oracle PL/SQL package with heterogeneous code formatting
> 
> [test_re.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10122119/test_re.txt)

I omitted, this is in response to @Mateos81

**Comment by donho** [comment]
@malix0 
Could you provide the result of BEFORE and AFTER your PR?

**Comment by donho** [comment]
The merge is not necessary, and it will break the workflow of integration.
Please create a new PR and provide the result (screenshot) of BEFORE & AFTER of your PR.

**Comment by demetrio72** [comment]
Some little improvement starting from @malix0 contribution.

It recognizes package and package body, so you can distinguish if you have both in the same file. It still doesn't group functions and procedures under its node, I didn't realize how to use classRange node.

I can't attach file because of enterprise policies, sorry, I just copy-paste the core code here:
`				<function
				mainExpr="^[ \t]*(CREATE([\s]+OR[\s]+REPLACE)?[\s]+)?((PACKAGE([\s]+BODY)?)|(PROCEDURE)|(FUNCTION))[\s]+[A-Za-z][\w_]*([\s]*(?'open'\().*?(\)))?(([\s]*;)|([\s]*([ia]s)\s)|([\s]+(RETURN)([\s]+[\w%\.]+)+(([\s]*;)|([\s]+([ia]s)\s))))"
				displayMode="$className->$functionName"
			>
			<className>
					<nameExpr expr="((PACKAGE([\s]+BODY)?))[\s]+[A-Za-z][\w_]*([\s]+[ai]s[\s]*)?"/>
				</className>
			<functionName>
					<nameExpr expr="[\s]+[A-Za-z][\w_]*([\s]*(?'open'\().*?(\)))?(([\s]*;)|([\s]*([ia]s)\s)|([\s]+(RETURN)([\s]+[\w%\.]+)+(([\s]*;)|([\s]+([ia]s)\s))))"/>
					<nameExpr expr="[A-Za-z][\w_]*([\s]*(?'open'\().*?(\)))?(([\s]*;)|([\s]*([ia]s)\s)|([\s]+(RETURN)([\s]+[\w%\.]+)+(([\s]*;)|([\s]+([ia]s)\s))))"/>
					<nameExpr expr="[A-Za-z][\w_]*([\s]*\([^\)]*\))?(([\s]+(RETURN)([\s]+[\w%\.]+)+))*"/>
				</functionName>
			</function>`

**Pull request closed without merging**
