### PR TITLE
Singular to plural, title case (dockable "Find Results" dialog)

### PR DESCRIPTION
**Pull request by h-h-h-h**
Most times it's more than one "Find result" ("Find in Files"). Used title case as in "Document Map".

### CODE REVIEW

**Comment by Rikk** [comment]
I'm not sure the second word should have capital letter, as it mostly appear followed by 'X hits', eg. "Find result - 3 hits".
Imo, it could also be "Search results: X hits".

**Comment by h-h-h-h** [comment]
Because it reads "Document Map", I changed it to "Find Results - 100 Hits".

What about a proper em dash? Today's default fonts like Segoe UI are no barrier to this. Example: "Find Results—100 Hits".

**Comment by Rikk** [comment]
Imo, it's wrong and strange. Doesn't fallow any Windows or written language conventions.
Both words capitalized would make sense in a title, but not in a description.
Unless it only contained "Find Results" in the title, I would agree, but because it has extra text, imo, it should be "Find results: X hits". (Although I prefer "Search results: X hits").

**Comment by h-h-h-h** [comment]
A newspaper headline of this format is imaginable. I'll leave the pull request as-is to see the opinion of the one accepting or declining it.

**Comment by donho** [comment]
Thank you for the PR. However, it'll be better to create an issue instead of PR for renaming or typo:
"Your pull requests are welcome; however, they may not be accepted for various reasons. If you want to rename some graphic items or fix typos, please create the issue instead of the pull requests." 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
