### PR TITLE
Refactoring file saving routine

### PR DESCRIPTION
**Pull request by Klotzi111**
This PR replaces the file saving routine to be able to fix certain problems.
This PR fixes https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1498, fixes https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5664, fixes https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133

It contains the following changes/additions:

1. The file is opened with the following disposition values. `allowOverwrite ? OPEN_ALWAYS : CREATE_NEW`
    1. This opens the file without truncating it
        1. This is to ensure that if we fail to write the entire file (or were unable to write anything) we lost as little data as possible. (data is still lost in those cases. Backups are required anyways and are independent of these changes)
    2. We "reuse" the existing file. So we are not losing any metadata or ADS
2. Opens the file with the additional flags `FILE_FLAG_WRITE_THROUGH | FILE_FLAG_NO_BUFFERING`
    1. This causes the Windows file cache to be bypassed for writes to that file and to do atomic writes to the sectors of the storage device
        1. This improves performance because the device does not need to read, update and write a sector
        2. This should prevent cases in which data is lost after the write happened when a fatal system failure occurs (like power loss) because there is not cached data to be lost (at least from the OS side. The hardware cache might still be active and can be lost)
    2. This has some drawbacks, In order to do this the data buffer must be aligned to the physical sector size. And because of that we need to create a buffer that meets these requirements and copy the entrire data over in memory. This can require a lot of memory if the file is big.
        1. A possible solution would be to have the internal buffers of N++ already aligned correctly (Note: physical sector size can change between devices. So a big alignment needs to be used to be safe)
3. Before the actual write operation the required file space is preallocated
    1. This is to ensure we can write the entire content and a OutOfDiskSpace error can not occur (or write nothing if the preallocation fails)
    2. This also reduces data fragmentation because all the required space is allocated in one go
4. The actual file size (more correct: the EOF mark) is set after a successful write
    1. This is required because we write in entire sector blocks and therefore the file can be larger than the wanted content after the write and before setting EOF
    3. If the process is killed before setting EOF there might be some NUL bytes at the end up to the next physical sectore aligned offset

**Testing is still required.**

My IDE automatically changed some whitespaces in some files. I hope this is ok.
Your comments are welcome.

@donho Can you also add this PR to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14085 ?

### CODE REVIEW

**Comment by Klotzi111** [comment]
I changed `-D_WIN32_WINNT=_WIN32_WINNT_VISTA` to `-D_WIN32_WINNT=_WIN32_WINNT_WIN8` because otherwise some structs in the `Windows.h` are not available.
This should be ok since https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md says only Windows 8.1 and above is supported

**Comment by rdipardo** [comment]
> This should be ok since https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md says only Windows 8.1 and above is supported

The table is not clear, but the "supported" colummn actually means "supported __*by Microsoft*__". Even in that sense it's out-of-date; 8.1 went [out of support in January][0].

Since N++ version v8.4.7, the minimum required Win32 API level *at runtime* is Windows 7 (i.e. `_WIN32_WINNT_WIN7`): 

- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13074#issuecomment-1445191786
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12546#issuecomment-1631733555

I say "runtime" because you actually need a Windows __*11*__ SDK to build the project. The minimum Windows version supporting `DWMWA_USE_IMMERSIVE_DARK_MODE` is build number 22000, [according to Microsoft], not "19041", as the code mistakenly assumes here:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b62b77b3ea55629ff8fdbc856fe2cd3511f8df04/PowerEditor/src/NppDarkMode.cpp#L2889-L2894


[0]: https://learn.microsoft.com/en-us/lifecycle/products/windows-81
[according to Microsoft]: https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute#:~:text=use%20light%20mode.-,This%20value%20is%20supported%20starting%20with%20Windows%2011%20Build%2022000.,-DWMWA_WINDOW_CORNER_PREFERENCE%0AUse%20with

**Comment by Klotzi111** [comment]
What does that mean for this PR? Do I need to change something?
Also Dark Mode is totally unrelated to this PR.

**Comment by rdipardo** [comment]
@Klotzi111,

> What does that mean for this PR?

Assuming you mean [my earlier comment][0], the point is that targeting Windows 8 should be justified by something better than the outdated table in SUPPORTED_SYSTEM.md, which does not reflect the actual minimum requirements of the source code, nor even Microsoft's current support policy. If the PR doesn't build without it, it's up to @donho to decide whether that's a fatal blocker or not. What's in SUPPORTED_SYSTEM.md has no authority whatsoever.

If it were my choice to make, Windows 7 would already be the minimum target, since Vista is definitely unsupported in all scenarios; there's a small but devoted group of users on Windows 7 (see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8108#issuecomment-612923727); and major vendors like Mozilla still support it ([for now][1]).

By the time there's a good reason to make Windows 8 the *mandatory* minimum, Windows 10 will be end-of-life, and you might as well make *that* the minimum target, because practically nobody will be running older versions by then.


[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14090#issuecomment-1704401404
[1]: https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support

**Comment by Klotzi111** [comment]
> targeting Windows 8 should be justified by something better than the outdated table in SUPPORTED_SYSTEM.md

The justification is that without increasing the minimum version certain features of my new file saving routine might not be supported. Then a version check at runtime would be required to only use those features if they are supported.
In both cases the change to `-D_WIN32_WINNT=_WIN32_WINNT_WIN8` will be required because otherwise the structs for the features will not be available. Which they need to be in order to compile the code for using the affected features (even if they are behind a runtime version check)

> What's in SUPPORTED_SYSTEM.md has no authority whatsoever.

Why does it even exist then? It makes things only confusing.

So we are waiting on a decision from @donho then.

**Comment by donho** [comment]
@Klotzi111 
> I changed -D_WIN32_WINNT=_WIN32_WINNT_VISTA to -D_WIN32_WINNT=_WIN32_WINNT_WIN8 because otherwise some structs in the Windows.h are not available.
This should be ok since https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md says only Windows 8.1 and above is supported


The main issue for this PR is not the problem above.
As I explained before, [it's very unlikely that Notepad++ integrate a heavy refactoring code of IO, for the sake of stability.](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14029#discussion_r1306643455)
I have to admit that you have done a huge coding effort to bring this PR to us.  I appreciate that very much. However, it's out of the question for me to go through several versions again for stabilizing the core feature of Notepad++. As a result I have to decline your PR with a lot of regret. Still, thank you very much for your coding effort.

**Comment by Klotzi111** [comment]
> As I explained before, it's very unlikely that Notepad++ integrate a heavy refactoring code of IO, for the sake of stability.

I do not understand that. Because the saving routine is already not stable. See all the issues about saving.

I will need to use my fork then.
Also I will continue testing this saving routine with the use cases described in #14085

**Comment by xomx** [comment]
@Klotzi111 
I tried this PR also in the testing of #14103 (saving to a WebDAV mapped folder), but your code failed in your `FileSystemHelper::getStorageInfo`, where the `GetFileInformationByHandleEx` failed with the `ERROR_INVALID_FUNCTION` (0x1), which resulted in errdlg:
PR#14090-error
The usual saving of files to local disk worked fine though.

Anyway, thanks for the interesting solution.

**Comment by Klotzi111** [comment]
> but your code failed

Thats odd. Because the error `ERROR_INVALID_FUNCTION` is not documented for `GetFileInformationByHandleEx` on msdn.
That probably means that the driver for your network share does not implement this method (or the requested information class)

**Comment by xomx** [comment]
> That probably means that the driver for your network share does not implement this method

Exactly my suspicion, there is a [similar issue](https://github.com/gradle/native-platform/issues/43).

**Pull request closed without merging**
