### PR TITLE
Added Document List Panel in toolbar and View menu:

### LINKED ISSUE #3526: Preferences->General->Document List Panel->Show should have toggle in View menu
### Description of the Issue

`Preferences->General->Document List Panel->Show` should have toggle in `View menu` to allow the `'Doc Switcher'` panel to be shown or hidden with a shortcut key assigned to the menu item. Similar to what can be done with the `'Document Map'` entry in the View menu. It is currently awkward to have to open Preferences to check or uncheck the `"[x] Show"` checkbox in the Document List Panel group.

The current `'Doc Switcher'` panel is fantastic, but you need to be able to **show/hide** it with a shortcut to provide full-window editing without having to open Preferences each time.

### Steps to Reproduce the Issue

1. Check the `"[x] Show"` checkbox in the `Document List Panel` group (in Preferences->General)
2. Now try and find a convenient way to show/hide the `'Doc Switcher'` panel to provide additional editing space.
3. (cannot currently be done)

### Expected Behavior

Some View menu 'Doc Switcher' or 'Document Panel' toggle that could be assigned a shortcut

### Actual Behavior

Searched diligently but no way other than opening Preferences and unchecking `[x] Show` could be found to hide the `'Doc Switcher'` panel.

### Debug Information

**No debug Info -- Just a feature request** `:)`

Keep up the great work. NPP is a good package.

### LINKED ISSUE #9015: No menu entry and no ability to define a keyboard shortcut to toggle/switch to document list panel
### Description of the Issue
After getting the ability to toggle/switch to _Project Panel x_ and _Folder as Workspace_ panels in v7.9, the _Document List_ panel is the only sidebar panel which is not operable by keyboard shortcuts and it even has no menu entry to do so, too. The only place to toggle _Document List_ panel is the main preferences dialog. A means to set input focus on it doesn't exist.

### Steps to Reproduce the Issue
1. Open shortcut mapper and search for an entry of _Document List_ panel.
2. Dig into the main menu and try to find a menu entry to toggle/switch to _Docment List_ panel.

### Expected Behavior
At least it should be possible to define a keyboard shortcut to switch to (set input focus to) the _Document List_ panel. To be **consistent**, it would be nice to have the ability to define a keyboard shortcut to toggle _Document List_'s visibility as well. To be **complete**, a menu entry for toggling visibility of _Document List_ would be perfect.

### Actual Behavior
Nothing of the above is available.

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : xxx\Notepad++Portable\npp.7.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : AutoCodepage.dll BetterMultiSelection.dll BracketsCheck.dll ChangedLines.dll CodeAlignmentNpp.dll ComparePlugin.dll Explorer.dll ExtSettings.dll LanguageHelp.dll LuaScript.dll mimeTools.dll NavigateTo.dll NppColumnSort.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppGist.dll NppHasher.dll NppHorizontalRuler.dll NppMarkdownPanel.dll NppSaveAsAdmin.dll NppTextFX.dll NppToolBucket.dll NppUISpy.dll NppYEtc.dll OpenSelection.dll pork2sausage.dll ReloadFile.dll SelectQuotedText.dll SurroundSelection.dll XMLTools.dll _CustomizeToolbar.dll

### PR DESCRIPTION
**Pull request by Ashfaaq18**
fix #3526 
fix #9015

1. Toggle toolbar item and view menu item for Document List Panel
2. Added standard, filledFluent, darkmode->toolbar->(fluent and filledfluent) icons for the Document List Panel toggle
3. Working shortcut for the Document List Panel under shortcut mapper
4. removed show document panel from the preference menu, kept the extension option

docPanelToggleinView1

### CODE REVIEW

**Comment by donho** [comment]
@WildByDesign
Is the icon OK for you or you have a better idea?

**Comment by donho** [comment]
@ArkadiuszMichalski @pryrt and the others
Between "Doc Switcher" and "Document List" which one is suitable to you?
I am trying to unify its name, just wanna get your thoughts. Thank you in advance.

**Comment by pryrt** [comment]
I personally prefer "Document List", but based on my experience in the Community Forum, most users seem to think of it as the "Doc Switcher".  But yes, the most important thing is that the Menu, Preferences, and panel title all agree.

**Comment by ArkadiuszMichalski** [comment]
Rather "Document List" because "Doc Switcher" colidate with "Document Switcher" (Ctrl+TAB), and this has its own settings in MISC. Better to have some more distinctive names for the two mechanisms.

**Comment by pryrt** [comment]
@ArkadiuszMichalski is right.  It should be renamed to "Document List" in the panel's titlebar, in the menu, and stay "Document List" in the Preferences > General section.

**Review by donho — CHANGES_REQUESTED** [review]
1. User "Document List" instead of "Document List Panel" or "Doc Switcher" - that means change also the title bar "Doc Switcher" to "Document List" (and in the localization file).
2. Symbol name should be also adapted: IDM_VIEW_DOCLIST or IDM_VIEW_DOCLIST_ICO, etc...

**Comment by WildByDesign** [comment]
> Is the icon OK for you or you have a better idea?

In my opinion, this icon looks quite good.

**Review by donho — APPROVED** [review]

**Comment by GOLEM777** [comment]
44081  is occupied by another option - Project Panel 1
and 
  `  #define    IDM_VIEW_DOCLIST                   (IDM_VIEW + 70)`
`44081` must be changed on `44070`
If I don't confuse anything!

**Comment by Ashfaaq18** [comment]
Good Spot @GOLEM777!

**Pull request closed without merging**
