### PR TITLE
Update turkish.xml

### PR DESCRIPTION
**Pull request by Tmp341**
Changed version to latest and added id 44085.

### CODE REVIEW

**Comment by donho** [comment]
@Tmp341 Please update your PR for 7.0

**Comment by donho** [comment]
Please reopen it while you update this PR.

**Comment by gamzeakmann** [comment]
<Item id="44085" name="Folder as &amp;Workspace"/> 
This line is still missing in turkish xml.
<Item id="44085" name="Çalışma Alanı Olarak Klasör"/>
This line should be added to xml.
I want to work on it. @donho

**Comment by gamzeakmann** [comment]
<Item id="44085" name="Folder as &amp;Workspace"/>

**Pull request closed without merging**
