### PR TITLE
Update Slovak translation

### PR DESCRIPTION
**Pull request by kubalav**
ref 8e38b9dabab11da0b7f3972a99e2d15a0a6cdeb6
ref 7b1e6546a1353023b86c546b2bdc305493d73d15
ref 5b9e3b6406bcc14cef4a1eedb24f78f5a5f8e8ed

### CODE REVIEW

**Comment by donho** [comment]
Here is the diff between v8.1.2 & v8.1.3:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10297

Could you check it and confirm me it's all done (or you prefer do it later in the next release)?
Thank you.

**Comment by kubalav** [comment]
@donho All changes are includes.

**Comment by donho** [comment]
While merging your PR, I've got the following message:
```
$ git rebase -i
error: could not apply 1b8c4b19... Update Slovak translation
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 1b8c4b19... Update Slovak translation
Auto-merging PowerEditor/installer/nativeLang/slovak.xml
CONFLICT (content): Merge conflict in PowerEditor/installer/nativeLang/slovak.xml
```

This PR is not merged.
Please redo your PR properly then I will remerge it.

**Comment by kubalav** [comment]
I can't to reopen PR. I made new one.

**Pull request closed without merging**
