### PR TITLE
Hotkey for "Copy Selected Line(s)" in find space.

### PR DESCRIPTION
**Pull request by GOLEM777**
Ctrl+Shift+X hotkey for Copy Selected Line(s) in find field.

### CODE REVIEW

**Comment by GOLEM777** [comment]
Macro doesn't record operation///
```
		case NPPM_INTERNAL_SCINTILLAFINDERCOPY :
				{
					copy();
					return TRUE;
				}
```
replacement  on SCI_LINECOPY  won't help for hot key?
you can help?

**Comment by alankilborn** [comment]
>you can help?

I can try, if @donho approves and has an idea for how it should work.

**Comment by donho** [comment]
@alankilborn 

SCI_LINECOPY is already in Shortcut Mapper.

But I wonder [why Finder::copy()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp#L4838) shouldn't use SCI_LINECOPY instead of current more complex code:
```cpp
void Finder::copy()
{
	_scintView.execute(SCI_LINECOPY );
}
```
 Could you check it please?

**Comment by GOLEM777** [comment]
SCI_GETSELECTIONS  - tied selection by column
Therefore the field ignores the column selection.
**The problem is copying associated garbage!**
I think this is a bad idea. I was stupid!
------
I don't know how to compile and can't test it.  )))
But  judging by the code, it will be so.

**Comment by alankilborn** [comment]
>But I wonder why Finder::copy() shouldn't use SCI_LINECOPY instead of current more complex code

This is the _Copy Selected Line(s)_ choice from the _Search results_ right click menu.  It does a very special type of copy (thus needing the complex code) as detailed in the [user manual](https://npp-user-manual.org/docs/searching/#rightclick-commands-in-the-client-area-of-a-search-results-window-s-tab:~:text=What%20gets%20copied%20when%20RightClick%20%3E%20Copy%20Selected%20Line(s)%20is%20run).

Code is correct as is.

**Comment by donho** [comment]
@alankilborn 
> This is the Copy Selected Line(s) choice from the Search results right click menu. It does a very special type of copy (thus needing the complex code) as detailed in the [user manual](https://npp-user-manual.org/docs/searching/#rightclick-commands-in-the-client-area-of-a-search-results-window-s-tab:~:text=What%20gets%20copied%20when%20RightClick%20%3E%20Copy%20Selected%20Line(s)%20is%20run).

Hmm... indeed.

In this case, I see no trivial way to attribute Ctrl+Shift+X to this command.

**Comment by kor44** [comment]
Is it possible add option to redefine shortcut `Ctrl+C` not for `Copy` but for `Copy Selected Line` in `Search result Window`?

**Pull request closed without merging**
