### PR TITLE
Fix many GCC compile warnings and some errors

### LINKED ISSUE #1662: Many distracting compile warnings with GCC
There is a huge load of warnings, up to 200 identical warning lines per C++ file. They cause very enlarged output and distract from real problems.

### PR DESCRIPTION
**Pull request by marcows**
Fixes #1662

The MinGW build is not successful anymore since addition of the file browser. This pull request doesn't fix this problem.

### CODE REVIEW

**Comment by donho** [comment]
> This pull request doesn't fix this problem.
???

**Comment by marcows** [comment]
> > This pull request doesn't fix this problem.
> ???
Sorry for the confusing description, this was just meant as additional information.

Rewording:
This pull request fixes many GCC compile warnings and some errors.
However, some problems with MinGW, introduced by the recent addition of the file browser, are not fixed and still cause compile errors.

**Comment by marcows** [comment]
I have just pushed the branch with a new commit, which adds a minimal FileBrowser stub for MinGW. Now it can be built and is running successfully again because the unsupported ATL is not used anymore. There were no changes to the original source files needed for this.

@mzbab88 Try out this reworked branch.

**Comment by milipili** [comment]
Closing since merge conflict but I will take care of that using the current patch.

**Comment by marcows** [comment]
I have rebased my branch, conflicts resolved:
https://github.com/marcows/notepad-plus-plus/tree/gcc-fixes

**Comment by marcows** [comment]
Rebased after conflicts.
With Linux/Wine (MinGW 5.3.0) I get a std:exception now, with Windows 7 (MinGW 5) it is running. When reverting the changes in PowerEditor/src/Notepad_plus.cpp from commit bd373788ad997f5d3fd97f9f874acf4081bb10bb it is running with Linux/Wine again.

**Comment by dail8859** [comment]
I ran [this](https://ideone.com/GHvCmo) code snippet in ideone and it gives:

> terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

Which appears to be coming from `std::locale("")`. Which is weird because that should be [supported](http://www.cplusplus.com/reference/locale/locale/locale/).

**Pull request closed without merging**
