### PR TITLE
Fix extension appending depending on file type in file dialog

### LINKED ISSUE #9510: File doesn't save as extension type
### Description of the Issue
In Notepad++ 7.9.2 I can do "Save as", file name: "lol" and "Save as type": "Normal text file (*.txt)" and the output file will be "lol.txt". Choosing the same options in 7.9.3 and the output file is named "lol" with no extension.

I don't have the option "Set Save dialog file extension filter to \*.\*" checked.

### Steps to Reproduce the Issue

Steps are above

### Expected Behavior
Above

### Actual Behavior
Above

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

### PR DESCRIPTION
**Pull request by mere-human**
When changing file path, ensure both dialog data and edit control are set.
Use mouse button state change to track dialog confirmation.

Fix #9510

### CODE REVIEW

**Comment by mere-human** [comment]
This PR should fix the problems with the file dialog on Windows 7 as well.

**Review by donho — CHANGES_REQUESTED** [review]
Fix: 
Press tab until the Save button has the input focus, then press return: .txt is not appended.
ref: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9510#issuecomment-779079803

**Comment by sasumner** [comment]
@donho said:

>To be fixed:
Press tab until the Save button has the input focus, then press return: .txt is not appended.

Testing this PR, I agree with @donho findings.

Curiously, though, if you do this:

Press tab until the Save button has the input focus, then press **spacebar**: .txt ***IS*** appended!

**Comment by mere-human** [comment]
> To be fixed:
> `Press tab until the Save button has the input focus, then press return: .txt is not appended.`
> ref: [#9510 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9510#issuecomment-779079803)

Originally, I tested this scenario and everything was fine. So I was puzzled as to what should I fix.
But then I tried to change the _Save as type_, then remove the extension from file name and then press the button (by any means).
It didn't appended the extension. Everything should be fine now.

**Pull request closed without merging**
