### PR TITLE
Fix typo in ScitillaComponent directory name

### PR DESCRIPTION
**Pull request by mere-human**
Rename ScitillaComponent -> ScintillaComponent.
Git history should be kept because `git mv` was used.
Also change paths in source code.

This was noted  in scope of #9403

### CODE REVIEW

**Comment by sasumner** [comment]
Hmmm, that's bold.
TBH, seeing `Scitilla` has always bothered me (on some level).
But I've never been "bold enough" to do anything about it, because of the rule about "typo fixing".
I guess we'll see what happens this time with it.  :-)

**Comment by mere-human** [comment]
I understand that it's been like this for so long.
But I think this has to be fixed finally.

Just for reference, was found here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9403#issuecomment-767087243

**Comment by mere-human** [comment]
Should I create an issue for this kind of change?

**Comment by donho** [comment]
> Should I create an issue for this kind of change?

It's not necessary.

**Comment by donho** [comment]
@sasumner 
> But I've never been "bold enough" to do anything about it, because of the rule about "typo fixing".

We have talked about this, and my answer was "to avoid the tourists" - by **tourist** I mean people who scan the project for fixing the typos just because they want their names on the list of contributors, and believe me, there were a bunch of people, and they wasted my time.
So there's no problem for the team members or real contributors - but please fix typos when you see them while you're doing another PR, instead of creating a PR for one or two typos.

**Comment by sasumner** [comment]
>We have talked about this,

It's true, but I probably forgot.  :-(

>just because they want their names on the list of contributors

Hmm, I wouldn't know where to find MY name on the list of contributors; well, aside from github's little contribution "map".  But such things aren't important to me, anyway.

**Comment by sasumner** [comment]
>But I think this has to be fixed finally.

It's fine to fix it, but I still am unclear on the "has to be".

I'm going to guess at the origins:  `Scitilla` has 8 characters; `Scintilla` has 9 -- could it be a vestige from the "dark ages" when filenames were limited to "8+3" (and directories were limited to, typically 8 -- no extension)?

**Comment by donho** [comment]
@sasumner 
> Hmm, I wouldn't know where to find MY name on the list of contributors; well, aside from github's little contribution "map". 

https://github.com/notepad-plus-plus/notepad-plus-plus#contribution

> But such things aren't important to me, anyway.

Real contributor doesn't care indeed. But there's another interest: Some (a lot?) recruiters check the github account and try to spot the account having the high contribution statistics. I have had some contact from them because of my contribution to Notepad++ project on Github. 
I noticed one of translators modified a large amount of content every months - it lasted around 6 months then I asked him why he needed to move around the XML nods - no reply from him and his per month modification stopped. That's why such rule does exist. I don't care about impostors, if they don't waste my time and increase the repository size of my project.

> I'm going to guess at the origins: Scitilla has 8 characters

LOL. Still, Notepad++ is younger than Dos.

**Comment by mere-human** [comment]
> It's fine to fix it, but I still am unclear on the "has to be".

Ok, it was just my personal opinion.
I try to follow the rule "always leave the code behind in a better state than you found it".

**Pull request closed without merging**
