### PR TITLE
Update czech.xml

### PR DESCRIPTION
**Pull request by xomx**

### CODE REVIEW

**Comment by donho** [comment]
@xomx 
Could you please update your translation with it:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10408

**Comment by xomx** [comment]
@donho 
Done.
I have also reviewed again the Mark&Style stuff, I hope that this time I got it right (I am not using it).

**Comment by donho** [comment]
Please redo your PR, the file is changed entirely:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10406/files

**Comment by xomx** [comment]
@donho 
Sorry, I cannot do that until Monday. I have the source czech.xml file at my PC at work and unfortunately I switched it off before weekend, so I cannot connect to it via RD. And I did not succeed to restore the newest file from the closed PR, Github are showing to me only my 2 patches (but incomplete, as they are very long - it incorrectly thinks that these are completely different). And when I look into my patch-36, the czech.xml file is empty.

**Comment by donho** [comment]
No problem @xomx !

**Pull request closed without merging**
