### PR TITLE
[xml] Prevent duplicate entries in function list panel of Pascal/Delphi files

### LINKED ISSUE #12693: FunctionList parser for Pascal/Delphi is buggy because I accidentally commited an outdated version
### Description of the Issue
The current version of FunctionList parser included with upcoming Notepad++ v8.4.8 produces duplicate entries in FunctionList panel.

### Steps to Reproduce the Issue
See discussion in community forum [>> here <<](https://community.notepad-plus-plus.org/post/82696), try test code provided by user _James Richters_ (known as @Zaaphod here on GitHub).

### Expected Behavior
**Declarations** of procedures/functions in the **interface section** of a Pascal unit should not produce entries in FunctionList panel, only the **definitions** of these procedures/functions in the **implementation section** should produce such entries.

### Actual Behavior
With the current version of Pascal/Delphi function list parser also **declarations** of procedures/functions in the **interface section** of a Pascal unit produce superfluous entries in FunctionList panel.

### Applies To
Upcoming Notepad++ v8.4.8

### Related issues
This is related to issue  #12687 which is supposed to be fixed by PR #12686. Since in the community thread mentioned above _James Richters_/@Zaaphod wrote this fix doesn't really solve the problem, I created this new issue and will also create a new PR to fix it in a more reliable way.

### PR DESCRIPTION
**Pull request by dinkumoil**
Fixes #12693, #12687
Also closes #12686

### CODE REVIEW

**Comment by rdipardo** [comment]
It seems to work as intended, but the [unit tests have not been updated]:

~~~
pascal ... KO
result = {"leaves":["FreeFunc","FreeFunc","FreeFunc2","FreeFunc2Internal","FreeFunc3","FreeFunc3Internal","FreeFunc4","FreeFunc4Internal","FreeFunc5","FreeFunc5Internal","InitStdInternalClass","ReInitStdInternalClass"],"nodes":[{"leaves":["Create","Destroy","Init","DeInit","SetValue","Convert<X>"],"name":"TStdClass"},{"leaves":["Create","Destroy","CopyTo"],"name":"TStdClass.TStdInternalClass"},{"leaves":["Create","Destroy","Init<I>","DeInit","SetValue"],"name":"TGenericClass<T>"},{"leaves":["Create","Destroy","CopyTo<I>"],"name":"TGenericClass<T>.TGenericInternalClass<T, I>"},{"leaves":["ToString","FromString"],"name":"TEnumHelper"},{"leaves":["AsString","FromString"],"name":"TStdClassHelper"}],"root":"unitTest"} 
vs
 {"leaves":["FreeFunc","FreeFunc","FreeFunc2","FreeFunc2Internal","FreeFunc5","FreeFunc5Internal","InitStdInternalClass","ReInitStdInternalClass"],"nodes":[{"leaves":["Create","Destroy","Init","DeInit","SetValue","Convert<X>"],"name":"TStdClass"},{"leaves":["Create","Destroy","CopyTo"],"name":"TStdClass.TStdInternalClass"},{"leaves":["Create","Destroy","Init<I>","DeInit","SetValue"],"name":"TGenericClass<T>"},{"leaves":["Create","Destroy","CopyTo<I>"],"name":"TGenericClass<T>.TGenericInternalClass<T, I>"},{"leaves":["ToString","FromString"],"name":"TEnumHelper"},{"leaves":["AsString","FromString"],"name":"TStdClassHelper"}],"root":"unitTest"} -1
There are some problems in your pascal.xml
~~~

[unit tests have not been updated]: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45762400/job/7dg67j1rb2hu0du2#L1186

**Comment by dinkumoil** [comment]
If the unit tests fail then there are some other issues. I took the version of my parser I commited in this PR from another machine, seems like it is also outdated. Currently I'm not at home and will not be until next week, thus I'm not able to fix the issue.

@donho : This PR will be corrected next week, do **NOT** accept it for now.

**Comment by donho** [comment]
@dinkumoil 
Please also **add** new functions/methods which DON'T work with the current parser but DO work with the new modification in unitTest file.

**Comment by dinkumoil** [comment]
@donho 
PR is ready for merging now.

> Please also **add** new functions/methods which DON'T work with the current parser but DO work with the new modification in unitTest file.

Done.

**Review by donho — CHANGES_REQUESTED** [review]
Re-organize the unitTest:
There are a lot of "Foo", "Bar" "FreeFunc#" "FreeFunc#Internal", "TStdClass" etc.
Please make their name different and identifiable.

**Comment by donho** [comment]
@dinkumoil 
Could you let me know if you could accomplish the request so I could take a solution for this PR.
Thank you.

**Comment by dinkumoil** [comment]
@donho 

Currently I have no time to work on your request, life has thrown new challenges at me.

Moreover, I'm not sure how to satisfy your request. I could rename the `foo`, `bar`, `test` and `boo` functions, but I would like to rename them to another `FreeFunc#` functions because that's the most accurate description for them. And I have no idea how to rename `TStdClass` (or `TGenericClass<T>` respectively) and its methods because these are also descriptive names. What naming schema do you prefer?

Additionally there is still a problem with my Pascal function list parser, to be certain it seems to be a general problem applying to **all** function list parsers. There seems to be some bug in the C++ code that processes function list parser files and fills the tree in function list panel. See [>> this conversation <<](https://community.notepad-plus-plus.org/topic/23921/help-adding-pascal-to-function-list) in the community forum. This bug causes commented-out functions to be part of the function list only in case the parser file contains a mixed parser (function and class parser).

In some weeks I could try to debug the function list code, but I don't know if I will succeed because I'm not a C++ developer and have only limited knowledge of this language. If I will be able to fix the bug, this PR (respectively my function list parser) has to be changed again.

**Comment by donho** [comment]
@dinkumoil 

> In some weeks I could try to debug the function list code, but I don't know if I will succeed because I'm not a C++ developer and have only limited knowledge of this language. If I will be able to fix the bug, this PR (respectively my function list parser) has to be changed again.

Thank you for the information.

> Additionally there is still a problem with my Pascal function list parser, to be certain it seems to be a general problem applying to **all** function list parsers. There seems to be some bug in the C++ code that processes function list parser files and fills the tree in function list panel. See [>> this conversation <<](https://community.notepad-plus-plus.org/topic/23921/help-adding-pascal-to-function-list) in the community forum. This bug causes commented-out functions to be part of the function list only in case the parser file contains a mixed parser (function plus class parser).

I will see what I can do about it.
Beyond that, is there a regression in this PR comparing the parser in master now? Or it doesn't cover all aspect of new recognized functions?

**Comment by dinkumoil** [comment]
@donho 

> is there a regression in this PR comparing the parser in master now?

No, it's the other way around, this PR brings some progress. However, commented out functions in the implementation section of a _Pascal_ unit are erroneously included in the function list tree.

In some days I will provide an updated function list parser file in this PR that **should** work correctly (by defining everything between the `interface` and `implementation` keywords as a comment). But currently this doesn't work because of the bug in C++ code I mentioned above. Additionally I will update _unitTest_ and _unitTest.expected.result_ files accordingly.

**Comment by donho** [comment]
@dinkumoil 
> No, it's the other way around, this PR brings some progress. However, commented out functions in the implementation section of a Pascal unit (using block comments) are erroneously included in the function list tree.

OK, then I will include the PR as it IS.
You're always welcome to be back for enhancing Pascal parser when you have free time.

**Pull request closed without merging**
