### PR TITLE
Remove Google Search

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Not positive if we need some UI positioning adjustments, feel free to edit this PR as needed for that, I tried to use a previous commit for inspiration. However, in light of censorship and human rights concerns, we should remove all unethical search engine companies:

Former Google human rights chief says he was ‘sidelined’ over censored Chinese search engine
https://www.theverge.com/2020/1/2/21046522/google-china-dragonfly-ross-lajeunesse-human-rights-chief-censorship

World’s Leading Human Rights Groups Tell Google to Cancel Its China Censorship Plan
https://theintercept.com/2018/08/28/google-china-censorship-plan-human-rights/

Amnesty says Google and Facebook threaten human rights
https://www.businessinsider.com/amnesty-google-and-facebook-business-models-threaten-human-rights-2019-11?op=1

Alphabet faces pressure from shareholders on human rights at annual meeting
("That proposal, as well as all other shareholder proposals presented Wednesday, was voted down by investors."
As a note, Larry Page and Sergey Brin hold 51% of the vote due to dual-class shares.)
https://www.cnet.com/news/alphabet-faces-pressure-from-shareholders-on-human-rights-at-annual-meeting/

Google urged to abandon Saudi cloud project
https://edition.cnn.com/2021/05/26/tech/google-saudi-arabia-cloud/index.html

Apple and Google named in US lawsuit over Congolese child cobalt mining deaths
https://www.theguardian.com/global-development/2019/dec/16/apple-and-google-named-in-us-lawsuit-over-congolese-child-cobalt-mining-deaths

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
It might also make sense to investigate other particularly ethical search companies that Notepad++ could add easy support for. Ecosia, maybe Startpage, and once it launches, Brave Search.

**Comment by ocdtrekkie** [comment]
Is there an issue with the formatting of this submission? Or is there a difference between censorship from Google and censorship from Microsoft?

**Comment by sasumner** [comment]
>Is there an issue with the formatting of this submission?

The only thing I can think of is that the protocol is: issue first, then PR

**Comment by NathSoM** [comment]
why has this been closed? if bing gets removed, it only makes sense to remove google too, since they are way worse in terms of censorship

**Comment by sasumner** [comment]
>why has this been closed?

Author of the software closed it.
Seems a final word to me.

**Comment by MarkDeckert** [comment]
Whataboutism at its finest

**Pull request closed without merging**
