### PR TITLE
Add "Fold All" toolbar command in Folder As Workspace

### PR DESCRIPTION
**Pull request by donho**

### CODE REVIEW

**Comment by xylographe** [comment]
Nice complement to the AIM button!

**Comment by SinghRajenM** [comment]
A try was given to implement something similar (**not the fancy button, but functionality wise same**) exactly 3 years back. But it was rejected saying `I don't think this feature is useful for a lot of users.` https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2266

Now, suddenly it became useful. Interesting!!!

**Comment by donho** [comment]
@SinghRajenM  

The "Select/show current editing file" feature makes this feature more value. And GUI part does it as well. A good feature is not just a feature, it's the whole solution.
BTW, it's not at all the same implementation - this one is more compact and more consistent.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c8b70dacd7a25642c336b560194ab99cb7279b18
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e0d995c1a6a045c8effb9f412325ba14f0d329d1

**Pull request closed without merging**
