### PR TITLE
DlgProc returns INT_PTR and not BOOL.

### PR DESCRIPTION
**Pull request by NN---**
Use correct prototype and remove casts.
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms645469(v=vs.85).aspx

### CODE REVIEW

**Comment by ariccio** [comment]
Eek! Merge conflicts!

**Comment by NN---** [comment]
No conflicts :)

**Comment by donho** [comment]
I'm quite sure that DlgProc did (in old VS version) return BOOL but not INT_PTR, and both BOOL and INT_PTR are typeof int. But indeed it'll be safer to change it, in order to pass to 64 bits.

**Comment by NN---** [comment]
Interesting , I guess you are right.
In any case it is essential for 64bit.

**Pull request merged**
