### PR TITLE
Update Bulgarian localization

### PR DESCRIPTION
**Pull request by rddim**
* follow up https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5483ad13d0d580b7858176032819582d9daccc10

### CODE REVIEW

**Comment by donho** [comment]
Sorry for this change. Could you add a new commit for the modification of https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ffda03c41c660d255bffb0488cfaf8af4ea7fd46 ?

**Comment by rddim** [comment]
Yes, I've just edit and check it. Please, check my comment on it. Also line Line `1258` `<edit-verticaledge-nb-col value="Nb of Column:"/>` is not needed, but I can not add a comment on it.

**Comment by donho** [comment]
`<Item id="6213"` should be kept. 
I just fixed it: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3474b8b11ed2aab10bec8e72e277705a66eef141

Thank you for the heads up.

**Comment by donho** [comment]
FYI: I'll do a release in 2 hours

**Comment by rddim** [comment]
@donho 
Done

**Comment by donho** [comment]
Thank you @rddim

**Pull request closed without merging**
