### PR TITLE
[xml][force xml] Switch to Python311-x64

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Looks like Python was update and we have a problem with `lxml` package:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45673917
Or maybe `lxml` was update? We are using a specific version `Python310`. 

I use `--use-pep517` but still build faild:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45674624

On this PR I use prebuild `lxml` provided on the website project (anyway it's marked as unofficial):
https://lxml.de/installation.html
https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

Something like this works, but...

@alankilborn @pryrt 
Any tips how to do a proper build via pip? What's missing here?

### CODE REVIEW

**Comment by ArkadiuszMichalski** [comment]
Last working log:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45671050
```
Collecting lxml
  Downloading lxml-4.9.1-cp310-cp310-win32.whl (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 19.0 MB/s eta 0:00:00
```

I don't know where exactly this `.whl` file was located. There are no files for MS on the project page (even for earlier versions):
https://github.com/lxml/lxml/releases

Ohh I see it:
https://pypi.org/project/lxml/4.9.1/#files

**Comment by ArkadiuszMichalski** [comment]
Last commit passed. Any objection for migration to Python311-x64?

**Comment by ArkadiuszMichalski** [comment]
@donho 

It needs to be merged because since yesterday the xml tests will not pass.

**Comment by donho** [comment]
> It needs to be merged because since yesterday the xml tests will not pass.

@ArkadiuszMichalski 
Why and how come "since yesterday"?

**Comment by ArkadiuszMichalski** [comment]
@donho 
Yesterday `lxml` was update from 4.9.1 to 4.9.2, but pypi.org published `.whl` file only for Python-x64, that's why in another PR I had a problem with the XML tests. Today `.whl` was published also for Python-x32, so the problem is gone.

But still might be worth going to Python311-x64 anyway, it seems to have a higher priority than 32-bit. And we use it also in other place like [Plugin List](https://github.com/notepad-plus-plus/nppPluginList/commit/7879bb8810b0c49fdd972720e263a20c2ab1f5fe).

>For Python, do we install on the fly from the official site of Python?

Yes, we use official https://pypi.org/. Finally in this PR I only changed the python version, the rest is unchanged.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbe70f55a6fc7814819e35b674df15d999345ed5

**Pull request closed without merging**
