### PR TITLE
Minor performance tweaks

### PR DESCRIPTION
**Pull request by dail8859**
A few small commits to address some minor tweaks. It isn't easy to create an issue for this PR, so hopefully it can be discussed here.

* 7d3b54e - Scintilla has built in commands to move lines up/down, so this takes advantage of them which I'm sure is a bit more efficient since Scintilla can do it all at once internally instead of multiple calls to `currentLineUp()` etc. 
* d9190d0 - Some checks can be skipped since `SCI_GETSELECTIONSTART` is always the lesser of the two selection endpoints.
* 3b39bc2 - ~~When selecting a section of text Notepad++ would copy the *entire* selection to count the characters (this can spike memory when editing large files) -- Scintilla can do it internally with the [`SCI_COUNTCHARACTERS`](http://www.scintilla.org/ScintillaDoc.html#SCI_COUNTCHARACTERS) command. **NOTE:**  I've tested this as much as possible but I am not very familiar with the various character encodings,  so hopefully someone can verify this works with different encodings.~~ Removed due to Scintilla bug.

### CODE REVIEW

**Comment by dail8859** [comment]
Hmm, looks like 3b39bc2 may want to be skipped for now since Scintilla had a [bug](http://sourceforge.net/p/scintilla/bugs/1757/) that wasn't fixed until 3.6.1

**Comment by KamranMackey** [comment]
@dail8859 and what version of Scintilla does Notepad++ use?

**Comment by dail8859** [comment]
3.5.6

**Comment by donho** [comment]
@dail8859 could you reverse only 3b39bc2 then?

**Comment by dail8859** [comment]
@donho PR updated with just the 2 commits.

**Comment by donho** [comment]
Thank you @dail8859

**Comment by vgturtle127** [comment]
Switching to using more built-in Scintilla stuff will also make it more portable too! :smile:

**Pull request closed without merging**
