### PR TITLE
Enhancement: Make readonly tab identifiable even if tab is not active

### PR DESCRIPTION
**Pull request by SinghRajenM**
Fixes: #4492, #3170

image

### CODE REVIEW

**Comment by donho** [comment]
It's very clear about the indication. However the style of icon has changed completely - which doesn't go with the others at all. Hence this PR is not accepted.

**Comment by sasumner** [comment]
NIHS?

**Comment by SinghRajenM** [comment]
@sasumner 
> NIHS?

What? I'm hearing this abbreviation first time. 😉

**Comment by SinghRajenM** [comment]
@donho ,
You're right, but you're looking at one side of coin. We already have icon for monitoring which also does not go with others at all. And I felt, lock icon would be best to suit this, so it was used.

Anyway, the idea was to differentiate the readonly tab which should be taken somehow. Thanks!

**Comment by sasumner** [comment]
What does "not go with the others at all" mean?  This is a ridiculous reason for rejection. @SinghRajenM , why would you ever bother to do another PR on Notepad++ code?  Expend your efforts elsewhere, where they might be appreciated.

**Comment by SinghRajenM** [comment]
> What does "not go with the others at all" mean? This is a ridiculous reason for rejection. @SinghRajenM , why would you ever bother to do another PR on Notepad++ code? Expend your efforts elsewhere, where they might be appreciated.

@sasumner  yes sometime, it demotivates. I also felt the same as you. Not only this, but there are around 60 PRs (mine are 8~10) PRs are ready to merge, but still pending. Many of PRs got reject because of the amount of code change stating more code changes are prone to error/regression. This kind of attitude in software industry is not good at all. People's effort should be valued. 

@chcg asked me to look into file association issue #4595 . I was knowing these issues and fix for those already, but just to avoid wastage of time, I didn't paid much attention. But when @chcg asked, I look on those issues again and submitted the PR. But what after that? No response, no feedback, I would say not even reviewed.

I remember the case of @Rikk and why he left this community.

If we look at the bug tracker, as on today (06, dec, 2018) there are 2400 bugs reported. If we exclude duplicate or invalid cases , still around 1500 bugs can be seen which is not a good sign for a popular software. Instead of providing less valued features (e.g. doc peeker while we already have document map in place, Tools->MD5 etc.), some time should be spent to clear bug list as well. I'm not against new features, but meanwhile bug-fixes and enhancement also should be considered.

The only motivation have is: I would like to improve the software which I use daily basis and I love to code.

**Comment by chcg** [comment]
@SinghRajenM Hm, but which PR is releated to 4595? It is not referenced there.

Anyhow just donho is doing the work here and my feeling is that the inflow is a little bit to much for just one guy not working fulltime on it. Or maybe even too much for just one in fulltime.
And I guess a bug only mode with feature requests/enhencements/etc. are not rejected immediately to reduce the current amount of issues might be ok for a profit project but as this is just spare time the focus is probably more driven by current interests as user needs/problems. 
As my part is just https://github.com/notepad-plus-plus/nppPluginList I try to sort and classify things here.
I think some maintainer for various areas of N++ would be helpful as e.g. normal translation PR merges might be also done by someone else apart from donho with some multi-language background.

**Comment by SinghRajenM** [comment]
@chcg just for your reference, #4595 is from windows side (I think starting from 1803). But other defects referenced in that defect (and many reported on community) are handled in #5000. This PR deals around 6~7 issues (may be more) from tracker and hot topic on community as well. So don't you think it is also users needs/problems.

So concern is not this PR. The actual concern is something else. For example, as @sasumner pointed, what is wrong with this PR? If you don't like it does not mean that other will not like. Others will like if it really makes a difference. Similarly plugin admin design is another thing which currently people are discussing a lot.

**Moral of story**: BOSS is not always ➡️. Sometimes he takes ⬅️ and tries to defend that it is ➡️. Unfortunately, everyone is trying to become BOSS.

**Comment by sasumner** [comment]
One thing for sure, though:  BOSS is always BOSS !  :-)

**Pull request closed without merging**
