### PR TITLE
Off-selection rclick in find-result windows should follow preference

### PR DESCRIPTION
**Pull request by sasumner**
Implements #8828

### CODE REVIEW

**Comment by donho** [comment]
@sasumner 
If I do understand, this PR makes Find result windows has the same behaviour as Main edit areas' ones, according `Keep selection when right-click outside of selection` is checked or not ?

**Comment by sasumner** [comment]
@donho 

>this PR makes Find result windows has the same behaviour as Main edit areas' ones

Yes, it was something I didn't consider originally.
It makes the behavior consistent.

**Comment by donho** [comment]
Find result windows uses also class `ScintillaEditView` so what you have done in ScintillaEditView's procedure is kept. I don't think we need to do somethings more to keep Find windows aligns with main edit zones.

**Comment by sasumner** [comment]
Closing due to not being needed.

**Pull request closed without merging**
