### PR TITLE
Fixed Obsidian theme bug (issue #364)

### PR DESCRIPTION
**Pull request by xates**
Fixed this bug https://github.com/notepad-plus-plus/notepad-plus-plus/issues/364

### CODE REVIEW

**Comment by xates** [comment]
Can I know why?

**Comment by gamax92** [comment]
Also curious why this was rejected, almost 2 years later this is still an issue. Opening Notepad++ with the Obsidian theme has the wrong font and size and this patch still fixes the issue.

**Comment by xates** [comment]
¯\_(ツ)_/¯

**Comment by reyandme** [comment]
Bug is still there, sad

**Comment by ner00** [comment]
In my case I found that I had permission issues with theme folders under AppData, there were more than one theme folder so I'm not sure which one was bad, but when I tried to delete the folders I didn't have permissions, which is weird, but overriding the permissions for AppData's `Notepad++/*` did the trick.

**Pull request closed without merging**
