### PR TITLE
Update japanese.xml to v7.8.9

### PR DESCRIPTION
**Pull request by yasmise**
Follow-ups for these changes:
* Add keyboard navigation ability to Column Editor (7d289139e8d370da422bd4a74f8c878e537db172)
* Add 'Searching' subpage to Preferences (84ea510b67dec193eee605a1cca723151ef80448)

### CODE REVIEW

**Comment by yasmise** [comment]
Add translations for these commits:
* Add search scope to Find window status bar output (5ba7f99590b6ade8a5fb13edc7cb9f9f0981e18f)
* Add an option to prevent right-click from canceling selection (f1b059414b95fa49c164adaa3cca4e11691bf789)
* Add ability to sort lines randomly (ca3d5147228b351b66b6af410faec195fdc9b938)

**Comment by yasmise** [comment]
Add a translation for this:
* Make (Find) dlgAlwaysVisible a true Preference setting (33f042932f0b9faf4b1fe899a6b76c6bfaa25f41)

**Comment by yasmise** [comment]
Add a translation for this commit:
* Add word-wrap option to find-results context menu (3a2edb99c40f5577a29307f1321d9a3cbe2a69cb)

**Comment by yasmise** [comment]
* Add translation for "Improve some ambiguous commands naming in Shortcut Mapper" (ddd2e5fd23412d5e8410c2a821461f1f578bca0f)
* Fix translation errors

**Comment by yasmise** [comment]
Add a translation:
* Add confirmation preference for Replace All in All Opened Documents operation (209ccb97ecaf3c16a66b8401d4c2a594576b0c66)

**Comment by yasmise** [comment]
* Follow up: Add keyboard shortcuts for switching to panels (0fe971ca8888f97f17381d1a5520a7b383eac617)
* Better wording for previous translation, in accordance to the commit above.

**Comment by yasmise** [comment]
Add a translation:
* Add back hovered blue underlined URLs (84430809df2f6607a3bc5b9f05866149842f2bd9)

**Comment by yasmise** [comment]
Follow up: Disable controls on unshown tabs of Find dialog (8f3d7c1026a20cdb1b07f1f2dd3b590cc1c04b5a)

**Comment by donho** [comment]
@yasmise 
Thank you for your update. 
Could you check the diff from v7.8.9 to the newest `english.xml` to make sure there's nothing's missing?
http://download.notepad-plus-plus.org/repository/MISC/diff/english.diff.htm

**Comment by yasmise** [comment]
@donho
I just checked and confirmed everything is up-to-date.

**Pull request closed without merging**
