### PR TITLE
Some more Debug Info

### PR DESCRIPTION
**Pull request by xomx**
Implement #15903 .

Adding:
+ Placeholders
+ DirectWrite
+ Multi-instance Mode
+ File Status Auto-Detection
+ Dark Mode

### CODE REVIEW

**Comment by xomx** [comment]
@ozone10 
Is there another one you'd like to see?
I'm considering some sort of Display Info there (e.g. number of monitors present, virtual screen rectangle, monitors enum with resolution and scaling, cur N++ mon).

**Comment by ozone10** [comment]
@xomx 
I am late :(
N++ is currently using only system scaling, so maybe only system dpi value should enough for now.

**Comment by donho** [comment]
@ozone10 
> N++ is currently using only system scaling, so maybe only system dpi value should enough for now.

There is nothing about dpi thing in added info. Or is it not right PR you were commenting?

**Comment by xomx** [comment]
@donho 
> There is nothing about dpi thing in added info. Or is it not right PR you were commenting?

This PR was a reaction to this @ozone10 suggestion: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15793#issuecomment-2474298926

I included also some other info, which I considered most relevant for a possible future users problems solving.

Then I asked him if he does not have any other suitable candidates, but you closed this PR before he could react.

I talked specifically about the possible Display Info because there are a lot of issues reported, which are related to this area (e.g. problems with the multi-monitors setups, HiDpi, etc.)

**Pull request closed without merging**
