### PR TITLE
Add PL/SQL to FunctionList

### PR DESCRIPTION
**Pull request by bernema1**

### CODE REVIEW

**Comment by MAPJe71** [comment]
Alternative:
```xml
			<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			|   Based on:
			|       https://notepad-plus-plus.org/community/topic/13393/function-list-and-pl-sql-packages
			\-->
			<parser
				displayName="PL/SQL - Procedural Language/Structured Query Language"
				id         ="plsql_syntax"
				commentExpr="(?x)                                               # free-spacing (see `RegEx - Pattern Modifiers`)
								(?s:\x2F\x2A.*?\x2A\x2F)                        # Multi Line Comment
							|	(?m-s:-{2}.*$)                                  # Single Line Comment
							"
			>
				<classRange
					mainExpr    ="(?x)                                          # free-spacing (see `RegEx - Pattern Modifiers`)
							(?im)                                               # case-insensitive, ^ and $ match at line breaks
							^\h*                                                # optional leading whitespace at start-of-line
							CREATE\s+(?:OR\s+REPLACE\s+)?PACKAGE\s+(?:BODY\s+)? # start-of-package indicator
							(?:(?&amp;VALID_ID)\.)?                             # schema name, optional
							(?'PACKAGE_ID'                                      # package name, use for back-reference
								(?'VALID_ID'                                    # valid identifier, use as subroutine
									\b(?!(?i:                                   # keywords (case-insensitive), not to be used as identifier
										A(?:L(?:L|TER)|N[DY]|SC?|T)
									|	B(?:E(?:GI|TWEE)N|Y)
									|	C(?:ASE|HECK|LUSTERS?|O(?:L(?:AUTH|UMNS)|MPRESS|NNECT)|R(?:ASH|EATE)|URRENT)
									|	D(?:E(?:CLARE|FAULT|LETE|SC)|ISTINCT|ROP)
									|	E(?:LSE|ND|X(?:C(?:EPTION|LUSIVE)|ISTS))
									|	F(?:ETCH|OR|ROM)
									|	G(?:OTO|R(?:ANT|OUP))
									|	HAVING
									|	I(?:DENTIFIED|[FNS]|N(?:DEX(?:ES)?|SERT|T(?:ERSECT|O)))
									|	L(?:IKE|OCK)
									|	M(?:INUS|ODE)
									|	N(?:O(?:COMPRESS|T|WAIT)|ULL)
									|	O(?:[FN]|PTION|R(?:DER)?|VERLAPS)
									|	P(?:R(?:IOR|OCEDURE)|UBLIC)
									|	RE(?:SOURCE|VOKE)
									|	S(?:ELECT|HARE|IZE|QL|TART)
									|	T(?:AB(?:AUTH|LE)|HEN|O)
									|	U(?:NI(?:ON|QUE)|PDATE)
									|	V(?:ALUES|IEWS?)
									|	W(?:HE(?:N|RE)|ITH)
									)\b)
									[A-Za-z][\w\x23\x24]{0,29}                  # valid character combination for identifiers
								)
							)
							(?s:.*?)                                            # whatever, until...
							^\h*END\s+\k'PACKAGE_ID'\s*;                        # ...end-of-package indicator
						"
				>
					<className>
						<nameExpr expr="(?i)PACKAGE\s+\K(?:BODY\s+)?(?:\w+\.)?\w+" />
					</className>
					<function
						mainExpr="(?x)                                          # free-spacing (see `RegEx - Pattern Modifiers`)
								(?im)                                           # case-insensitive, ^ and $ match at line breaks
								^\h*                                            # optional leading whitespace at start-of-line
								(?:FUNCTION|PROCEDURE)\s+
								\K                                              # discard text matched so far
								(?'VALID_ID'                                    # valid identifier, use as subroutine
									\b(?!(?i:                                   # keywords (case-insensitive), not to be used as identifier
										A(?:L(?:L|TER)|N[DY]|SC?|T)
									|	B(?:E(?:GI|TWEE)N|Y)
									|	C(?:ASE|HECK|LUSTERS?|O(?:L(?:AUTH|UMNS)|MPRESS|NNECT)|R(?:ASH|EATE)|URRENT)
									|	D(?:E(?:CLARE|FAULT|LETE|SC)|ISTINCT|ROP)
									|	E(?:LSE|ND|X(?:C(?:EPTION|LUSIVE)|ISTS))
									|	F(?:ETCH|OR|ROM)
									|	G(?:OTO|R(?:ANT|OUP))
									|	HAVING
									|	I(?:DENTIFIED|[FNS]|N(?:DEX(?:ES)?|SERT|T(?:ERSECT|O)))
									|	L(?:IKE|OCK)
									|	M(?:INUS|ODE)
									|	N(?:O(?:COMPRESS|T|WAIT)|ULL)
									|	O(?:[FN]|PTION|R(?:DER)?|VERLAPS)
									|	P(?:R(?:IOR|OCEDURE)|UBLIC)
									|	RE(?:SOURCE|VOKE)
									|	S(?:ELECT|HARE|IZE|QL|TART)
									|	T(?:AB(?:AUTH|LE)|HEN|O)
									|	U(?:NI(?:ON|QUE)|PDATE)
									|	V(?:ALUES|IEWS?)
									|	W(?:HE(?:N|RE)|ITH)
									)\b)
									[A-Za-z][\w\x23\x24]{0,29}                  # valid character combination for identifiers
								)
								(?:\s*\([^()]*\))?                              # parentheses and parameters optional
							"
					>
						<functionName>
							<funcNameExpr expr="\w+" />
						</functionName>
					</function>
				</classRange>
				<function
					mainExpr="(?x)                                              # free-spacing (see `RegEx - Pattern Modifiers`)
							(?im)                                               # case-insensitive, ^ and $ match at line breaks
							^\h*                                                # optional leading whitespace at start-of-line
							CREATE\s+(?:OR\s+REPLACE\s+)?(?:FUNCTION|PROCEDURE)\s+
							\K                                                  # discard text matched so far
							(?'VALID_ID'                                        # valid identifier, use as subroutine
								\b(?!(?i:                                       # keywords (case-insensitive), not to be used as identifier
									A(?:L(?:L|TER)|N[DY]|SC?|T)
								|	B(?:E(?:GI|TWEE)N|Y)
								|	C(?:ASE|HECK|LUSTERS?|O(?:L(?:AUTH|UMNS)|MPRESS|NNECT)|R(?:ASH|EATE)|URRENT)
								|	D(?:E(?:CLARE|FAULT|LETE|SC)|ISTINCT|ROP)
								|	E(?:LSE|ND|X(?:C(?:EPTION|LUSIVE)|ISTS))
								|	F(?:ETCH|OR|ROM)
								|	G(?:OTO|R(?:ANT|OUP))
								|	HAVING
								|	I(?:DENTIFIED|[FNS]|N(?:DEX(?:ES)?|SERT|T(?:ERSECT|O)))
								|	L(?:IKE|OCK)
								|	M(?:INUS|ODE)
								|	N(?:O(?:COMPRESS|T|WAIT)|ULL)
								|	O(?:[FN]|PTION|R(?:DER)?|VERLAPS)
								|	P(?:R(?:IOR|OCEDURE)|UBLIC)
								|	RE(?:SOURCE|VOKE)
								|	S(?:ELECT|HARE|IZE|QL|TART)
								|	T(?:AB(?:AUTH|LE)|HEN|O)
								|	U(?:NI(?:ON|QUE)|PDATE)
								|	V(?:ALUES|IEWS?)
								|	W(?:HE(?:N|RE)|ITH)
								)\b)
								[A-Za-z][\w\x23\x24]{0,29}                      # valid character combination for identifiers
							)
							(?:\s*\([^()]*\))?                                  # parentheses and parameters optional
						"
				>
					<functionName>
						<nameExpr expr="\w+" />
					</functionName>
				</function>
			</parser>
```

**Comment by chcg** [comment]
See #3393

**Comment by bernema1** [comment]
@MAPJe71 Was unable to get your alternate suggestion to work. With the spaces and tabs in the regex, I can't imagine that this could work. But it didn't work either when I removed them.

**Comment by MAPJe71** [comment]
@bernema1 Could you supply an example PL/SQL file that does not work for you?

FYI: the extra spaces and tabs are ignored by the RegEx engine due to the `(?x)` 'free spacing' option.

**Comment by bernema1** [comment]
@MAPJe71 Thank you for pointing out the blanks.
The delimitation of a package by specifying the package name is optional, which the regex does not take into account. For some of our files the parcer will work with it, for others it will not.
This doesn't work, for example.
`CREATE OR REPLACE PACKAGE PA_ZWS_PEDI IS 

  TYPE ARRAY_ANIMALID IS TABLE OF ANIMAL.IDANIMAL%TYPE INDEX BY VARCHAR2(12);

  PROCEDURE ins_animals (pnAnimalID IN NUMBER, pnFlag IN NUMBER);
  FUNCTION  nInsertPedigree(pnAnimalID IN NUMBER, pnFlag IN NUMBER) RETURN NUMBER;

  PROCEDURE set_codierung;

  PROCEDURE pedigree_rrtdm(psFilename       IN VARCHAR2 DEFAULT 'pedigree_rrtdm.dat'
                         , pnMandant        IN NUMBER DEFAULT 1
                         , pnExportBlood    IN NUMBER DEFAULT 1
                         , pnExportNameDame IN NUMBER DEFAULT 1
                         , pnIgnoreOKCode   IN NUMBER DEFAULT 0
                         , pnGenmarker      IN NUMBER DEFAULT 0
                         , pbNewItb         IN BOOLEAN DEFAULT TRUE);
                         
  FUNCTION aGetPseudotiere RETURN ARRAY_ANIMALID;

  FUNCTION  datGetDategeburtParent (pnIdAnimal IN NUMBER) RETURN DATE;

/***************************************************************************/
END;
/
show errors;`

To be able to distinguish between overloaded functions and procedures, I would like to have them displayed in the tree including the parameters.

**Comment by MAPJe71** [comment]
@bernema1 

>To be able to distinguish between overloaded functions and procedures, I would like to have them displayed in the tree including the parameters.

See previous post with alternative parser for updates to accomplish the requested distinction between overloaded functions and procedures.

**Comment by bernema1** [comment]
@MAPJe71 Modified the classRange so that specifying the package name at the end becomes optional. 
`							^\h*END(\s+\k'PACKAGE_ID'){0,1}\s*;                        # ...end-of-package indicator
`
However, the class range ends with the first END of a function or procedure. Is it possible to build the regex in such a way that the "matching" end is taken? Or just the last for the next package definition.

Where can I find a "guide" to customize the display of the functions/procedures so that they also have the parameters.

**Comment by MAPJe71** [comment]
>Where can I find a "guide" to customize the display of the functions/procedures so that they also have the parameters.

There's no guide. I thought I applied the necessary changes to the parser above. Applied the changes: extended `<functionName>` nodes with option to display function and procedures with or without parameters by adding an additional filter.

**Comment by melksem** [comment]
@MAPJe71 I can't get it to work for package bodies, as @bernema1 said, it matched the first "end" from any function/procedure instead the "end" of the package body.

The following package body just displays the first procedure/function in my case.
`create or replace package body my_pkg is
  function my_fct_001(p_id in number) return varchar2
  as
  begin
  end;
   
  procedure py_prc_001(p_id in number, p_text in varchar2 default null)
  as
  begin
  end;
  
end my_pkg;
/
`

Thanks in advance

**Pull request closed without merging**
