### PR TITLE
Move TreeView cpp and h files to different folder in project

### PR DESCRIPTION
**Pull request by sasumner**
See originating request https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9073#issuecomment-718792506

Not sure why github shows every line of the cpp/h files as a "diff", it clearly knows the files were simply moved/renamed:

```
On branch remove_some_unused_files_part2_XXXX
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        renamed:    PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp -> PowerEditor/src/WinControls/TreeView/TreeView.cpp
        renamed:    PowerEditor/src/WinControls/ProjectPanel/TreeView.h -> PowerEditor/src/WinControls/TreeView/TreeView.h

```

### CODE REVIEW

**Comment by donho** [comment]
I use the following command:
`git mv PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp PowerEditor/src/WinControls/`

Is it what you used ?

**Comment by donho** [comment]
@sasumner 
Here I use `git mv` to move TreeView.cpp, whereas TreeView.h was moved by drag&drop in Explorer: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9077

**Comment by donho** [comment]
So I guess you need to do another PR.
I see there's another build error so I let it open so you try here to fix another error.

**Comment by sasumner** [comment]
>Is it what you used ?

No, I moved the file with Explorer on my local drive, then "added" the change with `git rm` and `git add` for both files.

My PR fails the mingw build, which I can't test because after repeated askings there is still no build instructions.
I could guess at the change needed, but I don't like guessing.

Your 9077 may fail ALL 6 builds because the project file needs adjustment as well (include directory) when the files move.  See change with THIS PR for that.

**Comment by donho** [comment]
> Your 9077 may fail ALL 6 builds because the project file needs adjustment as well (include directory) when the files move. See change with THIS PR (second commit) for that.

It doesn't matter - it's just for show you github reacts differently between `git mv` & moving manually.

> My PR fails the mingw build, which I can't test because after repeated askings there is still no build instructions.
I could guess at the change needed, but I don't like guessing.

I agree. where is the ticket you created and assigned to me regarding this issue?

**Comment by sasumner** [comment]
>where is the ticket you created and assigned to me regarding this issue?

I made it really hard to find: 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue+is%3Aopen+mingw

:-)

**Comment by donho** [comment]
@sasumner 
It's compile now - I'm not sure if you can redo `git mv` in this PR to keep the history in both file.
If you can't, just do another PR.

**Comment by sasumner** [comment]
But will there be action on #7743 ?

**Comment by donho** [comment]
@sasumner 
Sure, I'll take in charge of it.

**Comment by sasumner** [comment]
@donho 

Thanks.  MUCH appreciated.
Don't forget to include details on where to obtain the toolchain, what version should be used,...

**Comment by sasumner** [comment]
@donho 

I'm not sure how to accomplish this. :-(

If I do this from command prompt:

```
C:\notepad-plus-plus\> dir /s/b treeview.cpp
```

it shows the file is there:

```
C:\notepad-plus-plus\PowerEditor\src\WinControls\ProjectPanel\TreeView.cpp
```

but if I do:

```
C:\notepad-plus-plus\> git mv PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp PowerEditor/src/WinControls/TreeView/TreeView.cpp
```

I get this error:

```
fatal: renaming 'PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp' failed: No such file or directory
```

So barring a typo that I just don't see, I'm stuck on making this happen.

**Comment by donho** [comment]
I think that you have to create a new branch, then use the following commands:
```
git mv PowerEditor/src/WinControls/ProjectPanel/TreeView.h PowerEditor/src/WinControls/TreeView/
git mv PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp PowerEditor/src/WinControls/TreeView/
```

Let's make a new PR from this new branch.

BTW, do you use Git Bash or somethings similar?

**Comment by sasumner** [comment]
>I think that you have to create a new branch

I had done that on a new branch: `sasumner:remove_some_unused_files_part_2a_XXXX`
That's where I was getting that error.
I was just continuing to comment here because I wasn't able to create a new PR: after the error I got there weren't any changes to commit.

>do you use Git Bash or something similar?

Not quite sure exactly what I'm using.

`git --version` tells me I am using:  `git version 2.22.0.windows.1`

**Comment by donho** [comment]
@sasumner 
Try this one:
`C:\notepad-plus-plus\> git mv PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp PowerEditor/src/WinControls/TreeView/`
(without last "TreeView.cpp")

**Comment by sasumner** [comment]
@donho That worked.  I will create a new PR from my new branch.  And this should FINALLY BE FINISHED!  Wow.

**Pull request closed without merging**
