### PR TITLE
Fit accesskeys of the main menu to English behavior

### PR DESCRIPTION
**Pull request by Phroneris**
- Change an accesskey of `Encoding` from `&M` to `&N` just like english.xml
  (It seems like a relic of the days when it had been named `For&mat`. Watersheds can be seen [here](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cc875b2458db732f5234633f1567c58a01d72b61#diff-2a8496e2537c34b95cbeca007cd2346b) and [here](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5da5167b7d71ce7393a7e6ffffcb5c352a981087#diff-c9173bbe2e6128ab6cd2af6e2b5bf830))
- Add accesskeys to `Macro`, `Run`, `Plugins` and `Window` with their capitals
  (They originally don't have any accesskeys, but in English version they work with the Alt-key as if they have ones and in Japanese not)

### CODE REVIEW

**Comment by donho** [comment]
@yasmise Do you validate this PR ?

**Comment by yasmise** [comment]
@donho Yes, there is no problem with this PR. Many thanks @Phroneris !
I overlooked the change of accelerator key from `&M` to `&N`. This is a good catch.

Adding accelerator keys is another good catch, but this means that `english.xml` also misses these keys. I'm now checking whether GUI texts of Notepad++ are equivalent to english.xml. I'll open an issue soon.

**Comment by yasmise** [comment]
@donho I opened issue #4294. Could you take a look at that? Thanks in advance.

**Comment by Phroneris** [comment]
Oh, I didn't notice that some hard-coded menus like `Macro` have their accelerator keys. Perhaps I had checked only `english.xml`. Thanks for backing up.

**Comment by donho** [comment]
@Phroneris So I let you complete this PR before merging it.
Please let me know when you finish it.

**Comment by yasmise** [comment]
@donho Is it okay for you to merge this PR as it is? I mean, I started preparing japanese.xml to follow recent changes, so I can take care of the rest of this PR in my branch.

**Comment by Phroneris** [comment]
@donho I tried [updating my japanese.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...Phroneris:japanese) to fit to [yasmise's checks](https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...yasmise:acckey_update).
Then, I don't understand well because I'm a beginner of git and GitHub, how do I "complete this PR"? To close this and open another, or something else? Sorry for bothering.

And... though I noticed after I had done all, is my update overlapped with @yasmise's "take care of the rest of this PR"?
I'm pretty sorry if so...

**Comment by yasmise** [comment]
@Phroneris Thanks for your commits!
To complete this PR, you can just add commit(s) to opening branch (Phroneris:master) and push it. At this moment, your additional change was made on another branch (Phroneris:japanese), so it's impossible to merge that with this PR.
I think, you can fix this by merge branch (or just doing copy&paste your new file and commit) then push. Actually, there are some mistakes in your new commits, I will review after you push your commits here.

**Comment by yasmise** [comment]
@Phroneris I noticed that I can review your commits at this moment, so I left some comments in your commits. Could you fix them?

**Comment by Phroneris** [comment]
@yasmise Okay I will fix all, merge to master and push again. Thank you.

**Comment by Phroneris** [comment]
@yasmise @donho Done!

**Pull request closed without merging**
