### PR TITLE
Update german.xml to 7.8.7

### PR DESCRIPTION
**Pull request by schnurlos**
Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5483ad13d0d580b7858176032819582d9daccc10

### CODE REVIEW

**Comment by donho** [comment]
Sorry for this change. Could you add a new commit for the modification of ffda03c ?

**Comment by donho** [comment]
`<Item id="6213"` should be kept. 
I just fixed it: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3474b8b11ed2aab10bec8e72e277705a66eef141

**Comment by schnurlos** [comment]
@donho: done

**Comment by donho** [comment]
@schnurlos 
Sorry for bothering you again.
Please also add the following change:
93f7853

Thank you

**Comment by schnurlos** [comment]
@donho 
Done

**Pull request closed without merging**
