### PR TITLE
Use split button for find dlg swap/copy button

### PR DESCRIPTION
**Pull request by ozone10**
reorder controls for consistent tab switching
fix visual glitch for checkbox button focus rectangles

image
image
image
image

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13368
fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13021

### CODE REVIEW

**Comment by ozone10** [comment]
@Yaron10 
should be fixed.
Previously I used order left top to right bottom, with some exception for middle controls.

image

**Comment by Yaron10** [comment]
@ozone10,

Excellent! 👍 
Thanks again.

***

Allow me please an off-topic question. If you think it's possible, I'll open a new issue.

If the Find dialog has not been created, and you use `Select and Find Next` - the dialog is displayed for a split second.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5645ca150bf9b24813d5da7ee3a061e1306837d9/PowerEditor/src/NppCommands.cpp#L1329
Is it possible to create the dialog without the split second display?

Thank you.

**Comment by ozone10** [comment]
@Yaron10 
> Is it possible to create the dialog without the split second display?

Yes.

**Comment by Yaron10** [comment]
@ozone10,

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13381.

When you have some free time.
Thank you.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7e4b281b8abc34418028868cc80968b54b2b3740

**Pull request closed without merging**
