### PR TITLE
Hindi translation has been updated.

### PR DESCRIPTION
**Pull request by vkdinventor**
I have changed some words to their correct Hindi translation.

### CODE REVIEW

**Comment by donho** [comment]
@SinghRajenM  Do you approve these modifications?

**Comment by SinghRajenM** [comment]
These modifications looks fine to me.
Actually, I had to plan to update whole translation again because - 
1. Translation for many words/sentences are still missing
2. Few items go beyond the specified length.
3. Few are wrongs as well.

@vkdinventor may I ask you to revise whole file again considering above cases?
Also avoid tough translation (e.g. foe encoding -> एन्कोडिंग still looks better than संकेतीकरण)
Screenshot contains few items, there are many more.

hindi_lang

**Comment by vkdinventor** [comment]
@SinghRajenM  I will translate the whole file again and will try to use user friendly Hindi words.

**Comment by donho** [comment]
@vkdinventor @SinghRajenM  Then please add your commits here. I'll merge them once it's finished.

**Comment by donho** [comment]
So which one should I take? #2375 or this one?

**Comment by SinghRajenM** [comment]
As there was no update for long time. So I decided to update the whole xml myself. I have made all the required change in PR #2375. Please consider #2375 .

**Comment by vkdinventor** [comment]
@donho you can consider #2375 as it is complete. In #2304 translation of some words are still missing.

**Pull request closed without merging**
