### PR TITLE
Dynamic number of styles and languages

### PR DESCRIPTION
**Pull request by ivan-u7n**
As mentioned at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10454 to proper fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10206 but without any compile-time constant.

So now there may be any number of lexers having any number of styles independently of each other. Here is the showcase: 
image

EDIT: This is my first experience with git, so there are little more commits than strictly necessary.

### CODE REVIEW

**Comment by chcg** [comment]
@ivan-u7n You can squash the commits to a single one with git, see e.g. https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

**Comment by donho** [comment]
> You can squash the commits to a single one with git, see e.g. https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

No problem. I can use `git rebase -i` if this PR will be merged into master.

**Comment by ivan-u7n** [comment]
Oops, I think I messed things a little bit with my attempt to squash all commits into one. Although I hope nothing serious happened.

**Comment by ivan-u7n** [comment]
@donho It seems that despite the messy changeset, it nevertheless compiles and is ready for review. Is it necessary to make a clear one or this one will do?

**Comment by ozone10** [comment]
@ivan-u7n 
PR seems to contain commit from master, its quite messy. I would do new PR but it depends on you.

Next time you can do this when updating your local repository with upstream:
1. `cd ` to your local repository
2. `git remote add upstream https://github.com/notepad-plus-plus/notepad-plus-plus.git`
3. `git fetch upstream`
4. `git rebase upstream/master`
5. do some changes, add, commit and push
6. `git push origin HEAD`, sometimes you may need `git push origin HEAD --force`

**Pull request closed without merging**
