### PR TITLE
Update czech.xml translation to v7.5.5

### PR DESCRIPTION
**Pull request by xomx**

### CODE REVIEW

**Comment by donho** [comment]
@xomx Could you check the newest updated english.xml here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

which has been updated by this commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bd0867ee62b115b5f485abd8791da775c001ff8d

**Comment by xomx** [comment]
Ok, hopefully I have found all the english.xml corrections.

**Comment by donho** [comment]
@xomx  Please just make sure that all updated strings have been translated in czech.xml

**Comment by xomx** [comment]
Done.

**Pull request closed without merging**
