### PR TITLE
Synchronize VS2015 project

### PR DESCRIPTION
**Pull request by NN---**
Fixed PR #990

### CODE REVIEW

**Comment by donho** [comment]
Fixed PR #990 ?

**Comment by NN---** [comment]
@donho  I rebased and made one commit as was suggested.

**Comment by donho** [comment]
@NN--- The suggestion was for me I think. 
That says, what is done is done. It's not necessary to remerge for making a "pretty" commit.

**Comment by NN---** [comment]
@donho I see :)
Can you merge it ?
Thanks

**Pull request closed without merging**
