### PR TITLE
Mingw GCC update

### PR DESCRIPTION
**Pull request by chcg**
- changes necessary to get back to a buildable version with mingw, after last adaptation with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1229
- fixed some gcc compiler errors and warnings, see https://ci.appveyor.com/project/chcg/notepad-plus-plus/build/1.0.3 to https://ci.appveyor.com/project/chcg/notepad-plus-plus/build/1.0.13
- remaining task is the wincontrol "ReadDirectoryChanges", which uses ATL, propably not available with mingw 
  @donho 
- what is your preference here, maybe it is easier to switch off this feature by ifdef mingw, than to adapt the control. I created a buildable version, which remove the dependency to ATL and replaced most parts by c++11 equivalents, but that is quite intrusive, see https://github.com/chcg/notepad-plus-plus/commits/mingw_gcc/PowerEditor/src/WinControls/ReadDirectoryChanges and not really tested for maybe newly introduced issues
- should a build target for mingw(, see https://www.appveyor.com/docs/installed-software/#mingw-msys-cygwin) be added to appveyor?

### CODE REVIEW

**Comment by evpobr** [comment]
> remaining task is the wincontrol "ReadDirectoryChanges", which uses ATL, propably not available with mingw

Yes, MinGW doesn't have ATL.

**Comment by donho** [comment]
@chcg 
> remaining task is the wincontrol "ReadDirectoryChanges", which uses ATL, propably not available with mingw

So the makefile doesn't compile at all, does it?

**Comment by chcg** [comment]
@donho 
With just this PR build fails with:

In file included from ../src/NppIO.cpp:36:0:
../src/WinControls/ReadDirectoryChanges/ReadDirectoryChanges.h:46:21: fatal error: atlbase.h: No such file or directory
compilation terminated.
makefile:260: recipe for target '../src/NppIO.o' failed
mingw32-make: *** [../src/NppIO.o] Error 1
Command exited with code 2

After:
- replacement of ATL CStringW by generic_string
- replacement of CComCritSecLock<CComAutoCriticalSection> by std::unique_lock<std::mutex> 
- replacement of microsoft compiler specific __super by typedef
- replacement of _ASSERTE by assert
- removal of SAL annotation __in in two method definition, which can't be easily avoided by empty define in various.h

this config also compiles. Also still multiple warnings occur and I havn't tested the mingw output, just slightly the one from VS compiler with this changes, which seems to be still usable.  
-

**Comment by marcows** [comment]
Why is this PR applied after a few days while mine #1663, which included all of these changes and more, is dangling for months?
There is not even an associated issue, which is mandatory according to the contribution guide.
This is duplicated effort, these fixes have been implemented since a long time.

**Comment by chcg** [comment]
@marcows
Unfortunately didn't see your closed PR.  Thanks for the hint.
Would be nice to team up and fix the remaining issues. I will have a look at your changes.
Maybe just luck or that this PR was a little bit smaller.

Maybe one reason for donho was that milipili wanna take care, but I didn't see any action from him the last few month. But in the end just donho knows.

**Comment by ganego** [comment]
So I just tried to compile it with mingw. I applied all your patches from [HERE](https://github.com/chcg/notepad-plus-plus/commits/mingw_gcc/PowerEditor/src/WinControls/ReadDirectoryChanges)

Now I get this error: [On Pastebin to have better line breaks](http://pastebin.com/g5RqFajH)

**Pull request closed without merging**
