### PR TITLE
new theme based on Ruby Blue

### PR DESCRIPTION
**Pull request by airduv**
New theme based on Ruby Blue but started from DarkModeDefault.xml
It's a bit darker, I hope more fancier and more up-to-date than Ruby Blue (as the original Ruby Blue missed several languages and latest theme improvements)

### CODE REVIEW

**Comment by alankilborn** [comment]
@airduv User-supplied themes aren't likely to get accepted.  Just so you know.

**Comment by alankilborn** [comment]
@donho @pryrt Any plans for a "user supplied themes" repo similar to the UDL repo?  If so then I think this would be the proper location for @airduv 's effort in this PR.

**Comment by donho** [comment]
> @donho @pryrt Any plans for a "user supplied themes" repo similar to the UDL repo? If so then I think this would be the proper location for @airduv 's effort in this PR.

@pryrt  what do you think about the suggestion of @alankilborn ?

**Comment by pryrt** [comment]
I think having a theme repo would be easier to maintain than having users submit new themes to the main repo.

If you created the repo, I could rework the CONTRIBUTING and README  based on the UDL version

**Comment by vinsworldcom** [comment]
> I think having a theme repo would be easier to maintain than having users submit new themes to the main repo.

To go a step further, maybe removing all but the Dark Theme from the themes directory in Notepad++ distributions and letting users install themes from a repo.  Not that they would be anymore up-to-date if they are neglected there, but it maybe makes managing Notepad++ repo itself and pull requests to it easier? 

Just a thought ...

Cheers.

**Comment by alankilborn** [comment]
@vinsworldcom It is a good idea, except it requires that "extra step" of an additional download for those that might want to quickly try out a theme, or even quickly understand what is meant by the term "theme".  It might be a good thing to keep some themes bundled with Notepad++ and then let users know there is a place where they can download more from. like UDL does on the _Language_ menu:

image

I envision a "Notepad++ Themes Collection" link, perhaps close to here:

image

or here:

image

**Comment by pryrt** [comment]
Like @alankilborn , I think keeping the existing themes in the main app is best idea.  And for the additional themes, adding a link to the repo like the existing UDL link is a great idea.

**Comment by donho** [comment]
I'm rather on the same page with @alankilborn & @pryrt 
Let's do it this way.

**Comment by donho** [comment]
@airduv 
Could you close this PR, and do a new PR on:
https://github.com/notepad-plus-plus/nppThemes
please?

**Pull request closed without merging**
