### PR TITLE
Fix slow tab switching of folded XML (Issue #236 & #329)

### PR DESCRIPTION
**Pull request by BrainJelly**
Resolved slow tab switching of an folded XML file by deleting the SCNotification code that causes a recursion. 
:)

### CODE REVIEW

**Comment by BrainJelly** [comment]
To replicate this issue:
- Load an XML file like this one: https://gist.github.com/BrainJelly/e488d999bd477b0234a0
- Code fold the XML [Alt + 0]
- Switch to a different tab and notice how NPP goes off into the weeds

**Comment by MAPJe71** [comment]
So any code depending on the folding-state-changed-notification will no longer function after merging this change?

**Comment by BrainJelly** [comment]
That is a good question.
I am not sure what code depends on the folding-state-changed-notification.
I have been running a versions of NPP without these lines of code for years and I have not noticed any issues and NPP functions correctly.
The recursion that these lines of code cause seems to be unnecessary.

**Comment by MAPJe71** [comment]
The fact that you have not noticed any issues leaving out the code does not mean somebody else won't.
The notification has been added for a reason, do not remove it.
Prevent the notification to result in recursion when that's the cause of the slow tab-switch.

**Comment by BrainJelly** [comment]
Yea that is the pragmatic view point.
I will see if I can figure out how to prevent the recursion.
:smile:

**Comment by BrainJelly** [comment]
It took a bit to track down, but I think I found the correct answer.
I added the notification code back.
I found where a the **_isFolding** flag was being set to ignore events while folding is taking place.
I added the same flag to when switching to a new tab.
If I do say so myself, I think this is a better solution.
Thank you
:smile:

**Comment by MAPJe71** [comment]
:+1:

**Comment by BrainJelly** [comment]
This pull request would resolve this bug from SourceForge http://sourceforge.net/p/notepad-plus/bugs/5168/
:smile:

**Comment by dail8859** [comment]
Might be nice to squash the commits. Keeps the history cleaner instead of adding code changes just to immediately undo them.

**Comment by BrainJelly** [comment]
Thanks dail8859 :smiley:

**Comment by BrainJelly** [comment]
I found that when you delete a tab and the next tab has folded XML, the same issue is happening.
I added the _isFolding flag around this situation to resolve this.
:smile:

**Comment by aml11** [comment]
Built in Windows, fixed the issue for me and a few others, Thanks!

**Comment by NN---** [comment]
@donho Please accept this PR , without it Notepad++ hangs all the time.

**Comment by BrainJelly** [comment]
Hello @milipili and @donho ,

I have pushed a new version of my PR to rebase it with latest commit.
Can you please take a look at it?
I have been waiting 3 months, since I first submitted this PR, for it to be merged. 
Please, let me know if there is something I need to do.
Thanks
:smile:

**Comment by donho** [comment]
Sorry for not seeing your PR, it'll be merged as soon as possible.

**Comment by donho** [comment]
done:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f02e567c9eccade8b56d372b2865788e0651f8a2

**Pull request closed without merging**
