### PR TITLE
[Installer] Improve configurability of shortcuts creation

### PR DESCRIPTION
**Pull request by vlakoff**
* If user is admin: allow choosing (default: create for all users).
* If user is not admin: hide controls, create for current user.

### CODE REVIEW

**Comment by vlakoff** [comment]
UI has to be improved a bit…

installer-shortcuts

**Comment by vlakoff** [comment]
Ahhhh, much better:

installer-shortcuts-v2

**Comment by vlakoff** [comment]
It _seems_ to work, though some reviews would be greatly appreciated.

A further improvement could be to remember controls' states when navigating page back and forth again.

**Comment by donho** [comment]
This feature might be interesting for few people for taking risk of regression of installer.

**Comment by vlakoff** [comment]
I have managed to craft a fully functional page (including the "restore state" feature), and with code actually robuster than the current one.

But agree with keeping the code of this page as simple as possible. Even the "restore state" feature alone (just for the 2 checkboxes of the current page) significantly increases the code complexity.

**Pull request closed without merging**
