### PR TITLE
GUI Enhancement: Preference General & Editing

### PR DESCRIPTION
**Pull request by ozone10**
- increase width for some items for translation
- make translation consistent between source and xml files
- reorder items for consistent tab focus

image
image

ref https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13627
ref https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0cad36d636aaa517f8fd50bdc171f6fa01181a38#r108675058

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13657
fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13676

### CODE REVIEW

**Comment by rddim** [comment]
@ozone10 
Thanks for the `increase width for some items for translation`

Could you fix also `Settings` > `Preferences...` > `Auto-Completion` > `Ignore numbers` please

npp

**Comment by donho** [comment]
@ozone10 
Please rather do this way:

image

**Review by donho — COMMENTED** [review]
1. Use `Hide` of "**Status Bar**" instead of `Show`
2. Swap the position of "**Current Line Indicator**" & the one of "**Non-printing characters**"

**Review by donho — CHANGES_REQUESTED** [review]
1. Use `Hide` of "**Status Bar**" instead of `Show`
2. Swap the position of "**Current Line Indicator**" & the one of "**Non-printing characters**"

**Pull request closed without merging**
