### PR TITLE
Update japanese.xml to v8.4.8

### PR DESCRIPTION
**Pull request by yasmise**
Add translations for these commits:
* Add localization for Length label in the Customize Maximum Length popup (bc1487881ab15f3d5e5bc6c3fb06ff8168b5fdea)
* Update localization files (11ccc415e71cdd3674dac2595479302452965121)
* Fix localization files (3fcad98883bd719b6be63f234648f5712018548f)
* Fix inconsistencies at OS-forced Notepad++ (v8.4.7) exit (bd4c323d75bbe9a565e9bc31bb522133d78421a6)
* Make tab context menu customizable (aa8ae48b9946d0a26b1e51564246bb1dc981a827)

Also some fix to remove useless space characters.

### CODE REVIEW

**Comment by donho** [comment]
@yasmise 
Please add `[xml]` on the beginning of commit title next time, if the PR is about translation, and only xml file(s) is (are) modified.
Ex: `[xml] Update japanese.xml to v8.4.8`

**Comment by donho** [comment]
@yasmise 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

**Comment by yasmise** [comment]
@donho
I've confirmed it's ready to go. Thank you.

**Comment by donho** [comment]
Thank you @yasmise !

**Pull request closed without merging**
