### PR TITLE
Add Hollywood support

### PR DESCRIPTION
**Pull request by afalkenhahn**
Lexilla already has a lexer for the Hollywood programming language but apparently Notepad++ doesn't support this yet. This PR adds support for the Hollywood programming language in Notepad++ and also includes all the language keywords as well as core and plugin APIs and the regex for the function lister. I've tested everything and it's working.

### CODE REVIEW

**Review by donho — CHANGES_REQUESTED** [review]
1. Adding new function list xml file needs to add unit-test file(s). Please see: https://npp-user-manual.org/docs/function-list/#unit-tests
2. Please solve the conflict. (and squeeze the commit into 1 then force push)

**Comment by schnurlos** [comment]
Just a comment: is it no. 86 or 87?

**Comment by donho** [comment]
Ping @afalkenhahn 
Could you answer the demand & solve the request please?
Otherwise, the PR will close in 1 week.
Thank you.

**Comment by afalkenhahn** [comment]
I'll fix that very soon. I'm currently very busy with other things but will get back to this shortly.

**Comment by afalkenhahn** [comment]
Alright, I've updated the PR with a unit test. But what about the language IDs? Aren't they wrong in master? GDScript uses an ID of 88 in `overrideMap.xml` but in `menuCmdID.h` GDScript's ID is 87. Isn't that wrong?

**Comment by donho** [comment]
@afalkenhahn 
> GDScript uses an ID of 88 in `overrideMap.xml`

It's error in the comment, please modify GDScript's value to 87, and take value 88 for Hollywood.

**Comment by donho** [comment]
@afalkenhahn 
FYI: `AppVeyor was unable to build non-mergeable pull request `

Maybe redo a new PR is easier for both of us?

**Comment by afalkenhahn** [comment]
@donho 
> It's error in the comment, please modify GDScript's value to 87, and take value 88 for Hollywood.

I was talking about the Notepad++ master branch. I think GDScript IDs are wrong in the master branch, cf.

in `functionList/overrideMap.xml` and `filesForTesting/overrideMap.xml` we have this:
`<association id= "gdscript.xml"  	 langID= "88"/>`

But in `menuCmdID.h` we have this:
`#define    IDM_LANG_GDSCRIPT           (IDM_LANG + 87)`

Shouldn't that be fixed in master?

> Maybe redo a new PR is easier for both of us?

Ok, I'll do that as soon as I know which ID to use for Hollywood...

**Comment by afalkenhahn** [comment]
@donho 

Oops, sorry, not a problem in master. Obviously the language IDs used in the XML refer to the `enum LangType` and not to the `IDM_LANG_` definitions. I'll push a new PR soon.

**Comment by afalkenhahn** [comment]
Ok, here is the new PR: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13417

**Pull request closed without merging**
