### PR TITLE
Encoding Menu : add new options UCS-2 BE and UCS-2 LE

### LINKED ISSUE #5899: Encoding Menu - missing option
### Description of the Issue
In encoding menu it missing the following options:
- Encode in UCS-2 BE
- Encode in UCS-2 LE
- Convert to UCS-2 BE
- Convert to UCS-2 LE

### Steps to Reproduce the Issue

Open Encoding Menu

### Expected Behavior

FixAndAddEncoding_missing

### Actual Behavior
actual

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll PythonScript.dll

### PR DESCRIPTION
**Pull request by Cyrillev91**
Hi,

Fix #5899
Add option in Ecoding Menu:
- Encode in UCS-2 BE
- Encode in UCS-2 LE
- Convert to UCS-2 BE
- Convert to UCS-2 LE

1st Commit is PR #3836 (required to add new options)
2nd Commit add options (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5900/commits/7b7d0bd8b2a8aa2732170fd09a7d80db8dcecafc)

FixAndAddEncoding_missing

### CODE REVIEW

**Comment by chcg** [comment]
Further infos: https://en.wikipedia.org/wiki/UTF-16#Byte_order_encoding_schemes

**Comment by Cyrillev91** [comment]
conflict resolved

**Comment by MalcolmFinlayson** [comment]
This issue addresses 5899. Close notepad-plus-plus/notepad-plus-plus#5899

**Comment by Cyrillev91** [comment]
conflict resolved
@chcg UCS-2 become UTF-16 thank you

**Comment by Cyrillev91** [comment]
To test (automatic test with PythonScript)

[TestEncodeFile.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4975638/TestEncodeFile.zip)

Setup
```
0. unzip expected file (TestEncodeFile.zip) in C:\Code\npp_encode\ (For example)
TestEncodeFile.zip contain files : ANSI.txt, UTF-8_BOM.txt,  UTF-8.txt, UTF-16-LE_BOM.txt, UTF-16-LE.txt, UTF-16-BE_BOM.txt, UTF-16-BE.txt
all file containt text "A°’" but the encode is different (the name of file is the endode used in file)
all sub folder contain expexted file when we use Encodind >> Convert to xxxx (create by _createExpectedFile.bat)


1. open notepad++ (including PR5900 : https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5900)
2. install PythonScrip plugins
3. create a new script : Plugins >> Python Scrip >> New Script
4. copy and past Script and save as TestConvertToEncode.py
5. change directory (lines 3 and 4) : "C:\\Code\\npp_encode\\TestEncodeFile\\" For example
```

To test Encoding >> Convert To xxx
```
1. open notepad++
2. RunScript : Plugins >> Python Scrip >> Scrips >> TestConvertToEncode
3. compare all file in "Convet To xxx" folder with expected files (TestEncodeFile.zip) (git status)

```

To test encode (display)
```
open all file in C:\Code\npp_encode\TestEncodeFile (root not sub folder)
check display of all file : A°’
note : for UTF-16-BE.txt clic on Encoding >> UTF-16 BE then chek display

```


TestConvertToEncode.py
```
import time 
filesList = ["ANSI.txt", "UTF-8_BOM.txt",  "UTF-8.txt", "UTF-16-LE_BOM.txt", "UTF-16-LE.txt", "UTF-16-BE_BOM.txt", "UTF-16-BE.txt"]
inputDir = "C:\\Code\\npp_encode\\TestEncodeFile\\"
outputDir = "C:\\Code\\npp_encode\\TestEncodeFile\\"

cmdEncodeInList = ["ANSI", "UTF-8", "UTF-8 BOM", "UTF-16 BE", "UTF-16 BE BOM", "UTF-16 LE", "UTF-16 LE BOM"]
# for npp 7.8.9 with PR 5900
cmdConvertToInList = ["Convert to ANSI", "Convert to UTF-8", "Convert to UTF-8 BOM", "Convert to UTF-16 BE", "Convert to UTF-16 BE BOM", "Convert to UTF-16 LE", "Convert to UTF-16 LE BOM"]


for command in cmdConvertToInList:
    time.sleep(1)
    for file in filesList:
        notepad.open(inputDir+file)
        if file == 'UTF-16-BE.txt':
            notepad.runMenuCommand('Encoding', 'UTF-16 BE')
        # time.sleep(1) 
        notepad.runMenuCommand('Encoding', command)
        # time.sleep(1) 
        notepad.saveAs(outputDir + command + "\\" + file + "_" + command + ".txt")
        # time.sleep(1) 
        notepad.close()
        # time.sleep(1)



```

**Comment by Cyrillev91** [comment]
For language file ( PowerEditor/installer/nativeLang/xxxx.xml)

```
45004 : no change
45005 : no change
45006 : replace UCS-2 by UTF-16  (UTF-16 BE BOM)
45007 : replace UCS-2 by UTF-16  (UTF-16 LE BOM)
45008 : no change

45009 : to renumber in 45900
45010 : to renumber in 45901
45011 : to renumber in 45902
45012 : to renumber in 45903 and replace UCS-2 by UTF-16 (UTF-16 BE BOM)
45013 : to renumber in 45904 and replace UCS-2 by UTF-16 (UTF-16 LE BOM)

add 
45014 : UTF-16 BE
45015 : UTF-16 LE

and add
45905 : Convert to UTF-16 BE
45906 : Convert to UTF-16 LE
```

**Comment by Cyrillev91** [comment]
UCS-2 and UTF-16 are different.
if someone feels competent enough to do it (in new PR they can adapt the script for automatic testing)
more info on UTF-16 : #8612

**Pull request closed without merging**
