### PR TITLE
[xml] Update romanian.xml

### PR DESCRIPTION
**Pull request by AndreiMiloiu**

### CODE REVIEW

**Comment by donho** [comment]
@AndreiMiloiu 
The part of https://github.com/notepad-plus-plus/notepad-plus-plus/commit/aa0be99 is missing.

**Comment by AndreiMiloiu** [comment]
I added that part. Sorry, I forgot about it.

**Comment by donho** [comment]
@AndreiMiloiu 
What you add are not correct.
Please check again.

**Comment by AndreiMiloiu** [comment]
Please recheck. I think that now it's good.

**Comment by donho** [comment]
@AndreiMiloiu 
Have you ever tested your translation??

**Comment by AndreiMiloiu** [comment]
Yes, I did

**Comment by AndreiMiloiu** [comment]
I don't understand what's wrong now?

**Pull request closed without merging**
