### PR TITLE
Update italian language file to version 7.0RC

### PR DESCRIPTION
**Pull request by Ices-Eyes**

### CODE REVIEW

**Comment by cmeriaux** [comment]
can you update your commit title ? It's confusing. 
"Language file" or whatever.
Thanks

**Comment by Ices-Eyes** [comment]
Hpe it's done :)

**Comment by cmeriaux** [comment]
Thanks, but change the PR title is not enough. Your commit title hasn't changed. Here is some helps to do that : https://help.github.com/articles/changing-a-commit-message/

**Comment by Ices-Eyes** [comment]
I try to make it online, have a github client :)

**Pull request closed without merging**
