### PR TITLE
Function list default sorting (#11446)

### PR DESCRIPTION
**Pull request by dfs-**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11446:
* add new preference setting to allow function list to be sorted lexicographically by default
* fix sorting for mixed mode function list parsers on new file open
* add new translations to english.xml and german.xml

image

Stored in `config.xml`
```<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    ...
    <GUIConfigs>
        ...
        <GUIConfig name="MISC" ... sortFunctionList="yes" ... />
        ...      
    </GUIConfigs>
</NotepadPlus>
```

### CODE REVIEW

**Comment by ArkadiuszMichalski** [comment]
Don't you think that it is more convenient to put the options of individual panels in their context menu? This makes switching them much more convenient and faster. Similar what we have for `Document List` (`on/off Ext. and Path.` - it was also in `Preferences` in the past, but has been moved.).

**Comment by dfs-** [comment]
> Don't you think that it is more convenient to put the options of individual panels in their context menu?

I definitely see your point. 
I considered it but thought it would be a bit weird to have it as a single line context menu that also has nothing to do with the elements displayed in the function list. Another approach that I just now came up with is having a third button in the panel depicting a gear or something which would allow for the option to be changed...

**Comment by dfs-** [comment]
@ArkadiuszMichalski Something like this?
image

**Comment by dfs-** [comment]
> Btw, what is correlation beetwen this new option and AZ button? When I check this option then button is not active, but when I restart Notepad++ button is active. Same is when I turn off this option and restart Notepad++.

It will set the default sorting when a new document is opened. Some people like me prefer the list to be sorted by name rather than by where in the document the specific class/function might be found. 

It willingly does not align the currently opened documents function sorting as one might have specifically changed the setting for documents currently active/opened.

**Comment by donho** [comment]
@dfs-  @ArkadiuszMichalski 

Tested this PR, there are several problems:
image

1. Choose `Sort functions (A to Z) by default` doesn't check the menu item, you have choose it again to make check mark appear.
2. Choose `Sort functions (A to Z) by default` doesn't execute Sorting A-Z command.
3. Sort functions (A to Z) by default` is not memorized after Notepad++ being restarted

Or am I missing the point of this feature?

**Comment by ArkadiuszMichalski** [comment]
> @donho Or am I missing the point of this feature?

You're right, after the recent changes it doesn't work at all. One another problem is when we start or restart Notepad++ and try switch this option then we have two times click on it (first time doesn't change it state), after this single clicking change it state (until next restart).

**Comment by donho** [comment]
@ArkadiuszMichalski @dfs- 
It's a good idea to put this option into Function List Panel.
But there might be some GUI incoherence.
The current behaviour is: sorting option is applied to each document individually, and it's kept only in the current session.
I suppose `Sort functions (A to Z) by default` will apply sorting A-Z not only to the current document, but also to all opened documents of the current session. And of course, it will be remembered through the sessions.
Is my description accurate?

**Comment by ArkadiuszMichalski** [comment]
From this https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11447#issuecomment-1081091604 intention was change behaviour only for new opened document (which also means that after launching Notepad++ it will apply to everyone). But I didn't call for this option so I don't have any particular preferences here, just test what has been done. Maybe @Yaron10 has some additional suggestions?

**Comment by dfs-** [comment]
@donho @ArkadiuszMichalski 
I'll recheck the changes and see if I can reproduce your problems.

**Comment by dfs-** [comment]
@donho 

> * Choose `Sort functions (A to Z) by default` doesn't check the menu item, you have choose it again to make check mark appear.

Should have been fixed.

> * Choose `Sort functions (A to Z) by default` doesn't execute Sorting A-Z command.

Currently this is this implemented behaviour. The option should enable the "A-Z" button only for files that are opened after the setting has been changed, as all other files already have their state stored in the "previous params list", see also:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/658b626257d5f000575e3361a325c707dc5cf697/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L393-L410

If it should behave differently, it should be decided (by whom?) if the checkbox automatically enables/disables the sorting for all opened files or only the current one.

> * Sort functions (A to Z) by default` is not memorized after Notepad++ being restarted

Should have been fixed.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

Sorry for the late response. I was not by my PC yesterday.

I haven't tested the second version of this PR (i.e the toolbar button, before @donho's comments).
It seems to work as expected now.
Thank you all.

***

Isn't the use of the the toolbar button somewhat unconventional?
Left-clicking a toolbar button normally executes a command.

> I considered it but thought it would be a bit weird to have it as a single line context menu that also has nothing to do with the elements displayed in the function list.

The context-menu can be displayed only on right-clicking the toolbar or an empty space as implemented in the Documents List.

**Pull request closed without merging**
