### PR TITLE
Update belarusian.xml

### PR DESCRIPTION
**Pull request by a-polivanchuk**

### CODE REVIEW

**Comment by a-polivanchuk** [comment]
Ok, I'll ask the Belarusian translator to do it asap and then create a new commit.

**Comment by a-polivanchuk** [comment]
Here is the requested update.

**Comment by xylographe** [comment]
@a-polivanchuk 
Could you replace
```
<Item idName="Убудовы" name="Убудовы"/>
```
with
```
<Item idName="Plugins" name="Убудовы"/>
```
please?

**Comment by a-polivanchuk** [comment]
@xylographe Thank you for catching the mistake. Fixed!

**Pull request closed without merging**
