### PR TITLE
Improve tab alignment in Shortcut Mapper

### PR DESCRIPTION
**Pull request by A-R-C-A**
More accurate alignment of tabs to babygrid.

### CODE REVIEW

**Comment by A-R-C-A** [comment]
@MAPJe71
It seems you have improved your function list parsers. Can you please upload your functionList.xml here or make a PR for it?

**Comment by MAPJe71** [comment]
A bit off-topic here ;) but here's link to my [functionList.xml](https://github.com/MAPJe71/notepad-plus-plus/blob/All-FunctionList-Related/PowerEditor/src/functionList.xml).

**Comment by A-R-C-A** [comment]
thanks

**Comment by donho** [comment]
@MAPJe71 does your functionList.xml is compatible with Notepad++ official release completely?

**Comment by MAPJe71** [comment]
@donho 
All parsers should be compatible. Unfortunately most of the changed official-release/stock parsers appear **not** to be **functional**. At the time they were changed I used Scintilla 3.56 with Boost 1.58 for use with my FunctionList patch. More recent changes to the stock parsers (see date tags in file) are done with official release Notepad++.
Unless you want a sh!t load of complaints about FunctionList do NOT USE my functionList.xml AS IS. ;)

**Comment by donho** [comment]
> Unless you want a sh!t load of complaints about FunctionList do NOT USE my functionList.xml AS IS. ;)
Sorry, I have problem to understand double nagative. Are you telling me that your function list is better than current one?

**Comment by MAPJe71** [comment]
I advise you **NOT** to use my [functionList.xml](https://github.com/MAPJe71/notepad-plus-plus/blob/All-FunctionList-Related/PowerEditor/src/functionList.xml) as is.

Some parsers are improved IMO e.g. `Batch / Command Shell`, `INI Section` and `Python`;
Some are added and optimized for my use e.g. `XML Function List`
Some are possibly improved (*possibly* because I did not get a response yet for validation) e.g. #1919;
Some are added to be able to help others e.g. #2045, [Community #9725](https://notepad-plus-plus.org/community/topic/9725/trouble-adding-userdefinedlanguage-parser-to-notepad-v6-8-2/5), [Community #12126](https://notepad-plus-plus.org/community/topic/12126/regex-for-function-list-in-user-defined-language-business-rules/14);
Some are optimized for my [SourceForge #548 patch](https://sourceforge.net/p/notepad-plus/patches/548/) and do not work correctly without it i.e. not functional;

I do not use all the parsers myself, the ones I do use regularly function of course ;) (i.e. `Batch / Command Shell`, `INI Section`, `Python` and `XML Function List`).

**Comment by donho** [comment]
@MAPJe71 Thank you for the elaboration.
In this case, could you do a PR for the parsers that we are sure they are better than current (with the header which gives the explicite explanation)?

I have checked your PR (SF's one) - the reason that the PR was not accepted is the dificulty of its integretion - it was kind of rewritten and hard to tell what is fixed/enhancend. 
If you could do some effort to do PR again (without reformatting and change of code structure) , I'll check it again.

**Comment by MAPJe71** [comment]
@donho 
> ... do a PR for the parsers ...

Sure no problem.
Do you mean an explanation for the improvements or the regular expressions or both?

> Regarding SF's PR ...

Yep, I figured that would have been the case. There's a contributing guideline now ;)
I will create a separate PR for this and include the optimized parsers which dependent on this patch (with explanatory comment, before/after comparison)

**Comment by donho** [comment]
> Do you mean an explanation for the improvements or the regular expressions or both?

Yes, they are really neat :)

> I will create a separate PR for this and include the optimized parsers which dependent on this patch (with explanatory comment, before/after comparison

Thank you very much.

**Pull request closed without merging**
