### PR TITLE
Add debug info for crash of Windows Sever Core 2022

### PR DESCRIPTION
**Pull request by donho**
Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15315#issuecomment-2174300091
Ref: #15313

### CODE REVIEW

**Comment by Pmalhotra2024** [comment]
I have downloade the fresh build from https://notepad-plus-plus.org/downloads/v8.6.8/

Still getting the same issue. 

image

**Comment by xomx** [comment]
@Pmalhotra2024 

Ah, this is misunderstanding. For testing these PRs, you have to use the CI (for N++ the GitHub Actions) builds:
- you have to be signed into your GitHub account (otherwise the GitHub Actions download links will not be visible for you)
- go to the relevant PR commit, e.g. for this PR click here:
  npp-test-PR-click
- then click here:
  npp-test-PR-click2
- and dl here:
  npp-test-PR-click3
- then unzip the downloaded Notepad++.exe file and replace your current one (probably in the C:\\Program Files\\Notepad++\\)
- report back the results here

**Comment by Pmalhotra2024** [comment]
oh.. got it.. i'll test and let you know.

**Comment by Pmalhotra2024** [comment]
image

**Comment by Pmalhotra2024** [comment]
image

**Comment by xomx** [comment]
@Pmalhotra2024 
> * then unzip the downloaded Notepad++.exe file and replace your current one (probably in the C:\Program Files\Notepad++\)
> 

otherwise you run N++ exe-binary without all of its supporting environment files...
(or if you cannot or do not want to manipulate with your N++ installation in the C:\\Program Files\\Notepad++\\, download the portable N++ version only for this testing and replace its notepad++.exe file there...)

**Comment by Pmalhotra2024** [comment]
> @Pmalhotra2024
> 
> > * then unzip the downloaded Notepad++.exe file and replace your current one (probably in the C:\Program Files\Notepad++)
> 
> otherwise you run N++ exe-binary without all of its supporting environment files... (or if you cannot or do not want to manipulate with your N++ installation in the C:\Program Files\Notepad++\, download the [portable N++ version](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.8/npp.8.6.8.portable.x64.zip) only for this testing and replace its notepad++.exe file there...)

I'm testing uninstalling N++ and then reinstalling on my test machine.

**Comment by Pmalhotra2024** [comment]
image
image

**Comment by Pmalhotra2024** [comment]
now pulled from above checked in build.. more errors added .. included the ones shared above.

image
image
image

**Comment by Pmalhotra2024** [comment]
> @Pmalhotra2024 Thank you for your info. The info shows one of elementary win32 API (LoadImage) failed in you Sever Core 2022, which should not happen. In order to get more information, and to remedy your problem, this PR is just updated and compiled. Could you redo the test with the instructions that @xomx [has provided](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15316#issuecomment-2175775856), and provide the result here please?

image
image
image
image

getting errors in series one after another on each ok .

**Comment by donho** [comment]
@Pmalhotra2024 
I'm sure that you've tested the old version, otherwise the message should be different.
Could you please check again?

**Comment by donho** [comment]
@Pmalhotra2024 
Please dl from here:
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/9567400506/artifacts/1613334826

**Comment by Pmalhotra2024** [comment]
> @Pmalhotra2024 I'm sure that you've tested the old version, otherwise the message should be different. Could you please check again?

After refreshing i'm getting this download url :
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/9567400506/artifacts/1613334826

Error popups increased. Plz note that Windows core is based on minimal windows installation features and many .dlls and classes and windows modules are missing in Windows core as it has no desktop experience. It is mainly PowerShell based edition of windows.

image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by xomx** [comment]
@donho 
The updated test (with the translated codes) is not necessary, both messages mean the same:
HRESULT: 0x8007007E - The specified module could not be found.
- this is not surprising for a Win Core Server

WIN32 syserror code 126 means: ERROR_MOD_NOT_FOUND - The specified module could not be found.
- i.e. that WinCoreServer has not access even to that old LoadImage WINAPI!?
- according to [this](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ee391646(v=vs.85)), this should not be a problem, but this is evidently a legacy info only

**Comment by donho** [comment]
@Pmalhotra2024 
Thank you for the info.

Is it the VM your Server Core 2022? Is it the same machine you can run the v8.6.7 without error? 
I asked that because the latest modification I provide has included the same call in v8.6.7 so it could have some of shown errors but at the end Notepad++ should be launched.

**Comment by xomx** [comment]
@Pmalhotra2024 

You said in the issue:
> Debug Information
>
>Not able to launch Notepad++ after upgrading to v8.6.8 on Windows CORE 2022 Servers.

From which N++ version you upgraded (which is the last N++ version without this problem)?
You can try to go back one by one N++ version using this repository (use the portable zipped v8.x versions for the testing, installation takes more time...):
http://download.notepad-plus-plus.org/repository/8.x/

**Comment by Pmalhotra2024** [comment]
> @Pmalhotra2024
> 
> You said in the issue:
> 
> > Debug Information
> > Not able to launch Notepad++ after upgrading to v8.6.8 on Windows CORE 2022 Servers.
> 
> From which N++ version you upgraded (which is the last N++ version without this problem)? You can try to go back one by one N++ version using this repository (use the portable zipped v8.x versions for the testing, installation takes more time...): http://download.notepad-plus-plus.org/repository/8.x/

the last working version is v8.6.7 x64 on my windows core 2022 production instances.

**Comment by xomx** [comment]
> the last working version is v8.6.7 x64 on my windows core 2022 production instances.

This is really weird. I for surety compared the relevant source code part in the v8.6.8 & v8.6.7 and indeed, they are the same.
(The only change in the dpiManagerV2.cpp is the addition of the adjustWindowRectExForDpi stuff, which is completely irrelevant for the reported issue.)

**Comment by Pmalhotra2024** [comment]
> > the last working version is v8.6.7 x64 on my windows core 2022 production instances.
> 
> This is really weird. I for surety compared the relevant source code part in the v8.6.8 & v8.6.7 and indeed, they are the same. (The only change in the dpiManagerV2.cpp is the addition of the adjustWindowRectExForDpi stuff, which is completely irrelevant for the reported issue.)

I suggest that you should test it on windows 2022 core edition .. a virtual image can do. I'm using AWS windows 2022 core images. if any code change is using some other windows class/module/dll then previous 8.6.7 version.. it could be problem, as not all win classed are registered with windows core editions.

**Comment by donho** [comment]
@Pmalhotra2024 
> I suggest that you should test it on windows 2022 core edition

I will wait & see the other report from Windows Server Core 2022 - if there are, it's not a isolated case so I'll manage to have a VM of Server Core 2022.

Thank you for your test and bug report.

**Comment by xomx** [comment]
@Pmalhotra2024 
> I suggest that you should test it on windows 2022 core edition .. a virtual image can do

It is not easy as it looks like. Even if I take the time to install a Core Server in a VM, I will also need to install MS Visual Studio there for the N++ debugging. And I doubt that the big MSVS SW package will not need even more such desktop DLL calls to functioning properly...

**Comment by ozone10** [comment]
@Pmalhotra2024 
There are 35 commits between v8.6.7 and v8.6.8, maybe you could try to isolate the problematic commit if there is some.
Use @xomx's https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15316#issuecomment-2175775856 guide to get binary files from https://github.com/notepad-plus-plus/notepad-plus-plus/compare/v8.6.7...v8.6.8 and run them. 

You can use "binary search", choose commit in "middle", if there is no issue choose new "middle" commit between old "middle" and commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/61bcf3a2bc1a607383691e411fa06b71c2a36ca8

if there is issue choose new "middle" between commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8055b5687b480db9ad311a95bf7615b395a1c021 and old "middle".

Repeat until you find the commit causing issue.

**Comment by xomx** [comment]
@Pmalhotra2024 
> if any code change is using some other windows class/module/dll then previous 8.6.7 version.. it could be problem, as not all win classed are registered with windows core editions.

I tried to debug the v8.6.7 N++ startup and it uses the same code flow as the v8.6.8. So the code part in question is executed as well (and should crash on your system):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/57a89b257a769ea93405b5b34bcb2660e61db857/PowerEditor/src/dpiManagerV2.cpp#L283-L289

**Comment by xomx** [comment]
@donho
Now I have the Windows Core Server 2022 in a VM available.
I can confirm that the v8.6.7 works there but the v8.6.8 not, the reported description including its symptoms is accurate.
I will try the @ozone10 commits thing.

**Comment by xomx** [comment]
@donho 
The culprit is @ozone10 `Add missing monitoring icon for disabled state`: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c660a71b38ab662f9cf8346c84bc6a39e3d957c

**Comment by donho** [comment]
@xomx 
Bravo!
I suppose it's due to the icon format which not compatible?

**Comment by xomx** [comment]
@donho 
> I suppose it's due to the icon format which not compatible?

Confirmed.

I managed to install the MSVS there (it was not easy as I expected and a lot of things does not work, e.g. I even cannot open the N++ sln from the IDE). But building the debug version was not a problem then. At the N++ startup the icons are loaded just fine in the `DPIManagerV2::loadIcon` (that `LoadIconWithScaleDown` func there returned S_OK as it should), until it is called from the `IconList::addIcon` with the `iconID` 245:

npp-VM-CoreServer2022-crash-ICO-245

**Comment by ozone10** [comment]
@xomx 
I suppose from above image you're using the build with commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c660a71b38ab662f9cf8346c84bc6a39e3d957c as latest.

Could you replace "icons/light/toolbar/regular/monitoring_off.ico" with [monitoring_off.zip](https://github.com/user-attachments/files/15895551/monitoring_off.zip) and check if it fails on next ico id 246.

**Comment by ozone10** [comment]
@Pmalhotra2024 
could you open v8.6.7 and do these steps
1. Open Find dialog (ctrl+f)
2. Select Regular expression
3. Search for `[`

In status bar should appear "Invalid Regular Expression" text with icon.
Does the icon appear for you.

image

**Comment by xomx** [comment]
It also interests me how these used WINAPIs (LoadIconWithScaleDown or LoadImage) can work there, as theirs system DLLs (e.g. the comctl32 for the LoadIconWithScaleDown) most probably are not there. On that WinServers without the usual Desktop support installed, there must be some shim, which intercepts calling of these common DLL exported ordinals and provides some basic support equivalent for them, otherwise a user cannot run most of the apps depending on them...

**Comment by donho** [comment]
@xomx 
Could you provide the iso to download of Server Core 2022 please?

**Comment by xomx** [comment]
@donho 
Are you thinking about testing also on such platform before releasing the N++ new versions in the future?

> But it's not server core

Yes, maybe there is a special ISO for dl, but I could not find it either. I am not a server-guy, but IMO that "Core" simply means installing the Windows server in its minimalistic variant without the classic desktop support (also missing: shell package, any GUI & RSAT management, any OOBE for startup settings, etc). So for the dl I just went [here](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2022), but because I do not like registration forms, I opted for the WinServer 2022 Preview direct ISO [here](https://software-download.microsoft.com/download/sg/20348.1.210507-1500.fe_release_SERVER_EVAL_x64FRE_en-us.iso). I think that even your ISO links will work for the purpose.

In VBOX I cancelled the offered unattended iso-installation, because of I wanted to select a specific server version without that Desktop support. After such installation I ended up with the PowerShell admin console and the server "sconfig" configuration command, that is all you need.

I also needed to manually install the VBOX guest additions for creating a shared RW directory between the guest and host - I created a blank CD-ROM before booting VM and then plugged the guest additions in and manually started its install. Then the standard VBOX sharing started to work.

There is no Explorer like filemanager, for the filesystem manipulation I just run the usual "cmd" command from the PS console. Then I copied there my favorite Servant Salamander filemanager folder and from that point all the manipulation needed has started to be easy.

For the MSVS installation I dl the appropriate vs_Community.exe and then I created an offline Community ed 2022 v17.10 layout:
`vs_Community.exe --layout C:\MSVS-Community-2022 --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --includeOptional --lang en-US`
then copied it into the VM via shared folder and installed it there unattended:
`C:\MSVS-Community-2022\vs_Community.exe --noWeb --quiet --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended`

To open the N++ sln in MSVS, I run:
`"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" PATH_TO.\notepadPlus.sln`

**Comment by ozone10** [comment]
@donho @xomx 
I think the issue is that core api is really basic and it does not support loading ico files with only png images. I will modify ico files to have at least one bmp image.

**Comment by ozone10** [comment]
@xomx 
could you test these icons
[icons.zip](https://github.com/user-attachments/files/15905229/icons.zip)

**Comment by xomx** [comment]
@ozone10 

npp-VM-WCS-v868-fixed_icons

**Comment by ozone10** [comment]
@xomx 
could you check how toolbar fluent icons for monitoring look, especially large ones?

**Comment by donho** [comment]
@ozone10 
What's the difference between the icons which work and the ones don't work?

**Comment by ozone10** [comment]
@donho 
working icons contain at least one bmp image.

Interestingly icon for invalid regex contains only png images and is silently failing in windows server core.
Without this crash from loadicon it would probably remain unnoticed for much longer time.

**Comment by xomx** [comment]
> could you check how toolbar fluent icons for monitoring look, especially large ones?

npp-FluentUI-small

But the "Fluent UI: large" & "Filled Fluent UI: large" crashed in the same style as before.

**Comment by donho** [comment]
@xomx 
> Are you thinking about testing also on such platform before releasing the N++ new versions in the future?

Yes, I'm thinking of that, if the procedure is not complicated.

> In VBOX I cancelled the offered unattended iso-installation, because of I wanted to select a specific server version without that Desktop support. After such installation I ended up with the PowerShell admin console and the server "sconfig" configuration command, that is all you need.

Thank you for the hint - "unattended" is the keyword defiantly.

Here is where I'm of the installation:

image

I suppose that I can choose 15 to have the command line?

**Comment by xomx** [comment]
@donho
> I suppose that I can choose 15 to have the command line?
Yes.

**Comment by donho** [comment]
@xomx 
I have shared a folder via virtual box and auto-mount it. However, I see no way to access to this shared folder under PS.
Could you give me a hint about it?

**Comment by xomx** [comment]
@donho 

IDK if you have already installed the Oracle Guest Additions in your WinCoreServer WM (without that the VBOX sharing will not work), so here are my prerequisities 1st:

vbox-CD-GuestAdditions
vbox-shared-folder-RW

**Comment by xomx** [comment]
@donho 

Then follow this to reach your `S:` drive:

vbox-shared-folder-guide

**Comment by donho** [comment]
**Thank you** @xomx ! 

image

**Comment by donho** [comment]
> @xomx could you test these icons [icons.zip](https://github.com/user-attachments/files/15905229/icons.zip)

@ozone10 
Could you do a PR with these icons please?

**Comment by donho** [comment]
> @xomx could you test these icons [icons.zip](https://github.com/user-attachments/files/15905229/icons.zip)

> @ozone10 
> Could you do a PR with these icons please?

**Comment by ozone10** [comment]
@donho 
> Could you do a PR with these icons please?

> But the "Fluent UI: large" & "Filled Fluent UI: large" crashed in the same style as before.

I am not sure how to properly fix it.
Changing all icons to use only bmp will increase notepad++ size a lot and IMHO for only this version of OS not worth it. 
Is enough to make notepad++ to not crash with limitation that dark mode, large icons, and hidpi cannot be used?

**Comment by xomx** [comment]
@ozone10 @donho 
> I am not sure how to properly fix it.

1. The simplest - have one "loading failed" icon for all of these cases, i.e.:
```
void DPIManagerV2::loadIcon(HINSTANCE hinst, const wchar_t* pszName, int cx, int cy, HICON* phico, UINT fuLoad)
{
	if (::LoadIconWithScaleDown(hinst, pszName, cx, cy, phico) != S_OK)
	{
		*phico = static_cast<HICON>(::LoadImage(hinst, pszName, IMAGE_ICON, cx, cy, fuLoad));
		if (*phico == nullptr)
		{
			// safety measure for all the possible "failed loading" cases
			*phico = static_cast<HICON>(::LoadImage(hinst, MAKEINTRESOURCE(NPP_COMMON_SAFETY_ICON_ID), IMAGE_ICON, cx, cy, fuLoad));
		}
	}
}
```
2. Move all the large icons to external DLL module (this option also speeds up the notepad++.exe loading in case that such large icon sets are not needed).
3. Accept the increasing of the notepad++.exe module (BMP instead of PNG format...)

**Comment by xomx** [comment]
@ozone10 

> But the "Fluent UI: large" & "Filled Fluent UI: large" crashed in the same style as before.

Now I have debugged it more and I see that it fails again up to that icon 245 (so it can load other icons from that set ok).

**Comment by donho** [comment]
@xomx 
> Now I have debugged it more and I see that it fails again up to that icon 245 (so it can load other icons from that set ok).

However, you have said:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15316#issuecomment-2179475270

So if I understand well, the new icon set provided by @ozone10  works with release binary but not in debug binary?

**Comment by ozone10** [comment]
@donho 
I think it does not matter if it's debug or release binary.

**Comment by xomx** [comment]
@donho 
> > Now I have debugged it more and I see that it fails again up to that icon 245 (so it can load other icons from that set ok).
> 
> However, you have said: [#15316 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15316#issuecomment-2179475270)
> 
> So if I understand well, the new icon set provided by @ozone10 works with release binary but not in debug binary?

In that mentioned previous comment I was testing with the vanilla N++ settings (Standard icons: small), then @ozone10 asked for another test with the fluent ones:

npp-icons-set-explanation

**Pull request closed without merging**
