### PR TITLE
Include version info in Installer

### PR DESCRIPTION
**Pull request by SinghRajenM**
As of now, there is no version info available on the detail section of installer properties.
It is good to have version info.

file_info

### CODE REVIEW

**Comment by donho** [comment]
@SinghRajenM  I just don't understand why it's always 2 commits?

**Comment by SinghRajenM** [comment]
I use github Web for PR. So the commit count is equal to the number of
changed file.
Unfortunately, I couldn't setup git on my system. I'm finding it hard to
setup git on my system. I will try overcome it soon.
Sorry for inconvenience caused.

**Comment by donho** [comment]
Does it imply that you don't even compile your commit locally? 
Each PR should come with ONLY one commit.
Otherwise I cannot accept such PR.

**Comment by SinghRajenM** [comment]
No, it is not like that. I DO compile the changes and test it before submitting. Without compile it is hard to attach screenshot.

**Pull request closed without merging**
