### PR TITLE
Make install/update easy & quiet

### PR DESCRIPTION
**Pull request by donho**
Add command line parameter "/runNppAfterSilentInstall" for Notepad++ installer. This parameter launches installed Notepad++ after silent installation. Of course, the parameter takes effect only when "/S" (silent installation) is used.

Fix partially #8514, follow up #15230

### CODE REVIEW

**Comment by xstaindx** [comment]
If I was to deploy this version of your software with automation tools that use SYSTEM for the install with these new comamndl ines, would these launch the software in the SYSTEM context after install in Session 0 or would it be launched into the logged on user in Session 1?  I would think session 1 would be bad.

**Comment by donho** [comment]
No idea about concept of session 0 or of session 1.
It's launched under the accound of user.

**Comment by xstaindx** [comment]
I would strongly suggest that you do not allow a silent install to launch in the context of the user who installed it if the installation is SYSTEM. (like through tools such as SCCM, BIGFIX, Tanium or others)  You end up leaving an open session that a user cannot access that has SYSTEM rights, nor can user see or interact with.

**Comment by xstaindx** [comment]
> No idea about concept of session 0 or of session 1. It's launched under the accound of user.

https://techcommunity.microsoft.com/t5/ask-the-performance-team/sessions-desktops-and-windows-stations/ba-p/372473

**Comment by schenardie** [comment]
Is there a way that /runNppAfterSilentInstall will only run if /closeRunningNpp is also called? I would like to automatically re-open npp only if the installation closed it, but if it was already closed it should not open it.

**Comment by xomx** [comment]
@schenardie 

> I would like to automatically re-open npp only if the installation closed it, but if it was already closed it should not open it.

In the upcoming N++ version, there will be new installer param `/relaunchNppAfterSilentInstall` for it (for details check the current PR [#16626](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/16626#discussion_r2155473082) which added option to auto-update N++ also at its exit)

**Pull request closed without merging**
