### PR TITLE
Dark mode less intense by default; custom drawing implementations now handle custom colors better

### PR DESCRIPTION
**Pull request by adzm**

### CODE REVIEW

**Comment by adzm** [comment]
I'll have to figure out the conflicts here

**Comment by adzm** [comment]
@donho fixed merge conflicts. Still need to figure out the custom color stuff with the UI and saving but the plumbing is here at least.

**Comment by chcg** [comment]
@adzm 

Compilation issues from appveyor:
   

>      c:\projects\notepad-plus-plus\powereditor\src\wincontrols\toolbar\toolbar.cpp(479): error C2039: 'getPureBackgroundBrush': is not a member of 'NppDarkMode' [C:\projects\notepad-plus-plus\PowerEditor\visual.net\notepadPlus.vcxproj]
>          c:\projects\notepad-plus-plus\powereditor\src\wincontrols\toolbar\toolbar.cpp(479): error C3861: 'getPureBackgroundBrush': identifier not found [C:\projects\notepad-plus-plus\PowerEditor\visual.net\notepadPlus.vcxproj]

**Comment by donho** [comment]
@adzm 
The build failed of this PR on both Appveyor and my laptop.
It seems you forgot to commit `NppDarkMode.h` & `NppDarkMode.cpp` entirely:
The declartion & definition of `getPureBackgroundBrush()` is missing.

**Review by donho — CHANGES_REQUESTED** [review]
Fix build error.

**Comment by donho** [comment]
@adzm 
> custom drawing implementations now handle custom colors better

Could you provide more detail please?

**Comment by donho** [comment]
@adzm 
Awesome! You just gave the rainbow power to Notepad++ !
I'll play it to see if it's possible to change the color on the fly (runtime).
I merge it now and will fix the build error myself to avoid the merge conflict on the next time.

**Pull request closed without merging**
