### PR TITLE
Continuous integration with Appveyor

### PR DESCRIPTION
**Pull request by squarefractal**
This commit adds scripts to support continuous integration with Appveyor.

Registering an account with Appveyor is necessary for this to work, though.

### CODE REVIEW

**Comment by NN---** [comment]
What about using boost as NuGet instead of downloading manualy ?

**Comment by vgturtle127** [comment]
Also having support for Travis CI and Coverity might be nice. Especially with a large code base.

**Comment by donho** [comment]
@squarefractal I created an account at Appveyor and set notepad-plus-plus project.
But how can I test to validate your pr (without committing)?

**Comment by squarefractal** [comment]
@donho:

What you can do is make a new branch and commit the diff file available at https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1526.diff in this new branch to test out my changes.

**Comment by milipili** [comment]
Personally, I prefer to fork the repo, and then merge the changes to the main repo.

**Comment by vgturtle127** [comment]
@donho @milipili @squarefractal Yeah, probably best to do it how @milipili described.

**Pull request closed without merging**
