### PR TITLE
update scintilla 5.3.4 and lexilla 5.2.4 with:

### PR DESCRIPTION
**Pull request by chcg**
https://www.scintilla.org/scintilla534.zip

    Released 8 March 2023.
    Add multithreaded wrap to significantly improve performance of wrapping large files.
    More typesafe bindings of *Full APIs in ScintillaCall. Feature #1477.
    Fix overlapping of text with line end wrap marker. Bug #2378.
    Fix clipping of line end wrap symbol for SC_WRAPVISUALFLAGLOC_END_BY_TEXT.
    Where a multi-byte character contains multiple styles, display each byte as a representation. This makes it easier to see and fix lexers that change styles mid-character, commonly because they use fixed size buffers.
    Fix a potential crash with autocompletion list fill-ups where a SCN_CHARADDED handler retriggered an autocompletion list, but with no items that match the typed character.

https://www.scintilla.org/lexilla523.zip

    Released 8 March 2023.
    Add scripts/PromoteNew.bat script to promote .new files after checking.
    Makefile: Remove 1024-byte line length limit..
    Ruby: Add new lexical classes for % literals SCE_RB_STRING_W (%w non-interpolable string array), SCE_RB_STRING_I (%i non-interpolable symbol array), SCE_RB_STRING_QI (%I interpolable symbol array), and SCE_RB_STRING_QS (%s symbol). Issue #124.
    Ruby: Disambiguate %= which may be a quote or modulo assignment. Issue #124, Bug #1255, Bug #2182.
    Ruby: Fix additional fold level for single character in SCE_RB_STRING_QW. Issue #132.
    Ruby: Set SCE_RB_HERE_QQ for unquoted and double-quoted heredocs and SCE_RB_HERE_QX for backticks-quoted heredocs. Issue #134.
    Ruby: Recognise #{} inside SCE_RB_HERE_QQ and SCE_RB_HERE_QX. Issue #134.
    Ruby: Improve regex and heredoc recognition. Issue #136.
    Ruby: Highlight #@, #@@ and #$ style interpolation. Issue #140.
    Ruby: Fix folding for multiple heredocs started on one line. Fix folding when there is a space after heredoc opening delimiter. Issue #135.
    YAML: Remove 1024-byte line length limit.

### CODE REVIEW

**Comment by donho** [comment]
Very interesting improvement:
> Add multithreaded wrap to significantly improve performance of wrapping large files.

**Comment by rdipardo** [comment]
> https://www.scintilla.org/lexilla523.zip

It's best not to merge this until you've patched in the latest lexilla (5.2.__*4*__): https://groups.google.com/g/scintilla-interest/c/6CA58LYs3PU

There probably won't be a new Scintilla to go with it. Like [I said before](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11537#issuecomment-1100286679), "out-of-band" releases can be expected now that the lexers are a separate project.

BTW, has anyone ever thought of using [submodules] instead? The N++ organization can fork [ScintillaOrg/lexilla](https://github.com/ScintillaOrg/lexilla/fork), patch in `LexUser` and stuff, then the downstream repo only needs to check out a new commit hash from time to time.

~~~sh-session
$ git submodule update lexilla/
$ git submodule summary
* lexilla a9776965...b22cda8b (7):
  > Updates for version 5.2.4.
  > #149 Fix failure to recognize keywords containing upper case.
  > #145 146 Better handling of '%' used in string formatting.
  > #145 #146  Added $ and % highlighting for SCE_GD_NODEPATH in GDScript
  > #147 Prefer NSDM initialization where convenient
  > #147 Don't instantiate character sets at namespace level
  > Enable dead code stripping as Xcode 14 wants it set.
~~~

[submodules]: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by chcg** [comment]
+ https://www.scintilla.org/lexilla524.zip

    Released 13 March 2023.
    C++: Fix failure to recognize keywords containing upper case. Issue #149.
    GDScript: Support % and $ node paths. Issue #145, Pull request #146.

**Comment by chcg** [comment]
|                  | Fixed in Lexilla version...  | Ref.                          |
| :-----:          |  :-----:                     | :----:                        |
| #4964            |  5.2.3                       | ScintillaOrg/lexilla@397dfb1  |
| #4439, #9918     |  5.2.3                       | ScintillaOrg/lexilla@1e347a1  |

There was no own commit for lexilla 5.2.3

**Pull request closed without merging**
