### PR TITLE
Update polish.xml to 7.8.9

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Update polish.xml to 7.8.9 + one small correct.

### CODE REVIEW

**Comment by donho** [comment]
@ArkadiuszMichalski 
Thank you for your update. 
Could you check the diff from v7.8.9 to the newest `english.xml` to make sure there's nothing's missing?
http://download.notepad-plus-plus.org/repository/MISC/diff/english.diff.htm

**Comment by ArkadiuszMichalski** [comment]
@donho 
Any place where can I download the latest compiled version of NPP? This would make easier to update translation, because without "live preview of the current changes" I can only add the missing entries in their original translation. It would be nice if there was a version for translators before the RC version (2-3 days earlier) so that the update translations could go to the RC version.
 
Btw, what number would be mark next NPP version? In english.xml we still see `version="7.8.7"` which looks out of date.

**Comment by donho** [comment]
@ArkadiuszMichalski It'll be v7.9

> if there was a version for translators before the RC version (2-3 days earlier) so that the update translations could go to the RC version.

The workflow is include everything in the RC.

**Comment by ArkadiuszMichalski** [comment]
@donho 
I'm not sure if everything fit to the GUI (missing binary version), if no I will correct it next time.

**Pull request closed without merging**
