### PR TITLE
Update Slovak translation

### PR DESCRIPTION
**Pull request by kubalav**

### CODE REVIEW

**Comment by ArkadiuszMichalski** [comment]
@kubalav You forgot to add `"`, should be `message="`. When you making a new commit, add `[xml]` at the beginning of the title, so the test will be very fast.

**Comment by kubalav** [comment]
> @kubalav You forgot to add `"`, should be `message="`. When you making a new commit, add `[xml]` at the beginning of the title, so the test will be very fast.

Thank you @ArkadiuszMichalski  for the warning. IDK about [xml] trick in title.

**Comment by donho** [comment]
@kubalav 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

**Comment by kubalav** [comment]
@donho
Slovak translation done.

**Comment by donho** [comment]
Thank you @kubalav for your confirmation!

**Pull request closed without merging**
