### PR TITLE
Update portuguese.xml to v7.9.6

### PR DESCRIPTION
**Pull request by hugok79**
Finished all the translations
Fix some strings

### CODE REVIEW

**Comment by hugok79** [comment]
Portuguese translation fully translated

**Comment by hugok79** [comment]
Update

**Comment by hugok79** [comment]
For commits:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a0177e8d050291992a24e334762c824005ffcc06
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0dbdef320f8ce89d348959c3224210444f992532

**Comment by donho** [comment]
@hugok79 
Could you please check the latest report of the old localization file vs new localization file to make sure if your PR updated?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9854

Thank you!

**Comment by hugok79** [comment]
I'll take a look now.

**Comment by hugok79** [comment]
@donho All done. Portuguese.xml translation is complete.

**Comment by hugok79** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9843#issuecomment-840052805

**Pull request closed without merging**
