### PR TITLE
update for arm64 build

### PR DESCRIPTION
**Pull request by chcg**
see build https://ci.appveyor.com/project/chcg/notepad-plus-plus/builds/27890847 for issue  #5158

Seems at least adding the config makes sense even, if not build on a regular base via appveyor.

### CODE REVIEW

**Comment by donho** [comment]
@chcg I do believe it does compile Notepad++ ARM64 binary. However, Scintilla should be in ARM64 as well, that implies to compile PCRE of boost - without this part we cannot make a minimalist Notepad++ run. And I'm not even talking about WinGUp, PluginList and all plugins. Any suggestion?

**Comment by chcg** [comment]
@donho See https://ci.appveyor.com/project/chcg/notepad-plus-plus/builds/27890847/job/rxifl9trr50sln29, also scintilla is build with it, see at:

  Creating library ..\bin\SciLexer.lib and object ..\bin\SciLexer.exp
LINK : warning LNK4010: invalid subsystem version number 5.01; default subsystem version assumed
Generating code
Finished generating code
	LIB /OUT:..\bin\libscintilla.lib .\AutoComplete.obj .\CallTip.obj .\CaseConvert.obj .\CaseFolder.obj .\CellBuffer.obj .

I should be possible to use at least c++11 regex by scintilla. I could also test the compatiblity together with boost. Guess this might work also without to big troubels.

Also did already some time ago an experiment with npppluginlist:
https://github.com/chcg/nppPluginList/tree/appveyor_for_arm
, so that is also no big issue.

WinGup might be more interesting. I would start to provide PRs for the plugins part of the installer as a starting point, if you think arm64 support is of interest.

**Comment by donho** [comment]
@chcg Could you provide me the steps to follow to compile Scintilla (with boost's PCRE) please ?

**Comment by chcg** [comment]
@donho The magic is done via:

```
 if "%platform%"=="arm64" set archi=amd64_arm64
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
```
to setup the compiler flags accordingly for arm64. Apart from that the scintilla build is just done like the normal ones for x64,x86:


> - if "%configuration%"=="Unicode Debug" set scintilla_debug=DEBUG=1
> - if "%configuration%"=="Unicode Release" set scintilla_debug=
> - nmake SUPPORT_XP=1 %scintilla_debug% -f scintilla.mak

also SUPPORT_XP=1 doesn't make sense for arm64. It is probably better to remove that flag in case of the arm build.

**Comment by chcg** [comment]
@donho I overlook the "with boost" part. I haven't check that out yet.

Further hint:
See https://www.scintilla.org/ScintillaHistory.html for 3.6.6:

> 
>  Released 24 May 2016.
> C++ 11 <regex> support built by default. Can be disabled by defining NO_CXX11_REGEX. 

That one uses https://en.cppreference.com/w/cpp/regex/ecmascript as default mode, see
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/src/Document.cxx#L3065

Maybe the readme should be update to reflect that change compared to the previous builtin limited POSIX version with the scintilla update to 4.1.4/4.2.0.

**Comment by donho** [comment]
@chcg 

C++11 RegEx is attractive because it allows to get rid of the dependency on boost.
However, some Notepad++ built-in features uses heavily (like Function List & html/xml tag matching) so there could be some regressions if we switch the RE engin.

> Maybe the readme should be update to reflect that change compared to the previous builtin limited POSIX version with the scintilla update to 4.1.4/4.2.0.

Feel free to modify this part.

**Comment by sasumner** [comment]
@donho said:

>C++11 RegEx is attractive because ... 

>.. some Notepad++ built-in features uses heavily ... so there could be some regressions (due to C++11 RE performance and its different syntax flavor) if we switch the RE engin.

Not to mention ticking off the user base that is used to the current regex engine.  I think there would have to be significant, demonstrable benefits to changing the engine in order to actually do so.

**Comment by chcg** [comment]
@donho My hint was not meant for the main version which should still be build with boost to avoid loosing PCRE. Just for the build without boost which no longer uses the oldstyle limited regular engine, but due to the changed default by scintilla the C++11 regex flavour.

**Comment by donho** [comment]
@sasumner 
>  I think there would have to be significant, demonstrable benefits to changing the engine in order to actually do so.

What does make you say so? Could you elaborate it?

**Comment by donho** [comment]
@chcg I have tried to build Scintilla come with Notepad++ without boost:
[SciLexer.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3775342/SciLexer.zip)
(release, signed) 
After some quick tests, html/xml tag matching works but not  Function List.

**Comment by sasumner** [comment]
@donho 

>What does make you say so? Could you elaborate it?

I already said it:  Making the existing user base angry at having to learn something new.  But, give them something better (yet to be determined) and it will be okay. :-)

**Comment by donho** [comment]
@sasumner 
English is not my native language so sometimes I could misunderstand or ignore the hidden meaning :)
So you're saying that you are for changing RExpr engin from boost's one to C++11's one, because that make the community learn another RE syntax flavor, even it could make users irate.

Do I understand you correctly ?

**Comment by LordNyriox** [comment]
@donho:  English is my native language, so I cannot help but comment here… 

> Do I understand you correctly? 
Not exactly.  Near as I can tell, @sasumner is arguing in favor of changing the regex engine *despite* the inevitable frustration—but advises that you also add some new features to NPP's regex subsystem to give the users something to look forward to.

**Comment by donho** [comment]
@LordNyriox 
> but advises that you also add some new features to NPP's regex subsystem to give the users something to look forward to.

Thank you for the interpretation :)
Concretely, what kind of regex subsystem could it can be? It's still vague for me.

**Comment by LordNyriox** [comment]
@donho: 

> Concretely, what kind of regex subsystem could it be? It's still vague for me. 

I get the impression that @sasumner was leaving that one up to you to decide.  Either that or he figured the final decision could be left until after Boost was already removed as a dependency.  [*shrug*] 

I presume some sort of quality-of-life feature would be best—but I really am not the best person to ask in this case. 

I do not understand regex well enough to use it, much less make informed recommendations about enhancing others' usage of it.

**Comment by sasumner** [comment]
@donho @LordNyriox Given the apparent language barrier, please disregard any of my prior comments.

**Comment by chcg** [comment]
Seems boost could be build with commandline, e.g.:

`.\b2 -j2 architecture=arm link=static runtime-link=static threading=multi address-model=64 stage --toolset=msvc-14.1 --without-python`

the relevant parameter which differ from the x86/x64 build is:
architecture=arm
and
address-model=64
as we havearm64.

Further hint for x86 and x64:
Instead of building the regex lib on your own it is possible to use the prebuild windows binaries:
https://bintray.com/boostorg/release/boost-binaries/1.70.0#read
or
https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0/

**Comment by chcg** [comment]
Close this one as the changes are now part of https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9594

**Pull request closed without merging**
