### PR TITLE
Show Notepad++.exe bitness in about box

### PR DESCRIPTION
**Pull request by linquize**
Show Notepad++.exe bitness in about box

### CODE REVIEW

**Comment by linquize** [comment]
ping

**Comment by vgturtle127** [comment]
@donho @linquize Could we rebase this and merge it please? This would be helpful for many reasons.

**Comment by donho** [comment]
It'll be interesting when 64 bits is included in the release... in the future versions.

**Comment by vgturtle127** [comment]
@donho Very interesting. This will no doubt help with out of memory errors on larger files as well.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c059cc03dc0eab4ae40d61d291b0d05d4f006eb6

**Pull request closed without merging**
