### PR TITLE
update japanese.xml to v7.9.6

### PR DESCRIPTION
**Pull request by yasmise**
Follow-up to this commit:
* Catch regex search exceptions and show exception message (926e6e97d82b3d63103cb2297b372af5cd469ca6)

### CODE REVIEW

**Comment by yasmise** [comment]
Added these translations:
* Replaced UCS-2 by UTF-16, removed unused UniConversion.* (6834d796ab553438827fe7e07a1e4caef8460f6f)
* Add ability to avoid accumulating multiple search results (874f0d01401e7c73b9965294cec41f3245acfc5a)

**Comment by yasmise** [comment]
Follow-up these commits:
* Add ability to style only current instance of text (4369718925f90e88766de77c8e4549807cdd6545)
* Make new tab name translatable (1ae39c2dda5f26c5b6a641f5362c8fa65bf70270)

**Comment by yasmise** [comment]
Follow-up these commits:
* Add new feature "Distraction Free Mode" (cbf3d2c9cb35c3fee4cf750d283771a844beafd9)
* Add padding options in the edit zonze (1a9307b02d3381a77e033784edff43ca51d213ee)
* Add "Append extension" checkbox to Save As dialog (e3dbeda4c99e441f6bf2f77f717703f0dd4b798b)

**Comment by yasmise** [comment]
Follow-up these commits:
* Add pref setting to allow Replace to stop after replacement (a0177e8d050291992a24e334762c824005ffcc06)
* Add MarkAll Preference settings for case and word (0dbdef320f8ce89d348959c3224210444f992532)
* Add "Copy Pathnames" command to Search results context menu (b657f585806495570beb2256f64c3d9a570d5271)

**Comment by donho** [comment]
@yasmise 
Could you please check the latest report of the old localization file vs new localization file to make sure if your PR updated?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9854

Thank you!

**Comment by yasmise** [comment]
@donho 
I've added missing translations, and now it's ready. Thank you.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/37863f47a03c49bd4a1342f4fc7e9762c37b9739

**Pull request closed without merging**
