### PR TITLE
Fix issues with dialog background on Windows 11

### PR DESCRIPTION
**Pull request by ozone10**
fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10299

### CODE REVIEW

**Comment by donho** [comment]
Windows 11 is not out yet officially, so it could be a bug in Windows 11 (MS always does care about the retro-compatibility).
I would say let's wait for its coming to see if it needs to be fix.

**Comment by ozone10** [comment]
Hopefully `WM_CTLCOLORDLG` won't end like `WM_CTLCOLORMSGBOX`.

`WM_ERASEBKGND` should be also more reliable on older Windows.
Windows 11 is already on insider beta channel, but as you said it could be bug, so maybe wait for at least preview channel.

**Comment by ozone10** [comment]
@donho 
Notepad++ is using uxtheme textures for "white" background, for example here
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2576bf884b37a916cf5f597d87e436fb59864cec/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp#L212

and it seems that Windows 11 will handle uxtheme api differently
```
Win32 controls that use UXTheme will automatically get a "repaint" of the Light theme for select rejuvenated control visuals.
```
https://docs.microsoft.com/en-us/windows/apps/get-started/make-apps-great-for-windows#desktop-apps-win32

**Comment by donho** [comment]
@ozone10 
> and it seems that Windows 11 will handle uxtheme api differently

So no need to retrieve and call `enableDlgTheme` under Windows 11 anymore?

**Comment by ozone10** [comment]
@donho 
It's needed to make background white in light mode, without it will be "classic gray", which does not look good.

**Comment by ozone10** [comment]
@donho 
I've tried workaround with `EnableThemeDialogTexture` and it works great, I will do separate PR

**Comment by donho** [comment]
@ozone10 So could we close this PR since the better way has be done in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8ac13d90654e5ebaff2167582c7b24751d38b6ce ?

**Comment by ozone10** [comment]
@donho 
Sure, this PR is not needed for now.
In case it is needed I can always reopen or do another PR.

btw Microsoft has just released Windows 11 ISO for insider

**Pull request closed without merging**
