### PR TITLE
Add the UTF8 character ability for Run & Macro menu

### LINKED ISSUE #13488: shortcuts.xml gets mixed line-endings on macro record and save
### Description of the Issue
See StR.

### Steps to Reproduce (StR) the Issue
1. Extract a fresh portable version of 8.5.2.
2. Open its `shortcuts.xml` with it.
3. Do regex search for `(?<!\r)\n` and observe 0 hits.
4. Record and save any macro.
5. Restart.
6. Do regex search for `(?<!\r)\n` in `shortcuts.xml`.

### Expected Behavior
No hits.

### Actual Behavior
3 hits in the file.
Turn on visible line-endings.
Observe LF line-endings on lines 3 through 5 while the rest of the file has CRLF endings:
image
image

### Debug Information
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : W:\npp.misc\_NoBackup\Releases\npp.8.5.2\test\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2728
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

### PR DESCRIPTION
**Pull request by donho**
Add the UTF8 character ability for Run & Macro menu by using GUI or by editing shortcut.xml.
Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13221#issuecomment-1457325172

Fix #13488

### CODE REVIEW

**Comment by alankilborn** [comment]
When just beginning to test, I noticed this:

image

**Comment by ArkadiuszMichalski** [comment]
Have the same problem as above. And some other notes:
1. After save/change macro's name we lost some default comments in [`shortcuts.xml` ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/shortcuts.xml). Only the first one is preserved.
2. >However, the modification of shortcut makes shortcut.xml being rewritten, and the Human readable UTF8 char become raw data - at least it's readable in the menu, and the raw data is the same for the same unicode characters.

   Yes, but it's not limited to just this file, but to all `.xml`. Try searching for `макрос`, close Notepad++ and check what character is in the `config.xml` file (`<Find name="&#x043C;&#x0430;&#x043A;&#x0440;&#x043E;&#x0441;" />`). We just have HTML entities, not plain text. I don't know why TinyXML writes it like that, but if we consider it a bug/defect, it should rather be considered separately.

**Comment by alankilborn** [comment]
>After save/change macro's name we lost some default comments 

>Only the first one is preserved.

And, in that "first one", interestingly, this PR seems to solve #13488 !

**Comment by Yaron10** [comment]
@donho,

Thank you for your work. 👍 
(I haven't tested the new Run structure).

I was about to ask you about the presentation of characters in the XML files. 
@ArkadiuszMichalski mentioned it first:
> close Notepad++ and check what character is in the config.xml file (<Find name="&#x043C;&#x0430;&#x043A;&#x0440;&#x043E;&#x0441;" />).

EditPad displays them in "readable characters" if the encoding is set to:

תמונה

**Comment by rdipardo** [comment]
@ArkadiuszMichalski,
> I don't know why TinyXML writes it like that, but if we consider it a bug/defect, it should rather be considered separately.

As [was mentioned before](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12670#issuecomment-1359902802):

> TinyXML is not being developed anymore.
> 
> Maybe Notepad++ should try to move to [TinyXML2](https://github.com/leethomason/tinyxml2), but this will require major refactoring.

A good question (for a later time): the regex engine and Scintilla components get regular updates; has that XML engine *ever* been updated since the Subversion days?

**Comment by Yaron10** [comment]
@rdipardo,

👍 
Thank you.

**Comment by donho** [comment]
@alankilborn 
> When just beginning to test, I noticed this:

Fixed in the new commit.

> And, in that "first one", interestingly, this PR seems to solve https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13488 !

That's a good "side effect" of this PR. ;) 

@ArkadiuszMichalski 
> After save/change macro's name we lost some default comments in [shortcuts.xml ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/shortcuts.xml). Only the first one is preserved.

Indeed. But it's not a regression. The way to remove whole node and write the new one makes the comments in the old nodes are removed together. It's a no-humful bug though.

> Yes, but it's not limited to just this file, but to all .xml. Try searching for макрос, close Notepad++ and check what character is in the config.xml file (<Find name="&#x043C;&#x0430;&#x043A;&#x0440;&#x043E;&#x0441;" />). We just have HTML entities, not plain text. I don't know why TinyXML writes it like that, but if we consider it a bug/defect, it should rather be considered separately.

So for only shortcut.xml has such bug. Please create a new issue about unreadability of shortcut.xml while there's non-English character, and assign to me. I will see what I can do about it.

@Yaron10 
> EditPad displays them in "readable characters" if the encoding is set to:

I think the better solution is make tinyxml write it correctly, instead of adding another system/mechanism over on it.


@rdipardo 
> As https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12670#issuecomment-1359902802:

    TinyXML is not being developed anymore.

We got tinyxml source code so I'm gonna try to make it work.

**Comment by donho** [comment]
Now shortcut.xml can be saved as human readable Unicode attribute value.
Could you guy check it please?

**Comment by alankilborn** [comment]
>Could you guy check it please?

With that commit, my complaint [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/96b56f61f90d8b3f27d8fab804676a8ddcbd4a22#commitcomment-108781009) is resolved, and everything is human readable.  Thanks, @donho !

**Comment by Yaron10** [comment]
@donho,

> So for only shortcut.xml has such bug.

As @ArkadiuszMichalski has mentioned the problem was NOT unique to `shortcut.xml`.

> Yes, but it's not limited to just this file, but to all .xml. Try searching for макрос, close Notepad++ and check what character is in the config.xml file (). We just have HTML entities, not plain text.

Anyway, with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13538/commits/9289bb2d4ae616e9042b40a883abaf81bcc32a9b the issue in `shortcut.xml` is solved. 👍 

"One small step for `tinyxmlA.cpp`, one giant leap for Notepad++." :)
Thank you for your work.

The problem in `config.xml` still exists.
Search-terms and file-names are still not "human readable".

Search for `שלום`.

תמונה

***

I may not be by my PC tomorrow.

**Comment by donho** [comment]
> As @ArkadiuszMichalski has mentioned the problem was NOT unique to `shortcut.xml`.
> 
> > Yes, but it's not limited to just this file, but to all .xml. Try searching for макрос, close Notepad++ and check what character is in the config.xml file (). We just have HTML entities, not plain text.

Please check the latest commit which fixes this issue.

**Comment by Yaron10** [comment]
@donho,

It's not consistent.

Closing/restarting NPP, I get different results both in `config.xml` and in `Find what`.

תמונה

First - correct.
Second - wrong.

תמונה

Thanks again. I appreciate it.
Good night.

**Comment by donho** [comment]
Thank you @Yaron10 for your test.
I have checked in code source and there's no trivial way to make it right, so the latest commit is reverted.

**Comment by ArkadiuszMichalski** [comment]
@donho 
>After save/change macro's name we lost some default comments in [shortcuts.xml ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/shortcuts.xml). Only the first one is preserved.

>>Indeed. But it's not a regression. The way to remove whole node and write the new one makes the comments in the old nodes are removed together. It's a no-humful bug though.

Maybe add some function that will copy all of node's comments before deleting them and then insert them at the beginning when we restoring  a node (the order of occurrence can be memorized or omitted)? Thanks to this, the default ones would be remembered, but also all ours that we will add later (which is also rather expected). From what I can see this could cover `InternalCommands`, `Macros`, `UserDefinedCommands`, `PluginCommands`, `ScintillaKeys`.

**Comment by Yaron10** [comment]
@donho,

> I have checked in code source and there's no trivial way to make it right, so the latest commit is reverted.

👍 
Thank you for looking into it and trying. 
It's surely not a bug anyway.

**Comment by alankilborn** [comment]
Is this the end? :-(

**Comment by rddim** [comment]
There is already opened issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13222

**Pull request closed without merging**
