### PR TITLE
Fix Change History wrong display after "Reload from Disk" command

### LINKED ISSUE #12261: Reloading a file will mark all lines as changed in change history bar
Title pretty much explain all there is to it.

Stock notepad++ 8.4.6 32bits (if that matter...). No plugins, besides standard ones.

### LINKED ISSUE #12319: Change History Margin - reloading document
First time posting in GitHub, so apologies if I am doing something wrong.

I have just updated to the latest version of Notepad++ (v8.4.6 - 64bit) on my Windows 11 Pro.
I really like the change history margin. I did however find a slight annoyance with it:

If I reload the document (Reload from disk, or CTRL + R) then the history margin of the entire document is marked with a green bar. This then makes it more difficult to distinguish new changes, as they get 'lost' in the green bar, defeating a bit its purpose. The only way I could find to 'clear' the history margin again was to close the document and then open it again.

I believe a better option would be to simply 'clear' the history margin on reload, as if the document had just been opened for the first time.

Thank you for your time.

### LINKED ISSUE #13735: [Feature requests] Option to clear 'Change history margin' when reloading file from disk
Please add option to clear/reset 'Change history margin' after file is reloaded from disk.

### PR DESCRIPTION
**Pull request by donho**
The code for fixing is from Change Lines plugin:
https://github.com/vinsworldcom/nppChangedLines/blob/main/PluginDefinition.cpp

Fix #12319, fix #12261, fix #13735

### CODE REVIEW

**Comment by rdipardo** [comment]
This would [wipe out the undo buffer] along with the change indicators! Seems like [*un marteau pour écraser une mouche*] to me. 

You could at least create a warning dialog, so users will know they can't get their revisions back. Some are still upset about the *last* time you began clearing the undo buffer (to save memory): #5813

[wipe out the undo buffer]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fcebb59fa4ccf3da42534a32a8980683e1da9764/PowerEditor/src/Notepad_plus.cpp#L8666
[*un marteau pour écraser une mouche*]: https://en.wiktionary.org/wiki/écraser_une_mouche_avec_un_marteau

**Comment by Yaron10** [comment]
@donho,

Great. 👍 
Thank you for your work.

@vinsworldcom,

Thank you for your contribution to the Change History feature. 👍 

@rdipardo,

Could you please explain your concern? This PR is only addressing Reload.

**Comment by vinsworldcom** [comment]
> This would [wipe out the undo buffer](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fcebb59fa4ccf3da42534a32a8980683e1da9764/PowerEditor/src/Notepad_plus.cpp#L8666) along with the change indicators!

Correct.  So use with caution I what @rdipardo  is saying - or perhaps inform users with a confirm dialog.  I know it does this so I don't care and just use it if the full green change margin for a new file really bothers me.

[Note from](https://www.scintilla.org/ScintillaDoc.html#ChangeHistory) :

> Change history depends on the undo history and can only be enabled when undo history is enabled and empty. It should be enabled once when a file is loaded after calling [SCI_SETUNDOCOLLECTION(true)](https://www.scintilla.org/ScintillaDoc.html#SCI_SETUNDOCOLLECTION) and [SCI_SETSAVEPOINT](https://www.scintilla.org/ScintillaDoc.html#SCI_SETSAVEPOINT).

So that's what I do.

Cheers.

**Comment by donho** [comment]
@Yaron10 
Thank you for checking.

@vinsworldcom 

> or perhaps inform users with a confirm dialog. I know it does this so I don't care and just use it if the full green change margin for a new file really bothers me.

It's applied only to "Reload from Disk" command in which undo buffer is already wiped out.
It's a correct behaviour IMO after the command in question.

**Comment by vinsworldcom** [comment]
> Reload from Disk" command in which undo buffer is already wiped out.
It's a correct behaviour IMO

In that case, I would agree!

Cheers.

**Pull request closed without merging**
