### PR TITLE
[xml] Update romanian.xml

### PR DESCRIPTION
**Pull request by AndreiMiloiu**

### CODE REVIEW

**Comment by AndreiMiloiu** [comment]
@donho I know that I promised you I made all the needed changes. However, I discovered these days. Can I fix them? There are not many. If not and if the PR is good, this PR is ready.

**Comment by donho** [comment]
@AndreiMiloiu 
Please put all your fixes for the one last time here.
Take your time. This PR won't be in v8.7.3 but in v8.7.4

**Comment by AndreiMiloiu** [comment]
Good, thank you very much! Should I convert it as a draft?

**Comment by AndreiMiloiu** [comment]
@donho I'm ready. I also followed https://github.com/notepad-plus-plus/notepad-plus-plus/commit/83080c34040f66ea28841302270d2bc2d7dd457a commit.

**Comment by AndreiMiloiu** [comment]
@donho I'm ready. I also followed https://github.com/notepad-plus-plus/notepad-plus-plus/commit/83080c34040f66ea28841302270d2bc2d7dd457a commit.

**Comment by AndreiMiloiu** [comment]
The file was updated with the new strings in the last commit.

**Pull request closed without merging**
