### PR TITLE
disable upward searches in regular expression mode

### LINKED ISSUE #3640: Backward-direction checkbox enabled with Reg Exp search mode (at N++ startup)
### Description of the Issue
In Notepad++ 7.5, with the introduction of the "Backward direction" checkbox in the Find dialog, the checkbox is sometimes enabled when the search mode is Regular Expression.  It should never be enabled when the search mode is Reg Exp.

### Steps to Reproduce the Issue
1. Start Notepad++ 7.5 (32-bit) from a fresh unzip of the portable install.
2. Execute any Find operation with Regular Expression as the search mode (note that when the search mode is changed to Reg Exp the "backward direction" checkbox becomes disabled--correct behavior).
3. Quit and restart Notepad++ 7.5.
4. Invoke the Find dialog.  Note that the search mode is Reg Exp but the "backward direction" checkbox is now incorrectly enabled.

### Expected Behavior
Any time the search mode is set to Reg Exp (including if this is the case when Notepad++ starts up), the "backward direction" checkbox needs to be disabled.

### Actual Behavior
See point 4 above.

### Debug Information
Notepad++ v7.5   (32-bit)
Build time : Aug 15 2017 - 23:02:57
Path : ...\npp.7.5.bin_UNCHANGED\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

image

### PR DESCRIPTION
**Pull request by sasumner**
Fixes #3640, although that is only part of the story.  The full story, debated before, is that regular expression searching in a backward direction from the caret position causes matches that the user does not expect.  The best thing that was decided to do (group decision) is to fully disable upward searching.

@donho , I don't know if you disallow this type of coding, but it isn't in the contributing guide, so it is OK until you say it is not.  :-)
If you don't like it, I will change it.  
Here's what I mean:

image

I think this IF statement, used above in the image:

`if ((id == IDM_SEARCH_FINDPREV) && (op._searchType == FindRegex))`

has a bit clearer meaning than its opposite:

`if (!((id == IDM_SEARCH_FINDPREV) && (op._searchType == FindRegex)))`

### CODE REVIEW

**Comment by donho** [comment]
>  I don't know if you disallow this type of coding, but it isn't in the contributing guide, so it is OK until you say it is not. :-)

@sasumner It is OK for me such explicit way.
However, I think it's overlooked in this way to disable exgexpr upward search. It's enough to disable it from UI (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5a951531ad440c0080880b5ddcfda76f28071455).

**Comment by sasumner** [comment]
@donho 

>It's enough to disable it from UI (5a95153).

I do not think that it is enough to do just that.  
I have tested that commit and found out that:

1. Shift+F3 will incorrectly perform a backward regex search
2. With input focus in Find window, Shift+Enter will incorrectly perform a backward regex search
3. Macros that were recorded with an earlier version that allows backward regex search will still play back that search (should be disallowed)
4. Macros that are hand-edited to for a backward regex search will still play back that search (should be disallowed)

Point 3 is arguable, but you can't have point 4 without point 3.

**Comment by donho** [comment]
OK, good point.
Please solve the conflict and I will merge it.

**Comment by donho** [comment]
Thank you @sasumner for the merge.
However the whole contet of `FindReplaceDlg.cpp` has beed removed and added.
Could you check it please?

**Comment by sasumner** [comment]
@donho 

Hmm, I simply used github's web-based conflict resolver for this very simple case.
I guess I don't know what it does behind the scenes?

**Comment by sasumner** [comment]
I suppose I will just give up.

**Pull request closed without merging**
