### PR TITLE
Fixed defect and optimization

### PR DESCRIPTION
**Pull request by SinghRajenM**
1. Fixed defect #7523
2. Optimization
    1. There was duplicate code for `MAIN_VIEW` and '`SUB_VIEW` which is now brought under common code.
    2. There was just a minor difference which is kept as it was [here](https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...SinghRajenM:src_fixedDoubleSaveConfirmationIfCloned?expand=1#diff-76c62ef652708b4b7b02f049a16b0629R931) and [here](https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...SinghRajenM:src_fixedDoubleSaveConfirmationIfCloned?expand=1#diff-76c62ef652708b4b7b02f049a16b0629R964).

### CODE REVIEW

**Comment by SinghRajenM** [comment]
@chcg  this is a bug more than enhancement.

**Comment by sasumner** [comment]
That is a lot of code changed -- perhaps it will not be liked for that reason?

**Comment by sasumner** [comment]
Shouldn't there be a more descriptive name that will go into the history of the project than "Fixed defect and optimization"?

**Comment by SinghRajenM** [comment]
> 
> 
> That is a lot of code changed -- perhaps it will not be liked for that reason?

Not exactly. Changes for defect fix is just below piece of code - 

``` C++
if (uniqueBuffers.find(id) != uniqueBuffers.end())
	continue;
uniqueBuffers.insert(id);
```

Rest is just bringing two `for` loop's identical code together for maintainability.

>
>Shouldn't there be a more descriptive name that will go into the history of the project than "Fixed defect and optimization"?

Well, I agree. But in this case it is fix for the defect which well described #7523, so the content for change log can be picked from there. BTW almost in all the cases, @donho prepares change log himself irrespective of any title PR.

**Comment by sasumner** [comment]
>Rest is just bringing two for loop's identical code together for maintainability.

Yes, but @donho doesn't typically like these types of changes. :-)

>...content for change log...

I didn't mean the `change.log`, I meant the github history so that if one is looking for something in the commit history they find something more meaningful than "Fixed bug".

But yes, I have prepared "suggested change.log" entries to go along with my PRs, which have been ignored by @donho.  I wish they were accepted, because they are more descriptive than the ones @donho writes.  I acknowledge that English isn't @donho's mother tongue, which makes it even more unusual that he just doesn't accept someone's suggested change.log entry...written by someone for whom English IS a first language.

**Comment by donho** [comment]
@sasumner 
My viewpoint regarding the change log is, shorter is better. That should also make users understand easily. Anyway, I'll **try to** use the issue title in change log next time, especially if it comes from the **English native speakers** ;)

**Comment by donho** [comment]
@SinghRajenM 
When I saw the number of the lines of code, all I wanted to do is reject the PR.
Please consider the guideline of contribution:
*In short: The easier the code review is, the better the chance your pull request will get accepted.*
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

Please redo PR with the pertinent title.
The PR contains only strictly minimum needed change.
Thank you.

**Comment by sasumner** [comment]
@donho said

>shorter is better

Agreed, but if it needs to be a bit longer to convey meaning, to me it is OK and better.

I would also like to see an issue # and/or PR # added.  :-)

**Comment by sasumner** [comment]
I previously said:

>That is a lot of code changed -- perhaps it will not be liked for that reason?

@SinghRajenM Looks like I nailed that one.

**Comment by SinghRajenM** [comment]
@sasumner IMHO @donho should reconsider this PR. Because - 
1. Only duplicate code was removed by combining both `for` loops together.
2. It increases project maintainability. Please note this PR reduces around 55~60 LOC in file `NppIO.cpp`
3. Last but not least, my next PR (improvement for "close all but this" as I promised here https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7502#issue-336028036) will be based on this PR which will have less changes. If we don't consider this PR, then next PR will be again with more changes which also violates `shorter is better`. So somewhere we need to balance, right?

**Comment by bahusoid** [comment]
@donho  Have you tried to review it with whitespace changes disabled?

image

All the code noise due to refactoring that changed nesting levels of code. But overall it's a good change and quite reviewable with disabled whitespace changes.

**Comment by SinghRajenM** [comment]
>with disabled whitespace changes

@bahusoid interesting, I was not aware of this GitHub feature. Salute!!!

**Comment by sasumner** [comment]
@SinghRajenM For the record, I was not disagreeing with your PR in any way.  :-)

**Pull request closed without merging**
