### PR TITLE
option to enable explicit comment folding for c++ like languages

### PR DESCRIPTION
**Pull request by niekma**
This pull request adds the option to enable explicit comment folding for c++ like languages mentioned in issue #12337.

### CODE REVIEW

**Comment by dfs-** [comment]
I‘ve never seen a C++ IDE do this. Is this something common or a special feature?

**Comment by niekma** [comment]
It is an option the ScintillaComponent has (fold.cpp.comment.explicit). I tend to think of it as a special feature.

In previous versions of Notepad++ this option was enabled by default. Because of issue #4560 it was turned off (see pull request #10948).

I used it a lot, because it was a convenient way to fold larger blocks of code. So it would be nice to be able to turn it back on again. Because of the issue it is off by default.

**Review by donho — COMMENTED** [review]
I'm not convinced this feature is "most wanted" feature, and  it's even a confusing feature for users. This PR will be suspended to see if there are similar requests coming.

**Comment by niekma** [comment]
Sorry, did not intend to give the impression that this is a "most wanted" feature.

My I ask, if there is another way to do region folding?

**Comment by ArkadiuszMichalski** [comment]
@niekma You can use plugin like NppExec or PythonScript to get the same effect.

**Comment by niekma** [comment]
@ArkadiuszMichalski
I tried NppExec. The script is working, but I have to run it manually, because the setting is overwritten. I also tries NppEventExec. It is possible to set it up, but as you described in #12213 it would be nice, if it would work out of the box.
Thank you for your suggestions.

**Comment by victorel-petrovich** [comment]
> I‘ve never seen a C++ IDE do this. Is this something common or a special feature?

I was using it in Geany editor (also Scintilla based).
Reliably usable whenever you need hide lines that you cannot otherwise (the "Hide Lines" , Alt+H, is non-toggable and non-persistent). 
Just wish it were generalized to any other language, using `x{`, `x}`, with `x` being their own symbol for commenting rest of lines. 
But, one step at time...

**Comment by victorel-petrovich** [comment]
> I'm not convinced this feature is "most wanted" feature, and it's even a confusing feature for users. This PR will be suspended to see if there are similar requests coming.

FWIW: I was a rather beginner user of advanced editors when using Geany, and that was not confusing at all. It just needs a good name , like `Enable folding by //{ and //}`, and it will be clear. Lovers of folding will attempt anything that has "folding" in mentioned ;).

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12338#pullrequestreview-1143339187

**Pull request closed without merging**
