### PR TITLE
Tab highlighting on file change

### PR DESCRIPTION
**Pull request by HBerni**
Added support to _highlight_ (tab header blinks) inactive tabs when
automatic file change detection had detected a file change.
File reload-dialog is shown when tab is activated by user.

Added option "Highlight tab" in "preferences/MISC./File Status Auto-Detection"

See #1087
Possible workaround for #745, #1481

### CODE REVIEW

**Comment by corylulu** [comment]
This is exactly the feature I have been wanting for a long time!

**Comment by corylulu** [comment]
After testing for a day, I found one small issue with this update. Now, tabs will periodically flicker like they are occasionally being redrawn. This wasn't happening before, so I'm assuming it's due to these changes. I'll look at the source myself and see if I can find the problem, but I'm not very familiar with the code, so I might have to give up if I run out of time.

**Comment by Duellmann** [comment]
Please do not make *blinking tab header* the default for highlighting tabs whose content has changed from outside. Having to click on 20 blinking tabs to get rid of the blinking is almost more horrific than clicking 20 modal alerts away! Just choose a stable, notable highlight color for such tabs (blinking must be optional).

**Comment by Duellmann** [comment]
Please do NOT make *blinking tab header* the default behaviour for tabs whose file content has changed externally. Having to click on dozens of tabs AND one tab-modal prompt each to get rid of blinking eye sore is even more horrific than just clicking dozens of app-modal prompts away. Just choose a stable notable highlight-color or some other indication for such tab headers. Blinking must be optional.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ba60fbdd715d647aa5ce7be5b6b75182b4a52951

**Pull request closed without merging**
