### PR TITLE
Fix task list adjust size v8.4.9 regression

### PR DESCRIPTION
**Pull request by TaleTN**
Fixes the minor regression I reported here:
https://community.notepad-plus-plus.org/post/83819

### CODE REVIEW

**Comment by alankilborn** [comment]
You should create an "issue" here, before submitting a related PR.

**Comment by sXNA** [comment]
duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13054

**Comment by TaleTN** [comment]
> You should create an "issue" here, before submitting a related PR.

Oops sorry, I didn't know that, but #13054 is actually "my" issue... Anyway, I will close this pull request then, and comment on the other one.

**Comment by alankilborn** [comment]
I didn't know there was an issue already in existence.
All you really need to do is put "Fix # 13054" right next to where you have:

>Fixes the minor regression I reported here:

**Pull request closed without merging**
