### PR TITLE
Fix for Alt+Tab doesn't show NPP #6244

### PR DESCRIPTION
**Pull request by PalashBansal**
**Issue is because of Tool window being used instead of normal window for these 2 dialogs- "Close All" and "Rename"**
Known issue already discussed on- https://stackoverflow.com/questions/3760571/showdialog-makes-app-window-disappear-from-windows-alt-tab-list
Excerpt from https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles -

_WS_EX_TOOLWINDOW 0x00000080L_ | The window is intended to be used as a floating toolbar. A tool window has a title bar that is shorter than a normal title bar, and the window title is drawn using a smaller font. **A tool window does not appear in the taskbar or in the dialog that appears when the user presses ALT+TAB.** If a tool window has a system menu, its icon is not displayed on the title bar. However, you can display the system menu by right-clicking or by typing ALT+SPACE.
-- | --

_DS_MODALFRAME_ is added for "Close All" dialog, because after making it normal window, it started showing default empty windows file icon.

### CODE REVIEW

**Comment by donho** [comment]
I can not accept your PR if I cannot reproduce the bug.
Could you provide the detail instructions to reproduce it?

**Comment by xylographe** [comment]
Just as a reference to all, reproduction instructions in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6244#issuecomment-545389473.

**Comment by donho** [comment]
@xylographe 
Please confirm me if this PR fix the issue.

**Comment by xylographe** [comment]
@donho 
Yes, this PR fixes the issue in both cases: "Rename Current Tab" and "Save" dialogue.

OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0

**Pull request closed without merging**
