### PR TITLE
Added ability to toggle search results window

### PR DESCRIPTION
**Pull request by Vinatorul**
I have added a feature for Issue #61 
Now pressing _Alt+F7_ you can toggle search result window since the first search took place.
Also you can access it through _Search_ popup menu.

### CODE REVIEW

**Comment by NN---** [comment]
+1 !

**Comment by Rikk** [comment]
+1
Although, imo, it makes more sense to use the same key (F7) to open/close (= toggle).

**Comment by Vinatorul** [comment]
> Although, imo, it makes more sense to use the same key (F7) to open/close (= toggle).

As I replied in Issue #61 now F7 is using to switch between main and search window (if search window is closed, that it opens).
And Alt+F7 is toggling search window.

**Comment by donho** [comment]
Already implemented since long time.

**Comment by Vinatorul** [comment]
lol

**Pull request closed without merging**
