### PR TITLE
Make Scintilla build properly with GCC/MinGW

### LINKED ISSUE #1655: Scintilla cannot be built with GCC/MinGW
Some of the Notepad++ extensions cause compile errors with gcc.

### PR DESCRIPTION
**Pull request by marcows**
Fixes #1655.

### CODE REVIEW

**Comment by vgturtle127** [comment]
@marcows Does vanilla Scintilla build fine with GCC/MinGW?

**Comment by marcows** [comment]
> @marcows Does vanilla Scintilla build fine with GCC/MinGW?

Yes.

**Comment by vgturtle127** [comment]
@marcows OK, I had never tried with MinGW, so I wasn't sure. Thanks.

**Comment by marcows** [comment]
According to Scintilla's README, Visual Studio is the main development system for the Windows build, but MinGW is also officially supported.

Also have a look at the corresponding issue.
There I wrote that Notepad++ extensions cause the errors.

**Comment by vgturtle127** [comment]
@marcows Oh, I read that but I guess I misunderstood. Which extensions? Or is it extensions in general?

**Comment by marcows** [comment]
With extensions I meant the differences in source code compared to vanilla Scintilla.

**Comment by vgturtle127** [comment]
@marcows Oh, OK. I'm on a roll today. :laughing:

**Pull request closed without merging**
