### PR TITLE
Appveyor artifacts debug and release

### LINKED ISSUE #1942: Appveyor artifacts debug and release
Fix the Appveyor artifacts configuration.

Also generate the release configuration

### PR DESCRIPTION
**Pull request by cmeriaux**
Fixes #1942

@donho it's finally working. Here is the log https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.116

There are 4 jobs with differents platform and configuration.
Artifacts are also available
I tested on my computer that artifacts are actually x86 or x64 (notepad++.exe and scilexer.dll) and start up well.

As you asked, I removed the boos support

### CODE REVIEW

**Comment by donho** [comment]
@cmeriaux  For the reason that I ignore, I have committed this PR under my name (at least it's what Github displays).

@milipili Have you any idea about what it has happened?

Here're the comment I've used:
```
git remote add cmeriaux https://github.com/cmeriaux/notepad-plus-plus
git fetch cmeriaux
git merge cmeriaux/appveyor_release
git rebase -i
git commit --amend
```

Here's the whole console output:
donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git remote add cmeriaux https://github.com/cmeriaux/notepad-plus-plus

```
donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git fetch cmeriaux
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 29 (delta 18), reused 10 (delta 10), pack-reused 0
Unpacking objects: 100% (29/29), done.
From https://github.com/cmeriaux/notepad-plus-plus
 * [new branch]      appveyor_release -> cmeriaux/appveyor_release
 * [new branch]      exportShortcuts -> cmeriaux/exportShortcuts
 * [new branch]      master     -> cmeriaux/master

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git merge cmeriaux/appveyor_release
Removing appveyor-build.cmd
Merge made by the 'recursive' strategy.
 appveyor-build.cmd | 11 -----------
 appveyor.yml       | 52 ++++++++++++++++++++++++++++++++++++++++++++++------
 2 files changed, 46 insertions(+), 17 deletions(-)
 delete mode 100644 appveyor-build.cmd

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git rebase -i
[detached HEAD 061b356] Add x64 package
 Date: Tue Jul 12 09:19:56 2016 +0200
 4 files changed, 119 insertions(+), 24 deletions(-)
 delete mode 100644 appveyor-build.cmd
 rewrite appveyor.yml (90%)
Successfully rebased and updated refs/heads/master.

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git commit --amend
[master 79028b3] Appveyor artifacts debug and release for x86 & x64
 Date: Tue Jul 12 09:19:56 2016 +0200
 4 files changed, 119 insertions(+), 24 deletions(-)
 delete mode 100644 appveyor-build.cmd
 rewrite appveyor.yml (90%)

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

error: unable to read askpass response from 'C:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass'
Password for 'https://github.com':
remote: Anonymous access to notepad-plus-plus/notepad-plus-plus.git denied.
fatal: Authentication failed for 'https://github.com/notepad-plus-plus/notepad-plus-plus.git/'

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.71 KiB | 0 bytes/s, done.
Total 7 (delta 4), reused 0 (delta 0)
To https://github.com/notepad-plus-plus/notepad-plus-plus.git
   2573f4b..79028b3  master -> master

donh@DESKTOP-2Q5N80N MINGW64 /c/sources/notepad-plus-plus (master)
```

**Comment by cmeriaux** [comment]
@donho arrrf top bad
It's due to your  commit amend.
You should have used github website to integrate my ticket. Then you do a git pull in your local repository

**Comment by milipili** [comment]
We do not use github for merging PR since it creates a shitty history. `commit --amend` has nothing to do with that, it does not change the author by default. It does not seem that you did something wrong at a first glance. Should probably take a look at your configuration and your aliases

**Comment by donho** [comment]
@cmeriaux Sorry for committing your PR under my name. The procedure is good but there must be somethings wrong I have done. I will try to figure out the problem to prevent from the same error. I'll let you know if I get the cause.

**Comment by cmeriaux** [comment]
I think you "commit amend" some changes on my commit because I never modified files 

- .gitignore  (ignore +PowerEditor/installer/zipped.package.release64/)
-  PowerEditor/installer/packageAll.bat (sign release 64 binaries file)

Plus, my PR was named "Appveyor artifacts debug and release", now your commit is named "Appveyor artifacts debug and release for x86 & x64". This may be the main reason why github ignore me as an author

**Comment by milipili** [comment]
As said `commit --amend` preserves the author. We do that for a long time and I do the same on some other projects (to be sure I reproduced the procedure with my account, you can take a look if you want). However, as you noticed, some changes do not come from your PR, hence I suspect some mix up with another commit (or other changes) :)

**Comment by milipili** [comment]
@donho: Next time, if you want to check, you may ask `git log` (or any other pretty log printer) before pushing anything. It will show you the author of the commit (there is a difference between the author of the commit, and the author of the push). In this case you would be able to rollback.

**Comment by cmeriaux** [comment]
@donho  @milipili 
The problem may appeared during the command "git rebase -i". 
Git should have proposed to you two lines (my commit and your commit). You may have told him to squash my commit into yours 
For the record, Rebase propose different command : 

```
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#
```

**Pull request closed without merging**
