### PR TITLE
Added more improvements to C# intellisense

### PR DESCRIPTION
**Pull request by MCCshreyas**
Added bunch of overloads for important methods in Console class including WriteLine and ReadLine.

### CODE REVIEW

**Comment by MCCshreyas** [comment]
But why? Is there anything that I am missing? 🤔🤔

**Comment by dail8859** [comment]
Some things I've noticed:

- Since you have `.` in your autocomplete words you need `additionalWordChar="."` in your `<Environment>` tag. See the C++ autocomplete xml file.
- You need to remove the opening parenthesis for the keywords.
- The way you overloaded the functions is incorrect

untitled

> Is there anything that I am missing?

It's called testing your PR :)

**Comment by MCCshreyas** [comment]
Ohhhh. I see.
I will make required improvements in code in upcoming hours.

**Comment by MAPJe71** [comment]
Succeeded by #4097.

**Pull request closed without merging**
