### PR TITLE
Update breton.xml to v7.8.3

### PR DESCRIPTION
**Pull request by xylographe**
Clean-up of PR #7816.

### CODE REVIEW

**Comment by xylographe** [comment]
Added item 6348, and updated version to 7.8.3.

**Comment by donho** [comment]
@xylographe 
So I can close #7816 and use this one, can I ?

**Comment by xylographe** [comment]
@donho Yes.

**Comment by donho** [comment]
Et ne me dis pas que tu sais parler breton aussi :)

**Comment by donho** [comment]
@xylographe There are missing translation eventually, could you check them please?

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f44c3579994e0259c2f5ce24cf41555b92a0d005

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cbd1e83c02e5f0b9ddc1018eb3ac6554d6901b14

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ab207db6f7e06ef15951c5b2613582387a617f63

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a1d048fdd9367d37dbe17134cb88e4e24f83c311

**Comment by xylographe** [comment]
I haven't found missing items,
```
PS> git rebase master pr/2001060526/breton
First, rewinding head to replay your work on top of it...
Applying: Update breton.xml to v7.8.3
PS> npp-check-translation.ps1
**  English (7.8.3) ==> Brezhoneg (7.8.3)  **  PowerEditor\installer\nativeLang\breton.xml
```
Ne t'inquiète pas, je ne comprends pas du tout le breton. :)

**Comment by donho** [comment]
@xylographe there are somethings wrong in your branch:
```
$ git pull https://github.com/xylographe/notepad-plus-plus.git pr/2001060526/breton
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 44 (delta 32), reused 33 (delta 32), pack-reused 10
Unpacking objects: 100% (44/44), done.
From https://github.com/xylographe/notepad-plus-plus
 * branch              pr/2001060526/breton -> FETCH_HEAD
Updating 12bb0efc..02d83a62
Fast-forward
 PowerEditor/installer/nativeLang/breton.xml        | 1897 ++++++++++++--------
 PowerEditor/installer/nativeLang/bulgarian.xml     |   55 +-
 PowerEditor/src/Notepad_plus.cpp                   |    4 +-
 PowerEditor/src/NppCommands.cpp                    |    2 +-
 PowerEditor/src/NppIO.cpp                          |    8 +-
 PowerEditor/src/NppNotification.cpp                |    9 +-
 PowerEditor/src/Parameters.cpp                     |    4 +
 PowerEditor/src/Parameters.h                       |    2 +
 .../src/ScitillaComponent/ScintillaEditView.cpp    |   79 +-
 .../src/ScitillaComponent/ScintillaEditView.h      |    5 +-
 PowerEditor/src/langs.model.xml                    |    2 +-
 11 files changed, 1248 insertions(+), 819 deletions(-)
```

**Comment by donho** [comment]
My bad. 
It was my master which didn't updated.
Sorry for the bad alert.

**Pull request closed without merging**
