### PR TITLE
Feature #8074 Macro Move/Sort Buttons Implemented

### PR DESCRIPTION
**Pull request by szaboch**
Implemented the Macro move up/down/sort button as requested at Issue #8074.

Currently only supported for the Macro tab of the Shortcut Mapper menu, however the code could be expanded upon to support the other Shortcut Mapper tabs

### CODE REVIEW

**Comment by szaboch** [comment]
Capture

**Comment by szaboch** [comment]
> I don't think a comment like "this is bad" is going to get accepted.

That comment is in there multiple times for some of the other buttons in the Shortcut Mapper. I only included it because I saw the other buttons had it

For example if you're in the Scintilla Commands section of the shortcut mapper, the clear and delete buttons should not be clickable. You can see inside of the the associated switches:

`case STATE_SCINTILLA:
{
	return FALSE;			//this is bad
}`

**Comment by sasumner** [comment]
> I saw the other buttons had it

Coding styles change over the years.
A "new" comment like that begs for an explanation of why it is "bad".
Yours isn't "new", so it's probably OK.  Forget what I said.

**Comment by donho** [comment]
This PR is rejected for the following reasons:
1. These 3 buttons are unnecessary - move up/down could be mouse drag and drop, and sort could be controlled by the column header.
2. These 3 buttons work only for Macros, it makes them look clumsy.

**Comment by sasumner** [comment]
>move up/down could be mouse drag and drop

Two comments:
* Is there this kind of thing anywhere else in the UI?
* Mouse drag-and-drop only doesn't respect keyboardists.

**Pull request closed without merging**
