### PR TITLE
backward direction checkbox always enabled, even in regular exp. search mode

### LINKED ISSUE #3640: Backward-direction checkbox enabled with Reg Exp search mode (at N++ startup)
### Description of the Issue
In Notepad++ 7.5, with the introduction of the "Backward direction" checkbox in the Find dialog, the checkbox is sometimes enabled when the search mode is Regular Expression.  It should never be enabled when the search mode is Reg Exp.

### Steps to Reproduce the Issue
1. Start Notepad++ 7.5 (32-bit) from a fresh unzip of the portable install.
2. Execute any Find operation with Regular Expression as the search mode (note that when the search mode is changed to Reg Exp the "backward direction" checkbox becomes disabled--correct behavior).
3. Quit and restart Notepad++ 7.5.
4. Invoke the Find dialog.  Note that the search mode is Reg Exp but the "backward direction" checkbox is now incorrectly enabled.

### Expected Behavior
Any time the search mode is set to Reg Exp (including if this is the case when Notepad++ starts up), the "backward direction" checkbox needs to be disabled.

### Actual Behavior
See point 4 above.

### Debug Information
Notepad++ v7.5   (32-bit)
Build time : Aug 15 2017 - 23:02:57
Path : ...\npp.7.5.bin_UNCHANGED\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

image

### PR DESCRIPTION
**Pull request by sasumner**
Fixes #3640

### CODE REVIEW

**Comment by chcg** [comment]
@sasumner  Do you known what the regression in 6.3 was? Might this be fixed or modified by the updates of scintilla or boost?

**Comment by sasumner** [comment]
> @sasumner Do you known what the regression in 6.3 was? Might this be fixed or modified by the updates of scintilla or boost?

I don't.  6.3 was before my time.  I started with 6.7.5 four and a half years ago.  I have tried to elicit conversation on what this was a few times over the years, both here and on the Community, and anyone who might have known what the regression was either did not see it or chose not to respond.  Do you have any objection to this change?  It is fairly clear that the thing that is disabled in this one manner is allowed in at least two alternate ways of invoking, so this merely unifies the user interface...

**Comment by dinkumoil** [comment]
This logic is strange.

There is an inconsistency in GUI behaviour that allows users in some cases to perform actions that produce invalid results.

Instead of fixing the GUI inconsistencies in order to allow only valid user actions, you suggest a change that makes the GUI consistent in a way that users are **always** allowed to perform actions that produce invalid results.

That's not making things better, it's declaring a bug as a world-standard.

**Comment by sasumner** [comment]
@dinkumoil 

You posted the same comment here and in issue #3640 .  No sense in that or in posting the same reply here; please see my response in the comments for that issue.

**Comment by dinkumoil** [comment]
@sasumner 

Originally I wanted to leave my comment only here at the PR thread, but at first I accidentally left it at the issue thread. So I repeated my comment here because IMO the PR is more important than the issue.

To future readers: Please consider [this conversation](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3640) as well.

**Comment by xylographe** [comment]
There seems to be some confusion about backward regex search. It is correct that for some regex patterns the number of matches differs between forward and backward search. However, the conclusion that therefore backward regex search produces _invalid results_  is incorrect. The yielded results are consistent and logically valid. I don't see a compelling reason to prohibit backward regex search.

Hence, I go along with the uncomplicated solution to a minor issue, as provided by this PR.

**Comment by donho** [comment]
@xylographe 
> the conclusion that therefore backward regex search produces _invalid results_ is incorrect.

Yes, it doesn't work for old version of scintilla. However, it could be fine now with the new version.
Have you any example that regExpr backward search doesn't work?

**Comment by sasumner** [comment]
@donho 

I provide a good example regex search scenario in the issue for this PR.  Direct link: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3640#issuecomment-562273006

I don't think it has to do with Scintilla.  "Working" is sometimes a user interpretation.  Sometimes the results of a backward regex search may be unexpected, at first.  But if you take the time to understand it, it is consistent.  Thus, there isn't a "problem" with it, it simply sometimes gives different results than a forward regex search.

But in the end it is a decision for @donho backed by group voices here.  If no decision is made "soon", I will withdraw the PR and look at alternate "solutions".

**Comment by xylographe** [comment]
I guess, the alternative would be to always disable (grey) "backward direction" when "regular expression" is selected. Personally, I won't miss it, but I think, it's a tad patronizing.

**Comment by dinkumoil** [comment]
For sure, disabling backward direction regex search is indeed some kind of patronizing. BUT, all commenters involved in this PR have experience in giving support in the user forum. Wouldn't you agree that it is sometimes better to slightly patronize users than getting again and again the same user complaints and support requests why this or that feature doesn't work like expected?

A great example of wrong user expectations is [this thread](https://community.notepad-plus-plus.org/topic/18536/how-to-center-text) in the community forum. In short: The user complained about the lack of a "center text" feature in Notepad++ though allegedly there is a "align left" and a "align right" feature. Though he has been told that this kind of features is very uncommon for plaintext editors but are typical features of word processing software, he insisted that "center text" **should** be included in Notepad++ because the program is for text processing and additionally refered to his 35 years of experience working with computers (in marketing and advertisement business). Finally he tried to make the commenters feel ashamed by posting the advice he was given in another forum where someone told him to use the LTR/RTL writing feature to achive some kind of "align left"/"align right" behaviour. That clearly shows that he even didn't understand what he was doing when using those features.

I don't claim that backward regex search gives results which are wrong in a pure technical meaning. If one thinks about the results, he might have to admit that they are correct. Nevertheless, in most cases the results won't be that what a user has expected. Moreover, I bet they are even not helpful in most cases. And I bet there will be users complainig about the results.

So, why allow a feature which is not helpful and likely will create annoying support requests? Of course, it is a quick fix for the current inconsistency but it is "taking the lazy way" instead of doing it right (what I mean with "doing it right" I have elaborated about in [my posting in the issue thread](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3640#issuecomment-563196863)). And to say it again: I'm not a C++ dev, thus I can not do these changes by myself.

**Comment by sasumner** [comment]
As an additional data point, guy038 had some private email conversation with me on this issue (not sure why he didn't just comment here, but maybe he's not a github member and has his reasons for that).  Guy was more in favor of disabling backward regex searches entirely, rather than full-bore enabling.

>...getting again and again the same user complaints and support requests why this or that feature doesn't work like expected?

I think it's a catch-22 regarding user complaints with this.  It's either (a) _Why do backward regex searches work strangely in certain cases?_ or (b) _Why is backward search disabled when using regex?_.  Empirically, since I've been a Notepad++ user (version 6.7.5) backward regex search has been possible (methods not involving the direction checkbox), and I've seen exactly ZERO user complaints for (a).  We don't know the user reaction for (b), to a full disallow.  But, if we just consider the _Backward direction_ checkbox being disabled for regex search (current N++ behavior) only, I can recall exactly ONE user complaint...or maybe it wasn't a complaint but just a question.  The difference between zero and one complaint/query is likely statistically negligible over 4+ years; maybe the most conclusive thing we can pull from this is that user complaints probably would not be a problem.

With my _user_ hat on, rather than _developer_ hat, I know that I often walk back and forth among the matches in a search, and I don't remember any (non-contrived) time when the regex results were different enough to make me question the matches.  Not being able to move forward and backward through my hits, even in regex mode, would likely irk me every time I encounter it.  But that's just me as a _user_.

Maybe the best answer is to substantially change the search routines.  Instead of starting at the caret, all searches should cover the entire doc (BOF -> EOF) or maybe just BOF to caret and build a list of match positions within this space.  Then, code can look through the match list and see if the caret location satisfies.  Because the search to the "left" of the caret position will be covered by a forward search through that section of the doc, it is easy to determine the first, second, etc. backward moving result through the data.  This solves other problems as well, like the one posed in #6194.  So forward or backward searching would produce the same result, and there would be no need for disabling/disallowing anything.

**Comment by dinkumoil** [comment]
> (a) Why do backward regex searches work strangely in certain cases?
> I've seen exactly ZERO user complaints for (a)

The reason could simply be that users didn't try to use menu entries, toolbar buttons or whatever to do a regex search in backward direction while the search dialog has been open. And even if a user has tried to search in backward direction, when confronted with weird results I guess he might have thought "Oh well, weird results, but the 'search backward' checkbox is disabled so using the menu entry for that is possible but it is likely not to be a desired user action".

>... and build a list of match positions within this space. ... Because the search to the "left" of the caret position will be covered by a forward search through that section of the doc, it is easy to determine the first, second, etc. backward moving result through the data.

This is a really great suggestion though it causes a lot more effort.

**Comment by donho** [comment]
> I provide a good example regex search scenario in the issue for this PR. Direct link: #3640 (comment)

Indeed, still buggy in the current version of Scintilla.

**Comment by Ekopalypse** [comment]
I agree with @dinkumoil about the assumption users might have. 
For example, if I start with an forward search to find something and then overshoot my target and want to go back, I want to find the same result as I did before.
Technically it might be right to return a different match, but, as said, I think most users won't expect it.
From my point of view there are only two options:
1. disable regex backward search or
2. In case of a backward search do an forward search always and keep a list of the matches to get backward from current caret position

I did a test with the given example from @sasumner  with these editors
Notepad++
CudaText, Geany  ( those don't allow backward searches )
and Eclispe, VSCode, Sublime, Atom, Notepad2, PSPad, WingWare, PyCharm (these do forward searches and jump back to those matches)

**Comment by donho** [comment]
@sasumner 
> I don't think it has to do with Scintilla. "Working" is sometimes a user interpretation. Sometimes the results of a backward regex search may be unexpected, at first. But if you take the time to understand it, it is consistent. Thus, there isn't a "problem" with it, it simply sometimes gives different results than a forward regex search.

I've got your point. But Notepad++ users don't have the time to understand such logic. They just want a tool do things as they expected. 

Let's look at alternate "solutions" -> please grey out also arrow down ▼ button in reg expr mode.

**Pull request closed without merging**
