### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**

### CODE REVIEW

**Comment by donho** [comment]
@ArkadiuszMichalski 
For what this test?

**Comment by ArkadiuszMichalski** [comment]
@donho I need to check the versions of the currently used tools. Then I update build.md to take into account migrating to Msys2. These are short checks so I won't be blocking the build queue unnecessarily.

**Comment by ArkadiuszMichalski** [comment]
@ozone10 I will add some line to display using version of GCC, Make and SH, but now I have to wait when other builds will be completed.

**Comment by ozone10** [comment]
@ArkadiuszMichalski 
ok

I did some testing, there was issue, MSYSTEM variables were set wrongly, my mistake.

this should be right
```
  install:
    - set PATH=C:\msys64\usr\bin
    - if "%platform%" EQU "i686" set MSYSTEM=MINGW32
    - if "%platform%" EQU "x86_64" set MSYSTEM=MINGW64
    - if "%configuration%" EQU "Debug" set DEBUG=1
    # uncomment lines below to update packages to use latest gcc
    #- bash -lc "pacman --noconfirm -Syuu"
    #- bash -lc "pacman --noconfirm -Syuu"
    #- if "%platform%" EQU "i686" bash -lc "pacman --noconfirm -S mingw-w64-i686-gcc mingw-w64-i686-make"
    #- if "%platform%" EQU "x86_64" bash -lc "pacman --noconfirm -S mingw-w64-x86_64-gcc mingw-w64-x86_64-make"
    - if "%platform%" EQU "i686" set PATH=C:\msys64\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
    - if "%platform%" EQU "x86_64" set PATH=C:\msys64\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
    - bash -lc "gcc -v 2>&1 | grep -E '^Target|^gcc'"
```

last line will print
for platform "i686"
```
Target: i686-w64-mingw32
gcc version 12.2.0 (Rev1, Built by MSYS2 project) 
```
for platform "x86_64"
```
Target: x86_64-w64-mingw32
gcc version 12.2.0 (Rev1, Built by MSYS2 project)
```

**Pull request closed without merging**
