### PR TITLE
Improve the language detection at the beginning of a file

### LINKED ISSUE #1014: NP++ 6.8.4; Programming language can be detected via file content for php...
If php-file with unknown extension starts with "<?php" ("" just for clarity), it is not regocnized as php-file.
If it starts with "<?php ", then it is regocnized as php-file.

Is there really a need for the space character?

See screen captures of test file, one with space and another without space in
https://onedrive.live.com/redir?resid=FCCA3C47C268C13A%217100

### PR DESCRIPTION
**Pull request by ffes**
* The Shebang detection is much improved:
  * detect more languages
  * not tied to any specific full path
  * See https://en.wikipedia.org/wiki/Shebang_%28Unix%29 for more details about Shebang
* There is not need to have a space after <?php. Closes #1014 
* Remove the closing `>` in the html doctype to support older versions of html as well

### CODE REVIEW

**Comment by ffes** [comment]
@linquize Thanks for the suggestion. Added with last commit

**Comment by ffes** [comment]
@linquize Yes, it does. That was the reason to create the PR: To eliminate the use of full paths in the shebangs. And to support more languages ;-)

The code first checks if the first two chars of the file are `#!` (the shebang magic number). If so it checks the first line for the various commonly used languages and their interpreters.

And `#!/usr/bin/env node` matches those criteria, so it returns `L_JAVASCRIPT`.

**Comment by donho** [comment]
Nice enhancement!

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8ac0aba68eed9fb37e75566be0b831ef5d79042d

**Pull request closed without merging**
