### PR TITLE
Update : Thai.xml [Convert to UTF-8] base english.xml

### PR DESCRIPTION
**Pull request by sctnightcore**
English.xml
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5719420c3ba6b8eca06a911e7690011bff8f9021/PowerEditor/installer/nativeLang/english.xml#L268-L269

Thai.xml
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5719420c3ba6b8eca06a911e7690011bff8f9021/PowerEditor/installer/nativeLang/thai.xml#L202-L203

### CODE REVIEW

**Comment by donho** [comment]
@sctnightcore Could you check the newest updated english.xml here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

**Comment by sctnightcore** [comment]
@donho  if have freetime . i will back to update it .

**Comment by donho** [comment]
@sctnightcore Thank you.
I'll keep you PR here. Feel free to update it so I can merge your updated translation into master.

**Comment by sctnightcore** [comment]
@donho  it ok . you can merge my pr . xD 


I'm lazyyyyyyyyyyyyyyyyyyyy

**Comment by AngryGamer** [comment]
donho meant the PR will be merged once it's updated with changes from english.xml 😉

**Comment by donho** [comment]
@sctnightcore  I see. So please re-open your PR when it is ready.

**Pull request closed without merging**
