### PR TITLE
Corrected CoffeeScript file extension

### PR DESCRIPTION
**Pull request by MCCshreyas**
1. Changed extension to .coffee instead of .litcoffee.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Quick Googling shows:

`Literate CoffeeScript
Besides being used as an ordinary programming language, CoffeeScript may also be written in “literate” mode. If you name your file with a .litcoffee extension, you can write it as a Markdown document — a document that also happens to be executable CoffeeScript code. `

Aren't both extensions valid then? In which case you should append .coffee instead of replacing it.

**Comment by MCCshreyas** [comment]
Added that one too.

**Comment by dail8859** [comment]
@MCCshreyas This really needs to be one commit. If you are unable to squash these commits, I can do it to this PR for you if you'd like instead of opening a new PR.

**Comment by MCCshreyas** [comment]
Yes. Please squash those two commit into one. Can you please do that for this one to? https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4104

**Comment by dail8859** [comment]
Commits have been squashed for this PR. #4104 is already a single commit.

**Comment by MCCshreyas** [comment]
OK. Thanks for squashing commits!

**Comment by dail8859** [comment]
Closed by e0c4011982a6c3572258b13f066fd0a710258937

Thanks for the PR

**Pull request closed without merging**
