### PR TITLE
Fixes for the npp backup thread

### LINKED ISSUE #14906: possible crash when recursively entering the Notepad++ backup_mutex
### Description of the Issue

[While simulating](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14842#issuecomment-1986083321) the stalled/blocked/hanged file saving / filecache flushing for the NUL-corruptions issues debugging purposes, I found a bad N++ design - under some circumstances like that blocked file-IO, there is a possibility of multiple entry to the N++ `backup_mutex` `std::mutex` from the same thread, resulting in a N++ crash.

Ref: https://en.cppreference.com/w/cpp/thread/mutex/lock 
"If lock is called by a thread that already owns the std::mutex, the behavior is undefined: for example, the program may deadlock.
An implementation that can detect the invalid usage is encouraged to throw a std::system_error with error condition
resource_deadlock_would_occur instead of deadlocking."
(Note: In such a case MS C++ throws the _RESOURCE_DEADLOCK_WOULD_OCCUR)

This can lead to loss or corruption of the opened/saved files in N++, as well as failure to save some important configuration files, which are saved when the N++ is being closed (e.g. the session.xml, config.xml, etc.).

### STR

Current N++ design allows calling of its `FileManager::backupCurrentBuffer()` func multiple times from the same thread even before finishing the backup saving there but the file-IO could be slow/blocked, e.g.:
- HW not ready (disk spinning up, waking up from a deep powerstate sleep, a network slowdown/error...)
- busy disk (saving/flushing some other-app big data, etc.)
- user set a too short backup time interval (e.g. 1 sec in the Preferences > Backup > Backup in every ...)
  and the file to be saved is bigger and the disk used is not fast enough
- possible disk driver errors blocking the IO

1.  Simulate blocked file-IO by putting superfluous  modal MessageBox WINAPI call to the N++ `Win32_IO_File::write` or `Win32_IO_File::close()`
2. Run that special N++ build.
3. Ensure that the N++ Preferences > Backup  is ON:
   npp-pref-backup
4. Either open a new N++ tab, type something in it to make it dirty, wait for the N++ backup-thread crash (default is the 7 secs as is visible in the pic above) or close the N++ (files will be written at the N++ exit ...)

### Expected Behavior
N++ handles that (temporarily) "blocked-IO" situation without the crash.

### Actual Behavior
N++ will start to pointlessly stack up its `NPPM_INTERNAL_SAVEBACKUP` messages via the periodically called `PostMessage` in the `Notepad_plus::backupDocument(void * /*param*/)` no matter if the backup file-saving can be / is completed or not, the `FileManager::backupCurrentBuffer()` will be reentered from the same thread causing crash at the `std::lock_guard<std::mutex> lock(backup_mutex)` .

### Proposed solutions

1. The simplest (I highly do not recommend that) is the replacing `std::mutex` by `std::recursive_mutex`. This will only delay the possible crash of the app. The `std::recursive_mutex` has not its own locking counter method (and its native_handle() method is unfortunately not implemented on the Windows platform) needed for a proper solution.
2. Use a custom std::mutex solution enhanced by a safe `lockcount()` method, as the correct solution is the immediate returning from that `FileManager::backupCurrentBuffer()` func when a recursive lock-situation (not finished previous backup) is detected.
3. A complete change of the N++ backup-design.

@donho 
If you agree with the above no.2 proposal, assign me please to this issue, I will try a PR.

### PR DESCRIPTION
**Pull request by xomx**
Fix #14906 .

This PR fixes:
- possible backup thread deadlock exception (re-entering the std::mutex from the same thread)
- possible thread message queue flooding by the multiple PostMessages when a backup IO is blocked somehow or takes a longer time than the backup period set
- unhandled backup worker thread closing at the very Notepad++ exit (e.g. in the nppLogNulContentCorruptionIssue.log you can sometimes see that the backup thread is still running & doing its job even in the very last stages of the Notepad++ app existence, which is IMO not completely safe...)

### CODE REVIEW

**Comment by donho** [comment]
Currentely #14906 cannot be reproducible, so the PR is on standby.

**Comment by donho** [comment]
@xomx 
Any news for the reproduction of crash?

It seems https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133 has been fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbeaafac8bde911d3268f2d40b90329feb5c57f4

**Comment by xomx** [comment]
@donho Vacation until Aug 5th. Then I will recheck this again.Dne 21. 7. 2024 13:01 napsal uživatel Don HO ***@***.***>:
@xomx
Any news for the reproduction of crash?
It seems #6133 has been fixed by bbeaafa

**Comment by donho** [comment]
@xomx 
Enjoy your holidays!

**Comment by donho** [comment]
@xomx 
No rush.
I just want to know if we can close the PR.

**Comment by donho** [comment]
FYI: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15669#issuecomment-2397916755

**Comment by xomx** [comment]
@donho 
I still think that this PR fixes the first two points mentioned in this PR 1st post better than the https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbeaafac8bde911d3268f2d40b90329feb5c57f4 (this PR will not block the main N++ thread in case that the backup worker thread is busy or does not respond at all). But this PR is not as simple as the mentioned PostMessage->SendMessage change, so it's clear to me that you probably won't be inclined to accept it.

But there is also the 3rd point

> * unhandled backup worker thread closing at the very Notepad++ exit (e.g. in the nppLogNulContentCorruptionIssue.log you can sometimes see that the backup thread is still running & doing its job even in the very last stages of the Notepad++ app existence, which is IMO not completely safe...)

for which we now have a solid proof https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15681#issuecomment-2403168094 why it is bad.

Changes needed to fix this backup-thread-crash-after-npp-winmain-exit are only few:
- adding new atomic exit flag
  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0478122f8af69fce07652d8ccbc189dc265980f1/PowerEditor/src/NppBigSwitch.cpp#L42
  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0478122f8af69fce07652d8ccbc189dc265980f1/PowerEditor/src/Notepad_plus.h#L51
- set this in an appropriate place
  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0478122f8af69fce07652d8ccbc189dc265980f1/PowerEditor/src/NppBigSwitch.cpp#L2610-L2613
- and use it in the backup worker thread loop
  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0478122f8af69fce07652d8ccbc189dc265980f1/PowerEditor/src/Notepad_plus.cpp#L8470

Do you agree with closing of this PR and creating new simpler one for the point No.3 only?

**Comment by donho** [comment]
@xomx 
Does the fix of the point No.3 has been done in this PR entirely?

**Comment by xomx** [comment]
@donho 
Yes, the snippets in my previous post above is from this PR branch.

**Comment by donho** [comment]
@xomx 
> Do you agree with closing of this PR and creating new simpler one for the point No.3 only?

OK please.

**Comment by xomx** [comment]
Closed, will be replaced by a simpler variant later.

**Comment by xomx** [comment]
@donho 
For now, I will continue here with some questions before I create new backup-PR.

1)
While debugging I noticed one strange variable declaration. In fact I noticed that because I saw the `'\x1'`:

npp-boolean-insteadof_bool

I am guessing this `boolean` (boolean == unsigned char type) should be `bool` instead. Fortunately, it does not matter functionally in the code, but I would replace it (I found it in two places) with the standard `bool` type - are you in favor of that change?

2)
Until now, I mistakenly believed that the N++ only writes a backup when changes are detected in an open filebuffer/tab, when the "Trigger backup on modification in every xxx seconds" interval has elapsed. Now I see that backup with exactly the same data are written over and over again, even if nothing else has been changed from the last change detection.

STR:
- open one file (or use one unsaved new buffer/tab, it does not matter)
- modify that buffer/tab somehow
- because the buffer/tab is now marked as "dirty" and "modified", the same data will be written over and over again by the backup thread regardless of whether the user actually makes any further changes to it afterwards

Is this an intended way how the backup thread should operate?

**Comment by donho** [comment]
@xomx 
> I am guessing this boolean (boolean == unsigned char type) should be bool instead. Fortunately, it does not matter functionally in the code, but I would replace it (I found it in two places) with the standard bool type - are you in favor of that change?

I must use it by mistake - please replace them.

> Is this an intended way how the backup thread should operate?

Yes. But if you've got a better idea & the implementation is not complicated, you can do a another PR for changing this logic.

**Pull request closed without merging**
