### PR TITLE
NPP RTL: Floating panel movement fix

### LINKED ISSUE #10579: NPP RTL: Floating panels can not be moved
**STR:**
`Settings -> Preferences -> General -> Localization`: select a RTL language (e.g. Hebrew).
Restart NPP.
Open the Document List.
Double-click the title bar (- the panel should be floating now).
Left-click the title bar, keep the button pressed and try to move the panel.

**Result:**
The panel can not be moved.

***

Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Users\---\Downloads\npp.8.1.4.portable\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

### PR DESCRIPTION
**Pull request by Ashfaaq18**
fix #10579

tested LTR and RTL, works as expected on both layouts.
Still got to fix the docking of the panels in RTL format, will need to open another issue for it.

### CODE REVIEW

**Comment by Yaron10** [comment]
@Ashfaaq18,

Great work as always. 👍 
You're officially the NPP RTL master. :) 

Thank you very much.

***
> Still got to fix the docking of the panels in RTL format, will need to open another issue for it.

👍

**Comment by Ashfaaq18** [comment]
>
> Great work as always. 👍
> You're officially the NPP RTL master. :)
> 

Haha, Thank you @Yaron10 and @donho for all the support.

**Comment by donho** [comment]
Thank you both @Yaron10 & @Ashfaaq18 to make RTL great again!

**Comment by Yaron10** [comment]
The thanks and flowers to @Ashfaaq18.
He has fixed some major RTL issues in a short time. Professional and clever!

"Make RTL Great Again". An interesting paraphrase. :)

**Comment by Ashfaaq18** [comment]
> @Ashfaaq18,
> 
> > Still got to fix the docking of the panels in RTL format, will need to open another issue for it.
> 
> Should I open the issue?
> 

Yeah, sure.

> OFF-TOPIC:
> 
> (I know it's not your code).
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d692b5060fe8ad6e5a6fcc5e640c9d95e25052ff/PowerEditor/src/WinControls/VerticalFileSwitcher/VerticalFileSwitcherListView.cpp#L155
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d692b5060fe8ad6e5a6fcc5e640c9d95e25052ff/PowerEditor/src/WinControls/VerticalFileSwitcher/VerticalFileSwitcherListView.cpp#L311
> 
> Shouldn't there be `delete` statements after those `new` calls? If positive, I think there are quite a few similar cases throughout NPP code.
> 
> Thank you.

I think they do get deleted when the application exits, Its the "delete tlfs" lines in the below 2 code snippets.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d692b5060fe8ad6e5a6fcc5e640c9d95e25052ff/PowerEditor/src/WinControls/VerticalFileSwitcher/VerticalFileSwitcherListView.cpp#L348-L357

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d692b5060fe8ad6e5a6fcc5e640c9d95e25052ff/PowerEditor/src/WinControls/VerticalFileSwitcher/VerticalFileSwitcherListView.cpp#L65-L79

**Pull request closed without merging**
