### PR TITLE
Create Corsican translation for Notepad++ 6.9.2 and 7.0

### PR DESCRIPTION
**Pull request by Patriccollu**

### CODE REVIEW

**Comment by schnurlos** [comment]
For the new translation language there should also be updated the file
notepad-plus-plus/PowerEditor/src/localizationString.h like that:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2354

**Comment by Patriccollu** [comment]
Hi Schnurlos,

In my opinion, the file  notepad-plus-plus/PowerEditor/src/localizationString.h

needs to be updated with the following line:

	{TEXT("Corsu"), TEXT("corsican.xml")},

Thanks,
Patriccollu

**Comment by donho** [comment]
@Patriccollu It's confusing that there are another 2 other PR about Corsica.
Could you let me know which one should I get among #2344, #2354 and #2355 ?

**Comment by Patriccollu** [comment]
@donho I created #2344 to add the Corsican translation file. @schnurlos has created #2354 and #2355 to update respectively PowerEditor/src/localizationString.h and PowerEditor/installer/nsisInclude/langs.nsh (in order to recognize the Corsican language). I've noticed a typo in line 144 of the proposed langs.nsh. So I've tried to modify and add the two additional files to my PR but I've just created Patch-2 and 3. Actually I'm a little bit lost in GitHub! As it's my first experience with GitHub, please tell me what to do? Thanks.

**Pull request closed without merging**
