### PR TITLE
fix undefined fgColors for python

### PR DESCRIPTION
**Pull request by gnbl**
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1970

### CODE REVIEW

**Comment by donho** [comment]
@gnbl Could you provide 2 screenshots : before and after?

**Comment by gnbl** [comment]
No, it's all in the diff :-)

**Comment by gnbl** [comment]
LOL

**Comment by donho** [comment]
@gnbl Your PR fix partially the problem (only one theme).
I'll accept if you provide a patch which fixes in all themes.

**Pull request closed without merging**
