### PR TITLE
Update VS projects

### PR DESCRIPTION
**Pull request by NN---**
Add _WIN32_WINNT=0x0501 to defines list.

### CODE REVIEW

**Comment by NN---** [comment]
Would you accept this and other pull requests ?

**Comment by donho** [comment]
@NN--- 
I will test it at home this evening. I don't see why I reject this patch if it compiles.
Sorry for the delay, but I have a daytime job like everybody, and my family (especially my 7-years-old son) needs me as well. I do my best to manage Notepad++ project, I hope you understand that.

**Comment by NN---** [comment]
I fully understand you.
All my colleagues use Notepad++ and I am really willing to improve it.
I think you should add more commiters to the project to develop it faster.

**Comment by donho** [comment]
The project was in the mode what you suggest. Unfortunately in the end I'm the only maintainer who remains with some source code being difficult to be maintained.
So I don't see the other better ways so far than that the project moves forward with the speed I can provide.
Thank you for your comprehension.

**Pull request merged**
