### PR TITLE
Update czech.xml translation to 7.4.2

### PR DESCRIPTION
**Pull request by xomx**

### CODE REVIEW

**Comment by xomx** [comment]
Hmm, isn't it failing because of I used the &lt; and &gt; notation for the << and >> in the Find dlg?

**Comment by schnurlos** [comment]
Seems to be. I would change it from "Najít &gt;&gt;" to "Najít >>" and from "&lt;&lt; Najít" to "<< Najít" as this is the only real change you made. And this works in english and other languages.

**Comment by xomx** [comment]
Sure, I could switch to real <> chars but then I think it will not be a valid xml-file (invalid starting tag ...).

**Comment by schnurlos** [comment]
Better invalid and working as valid and not working as the checks fail ...

**Pull request closed without merging**
