### PR TITLE
VB: Remove duplicate automcomplete keywords

### PR DESCRIPTION
**Pull request by SinghRajenM**
Even VB has lot of duplicate autocomplete keywords.

### CODE REVIEW

**Comment by dail8859** [comment]
@SinghRajenM if you do have a C++ program to parse all the API XML files I can close my PR in favor for your better solution.

**Comment by SinghRajenM** [comment]
@dail8859 , I took base from your PR. There is no issue in your PR except "actionscript.xml" (only one keywod). I parsed full directory and found only VB was left in your PR.

**Comment by dail8859** [comment]
Ah ok that's good to know. In the end it is probably best our PRs be a single PR instead of 2.  You can include my PR changes in this or I can include yours. Either way is fine with me.

**Comment by SinghRajenM** [comment]
Good one, merge my change with your PR as your PR already includes many other files.

**Comment by SinghRajenM** [comment]
closing as changes have been accommodated in PR #3976.

**Pull request closed without merging**
