### PR TITLE
Appveyor release

### LINKED ISSUE #1881: Appveyor build release
Also build the "Unicode Release" configuration

### PR DESCRIPTION
**Pull request by cmeriaux**
Fixes #1881

### CODE REVIEW

**Comment by donho** [comment]
Have you test it with your Appveyor account?

**Comment by cmeriaux** [comment]
yep. Here is the log : 
https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.23

two artefacts are available:
https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.23/artifacts

**Comment by donho** [comment]
please make one commit for Appveyor issue.

**Comment by cmeriaux** [comment]
@donho ok there is two commit, but the first one was another PR that was supposed to be integrated first ! #1878 contains sha1: 3770f32ac5f7401c49a8463ceda1e47b3514286c

#1882 contains sha1: 3770f32ac5f7401c49a8463ceda1e47b3514286c and sha1: ece197ca43c81475d0ed7a30f527e4b3b44752a0

It's so paintfull to contribute here .............

**Pull request closed without merging**
