### PR TITLE
Fixed UI issue for RTL layout

### PR DESCRIPTION
**Pull request by SinghRajenM**
1. For RTL languages such as hebrew, "Close" button goes beyond the dialog.
2. Few Text is chopped (specially ". matches newline" and "Regular expression")

### CODE REVIEW

**Comment by SinghRajenM** [comment]
Adding screenshots...... 

find_file
find_in_file1
hindi_find_dlg
replace

**Comment by Yaron10** [comment]
Hello @SinghRajenM,

Excellent! :+1: 
Thank you very much.

Moving the ". matches newline" is a bonus.
Isn't this more relevant to Regex? - Wouldn't it be better increase the dialog *width* and restore its previous position?

Also, the localization files should be updated for this item.

Best regards.

**Comment by SinghRajenM** [comment]
Hello @Yaron10,
Thank you for your feedback. But at this moment changing localization is bit tough in order to reduce the string length.  Also it has to be updated by various persons which is again time consuming activity.

Therefore to make it simpler, I have provided indention for  ". matches newline" similar to other items such as "preference ->New Document -> Encoding", "Preference -> Editing ->Vertical Edge Setting" etc.

I think, it should okay.

find_indent

**Comment by Yaron10** [comment]
Hello @SinghRajenM,

Really nice.
Thank you very much.

Thanks also for your other contributions. They are all great.

Best regards.

**Comment by donho** [comment]
@SinghRajenM It's hard to review your code with all the commits. Could you make 7 in 1 so I can check it easier?

**Comment by cmeriaux** [comment]
@donho  for the record, you can review multiple commit easily using git diff  with commit option

> git diff [--options] <commit> [--] [<path>…​]
This form is to view the changes you have in your working tree relative to the named <commit>. You can use HEAD to compare it with the latest commit, or a branch name to compare with the tip of a different branch.

so you just have to check out the sha1 of the PR and do git diff or git difftool to use a diff front end (my prefered is beyond compare)

> git checkout PR_sha1
> git difftool master

**Comment by donho** [comment]
@cmeriaux Thank you for the tip.
But it's not my point. What I want is each PR has only one commit - so it'll be easy (not only for review) to reverse if need.

**Pull request closed without merging**
