### PR TITLE
FunctionList Update 2

### PR DESCRIPTION
**Pull request by MAPJe71**
1. Implemented XML Schema for functionList.xml.
2. functionList.xml:
   * new layout of association map;
   * placed `displayName` before `id` attribute where applicable;
   * utilize inline comments;
   * parsers added: 'XML for FunctionList', Assembly, AutoIt3, InnoSetup, PowerShell (#2317 and Community topic [12475](https://notepad-plus-plus.org/community/topic/12475/function-list-for-powershell)), KRL (half of Community topic [12264](https://notepad-plus-plus.org/community/topic/12264/function-list-for-new-language)), Sinumerik (Community topic [12520](https://notepad-plus-plus.org/community/topic/12520/function-list-for-simatic)) and UniVerse BASIC (Community topic [12742](https://notepad-plus-plus.org/community/topic/12742/functionlist-different-results-with-different-line-endings));
   * parsers improved: C, Java (#1015 and Community topic [12691](https://notepad-plus-plus.org/community/topic/12691/function-list-with-java-problems)), Batch, Bash (#2318), XML and NSIS (#2462);
   * replaced `[\t\x20]` with `\h` where possible;
   * using upper case notation for hexadecimal values e.g. `\x7F-\xFF`;

### CODE REVIEW

**Comment by donho** [comment]
I see a regression so far in NSIS:
```
!macro define_detectVersionToInstall threadid
Var common_15
Function detectVersionToInstall
	Pop $common_15
FunctionEnd
Function detectVersionToInstall_${threadid}
	${If} $VER != "noVersion"
		return
	${EndIf}
FunctionEnd
!macroend
```
The code above has 1 macro and 2 function. With the old functionList all are listed. Whereas in yours the middle function entry is skipped.

**Comment by donho** [comment]
In C, it's better than old one (according the sample I use to test), and I like the idea of parameters including .
However, not all macros are detected, and one wrong entry (see attatched file).
[INFBLOCK.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/613397/INFBLOCK.zip)

**Comment by donho** [comment]
**Java** : I have tried with attached file, and got the following declarations are listed as function entries:
```
    native public void onErrorNative(int what, int extra, long id);
    native public void onBufferingUpdateNative(int percent, long id);
    native public void onProgressUpdateNative(int progress, long id);
    native public void onDurationChangedNative(int duration, long id);
    native public void onInfoNative(int what, int extra, long id);
    native public void onVideoSizeChangedNative(int width, int height, long id);
    native public void onStateChangedNative(int state, long id);
```
For me, function list provides only entries of function denition. What do you think?

[QtAndroidMediaPlayer.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/613425/QtAndroidMediaPlayer.zip)

**Comment by donho** [comment]
It seems OK for me for **Batch** and **Bash**. Good work, @MAPJe71

**Comment by MAPJe71** [comment]
I try to base a languages parser on its grammar. When I can't find a/the grammar I use gathered source files and presume they are proper examples knowing the latter is not always the case. Furthermore, I'm not familiar with every language and their quirks so any comment to improve a parser is appreciated.

@DonHo

**NSIS**:
When the functions contained in a macro are indented it will show the macro only.
``` NSIS
!macro define_detectVersionToInstall threadid
    Var common_15
    Function detectVersionToInstall
        Pop $common_15
    FunctionEnd
    Function detectVersionToInstall_${threadid}
        ${If} $VER != "noVersion"
            return
        ${EndIf}
    FunctionEnd
!macroend
```
Q: How should functions contained in a macro be listed?
1. separately (i.e. in addition to the macro itself);
``` NSIS
    [-] example.nsi
     +--- define_detectVersionToInstall threadid
     +--- detectVersionToInstall
     \--- detectVersionToInstall_${threadid}
```
2. as 'members/leafs' of a macro 'class/branch'.
``` NSIS
    [-] example.nsi
     \---[-] define_detectVersionToInstall threadid
          +--- detectVersionToInstall
          \--- detectVersionToInstall_${threadid}
```

**C**:
Macros are a PITA :) I'll have another look.

**Java**:
Oops, will update.
And yes I agree FunctionList should only display definitions.

**Comment by donho** [comment]
> Q: How should functions contained in a macro be listed?

I'm not an expert of NSIS, but I'm sure that a macro can contain several functions - the sample I provided is a piece of code come from a compilable nsis file. Unfortunately I cannot provide you the whole code source here.

> Macros are a PITA :)

Macro entries is a "nice to have" feature. However, it's not indispensable in "function" list. :)

**Comment by MAPJe71** [comment]
Fixed Java parser.

**Comment by donho** [comment]
@MAPJe71 Please let me know while C and NSIS are fixed.

**Comment by MAPJe71** [comment]
@donho Fixed C, NSIS, KRL and UniVerse BASIC parsers.

**Comment by dail8859** [comment]
@MAPJe71 can #1015 be closed now? (All the other issues you referenced in the original post are already closed.)

**Comment by MAPJe71** [comment]
@dail8859 Yes.
issue 1015

**Comment by dail8859** [comment]
Thanks

**Pull request closed without merging**
