### PR TITLE
Update german.xml

### PR DESCRIPTION
**Pull request by McLoo**
"Always Yes"-Text adapted to button text
It sayed press "Ja, immer" but there is only a the button "Immer Ja"

### CODE REVIEW

**Comment by donho** [comment]
@schnurlos 
Could you validate this PR please?
If it's valid, could you integrate into you current PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13795 please?

**Comment by rdipardo** [comment]
~If it's valid...~

Don't blame the translation; it's that [random `t` in the French localization again](https://github.com/McLoo/notepad-plus-plus/blob/211a2dff85d1115b6a839a71e69885c36f28127d/PowerEditor/installer/nativeLang/french.xml#L1).

@McLoo, like this:

    git remote add upstream https://github.com/notepad-plus-plus/notepad-plus-plus.git
    git fetch upstream --no-tags
    git rebase upstream/master 
    git push origin --force

**Comment by McLoo** [comment]
@rdipardo thanks for the git commands. I still have to learn...

**Comment by donho** [comment]
@rdipardo 
I did know the problem of invalid XML of French translation.
But here I ask the original/regular translator to validate the translation since I don't speak German.

@schnurlos 
Could you validate the translation?

**Comment by chcg** [comment]
The change fixes a consistency issue for the dialog:

image001

, see
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/dea388bf594df4934d41d86127ff949d96fd3dc9/PowerEditor/installer/nativeLang/german.xml#L1375

**Comment by donho** [comment]
@chcg 
Thank you for your confirmation!

**Comment by schnurlos** [comment]
@donho I can confirm the change.

**Comment by chcg** [comment]
Obsoleted by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13965.

**Pull request closed without merging**
