### PR TITLE
Synchronize VS2015 project

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by NN---** [comment]
#230

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb2f771cbab13fafc40a2920769a2d97f6049175

**Comment by Croydon** [comment]
You should try to avoid merge commits by using rebase ;)

**Comment by NN---** [comment]
@Croydon done

**Comment by donho** [comment]
@Croydon I know. I trigered sync button of github app by accident.

**Pull request closed without merging**
