### PR TITLE
Fix broken indices in EncodingMapper

### LINKED ISSUE #3983: OEM 737 encoding broken from version 7.5.2
### Encoding to Greek OEM 737 character set is broken
Up until version 7.5.1, the display conversion to OEM 737 (Greek DOS codepage) worked fine. From version 7.5.2 this conversion function is broken.

### Steps to Reproduce the Issue
1. Open a file that contains Greek written from a DOS window (copy con ....) in Notepad++ 7.5.2+.
2. Click on Encoding -> Character Sets -> Greek -> OEM 737.
3. You should see the Greek characters displayed, but instead you see another character set.

### Debug Information
Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

### LINKED ISSUE #3991: Character encodings are broken
### Description of the Issue
The heart of the issue lies in the way the menu item IDS interact with the EncodingMapper. IE a constant is subtracted from the ID and used as an index into the encoding map
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/e339c0f600295267db7a8df01598d1cdb8f1c5cc/PowerEditor/src/NppCommands.cpp#L2174-L2177

However with the recent removal of a number of unused character encodings (60f1137), causes this to breakdown. the command IDs remain the same, however the indexes in the Encoding map have changed. This means that any encoding with a command id greater than the first deleted encoding, no longer behaves as expected.

### PR DESCRIPTION
**Pull request by dnakamura**
Fixes #3983
Fixes #3991

### CODE REVIEW

**Comment by SinghRajenM** [comment]
Oops!! That me who caused this issue. Even after thoroughly testing, this couldn't be caught.

However, I feel to avoid further confusion, updating encoding definition value in "menuCmdID.h" would be good deal (as commented items are no longer used.). 
Updating something like below - 
from
```
    #define    IDM_FORMAT_ISO_8859_9        (IDM_FORMAT_ENCODE + 17)
    //#define    IDM_FORMAT_ISO_8859_10     (IDM_FORMAT_ENCODE + 18)
    //#define    IDM_FORMAT_ISO_8859_11     (IDM_FORMAT_ENCODE + 19)
    #define    IDM_FORMAT_ISO_8859_13       (IDM_FORMAT_ENCODE + 20)
    #define    IDM_FORMAT_ISO_8859_14       (IDM_FORMAT_ENCODE + 21)
    #define    IDM_FORMAT_ISO_8859_15       (IDM_FORMAT_ENCODE + 22)
    //#define    IDM_FORMAT_ISO_8859_16     (IDM_FORMAT_ENCODE + 23)
    #define    IDM_FORMAT_DOS_437           (IDM_FORMAT_ENCODE + 24)
    #define    IDM_FORMAT_DOS_720           (IDM_FORMAT_ENCODE + 25)
```
to
```
    #define    IDM_FORMAT_ISO_8859_9        (IDM_FORMAT_ENCODE + 17)
    //#define    IDM_FORMAT_ISO_8859_10     (IDM_FORMAT_ENCODE + 18)
    //#define    IDM_FORMAT_ISO_8859_11     (IDM_FORMAT_ENCODE + 19)
    #define    IDM_FORMAT_ISO_8859_13       (IDM_FORMAT_ENCODE + 18)
    #define    IDM_FORMAT_ISO_8859_14       (IDM_FORMAT_ENCODE + 19)
    #define    IDM_FORMAT_ISO_8859_15       (IDM_FORMAT_ENCODE + 20)
    //#define    IDM_FORMAT_ISO_8859_16     (IDM_FORMAT_ENCODE + 23)
    #define    IDM_FORMAT_DOS_437           (IDM_FORMAT_ENCODE + 21)
    #define    IDM_FORMAT_DOS_720           (IDM_FORMAT_ENCODE + 22)
```

**Comment by dail8859** [comment]
I don't think it is a good idea to change `IDM_xxx` constants. If a plugin uses these then it will break their usage of calling these menu commands.

**Comment by dnakamura** [comment]
I think the best solution is to probable modify the encoding mapper to map based on the `IDM_xxx` constants rather than an index.  Yes it would make lookups more expensive, but its not like the user will be changing encodings frequently

**Comment by dinkumoil** [comment]
@SinghRajenM 

Currently my [AutoCodepage plugin](https://sourceforge.net/projects/autocodepage/) is broken because of your changes in v7.5.2. Updating encoding definition value in "menuCmdID.h" would break it permanently.

I think the fix of @dnakamura is the best solution.

**Comment by dail8859** [comment]
I found this in another part of the code, would this need updated as well (I honestly have no clue but if the EncodingMapper is changed this looks like it would have to change too).

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/440577f6479adb0b8edecffea9ece54916dab8ab/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp#L48-L97

**Comment by dinkumoil** [comment]
@dail8859 

Seems to be used for this list (screenshot taken from Npp v7.3.3):

grafik

The list gets filled by the for-loop starting in line 1159 of preferenceDlg.cpp. This loop uses the array `encodings` as source for the encodings to be shown in the combobox. That means it would be possible to remove some items of the `encodings` array to reduce the set of encodings shown in the combobox.

I would say preferenceDlg.cpp has **not** to be changed.

**Pull request closed without merging**
