### PR TITLE
GUI enhancement: Find Characters in Range... dlg

### LINKED ISSUE #13577: [GUI] Find Characters in Range... dlg accelerators and edit fields
### Description of the Issue

Find Characters in Range... dialog does not have key accelerators for all controls.
Changing values in edit controls have no effect if "My Range" is not selected, this can cause confusion. 
image

### Steps to Reproduce the Issue

1ab. Open Find Characters in Range... dialog
2a. Press ALT key to show key accelerators
2b. Change values in edit controls without selecting "My Range"
3b. Press Find button

### Expected Behavior

Key accelerators for all controls.
Better handling for edit controls and "My Range"
### Actual Behavior

Missing key accelerators.

### Debug Information

Notepad++ v8.5.2

### PR DESCRIPTION
**Pull request by ozone10**
add accelerators
add initializers
improve edit controls behavior 
image

fix #13577

### CODE REVIEW

**Comment by Yaron10** [comment]
@ozone10,

The new smaller design is very nice. 👍 

I have some font glitches on my machine.

Master:
תמונה

This PR:
תמונה


Thank you.

**Comment by Yaron10** [comment]
Probably `–` instead of `-`.

**Comment by Yaron10** [comment]
@ozone10,

👍 
Thank you.

**Comment by Yaron10** [comment]
@ozone10,

With the new _notepadPlus.Cpp.props_,

changing

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/80b34f0adf3c5249f9d9c1dc52c41e9ef2c84926/PowerEditor/src/Notepad_plus.rc#L1221

to `ע&זרה`,

I get gibberish in the menu.

_MS VS 2017._

Is that expected?

Thank you.

**Comment by ozone10** [comment]
@Yaron10 
it works fine for me, but I've changed flag to make it to have less impact on other people

**Comment by Yaron10** [comment]
@ozone10,

I Still have issues with that.
I'll change the flag for my build.

Thank you for looking into it. :+1: 

> why VS 2017?

I installed it a long time ago on an old PC, and I'd rather not change anything there.

**Comment by ozone10** [comment]
@Yaron10 
IIRC VS 2017 has some issue with UTF8. Check if you have the latest version 15.9.54.

**Comment by Yaron10** [comment]
@ozone10,

My version is 15.9.8. I'll keep it for the time being.

Thanks again.

**Pull request closed without merging**
