### PR TITLE
fix 8 uninitialized reads

### PR DESCRIPTION
**Pull request by ariccio**
Fixing 8 uninitialized reads, in the same spirit as #146, #145, #144, and #138.

### CODE REVIEW

**Comment by Eldaw** [comment]
ariccio, it sounds to me like you are a skilled developer. However, I must say that I (as someone who is not a C++ developer) do wonder why you choose to contribute only changes that relate to the technical correctness of the code.

On this project's growing Issues list are quite a number of small usability bugs and usability enhancement requests. I bet that some of them could be quickly implemented with just a couple of lines of code and make a big difference to the experience of using the application.

All I'm saying is I wonder if it wouldn't be a better use of your expertise to knock some of those out.

**Comment by MAPJe71** [comment]
@eldaw the technical incorrectness of the code could easily be the cause for some of the bugs.

**Comment by Eldaw** [comment]
@MAPJe71 Yes, I agree with you. Do you think it would make sense to specifically target some of the reported bugs, usability enhancements, and functional enhancements, and at the same time make sure that the introduced code is technically correct? Rather than only making general changes which might also end up making some of the reported issues stale/obsolete as a side effect, but might not.

**Comment by MAPJe71** [comment]
First of all, any introduced code should be technically correct!
Second, addressing the technical incorrectness of the code should not depend on addressing reported bugs, usability enhancements, and functional enhancements solely.

**Comment by donho** [comment]
@Eldaw I couldn't agree more.
@ariccio Unless you wanna do some bug-fixes or add the new feature, don't waste your time here. 
as I mentioned in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md :
"Only bug-fix and feature request will be accepted. For the other things, I can run static code analysis tool myself."

**Comment by ariccio** [comment]
>  Shouldn't you pass the size of target string  str  to  _tcscat_s  as second argument?

[Template parameter inference](https://msdn.microsoft.com/en-us/library/ms175759.aspx) is a [pretty cool thing](https://randomascii.wordpress.com/2013/04/03/stop-using-strncpy-already/).

**Comment by MAPJe71** [comment]
Hmm, missed that one and yes it is.

**Comment by ariccio** [comment]
> Unless you wanna do some bug-fixes or add some new features, don't waste your time here.

I assumed, because #146, #145, #144, and #138, were all merged, that this was an acceptable change. I'll have to dig through some bug reports...

**Comment by ariccio** [comment]
Meanwhile, an uninitialized read fix has been accepted in 223caa25d0c01c91f631f55f4fc031a165005a9e .

**Pull request closed without merging**
