### PR TITLE
Fix typo on change.log

### PR DESCRIPTION
**Pull request by DavidePastore**
**removes** instead of **romoves**.

### CODE REVIEW

**Comment by MetaChuh** [comment]
@DavidePastore 

you can impossibly be serious.
a typo fix for the old change.log, which will not be part of the next release, does not make much sense, does it ?

peace.

**Comment by sasumner** [comment]
@MetaChuh Maybe it was a practice PR.  :)

**Comment by DavidePastore** [comment]
I've never seen such a confident and friendly repository.

**Comment by sasumner** [comment]
@DavidePastore Nono, we're friendly.  Please, give as good as you get. Don't be discouraged. We aren't above some humor here. :)

**Pull request closed without merging**
