### PR TITLE
Update old themes to use the correct style IDs for Pascal

### PR DESCRIPTION
**Pull request by nmlgc**
Scintilla got a [new Pascal lexer] in version 1.78, which was included in Notepad++ version 5.4.4. However, this lexer also introduced [new style IDs] and most of Notepad++'s bundled themes that were created before version 5.4.4 haven't been updated in all that time.

This probably fixes what #249 was referring to.
    
[new Pascal lexer]: https://sourceforge.net/p/scintilla/feature-requests/541/
[new style IDs]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4ac665d0ce83d9313e4eec3c41ede59c9d13b707/scintilla/include/SciLexer.h#L1524

### CODE REVIEW

**Comment by donho** [comment]
could you provide one screenshot of before/after ?

**Comment by nmlgc** [comment]
Sure, here's one for every affected theme. Before is on the left, After on the right. As mentioned in #249, identifiers had the same color as comments, and the colors of keywords and preprocessor statements were swapped.

**Bespin**
beforeafter

**Black Board**
beforeafter

**Choco**
beforeafter

**Deep Black**
beforeafter

**Hello Kitty**
beforeafter

**Mono Industrial**
beforeafter

**Monokai**
beforeafter

**Obsidian**
beforeafter

**Plastic Code Wrap**
beforeafter

**Twilight**
beforeafter

**Vibrant Ink**
beforeafter

**vim Dark Blue**
beforeafter

**Comment by donho** [comment]
@nmlgc Thank you.
Could you solve the conflict so I can merge your pr please?

**Comment by nmlgc** [comment]
Done.

**Pull request closed without merging**
