### PR TITLE
Create catalan-valencian.xml language file

### PR DESCRIPTION
**Pull request by DavidCB14**
[catalan-valencian.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4165672/catalan-valencian.zip)

For the Valencian or western Catalan variant

### CODE REVIEW

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7770 which files additionally need to be modified to support localization.

**Comment by DavidCB14** [comment]
All 4 archives modified.

**Comment by donho** [comment]
"Valencian or Valencian language[4] (/vəˈlɛn(t)siən, -nʃən/; endonym valencià, llengua valenciana or idioma valencià [valensiˈa, ba-])[note 1] is the historical, traditional and official name used in the Valencian Community (Spain), and extra-officially in the El Carche comarca in Murcia (Spain),[5][6][7][8] to refer to the romance language also known as Catalan."

ref: https://en.wikipedia.org/wiki/Valencian

So Catalan is available in Notepad++:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/catalan.xml

You're welcome to improve it on the existing version, but it's no need to add a new localization in Notepad++ project.

**Comment by DavidCB14** [comment]
I don't think it's right what you're doing to close the subject. We have the same language as American English or British English or the various variants of Spanish that you have in the application.
Although it is the same language we have dialectal differences and different official language academies.
The Catalan variant is spoken by 5 million people and the Valencian variant is spoken by 2.5 million people, I think we deserve to hear our version from time to time.

Thank you

**Comment by pan93412** [comment]
@donho He gave us the difference between those languages, so I think you can reopen it, and waiting for someone who are using Valencian.

He said,

> For the Valencian or western Catalan **variant**

This case is just like:

You submitted a "繁體中文" and had said "繁體中文 is a variant of 簡體中文", but the manager just closed your request, and said "簡體中文 and 繁體中文 both are '中文'", and you don't need to submitted a "繁體中文".


I am a localization translator, and I am really care these "rejections", **DO NOT** reject those so fast, before anyone reviewed or submitted his opitions.

**Pull request closed without merging**
