### PR TITLE
Added bunch of improvements to C# intellisense

### PR DESCRIPTION
**Pull request by MCCshreyas**
1. Added parameter suggestion for methods in System.Console class. 
2. Added overloaded methods for Console.WriteLine and Console.ReadLine method.

### CODE REVIEW

**Comment by MAPJe71** [comment]
Replacement for #4097.

@MCCshreyas you could have "squashed" the commits of #4097 into one commit (as @dail8859 requested) and prevented repository clutter. The history of the changes is smeared over three PR's now i.e. #4082, #4097 and #4104 (this one).

**Comment by MCCshreyas** [comment]
How should I do that on github web?

**Comment by MAPJe71** [comment]
No idea, I'm using a Git in a Windows Command Prompt or TortoiseGit depending the task at hand.

**Comment by MCCshreyas** [comment]
I just edited that file on git web itself. Added code and created the pull request. Then how can I merge those commit from here.

**Comment by donho** [comment]
@MCCshreyas Never use github web edit feature to do you PR - it means you have never tested your code.
Install git on your windows, modify and test your change on your machine, and make sure it works before doing your PR.

**Comment by MCCshreyas** [comment]
Okk.

**Pull request closed without merging**
