### PR TITLE
Updated Scintilla to 3.6.2

### PR DESCRIPTION
**Pull request by KamranMackey**
I have updated Scintilla to 3.6.2, the latest Scintilla version as of this PR.

### CODE REVIEW

**Comment by chcg** [comment]
see #333, will be done by donho

**Comment by donho** [comment]
Indeed. I'll take in charge of updating of Scintilla.

**Comment by KamranMackey** [comment]
@donho Okay, fair enough.

**Comment by KamranMackey** [comment]
But please update Scintilla soon.

**Pull request closed without merging**
