### PR TITLE
[xml] Update german.xml

### PR DESCRIPTION
**Pull request by schnurlos**
Following https://github.com/notepad-plus-plus/notepad-plus-plus/commit/78d0e7e12f3d164eec1b6b1851ad21f987b0dc6d

### CODE REVIEW

**Comment by donho** [comment]
@schnurlos 
Could you please consider to add new entries for https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d039eaa9009e3561589cb3b5e9849ab9aefa3e02 ?

**Review by donho — CHANGES_REQUESTED** [review]
Add new entries for https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d039eaa9009e3561589cb3b5e9849ab9aefa3e02

**Comment by schnurlos** [comment]
@donho done

**Comment by donho** [comment]
@schnurlos 
Thank you!

**Pull request closed without merging**
