### PR TITLE
#2433 Initial implementation of folder exclusion find in files.

### PR DESCRIPTION
**Pull request by jetand**
#2433 Initial implementation of folder exclusion find in files.

### CODE REVIEW

**Comment by Lonzak** [comment]
Why hasn't that pull request been accepted? Lots of people waiting on that...

**Comment by donho** [comment]
Is that some kind of joke?

image

**Comment by Lonzak** [comment]
@jetand Can you fix that ui issue? I currently doesn't have my c++ env set up to have a look... But why that took half a year is beyond me...

**Comment by dazey3** [comment]
@donho Rather rude, don't you think? Not at all constructive.

**Comment by cfoxy17** [comment]
Notepad++ needs to be changed in one of two ways:

1. The UI issue with this "fix" needs to be resolved

OR

2. filters should allow you to enter multiple filters separated by a semicolon.. we should be able to exclude searching certain directories. This isn't a helpful feature, it's necessary. Perhaps it could be implemented by using a "!" before directories we want to omit.

**Comment by cfoxy17** [comment]
You can exclude certain folders from the search by making the folders hidden that you want to omit. 

Right click the folder -> properties -> check the "Hidden" box -> click apply

**Comment by jgreywolf** [comment]
@cfoxy17 This only works if the files you want to exclude are in specific folders.  If you want to exclude certain filetypes no matter where they are located within the folder structure you need to be able to exclude those files in a different way.

Being able to prepend ! before an extension seems the most logical way to handle this to me...

**Comment by xylographe** [comment]
Implemented in commit dc48cee5f7f4efe1f70e7269fe5e46ac8b861b1b.

**Comment by Lonzak** [comment]
@xylographe Really? Thank you!

**Comment by sasumner** [comment]
@Lonzak : Well...I haven't looked at it super-closely, but I believe the commit mentioned by @xylographe is for file pattern matching based exclusion, and this issue _seems_ to be (from its title) for excluding folders, what you are interested in may truly _not_ be implemented by the commit.

**Comment by Lonzak** [comment]
I had a look at the code and my c++ times have been awhile however it looks to me that its for files*:

```
bool matchInList(const TCHAR ***fileName**, const std::vector<generic_string> & patterns)
...
		if (patterns[i].length() > 1 && patterns[i][0] == '!')
		{
			if (PathMatchSpec(**fileName**, patterns[i].c_str() + 1))
				return false;

			continue;
		} 
```

except fileName means folders but than it is bad naming of variables imho

**Comment by xylographe** [comment]
Yes, my comment was in response to [the previous comment by @jgreywolf](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4429#issuecomment-557190010).
Commit dc48cee5f7f4efe1f70e7269fe5e46ac8b861b1b implements glob pattern based _file_ exclusion.

Excluding _folders_ is still only possible with [the workaround posted by @cfoxy17](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4429#issuecomment-495633652).

**Comment by Lonzak** [comment]
Perfect! So my last question in which version will this commit go? 7.8.2? 7.9?

**Comment by xylographe** [comment]
@Lonzak If you do not want to wait for the next release (probably 7.8.2), you can download the updated Notepad++ executable from [the AppVeyor Artifacts](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/29050635). Do _not_ replace `SciLexer.dll`, only `notepad++.exe`.

**Comment by Lonzak** [comment]
7.8.2 is out and its working! Finally :-)

**Comment by dazey3** [comment]
Been waiting a long time to exclude file types! Great work @xylographe! 👍

**Comment by donatelloOo** [comment]
What about the initial feature request which was "**folder** exclusion find in files" ?
Is it planed to have a way to exclude directories based on file path ?

For instance, never look into `target/` sub-folders using `!target/**`, or `!**/target/**`, or something like that ?

**Pull request closed without merging**
