### PR TITLE
Apply dark mode to function list's toolbar

### PR DESCRIPTION
**Pull request by donho**
Function list's toolbar is not in dark mode yet.
This PR intends to make Function list's toolbar conform to dark mode.

### CODE REVIEW

**Comment by donho** [comment]
@ozone10 
In order to make edit field apply to dark mode, I've check the way of edit field in increment search. However, it's totally different the way in increment search (no NM_CUSTOMDRAW). Could you give me a hint?
@adzm Any idea about it?

**Comment by ozone10** [comment]
> In order to make edit field apply to dark mode, I've check the way of edit field in increment search. However, it's totally different the way in increment search (no NM_CUSTOMDRAW). Could you give me a hint?

@donho 
use this message 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1d349d6404f57fa930dd8265b0095c60ff6ddede/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L766

I added
```
if (NppDarkMode::isEnabled())
{
	SetTextColor((HDC)wParam, NppDarkMode::getTextColor());
	SetBkColor((HDC)wParam, NppDarkMode::getBackgroundColor());
	return (LRESULT)NppDarkMode::getBackgroundBrush();
}
```
and it works, still need to adapt it for wrong text and C++ conversion

**Comment by donho** [comment]
@ozone10 
I just [adapted your code](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10058/commits/1e46691495f707517f97df7b348a2338ae559bb8) (with my understanding). However, the result remain the same:

image

What am I missing?

**Comment by ozone10** [comment]
@donho wrong, you have to add it below line 766 where `case WM_CTLCOLOREDIT : `  in this `INT_PTR CALLBACK FunctionListPanel::run_dlgProc(UINT message, WPARAM wParam, LPARAM lParam)`

**Comment by donho** [comment]
@ozone10 
My bad! Thank you!

**Pull request closed without merging**
