### PR TITLE
Update Turkish Localization

### PR DESCRIPTION
**Pull request by Tmp341**
* According to 2e7c5e3, 926e6e9, 6834d79, 874f0d0, 4369718, 1ae39c2, cbf3d2c, 1a9307b, e3dbeda, a0177e8, 0dbdef3, b657f58, 70515c8 and ddd4448 commits.

### CODE REVIEW

**Comment by donho** [comment]
@Tmp341 
Could you please check the latest report of the old localization file vs new localization file to make sure if your PR updated?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9854

Thank you!

**Comment by Tmp341** [comment]
What is difference with these?

`<Item id="6352" name="Match case"/>`
`<Item id="6332" name="Match case"/>`

I've translated id 6352 without checking below, if they are not same, i might need to fix one of them.

**Comment by donho** [comment]
@Tmp341 
> What is difference with these?

image

**Comment by Tmp341** [comment]
Oh, they were same (Lower/Upper Case) meaning? Let me fix that.

**Pull request closed without merging**
