### PR TITLE
Enhance -n -c -p command line args behavior

### LINKED ISSUE #9146: Command Line Parameters: -1 vs. -2
**STR:**
Open a file.
Place the caret at line 3.

Run that file from the command-line with `-n-1`.
-- The caret remains at line 3. 

Run that file from the command-line with `-n-2`.
-- The caret is at line 0.

**Expected:**
The same result in both cases.
***
Notepad++ v7.9.1 (32-bit)
Build time : Nov 2 2020 - 01:03:56
Path : C---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit)
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

### PR DESCRIPTION
**Pull request by sasumner**
Fix #9146

@Yaron10 Please test

Notes:

* -p remains zero-based (we weren't out to change that with this issue/PR).
* -p has priority over the others if it is specified along with -n and/or -c

### CODE REVIEW

**Comment by chcg** [comment]
@sasumner Fails to compile because isParamePresent is now an unused parameter and setting warning as error makes the build break.

**Comment by sasumner** [comment]
@chcg Thanks, not sure how that was missed...pushing the fix for that...

**Comment by ArkadiuszMichalski** [comment]
Works as specified in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9146#issuecomment-727277500. Only some things:
- now alone `-c` works fine (`-n` is set by default, same as manually passing `-n` or `-n0`)
- preceding 0 in value are ignored, so `009` is same as `9`.
- `-0` and `+0` in value is same as `0`.
- if `-p` remains zero-based then `-p` or `-p0` does not mean a remembered last position (as is the case for `-n` or `-c`), but set it to 0.

**Comment by sasumner** [comment]
>-p or -p0 does not mean a remembered last position

Just to add something to this:  With `-p` there is nothing "remembered" anyway, so...

**Comment by ArkadiuszMichalski** [comment]
> > -p or -p0 does not mean a remembered last position
> 
> Just to add something to this: With `-p` there is nothing "remembered" anyway, so...

Right, and if changing to the numbering from 1, then `-p` and `-p0` must be determined somehow, but it can be done in next bug (if this behavior will be changed).

**Comment by sasumner** [comment]
@ArkadiuszMichalski 
Well, if positioning is changed to be 1-based, then `-p0` is an error and should probably do nothing.  Same for `-p`.

**Comment by ArkadiuszMichalski** [comment]
Yes, and in practice, it would mean the last remembered position (line and column).

**Comment by sasumner** [comment]
>Yes, and in practice, it would mean the last remembered position (line and column).

Well, I'm confused by what that statement is saying, I think.
If a `-p` value is fed in, and that value is an "error", then logic that changes position would be aborted at that point and no change-of-position would be done.
So...if we're saying the same thing two different ways, that's fine, but it feels like we are each saying something different.

**Comment by ArkadiuszMichalski** [comment]
If `-p` will faild then where carrect will be positioned, on the begining in line 1? Actually, that's how it is now, so it could stay that way.

**Comment by sasumner** [comment]
I suppose `-p1` or `-p0` could do the same (put caret at very top of file), but let's save final judgment on that for a future time/issue.

**Comment by Yaron10** [comment]
Nice work. Assuming it's needed and useful. :)

**1.** `-c` -> ignored (correct). `-n` NOT ignored but moves the caret to Col 1.
**2.** I think that ignoring `-n0` is a bit weird (any other number is not ignored). I'd treat it as 1.
**3.** Why should Pos override any other args? Wouldn't it better if the first (or probably better *last*) arg overrides?

**Comment by sasumner** [comment]
>Why should Pos override any other args? Wouldn't it better if the first (or probably better last) arg overrides?

It was the old behavior, just being continued.
There isn't any detection-order logic in the code; adding something like that for this purpose seems like a lot to ask.

**Comment by donho** [comment]
@sasumner  Thank you for the PR.

The algorithm of current code is:
If `pos` argument is present, then got to pos (and ignore the 2 other arguments), otherwise no `pos` and no `col` then go to `line`. otherwise both `col` &  `line` must be present, then go to line & go to col. Simple and straight forward.
 
The code of this PR is much darker (more difficult to understand) comparing with the current code. From my viewpoint, there's only one added factor (positive or negative) for each argument - could the code be improved to make it more readable?

**Comment by sasumner** [comment]
@donho

>code...is much darker

LOL. I've never heard of "dark code" before, but I like that phrase.

>could the code be improved to make it more readable?

Probably not.
Certainly more comments could be added, but I don't think that is what you mean.

While I feel this code "works", I don't really like this code.

So here's the sequence of events that got us here:

* I notice #9146 and think that it is unimportant because a argument to `-n` is always >= 1
* However, I remember a user that wanted a command-line way to open a file and position caret on the last line
* My Python background makes me think that `-n-1` is a nice syntax for that, and could "fix" 9146 at the same time
* Back-and-forth discussion with other users in issue comments causes feature to "bloat"
* In my desire to please everyone, I finished the "bloated" version of the feature and submitted PR

Here's my suggestions:

* Close this PR (I will do this)
* Advise a user with need to jump to last line of file to use `-n2147483647` (or similar)
* Close 9146 with the advice that "negative arguments to `-n` are not defined, and could cause undefined behavior" which is an implied suggestion of "don't do that" and that we "won't fix"

I think, moving forward, that I will work on small things that interest me, in the way that I think they should be handled.
I will submit PR, and if it can be accepted, that's good.
If changes to PR are requested, and they are very-small and reasonable to me, I will make them.
Otherwise I will just self-close the PR.
I need to concentrate on keeping it "fun". :-)

**Comment by donho** [comment]
> I need to concentrate on keeping it "fun". :-)

I couldn't agree more with you! 

> In my desire to please everyone, I finished the "bloated" version of the feature and submitted PR

What I've learnt from this project is, you can't please everyone. 

> Close this PR (I will do this)

Sorry for making you code but not integrating it. And it was my fault - I should make myself more clear for the PR acceptation criteria before you coding. I'll pay more attention about it for the next time.

**Comment by sasumner** [comment]
@donho 

> It was my fault

I don't think there is any blame or fault here.
It just sort of happened.
:-)

**Pull request closed without merging**
