### PR TITLE
Add Pascal/Delphi FunctionList parser

### LINKED ISSUE #3664: Function List has no parser for Pascal/Delphi
### Description of the Issue
There is no parser available for Pascal/Delphi source code files in Function List. Therefor the Function List pane remains empty.

### Steps to Reproduce the Issue
1. Open a Pascal/Delphi source file.
2. Activate Function List pane.

### Expected Behavior
The Function List pane should display the syntax tree of the opened source file.

### Actual Behavior
The Function List pane remains empty.

### Debug Information
Notepad++ v7.5   (32-bit)
Build time : Aug 15 2017 - 23:02:57
Path : D:\Daten Entwicklung\privat\Delphi\AutoCodepage\AutoCodepage V1.0 [DXE2]\AutoCodepage\_npp\Win32\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoCodepage.dll CustomizeToolbar.dll DSpellCheck.dll Explorer.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppSaveAsAdmin.dll PluginManager.dll ReloadButton.dll XMLTools.dll 

Applies also to the 64-bit version.

### PR DESCRIPTION
**Pull request by dinkumoil**
Fixes #3664

### CODE REVIEW

**Comment by donho** [comment]
`[dinkumoil:master](https://github.com/dinkumoil/notepad-plus-plus)` shouldn't be used for creating PR.
One of contribution rule is `Create a new branch for each PR. Make sure your branch name wasn't used before - you can add date (for example patch3_20200528) to ensure its uniqueness.`
(https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests)

I can accept this PR for your master for only the first time, because the workflow passes. Please create a new branch for your next PR.

**Comment by donho** [comment]
@dinkumoil 
These 2 files make Notepad++ hang with this PR (v8.4.8, with function list opened)
[2_files_hanging_npp.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10453363/2_files_hanging_npp.zip)

But it's fixed in the latest commit of pascal.xml in master - could you confirm it?

**Comment by dinkumoil** [comment]
@donho

> it's fixed in the latest commit of pascal.xml in master

Yes, with the latest version of my parser there is no problem.

The one from the PR here used a complicated and **recursive** approach to exclude procedure/function declarations in the `interface` section of a _Pascal/Delphi_ unit. I guess that's the reason why it hangs with your test files. To be able to define all code between `interface` and `implementation` keywords as a multi-line comment was the key to create a reliable function list parser. Thanks to @mpheath this is possible now at least for **mixed** parsers. With pure function parsers it is still **not** possible.

**Comment by donho** [comment]
@dinkumoil 
Thank you for your confirmation.
I'll add both files in project as unit tests part.

**Comment by dinkumoil** [comment]
@donho 

> I'll add both files in project as unit tests part.

OK, but please do not remove/overwrite the current content of the unit test file as it ensures the functionality of my parser for a wide spread set of _Pascal/Delphi_ language features.

**Comment by donho** [comment]
> OK, but please do not remove/overwrite the current content of the unit test file as it ensures the functionality of my parser for a wide spread set of _Pascal/Delphi_ language features.

Sure. I will create 2 new folders for these 2 files, so the old unit tests won't be touched at all.

**Pull request closed without merging**
