### PR TITLE
Request for pull of bug fix #520 and subsequent pull of feature #521

### LINKED ISSUE #520: Delete/modify Shortcut/Macro menu with 0 items results in crash
Not sure how long this has been an issue, but in 6.7.9.2, if you go to 'Settings'->'Shortcut Mapper' and in the 'Macros' and 'Run Commands' grids, if there are no items and 'Modify' or 'Delete' is clicked, N++ crashes due to a null pointer reference on an invalid index and it can't recover due to a pure virtual function call error (probably due to the stack being messed up afterwards). I already have a patch and will do a pull request (it's in BabyGrid.cpp, BabyGridWrapper.h and ShortcutMapper.cpp).

### PR DESCRIPTION
**Pull request by Zeriph**
Resolved an issue where a user could crash N++ if they elected to delete or modify non-existant items in the Shortcut Mapper window (#521).

Also added a scrollable tab bar functionality (added the WM_MOUSEWHEEL event in TabBar.cpp) to allow scrolling of the tabs if there are more open than can be displayed.

Note: I did mean to do 2 separate commits/pull requests to ensure proper upstream integration so if the pulls are accepted and only 1 at a time, that's completely copacetic. 

If I've missed anything or didn't document/comment/debug properly please let me know; I tested the tab scrolling capability in numerous configurations but couldn't test it with a bunch of different mouses unfortunately.

### CODE REVIEW

**Comment by milipili** [comment]
hum sorry I've broken your PR. I will try to recreate it.

**Comment by donho** [comment]
@Zeriph It sounds cool.
Could you update your PR (there are some conflicts currently) so I can check it please?

**Comment by GitMensch** [comment]
@Zeriph Please update your PR as I miss this option in NPP much

**Comment by Zeriph** [comment]
Trying to redo this; been too long apparently. Have the proper/updated files, just trying to get things merged properly with the current NPP branch so I can re-do a pull request for this.

**Comment by A-R-C-A** [comment]
@Zeriph
I've already updated your PR along with some modifications.
Take a look here #2071.
If it's not what you want, feel free to make some changes.

**Comment by Zeriph** [comment]
@A-R-C-A 
Oh nice! I must have missed that somehow, thanks! I'm still learning the in/outs of git (more specifically GitHub); was trying to get this updated to merge properly to the main branch but you've saved me that effort :)

Once the fix/feature are up-streamed not sure if I should just close this out to avoid the future confusion ..?

**Comment by A-R-C-A** [comment]
> Once the fix/feature are up-streamed not sure if I should just close this out to avoid the future confusion ..?

I've referenced your PR, so I suppose care will be taken to close both.

>  I'm still learning the in/outs of git (more specifically GitHub);

Maybe this git book will help: [Pro Git](https://git-scm.com/book).

**Pull request closed without merging**
