### PR TITLE
Split functionList.xml into multifile in functionList Folder

### LINKED ISSUE #4896: {FunctionList request] Split functionList.xml into multifile in functionList Folder
Hello,

As explain in Title, I wish to have one file by language in the same folder.
So it will be more easy to change or update them, copy/past from different sources or get them in git repo, etc.

### PR DESCRIPTION
**Pull request by donho**
New "functionList" will be added beside of notepad++.exe or "%APPDATA%\Notepad++\", according the installation mode.
All splited files are localized in this folder with the explicit language name.

"overrideMap.xml" is optional for overriding the default functionList parse rule files, and for adding UDL parse rule files.

Close #4896

### CODE REVIEW

**Comment by chcg** [comment]
Necessary build adaptions:
- mingw: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/makefile#L220
- unittest: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml#L74-L78

**Comment by donho** [comment]
@chcg Sure, the PR of build adaption will come later.

**Comment by donho** [comment]
@chcg I need your help.
The build of last commit failed on Unit test:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/35760820/job/q6d1c3mdd9s34hi2

However, the following line copy *.* from PowerEditor\installer\functionList\ to PowerEditor\bin\functionList, according this line I added in the previous commit:
`Copy-Item "$env:APPVEYOR_BUILD_FOLDER\PowerEditor\installer\functionList\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\PowerEditor\bin\functionList"`

What am I missing? 
Is there anyway to check if all the functionlist xml files are copied into PowerEditor\bin\functionList\ ?
Is PowerEditor\bin\notepad++.exe run for unit-tests ?

**Comment by chcg** [comment]
@donho Not much. The bin folder doesn't contain a subdir functionList and the command is not creating it in that format, see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7

`Copy-Item "$env:APPVEYOR_BUILD_FOLDER\PowerEditor\installer\functionList" -Destination "$env:APPVEYOR_BUILD_FOLDER\PowerEditor\bin" -Recurse
`

**Comment by chcg** [comment]
See https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/35763276/job/fgjg5kxym6ig76kf test are running again, but bash is failing:

> Downloading npp.7.9.portable.minimalist.7z (1,454,804 bytes)...100%
> Test: 807.3179 ms
> asm ... OK
> Test: 521.7907 ms
> autoit ... OK
> Test: 542.6816 ms
> bash ... KO
> result = -1
> There are some problems in your bash.xml
> Test: 521.0563 ms
> asm ... OK
> Test: 546.433 ms
> autoit ... OK
> Test: 546.6918 ms
> bash ... KO
> result = -1
> There are some problems in your bash.xml
> Command exited with code -1

**Comment by ArkadiuszMichalski** [comment]
Maybe for test check after copy how the new folder look like (immediately and with some delay)?

```ps1
$files = Get-ChildItem "path"
echo $files.Count
echo $files

Start-Sleep 5

$files = Get-ChildItem "path"
echo $files.Count
echo $files
```

**Comment by donho** [comment]
@chcg  Thank you for your commit.

I've modified `...\notepad-plus-plus\PowerEditor\Test\FunctionList\bash\unitTest.expected.result` for aligning with the current result (on my local repo), and the modified `unitTest.expected.result` is more accurate.

It seems there's the difference of test environment between my local repo & build system. What I know is ScinLexer.dll, but I have downloaded `https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.9/npp.7.8.9.bin.minimalist.7z` and swap it in my local repo, same result (modified `unitTest.expected.result` passed).

Is there any other difference you can tell in our building system?

**Comment by donho** [comment]
@chcg OK, I see the problem:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9019

I will switch back `unitTest.expected.result`.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c0c070abaf6c8acfac3fe91c777a50b537b240c6

**Pull request closed without merging**
