### PR TITLE
Update turkish.xml

### PR DESCRIPTION
**Pull request by Tmp341**
Updating to latest.

### CODE REVIEW

**Comment by a-polivanchuk** [comment]
Hi @Tmp341 

Turkish translators of Notepad++ are working on https://crowdin.com/project/notepadpp
There are a lot of new translations and it would be good if you join and collaborate with them.
Thanks!

**Comment by Tmp341** [comment]
This is not up to date after the latest changes.

I've taken a look. Why all i can see is english.xml?

**Comment by a-polivanchuk** [comment]
I'll update existing Turkish translation from this PR later today.

**Comment by Tmp341** [comment]
I'm trying to add a couple of changes. It will be added here today or maybe tomorrow.

**Pull request closed without merging**
