### PR TITLE
Function List tab stops

### LINKED ISSUE #8665: [Feature Request] Function List tab stops
### Description of the Issue
When using the built-in Function List (View menu => Function List), the Tab key does not seem to do anything.  One would normally use the Tab key to keyboard-navigate between the forms controls (tab stops).  The Function List form has controls:

- Search box
- Sort button
- Refresh button
- Tree view

Can we make the Tab key cycle between those elements?  It would make searching in the search box then Tab to the results in the tree view and press Enter to navigate to that section of the document.  Currently, after searching, one needs to mouse click into the tree view results.

### Steps to Reproduce the Issue
1. Open document that has a Function List parser (e.g., C, C++)
2. Open Function List .. View menu => Function List
3. Click in the Search text box at the top of Function List
4. Type the name of a function to narrow the tree view results
5. Press the Tab key
6. Nothing happens

### Expected Behavior
I expect the Tab key to activate the Tree view control - or at least navigate between the Search box, sort order button, refresh button and tree view control.

### Actual Behavior
Nothing happens when pressing Tab key in the Function List form.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Aug  5 2020 - 03:12:03
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1339
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll AutoSave.dll BetterMultiSelection.dll ChangedLines.dll CodeAlignmentNpp.dll ColumnTools.dll ComparePlugin.dll CsvQuery.dll CustomizeToolbar.dll DoxyIt.dll DSpellCheck.dll Explorer.dll GitSCM.dll JSMinNPP.dll MarkdownTableGenerator.dll NppConsole.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppMarkdownPanel.dll NppMenuSearch.dll Python Indent.dll QuickText.dll RelativeLineNumbers.dll SpeechPlugin.dll SurroundSelection.dll TagLEET.dll XMLTools.dll ZoomDisabler.dll

### PR DESCRIPTION
**Pull request by vinsworldcom**
Resolve #8665 

Allows Tab key in Function List to switch between the search edit box and the treeview controls.

### CODE REVIEW

**Comment by donho** [comment]
@vinsworldcom 
Could you solve the conflict please?

**Comment by vinsworldcom** [comment]
@donho 
We need both `else if`, one is for the ESCAPE key to switch to main Scintilla, the other is for TAB key to switch to search box.  I tested the resolved merge on my local copy and I have both functions now.  Thank you!

**Comment by sasumner** [comment]
@vinsworldcom The diff for https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8897/commits/822c96b10a810328321f1047bbc3f1b2acd1746d shows the whole document as different.

**Comment by donho** [comment]
The result is whole file is removed and readded:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8897/files

I cannot merge this PR. Please redo a new one.

**Comment by vinsworldcom** [comment]
Sorry - I tried to resolve online with the GitHub tools.  I'll redo a new one.

**Comment by sasumner** [comment]
> I tried to resolve online with the GitHub tools.

I have not had great luck resolving conflicts that way either, if you mean via the web based stuff.

**Comment by vinsworldcom** [comment]
Ok - submitted PR #8924.

**Pull request closed without merging**
