### PR TITLE
#15604 open files from FolderAsWorkspace as read-only with switches -openFoldersAsWorkspace -ro

### LINKED ISSUE #15604: [Feature] LogViewer use-case: FoldersAsWorkspace open files as read-only with -ro option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When I launch Notepad++ with command line switches `-openFoldersAsWorkspace -ro ` and I pick files from the Workspace, the -ro switch is ignored.

We all hate modifying log files by accident!

### Describe the solution you'd like.

I would prefer if the editor operates in read-only mode when picking files from Workspace, unless I explicity unset the option for a file. 

### Debug Information

```shell
n/a
```

### Anything else?

Working on potential fix

### PR DESCRIPTION
**Pull request by BubuC**
(LogViewer use-case)
- When using -openFoldersAsWorkspace -ro  switches, I would prefer if the editor operates in read-only mode, unless I explicity unset the option for a file, for the session. 
- When I turn on monitoring, if file is stale, I expect file to be reloaded and scrolled to end.
- When I turn off monitoring, the read-only UI state should be restored to prior status, not cleared.

note: nppParam.getCmdLineParams not synced with nppParam.getCmdLineString from launch, so used latter

fix #15604  #15660 #13181

### CODE REVIEW

**Comment by donho** [comment]
There are 2 logic flaws in the behaviour of this PR.

Notepad++ can be launched from CMD to open files directly:
1. by listing their path one by one.
2. by listing a session file, for opening a group of files of the saved session (`-openSession`)

Currently `-RO` is applied only to the 1st case. Such behaviour is coherent to me.
It can be discussed for `-RO` being applied also to the 2nd case, since the result of `-openSession` is making the files opened directly.

So the 1st logic flaw in the behaviour is that `-openFoldersAsWorkspace` doesn't open any file but Folder as Workspace with the folder only. 

The 2nd logic flaw in the behaviour of the PR is, consider the following command:
`.\notepad++.exe -multiinst -nosession -openFoldersAsWorkspace -ro c:\temp`

After launching the above command, *c:\temp* is opened in Folder as Workspace, and open the files from *c:\temp* from Folder as Workspace, they are all read-only, which is good. However, when you add a new folder in FaW, and open any file under the new opened folder, the file is opened as read-only, but it shouldn't be - because `-RO` should be applied only to *c:\temp*.

As a result, `-RO` should not be applied to Folder as Workspace logically, IMO.

**Comment by BubuC** [comment]
I don't see it as an unreasonable request, but yes, it requires an accomodation from the prior strict logic. Currently -ro with -openFaW does nothing, so why not make the combination do something some users actually need and would reasonably expect?

My usecase is viewing log files in a folder, which I'd like to do with the editor in readonly by default, for the session. My suggested enhancement is simple, limited in scope, and does not break anything. So, why not consider it?

**Comment by donho** [comment]
@BubuC 
> My suggested enhancement is simple, limited in scope, and does not break anything. So, why not consider it?

I do consider it. And indeed the enhancement is simple & limited in scope. I'm finding a concise way to integrate this feature.

How about using `-readOnlyFoldersAsWorkspace` instead of `-openFoldersAsWorkspace -ro` ?
So with `-readOnlyFoldersAsWorkspace`, FaW will keep read-only constantly during the whole session whenever user add any folder in it - il'll be less confusing than `-openFoldersAsWorkspace -ro`.

Except making FaW read-only, `-readOnlyFoldersAsWorkspace` should have the same behaviour as `-openFoldersAsWorkspace`.

**Comment by donho** [comment]
@BubuC 
What do you think my suggestion?

**Comment by donho** [comment]
Due to the absence of reply, the issue is closed.

**Pull request closed without merging**
