### PR TITLE
Synchronize VS2015 project.

### PR DESCRIPTION
**Pull request by NN---**
Add x64 build for VS2015 project

### CODE REVIEW

**Comment by ariccio** [comment]
VS2015 comes out in ~20 days :)

Keep up the good work!!

**Comment by milipili** [comment]
Just to remind you that we will likely switch to cmake

**Comment by NN---** [comment]
When VS2015 comes out notepad++ should use it.
Currently we don't have cmake.

**Comment by Rikk** [comment]
Why removed `_CRT_NON_CONFORMING_WCSTOK`? I see you added it previously.
I wasn't able to compile here without it.

**Comment by NN---** [comment]
I see the project has been changed again and needs to be resynchronized

**Comment by NN---** [comment]
@Rikk see #628

**Comment by Rikk** [comment]
gj thanks

**Pull request closed without merging**
