### PR TITLE
Make (Find) dlgAlwaysVisible a true Preference setting

### PR DESCRIPTION
**Pull request by sasumner**
Implements #7908 

Removes the old hidden way of providing the same functionality by hand-editing `config.xml` and setting `FindHistory` section's `dlgAlwaysVisible` to `yes`.

Here's what the new _Preference_ looks like:

image

### CODE REVIEW

**Comment by sasumner** [comment]
@donho 
This one has been inactive for some time, wondering if there is a problem?
I thought it would be an "easy" one to accept, as you seemed to be in favor of it here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8131#issuecomment-664009375

**Comment by donho** [comment]
I let you modify the description about `dlgAlwaysVisible` in:
https://npp-user-manual.org/docs/searching/#dialog-based-searching

**Comment by sasumner** [comment]
>I let you modify the description about dlgAlwaysVisible in:  https://npp-user-manual.org/docs/searching/#dialog-based-searching

Okay, I will do so.
BTW, @pryrt , I have added a number of new features lately, but I have forgotten about updating the manual.
Is this something you are slowly taking care of (I haven't noticed) or (probably) I should be doing it?

**Comment by pryrt** [comment]
If it's mentioned in release notes, I try to get to it (I try to modify with the RC release and merge the PR after the final release)... but I don't think I made any specific updates for v7.8.8 - v7.8.9 (maybe because I thought the change list in the forum announcement didn't sound like new features... but maybe I was just too busy to check the manual).

All that to say, if you've added features and don't see a PR that updated the docs, you should go ahead and add them in. :-)

**Comment by sasumner** [comment]
@pryrt said

>I thought the change list in the forum announcement didn't sound like new features...

Don puts that together, and sometimes is rather "brief". :-)
Actually @guy038 does a nice job, post-release, of linking the change log items to issues on github, so it is fairly easy to get a more "in-depth" view of what something is, and if it affects the manual.

**Pull request closed without merging**
