### PR TITLE
One liner powershell install script

### PR DESCRIPTION
**Pull request by QuantumNovice**
If powershell execution policy set as such `Set-ExecutionPolicy Bypass -Scope Process -Force`
then the following one liner will install npp
```powershell
Invoke-Expression -Command (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/powershell-install.ps1')
```

### CODE REVIEW

**Comment by QuantumNovice** [comment]
To see if the patch-1 works. Run this one liner
```powershell
Invoke-Expression -Command (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/QuantumNovice/notepad-plus-plus/patch-1/powershell-install.ps1')
```

**Comment by mere-human** [comment]
What issue does this PR solve? How does it help?

**Comment by QuantumNovice** [comment]
+ Easy CLI installation on windows (almost feels like a package-manager)
+ VMs with npp are much easier to setup.

**Comment by donho** [comment]
@QuantumNovice 
Please see : 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#pull-requests

**Pull request closed without merging**
