### PR TITLE
Fixed the lua syntax highlighter once and for all. (Redone) (Redone)

### PR DESCRIPTION
**Pull request by ccuser44**
This is a redone version of #12656 which is a redone version of #12367
The XML formatter automatically reformatted it so I had to manually add it back. But now it is done. Phew, took a long time.

The Npp Lua syntax highlighter is known for being buggy and hard to develop with.

For some reason the Lua language xml file has the Corona SDK globals pasted in to it. This makes it so that the syntax highlighter makes incorrect suggestions suggesting totally irrelevant funtions from a 3rd party library which makes it cumbersome to use the typing suggestions and is confusing for new users.

Not to mention the Corona SDK including dublicate functions which bricks the suggestor preventing it from showing the arguments & description of the default global functions.

Here are the changes made here:

- Removed Corona SDK & Dublicate default globals
- Seperated different keywords to make it easier to update this in the future
- Added all of the keywords from the newer Lua versions

I'm not sure if there are bugs however. I manually copied the newer keywords from https://www.lua.org/manual/ so there might be a few missing keywords or something else might be incorrect.

### CODE REVIEW

**Comment by donho** [comment]
@ccuser44 
The file you have modified has nothing to do with syntax highlighting.
Have you tested your modification to see the difference?
Could you provide screenshot BEFORE and AFTER your PR to see the improvement?

**Comment by ccuser44** [comment]
> The file you have modified has nothing to do with syntax highlighting.

Well I don't know exactly what to call it. It's the thing that suggest functions&varables. And actually the syntax highligter does use this file to check if a function/variable is a Lua global.

But yes it removes unnecessary junk from the variables&function list from the thing that suggests them.

**Comment by ccuser44** [comment]
> @ccuser44 The file you have modified has nothing to do with syntax highlighting. Have you tested your modification to see the difference? Could you provide screenshot BEFORE and AFTER your PR to see the improvement?

This removes:

- [BUG] Dublicate keywords (These dublicate keywords sometimes cause odd glitches. They also make some features of the Lua (Lua syntax highlighter&variable suggestor) not work)

  image

  image

- [BUG] Removes unnecessary keywords (These make developing Lua with NPP a pain. When you are typing code NPP suggest nonsensical keywords to you. And when you wan't to find valid keywords from a list of 500 junk keywords it makes developing harder. Many users often complain about this (who develop Lua with NPP))

  image

This adds:

- Keywords from newer Lua versions (Makes developing newer versions of Lua easier with NPP)

**Comment by Mateos81** [comment]
> Well I don't know exactly what to call it. It's the thing that suggest functions&varables
It's the auto-completion :)

**Pull request closed without merging**
