### PR TITLE
Update swedish.xml

### PR DESCRIPTION
**Pull request by IluvBread**
Change "konfigurera programspråk" at line 278 to better represent what the menu actually is for.

### CODE REVIEW

**Comment by donho** [comment]
@magol  Could you validate it as well?

**Comment by md2perpe** [comment]
Considering that the English wording is "Style Configurator..." the translation "Stilkonfiguration" would be more straightforward than "konfigurera programspråk" (meaning "configure programming language"). The Danish, Norwegian (both *bokmål* and *nynorsk*) and German translations also talk about style or look (*udseende* in Danish).

**Comment by magol** [comment]
I agree that the current translation is not the best 
"Stilkonfiguration" is a literal translation, but I think the word is to long.
Maybe translate it to "konfiguration av stil" or "konfiguration av utseende"?

**Comment by md2perpe** [comment]
I think that "konfigurera stil" would be best. Words like "av" has little content, are distracting, and should be avoided.

**Comment by IluvBread** [comment]
"Konfigurera stil" would make the user have to read it all to understand what it configures while stilkonfiguration accomplishes the same thing with just a quick glance.

It's a little strange to prioritise the verb instead of the subject since we're literally inside the "settings" submenu.. I don't think anyone going into settings menu expects to do anything but change settings, so why would "Konfigurera stil" be more appropriate than "Stilkonfiguration" ?

**Comment by magol** [comment]
@IluvBread You have a point with your objection. But I do not agree that "Stilkonfiguration" is easier to read than "Konfigurera stil". At a quick lock, I would not understand what "Stilkonfiguration" mean, I have to read the whole word to understand what it's all about.

But I have no strong opinions about it really, if most people thinks that "Stilkonfiguration" is the best, I accept that :-)

**Comment by donho** [comment]
@magol I will close this issue and let you decide the best translation of this item for the next commit.
Thank you.

**Comment by m4gnify** [comment]
Any new thoughts about this? "Konfigurera stil" is a lot better than the **still** current "Konfigurera programspråk". "Konfigurera programspråk" says nothing about what it actually does.

**Pull request closed without merging**
