### PR TITLE
Update chineseSimplified.xml

### PR DESCRIPTION
**Pull request by popcorner**
add new string in 074a4bc

### CODE REVIEW

**Comment by GOLEM777** [comment]
U can add 2 lines in **MessageBox** block.
```
<ExitToUpdatePlugins   title="Notepad++ is about to exit"   message="If you click YES, you will quit Notepad++ to continue the operations.
Notepad++ will be restarted after all the operations are terminated.
Continue?"/>
<NeedToRestartToLoadPlugins  title="Notepad++ need to be relaunched"  message="You have to restart Notepad++ to load plugins you installed."/>

```

**Comment by popcorner** [comment]
@GOLEM777 I checked the english.xml and didn't find these two lines.
Can you tell me the reason? I don't know why I should do this.

**Comment by GOLEM777** [comment]
File NppCommands.cpp messageBox has a body "NeedToRestartToLoadPlugins".
You can check it yourself on 7.7
Add any plugin for install and u see.

**Comment by popcorner** [comment]
@GOLEM777 but my PR is just a translation.
Maybe creating a PR for english.xml will be a good idea?

**Comment by GOLEM777** [comment]
I add it soon in english.xml. Do not worry. Just add it.

**Comment by popcorner** [comment]
@GOLEM777 I'll translate these lines when they are merged into the master branch.

**Pull request closed without merging**
