### PR TITLE
Fix delimiter selection crash issue

### LINKED ISSUE #12384: Delimiter selection crashes program
### Description of the Issue

Setting open and close characters to quotation mark ("), and then double clicking with the left mouse button while holding the Ctrl key on the last empty line in a file crashes the program.

### Steps to Reproduce the Issue

1. Go to: Settings → Preferences... → Delimiter → Switch open and close characters to quotation mark (") and close the Preferences window.
2. Create new document (Ctrl + N), type something and press Enter to create a new line
3. While holding the Left Control key, double click your left mouse button on the empty line
4. Program should now close itself

### Expected Behavior

Program should not select anything (as nothing matches) and not close itself.

### Actual Behavior

Program crashes.

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2130
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Video: https://www.youtube.com/watch?v=RSd6CAQn8gk

### PR DESCRIPTION
**Pull request by donho**
Fix #12384

### CODE REVIEW

**Comment by xomx** [comment]
@donho 

I am not at my devel PC now but I think that this PR will suffer from [the same problem](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12620#issuecomment-1344324201) as the previously rejected one - try the following with your new fix:
- go to  the N++ Preferences -> Delimiter and check the "Allow on several lines" there
- then repeat the reported Ctrl+rightclick on an empty line after some text

**Comment by donho** [comment]
@xomx 
Thank you for your psychic debugging. The last commit should fix this issue.
Let me know if you find other problems.

**Comment by xomx** [comment]
Elegant universal solution.,no more crashes!

**Comment by donho** [comment]
@xomx 
Thank you for testing... and suggestion!

**Pull request closed without merging**
