### PR TITLE
Additions to HTML lang and auto-complete

### PR DESCRIPTION
**Pull request by Rikk**
HTML auto-complete
- add missing html elements and global events/attributes
- remove some deprecated elements, keeping popular ones
- remove duplicates

HTML lang
- add missing html elements (including deprecated ones) and global events/attributes to langs.model.xml
- remove duplicates

### CODE REVIEW

**Comment by Rikk** [comment]
Also fixes https://github.com/notepad-plus-plus/notepad-plus-plus/issues/222

**Comment by milipili** [comment]
There is no need for several commits here. Please make a single commit

**Comment by Rikk** [comment]
That's how web interface works, each file edited generates a new commit... I will need to create a local repo for doing that, oh hell

**Comment by milipili** [comment]
Do not worry for this time we will do it :)

**Comment by Rikk** [comment]
Created a new Pull https://github.com/notepad-plus-plus/notepad-plus-plus/pull/336

**Comment by milipili** [comment]
Thank you

**Pull request closed without merging**
