### PR TITLE
Show a tooltip for the close tab menu item

### LINKED ISSUE #9256: Add tooltip to [X] button located in the menu bar.
### Description of the Issue

There is no any infos what [X] button located in the menu bar does. It exists on menu bar so it might as well mean closing the menu bar.

I am also wondering if this tooltip could include the number of open files from both views (Total: 10 or Total: 10/2 if second view is open). which would solve the problem described in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8338.  If there is a possibility to detect the necessity of displaying the tooltip somehow, then determining the number of open files would only proceed when someone hovers over the [X] button (no need to listen to closing / opening tabs). This is just an additional note, but you can skip it if nobody wants it, I opened this bug mainly for basic information about what the [X] button does.

### Steps to Reproduce the Issue

1. Open Npp.
2. Move mouse curosr over the [X] button located in the menu bar.

### Expected Behavior
Display tooltip with proper infos (like "Close active tab").

### Actual Behavior
There is no tooltip.

### Debug Information
```
Notepad++ v7.9.1   (32-bit)
Build time : Dec 10 2020 - 20:20:23
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : Explorer.dll 

```

### PR DESCRIPTION
**Pull request by mere-human**
Close tab menu item is the rightmost "X" in the menu row.

Extend ToolTip class:
- move mouse tracking code to class methods
- add a posibility to show it at the cursor position
- reposition if it is outside the display bounds

Fix #9256

### CODE REVIEW

**Comment by mere-human** [comment]
Now the tooltip for the [X] button is displayed like this:
image
When maximized:
image

Also, this effectively fixed a weird bug with tooltips in docker panels that couldn't be shown when the app is maximized.
Before the changes:
image
After the changes (cursor wasn't captured):
image

**Comment by GOLEM777** [comment]
May be can you do it #8955 ?

**Comment by mere-human** [comment]
> May be can you do it #8955 ?

Do you mean, add a tooltip to the close button in "Incremental search" as well?
image

Or you want me to fix that other issue?

**Comment by GOLEM777** [comment]
Add translate of 'Rotate border' and 'Incremental search'!

**Comment by sasumner** [comment]
@GOLEM777 

>May be can you do it #8955 ?

Please try to avoid mentioning unrelated issues like this, presumably as a way to bring attention to them.

**Comment by GOLEM777** [comment]
Sry! ))

**Comment by mere-human** [comment]
@donho 
Could you, please, take a look at this PR?
It not only fixes a reported issue but also improves the tooltip positioning.

**Comment by sasumner** [comment]
@mere-human 

@donho _eventually_ gets to all open PRs.  
Don't worry.  :-)
Sometimes his prioritization is a mystery known only to him, but that's OK. :-)

**Comment by mere-human** [comment]
> Don't worry. :-)

I was thinking that these tooltip changes might be useful if there will be a new tooltip added in scope of #9566

**Comment by donho** [comment]
@mere-human 
I don't review the code yet, but a lot of modification for just adding a tooltip on a button... I wonder if it's really necessary.

**Comment by mere-human** [comment]
> I don't review the code yet, but a lot of modification for just adding a tooltip on a button... I wonder if it's really necessary.

@donho 
More modifications were made because:
1. Fixed bug when a tooltip located in the rightmost part of the display goes off screen.
With this bug, the new tooltip would be useless.
See my comments above https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9484#issuecomment-773577954
2. Duplicated code was moved to the ToolTip class.

**Comment by ArkadiuszMichalski** [comment]
In fact, the ["Close"](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9484#issuecomment-773577954) tooltip for `[X]` in docked panel (when put panel in right side) is out of screen (when main window is maximized). I don't see this problem, e.g. for these 3 buttons in FAW pannel (`Expand...`, `Collapse...`, `Locate...`) or for full path for files in this panel, for buttons on the toolbar in NPP, for `[X]` button on tabs or for the checkbox in the search window (upper right). 

Are there any other items where the tooltip shows  out of screen?

**Comment by donho** [comment]
> Fixed bug when a tooltip located in the rightmost part of the display goes off screen.
With this bug, the new tooltip would be useless.

Without applying this PR, I don't see any bug about tooltip, so it's not about "bug-fix", but rather an adaptation for this new feature.
 
> See my comments above #9484 (comment)

For few people it could be annoying, but it's absolutely not a bug.

Duplicated code was moved to the ToolTip class.

> Keep them as it then. I will do it myself when I've got time.

I will close this PR because the benefit of it is less than the eventual risk.
I have another idea and I'll post it on #9256. If you want to implement it, you're welcome.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9484

**Comment by donho** [comment]
@ArkadiuszMichalski 
I cannot reproduce it under Windows10 - it's surely an issue under only windows 7

image

**Comment by mere-human** [comment]
> I will close this PR because the benefit of it is less than the eventual risk.

I can split this PR up into 2 parts. To address the issue #9256 I will simply add a new tooltip and that's it.
I can create another issue for that problem when the tooltip is off the screen. The rest of the code will address that.
Sounds good?

**Comment by ArkadiuszMichalski** [comment]
@donho 
>I cannot reproduce it under Windows10 - it's surely an issue under only windows 7

But try on the [x] button above. 
image

**Comment by sasumner** [comment]
>But try on the [x] button above.

If I try it on FaW, I see the tooltip span the monitor I have N++ full-screen on and the monitor to its right:

image

But if I try it with N++ on my rightmost monitor, it is truncated and I only see the "C" in "Close" as the tooltip.

On Win10.

**Comment by mere-human** [comment]
> > I will close this PR because the benefit of it is less than the eventual risk.
> 
> I can split this PR up into 2 parts. To address the issue #9256 I will simply add a new tooltip and that's it.
> I can create another issue for that problem when the tooltip is off the screen. The rest of the code will address that.

@donho Any thoughts about this and the comments above?
If no, then just let me know and I'll try to forget about this PR.

**Comment by donho** [comment]
@mere-human 
>> > I will close this PR because the benefit of it is less than the eventual risk.
>> 
>> I can split this PR up into 2 parts. To address the issue #9256 I will simply add a new tooltip and that's it.
>> I can create another issue for that problem when the tooltip is off the screen. The rest of the code will address that.
>>
>@donho Any thoughts about this and the comments above?

Sounds good to me.

**Pull request closed without merging**
