### PR TITLE
Fixed Read-Only flag (user read only) syncing issue

### PR DESCRIPTION
**Pull request by SinghRajenM**
Fixed issue #4942

### CODE REVIEW

**Comment by SinghRajenM** [comment]
@donho Could you please review this PR?

**Comment by donho** [comment]
@SinghRajenM Thank you for the fix.
I just found another glitch: when the file is set RO via Notepad++, then set this file system RO outside of Notepad++, "Set RO" command is not disabled. Could it be enhanced with the minimum effort?

**Comment by SinghRajenM** [comment]
>I just found another glitch: when the file is set RO via Notepad++, then set this file system RO outside of Notepad++, "Set RO" command is not disabled. Could it be enhanced with the minimum effort?

@donho , I will check it soon. Thank you!

**Comment by SinghRajenM** [comment]
@donho I could not reproduce this issue with latest code.

However, figured out an MS bug (mostly due to cache). 😜 
1. Set a file RO in notepad++
2. Now set system read only file outside of npp (right click on file-> properties->check Read-Only). **Just click on apply, DON'T click OK that makes sure that properties dialog remains open**
3. Now clear system read only flag using from Npp using command (clear read-Only flag).
4. Now come back to file properties dialog. It will indicate that file is still read only (but in actual not, as we removed that flag using npp). Anyway, now uncheck and check again. Now click on OK/Apply and close the properties dialog.
5. Now open properties dialog again, **You will notice that still file is not read only, but we tried to make it read only in step 4.**

I feel, you might have encounter this scenario. If not let me know.

MSBug

**Comment by donho** [comment]
> I just found another glitch: when the file is set RO via Notepad++, then set this file system RO outside of Notepad++, "Set RO" command is not disabled. Could it be enhanced with the minimum effort?

Never mind, I guess it's due to the File Status autto-detection was disabled.
Thank you for your investigation.

**Pull request closed without merging**
