### PR TITLE
Fix for "Monitoring" doesn't detect changes #3142

### PR DESCRIPTION
**Pull request by jrocha**
Just added a flag to detect changes in file size.

### CODE REVIEW

**Comment by drewler** [comment]
I have tested your code and it works perfectly 😄 

I hope it gets merged soon!

**Comment by vdeconinck** [comment]
+1
This small fix should work 99.99% of the time (the exception being overwriting bytes in random access mode), and 100% of the logs, with no adverse effect. 
Nice catch.

**Comment by billybooth** [comment]
Any word on getting this PR accepted?  Seems like an exceedingly safe, no-brainer that will make many of us very happy.

**Comment by jrocha** [comment]
I really would like to know why this is still hanging over here, I really would like to use official binaries again.
@donho Any word on getting this PR accepted?

**Pull request closed without merging**
