### PR TITLE
Issue 8697 bug when using window menu to close last file open in second view

### PR DESCRIPTION
**Pull request by eljefe7000**
This is a fix for Issue [8697](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8697) (Bug when using Window menu to close last file open in second view).  

The code was not checking to see if _idxMap was empty, and _idxMap gets decremented when the user clicks on the "Close Window(s)" button, so I added code to send the dialog a WM_CLOSE message if _idxMap.size() is less than 1.

### CODE REVIEW

**Review by sasumner — DISMISSED** [review]
In testing the PR, I noticed that `new 2` remains in the `Document Switcher` window after closure of that file in the second view -- it should also be removed from there:

image

**Comment by donho** [comment]
@sasumner  Just checked it in master, indeed I can reproduce it as well: 
With 2 new docs in 2 views respectively, this bug can be reproduced not only in Window dialog, but also close it directly via the close button on document tab.

**Comment by sasumner** [comment]
@donho So it seems unrelated to this PR then.
Should open a separate issue for that, I suppose?
Continue evaluating this PR but ignoring that?

**Comment by donho** [comment]
@sasumner 
This PR works around the problem - it's a solution though I don't really like it. In the mean while, I have no better solution so it'll be accepted.

> Should open a separate issue for that, I suppose?

Yes, please. I will close #8697 with this PR.

**Pull request closed without merging**
