### PR TITLE
Make macro menu organizable with submenu

### LINKED ISSUE #5349: Macro submenus feature request
I have many macros and would like to be able to organise them into sub-menus, rather than scrolling through a single long list. Could this be added to a future version please?

### PR DESCRIPTION
**Pull request by donho**
This PR allows users to add one level of submenu manually for macro command in shortcuts.xml, in order to better organize macro menu commands.
For doing it, `<MenuFolder name="my menu 1">` should be added under `<Macros>` tag. User can put any number of `<MenuFolder>` tag, and each `<MenuFolder>` tag can contain any number of `<Macro>` tag. Only 1 level of submenu is allowed.

Here is an example: 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <InternalCommands>
        <Shortcut id="44104" Ctrl="no" Alt="no" Shift="no" Key="0" />
        <Shortcut id="41019" Ctrl="no" Alt="no" Shift="no" Key="0" />
        <Shortcut id="42086" Ctrl="yes" Alt="yes" Shift="no" Key="74" />
        <Shortcut id="42084" Ctrl="yes" Alt="yes" Shift="no" Key="75" />
        <Shortcut id="42085" Ctrl="yes" Alt="yes" Shift="no" Key="81" />
    </InternalCommands>
    <Macros>
        <Macro name="aa" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="A" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="A" />
        </Macro>
        <MenuFolder name="words">
            <Macro name="azerty" Ctrl="no" Alt="no" Shift="no" Key="0">
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="a" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="z" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="e" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="t" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="y" />
            </Macro>
            <Macro name="qwerty" Ctrl="no" Alt="no" Shift="no" Key="0">
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="q" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="w" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="e" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="t" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="y" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000D;" />
                <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000A;" />
            </Macro>
        </MenuFolder>
        <Macro name="BB" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000D;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000A;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="B" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="B" />
        </Macro>
        <MenuFolder name="func">
            <Macro name="Trim Trailing Space and Save" Ctrl="no" Alt="yes" Shift="yes" Key="83">
                <Action type="2" message="0" wParam="42024" lParam="0" sParam="" />
                <Action type="2" message="0" wParam="41006" lParam="0" sParam="" />
            </Macro>
        </MenuFolder>
        <Macro name="azerty2" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="a" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="z" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="e" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="t" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="y" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="2" />
        </Macro>
    </Macros>
    <UserDefinedCommands>
        <Command name="Get PHP help" Ctrl="no" Alt="yes" Shift="no" Key="112">https://www.php.net/$(CURRENT_WORD)</Command>
        <Command name="Wikipedia Search" Ctrl="no" Alt="yes" Shift="no" Key="114">https://en.wikipedia.org/wiki/Special:Search?search=$(CURRENT_WORD)</Command>
        <Command name="Open selected file path in new instance" Ctrl="no" Alt="yes" Shift="no" Key="117">$(NPP_FULL_FILE_PATH) $(CURRENT_WORD) -nosession -multiInst</Command>
    </UserDefinedCommands>
    <PluginCommands />
    <ScintillaKeys />
</NotepadPlus>

```

Fix #5349

### CODE REVIEW

**Comment by alankilborn** [comment]
@donho I think it is awesome that this feature is getting some attention.  Thank you for it, and I look forward to testing it and seeing it in a release!

**Comment by donho** [comment]
The commit of "Updating macro menu on removing macro" ([fbb9689](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12018/commits/fbb96899d2487778bf66eb930fd781d5814fd607)) is not working (cannot remove the menu item from the submenu correctly) and I have no idea to make `RemoveMenu` API work correctly. 

This PR is not for being merged due to this part. If you know how to solve the problem, please let me  know.

**Comment by Patriccollu** [comment]
This change would be great!

I use a lot of macros, especially to handle and prepare source files to be used as input to _OmegaT_ and realize translations from English to Corsican. And it would be very convenient to be able to group all the macros which concern a specific application.

This PR will not only reduce the menu size (from 17 rows to 10 in the below screenshot) but will also avoid confusion between macros that concern several applications.

image

**Comment by donho** [comment]
Please check #12605

**Pull request closed without merging**
