### PR TITLE
Fix tab dragging on WINE and ReactOS

### PR DESCRIPTION
**Pull request by AngryGamer**

### CODE REVIEW

**Comment by donho** [comment]
@AngryGamer I can reproduce #4885 under WINE.
But just applied your PR and test it under my WINE, it dosn't fix this issue :(

**Comment by AngryGamer** [comment]
Alright, I was able to replicate #4885. This should fix it all!

**Comment by donho** [comment]
@AngryGamer Bad news: the new modification in this PR doesn't change anything. After drag & drop a tab, it remains active (which is good), but I cannot activate the other tabs via mouse click. until I close the active one.

**Comment by AngryGamer** [comment]
There's just no way. Are you sure your local build has all patches applied? Try the AppVeyor builds just in case. [win32](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/25346596/job/xa155uoiy4qmn2d5/artifacts) [x64](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/25346596/job/nd525m7nlv8sfqrs)

I was getting weird behavior under this setup, but it's fully functional with all patches applied.
`[user@localhost ~]$ cat /etc/fedora-release`
`Fedora release 29 (Twenty Nine)`
`[user@localhost ~]$ wine --version`
`wine-4.0.1`

**Comment by AngryGamer** [comment]
Actually, I know what's wrong. I'll update the patch again.

**Comment by AngryGamer** [comment]
This should do it.

**Comment by donho** [comment]
@AngryGamer  Good news, it works with the latest modification.
But my concerning is that it might bring some regression ?

**Comment by AngryGamer** [comment]
I think it's probably fine, but I can only vouch for Windows 10. I'd put it into a Release Candidate and let the masses tell us. 😊

**Comment by LordNyriox** [comment]
@AngryGamer: 

>I'd put it into a Release Candidate and let the masses tell us. 

You can test the result using the PR's [AppVeyor build](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/25371531/job/qlgfctopj8b3g5o1/artifacts).  

Just replace the exe from your own Notepad++ 7.7 installation with the equivalent AppVeyor artifact.  But leave the dll alone, because the AppVeyor dll fails NPP's on-launch signature check.

**Pull request closed without merging**
