### PR TITLE
Enhance multi-edit paste and Enter key type

### PR DESCRIPTION
**Pull request by donho**
Also disable auto-indent during multi-editing.

Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14338#issuecomment-1809045648

### CODE REVIEW

**Comment by donho** [comment]
@Ekopalypse @vinsworldcom

This PR should fix [the bugs](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14338#issuecomment-1809045648) reported by @Ekopalypse.
Could you test it and let me know if there are somethings need to be enhanced?

**Comment by vinsworldcom** [comment]
I don't like having to disable auto-indent during multi caret edit.  This is not needed for BetterMultiSelect and it really impacts how I use it.  Using @Ekopalypse example:

```Perl
sub test1 {
    my ($) = @_;

    |
}


sub test2 {
    my ($) = @_;

    |
}

```

I should be able to add commands with multi-caret at the pipe (`|`) symbols and press `Enter` and get the auto-indent.  Before this commit with BetterMultiSelection, this works.  After this commit - **_even with_** BetterMultiSelect - it does not work.

Cheers.

**Comment by donho** [comment]
@vinsworldcom 
> I don't like having to disable auto-indent during multi caret edit. This is not needed for BetterMultiSelect and it really impacts how I use it. Using @Ekopalypse example:

OK, I will see what I can do for it.

**Comment by donho** [comment]
@vinsworldcom 
Could you test the latest commit please? It should work now.
OTOH, it could break BetterMultiSelet... I didn't test with it though.

**Comment by Ekopalypse** [comment]
Works as expected, thank you very much. I'll be testing this version as my "workhorse" for the next couple days to see if anything else pops up, but so far it looks good.

**Comment by vinsworldcom** [comment]
> Works as expected, thank you very much. I'll be testing this version as my "workhorse" for the next couple days to see if anything else pops up, but so far it looks good.

My sentiments exactly.  I'll continue to test, but it works the same both with or without BetterMultiSeletion.

Cheers.

**Pull request closed without merging**
