### PR TITLE
[xml] Update japanese.xml

### PR DESCRIPTION
**Pull request by yasmise**
Add translation texts for these commits:
* Add new localization entries (d039eaa)
* Add navigation to the 1st & last tab abilities (4e6bbbc)

This also includes fix-ups to existing texts, to make it clearer.

### CODE REVIEW

**Comment by yasmise** [comment]
GitHub Action's `xml validation test` failed, but syntax checking by XML Tools plugin reports no error. Maybe this fail comes from temporary error of Action.

**Comment by yasmise** [comment]
@donho Thanks for looking into this.
Reading the Action's log, building lxml caused the fail, and I found that [the last good run used `lxml-4.9.4`](https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/7359505432/job/20034381548), but now, `lxml-5.0.0` is used. Is it possible that version change of lxml affects Actions?

**Comment by rdipardo** [comment]
> I found that [the last good run used `lxml-4.9.4`](https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/7359505432/job/20034381548), but now, `lxml-5.0.0` is used. Is it possible that version change of lxml affects Actions?

@yasmise, @chcg

This does not appear to affect Python 3.12. Could be the runner's [built-in software][0] needs updating. Instead of waiting for GitHub to do it, why not install a newer Python by ourselves?, e.g.

```diff
diff --git a/.github/workflows/CI_build.yml b/.github/workflows/CI_build.yml
index 84ff0eb5e..f9528f895 100644
--- a/.github/workflows/CI_build.yml
+++ b/.github/workflows/CI_build.yml
@@ -58,6 +58,11 @@ jobs:
           name: Notepad++.MSVC.${{ matrix.build_platform}}.${{ matrix.build_configuration}}
           path: PowerEditor\visual.net\${{ matrix.build_configuration}}\Notepad++.exe
 
+    - name: Set up python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
     - name: Run xml validation test for Win32 / Debug only
       if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Debug'
       working-directory: .\
```

[0]: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#language-and-runtime

**Comment by donho** [comment]
> This does not appear to affect Python 3.12. Could be the runner's [built-in software](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#language-and-runtime) needs updating. Instead of waiting for GitHub to do it, why not install a newer Python by ourselves?, e.g.

It seems Github has fixed the problem now.

**Pull request closed without merging**
