### PR TITLE
Clean a bit of Don Ho's foulness

### PR DESCRIPTION
**Pull request by Rikk**

### CODE REVIEW

**Comment by donho** [comment]
I can understand that some of these easter eggs could be appalled. But the part of quotes you want to remove could be appreciated by other people - we all don't have the same sense of humour.

In the future all these easter eggs will be in the plugins included by default (#545). User will be able to remove the easter egg plugin. So this commit is unnecessary.

**Comment by Rikk** [comment]
Good idea. Although poor tasted ones, like the ones I removed, are not recommended for public releases, programs that pretend to be serious, and as widespread as Npp.

**Comment by Rikk** [comment]
Maybe it's good to clarify my opinion about the jokes in general: I'm not against the absolute majority, some are very good indeed! Only a few need to take shower.

**Comment by h-h-h-h** [comment]
:-1: to criticized content.

**Comment by donho** [comment]
Here's my favorite: Anonymous #22 

"It's impossible." said pride.
"It's risky." said experience.
"It's pointless." said reason.
"Give it a try." whispered the heart.
"What the hell was that?!?!?!?!?!" shouted the anus two minutes later.

:)

**Comment by milipili** [comment]
kitten-out
(interpret it as you wish... ^^)

**Pull request closed without merging**
