### PR TITLE
Fix issue 1948 to make inverse bookmarking macroable

### LINKED ISSUE #1948: Marking issues in recorded macro
**Have the following text:**
This is a text is want to keep
This is a text is want to remove
This is a text is want to keep
This is a text is want to keep
This is a text is want to remove
This is a text is want to keep

I.
Start recording a macro.
1. Go at the beginning of the text
1. Go to Find and Replace, Mark tab, check Bookmark line option and enter text _keep_ in Find what area
2. Press Mark all (leave window open) -> lines 1,3,4,6 are marked 
3. Go to Search - Bookmark - Remove unmarked lines -> lines 2 and 5 are removed
4. Press Clear all marks.  -> all marks are cleared
5. Close window and stop recording the macro.
Restore the original text and run the macro.

Expected: 
_This is a text is want to keep_ appears on 4 lines, all of which are **unmarked**,

Actual:
_This is a text is want to keep_ appears on 4 lines, all of which are **marked** 

II. 
**Have the same text.**
Start recording a macro.
1. Go at the beginning of the text
1. Go to Find and Replace, Mark tab, check Bookmark line option and enter text _keep_ in Find what area
2. Press Mark all (leave window open) -> lines 1,3,4,6 are marked 
3. Go to Search - Bookmark - Inverse bookmark -> lines 2 and 5 are marked, lines 1,3,4,6 are unmarked 
4. Go to Search - Bookmark - Remove bookmarked lines. -> Lines 2 and 5 are removed
5. Press Clear all marks.  -> all marks are cleared
6. Close window and stop recording the macro.
Restore the original text and run the macro.

Expected: 
**_This is a text is want to keep_ appears on 4 lines**, all of which are unmarked,

Actual:
**_This is a text is want to remove_ appears on 2 lines** 

System details: Intel i5 at 2.6 GHz, 4GB RAM, Windows 7 Ultimate 64 bit
Application version: Notepad++ v6.9.2

### PR DESCRIPTION
**Pull request by sasumner**
Fix #1948

### CODE REVIEW

**Comment by donho** [comment]
@sasumner 
I've applied your PR, but I can still reproduce the bug.

**Comment by sasumner** [comment]
@donho 

If I grab a fresh copy of 7.7.1 (32-bit) portable, extract to sandbox folder and run `notepad++.exe` from there, I see the bug:

* start macro recording
* execute `Search` (menu) -> `Bookmark` -> `Inverse Bookmark`
* stop macro recording
* attempt to execute `Macro` (menu) ->`Playback` (**cannot do it because it is not enabled**)

If I then grab `Notepad++.Win32.Unicode Release.exe` from the AppVeyor build from this PR and put it in the sandbox folder, running it and executing the above steps results in `Macro` (menu) -> `Playback` item being enabled, and correctly played back (bookmarks inverted) if chosen.

So while I can accept that you can reproduce the bug, I don't know what I'd do next to resolve the situation.  @chcg , can you help me sort this out so as to not bother Don with it further?

**Comment by xylographe** [comment]
@sasumner 
I can confirm (reproduce) your results:
- Without this patch menu item **Macro > Playback** is disabled (grey).
- With this patch applied menu item **Macro > Playback** is enabled, and works as expected, inverting the bookmarks.

However, I can still reproduce case [1] from issue #1948:
Expected:
_This is a text is want to keep_ appears on 4 lines, all of which are unmarked.
Actual:
_This is a text is want to keep_ appears on 4 lines, all of which are marked.

Issue #1948 actually reports two problems. One of them (Inverse Bookmarks not available in macro) is fixed by this PR. The other problem (marks not cleared) seems to persist.

**Comment by donho** [comment]
> However, I can still reproduce case [1] from issue #1948:

Yes, that's what I meant.

**Comment by donho** [comment]
@sasumner OK I saw this PR fixes the 2 part, sorry for not checking that.

**Comment by donho** [comment]
```bash
$ git log
commit 0854647dc01c8803cede919fcb4f830e827577eb (HEAD -> master)
Merge: c37525cd d457753c
Author: Don HO <don.h@free.fr>
Date:   Thu Aug 1 10:02:09 2019 +0200

    Merge branch 'sasumner-issue_1948'

commit c37525cd90d9d7ed0a4c7f50acc1c25fb22fa12f (origin/master, origin/HEAD)
Author: Jani Kesänen <jani.kesanen+github@gmail.com>
Date:   Tue Jun 25 20:59:41 2019 +0300

    Updated Zenburn theme to contain all the languages supported by 7.7

    Close #5829

commit ac1d9deed65df6f3895c690ffed1b74a250afd88
Author: Waldi Ravens <wr86420@gmail.com>
Date:   Wed Jul 31 15:01:12 2019 +0200

    Update french.xml to 7.7.2

    - Add missing entries.
    - Remove surplus entries.
    - Modify encoding menu entries according to #5951.

    Close #5985

commit d457753c0a3c188a8812036b2f2648c56fed085a (sasumner-issue_1948)
Merge: 12ca8921 d54cb56f
Author: Don HO <don.h@free.fr>
Date:   Wed Jul 31 10:10:41 2019 +0200

    Merge branch 'issue_1948' of https://github.com/sasumner/notepad-plus-plus into sasumner-issue_1948

commit 12ca892176745e7bf2370ec561942dc0372a885d
Author: Waldi Ravens <wr86420@gmail.com>
Date:   Wed Jul 31 04:02:46 2019 +0200

    Update french.xml to 7.7.2

    - Add missing entries.
    - Remove surplus entries.
    - Modify encoding menu entries according to #5951.
```

**Comment by donho** [comment]
@sasumner The above info from `git log` after merging your PR into my local master.

Could you redo your PR by following the following steps:
1. Force update your master : 
```
git fetch --all
git reset --hard origin/master
```
2. Create a new branch with a new name.
3. Make your modification and redo a PR.

Sorry for the inconvenience.

**Comment by xylographe** [comment]
@donho 
I tried to reproduce your `git log` result, but everything seems to be OK, no duplicated/spurious commits at all :
```gitlog
PS> git fetch -v upstream master
From https://github.com/notepad-plus-plus/notepad-plus-plus
 * branch              master     -> FETCH_HEAD
 = [up to date]        master     -> upstream/master

PS> git checkout -b px/ScottSummer/InverseBookmarkInMacro master
Switched to a new branch 'px/ScottSummer/InverseBookmarkInMacro'

PS> git pull -v https://github.com/sasumner/notepad-plus-plus.git issue_1948
From https://github.com/sasumner/notepad-plus-plus
 * branch              issue_1948 -> FETCH_HEAD
Auto-merging PowerEditor/src/NppCommands.cpp
Merge made by the 'recursive' strategy.
 PowerEditor/src/NppCommands.cpp | 1 +
 1 file changed, 1 insertion(+)

PS> git rebase master px/ScottSummer/InverseBookmarkInMacro
First, rewinding head to replay your work on top of it...
Applying: Fix issue 1948 to make inverse bookmarking macroable

PS> git checkout master
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.

PS> git merge --ff-only px/ScottSummer/InverseBookmarkInMacro
Updating c37525cd..b793a0e0
Fast-forward
 PowerEditor/src/NppCommands.cpp | 1 +
 1 file changed, 1 insertion(+)

PS> git log -n4
commit b793a0e0f2b57eec451e55038cd75be4c312f5ce (HEAD -> master, px/ScottSummer/InverseBookmarkInMacro)
Author: Scott Sumner <BZWBFQ@NAM.corp.gm.com>
Date:   2019-06-21 15:58:56 -0400

    Fix issue 1948 to make inverse bookmarking macroable

commit c37525cd90d9d7ed0a4c7f50acc1c25fb22fa12f (upstream/master, upstream/HEAD, origin/master)
Author: Jani Kesänen <jani.kesanen+github@gmail.com>
Date:   2019-06-25 20:59:41 +0300

    Updated Zenburn theme to contain all the languages supported by 7.7

    Close #5829

commit ac1d9deed65df6f3895c690ffed1b74a250afd88
Author: Waldi Ravens <wr86420@gmail.com>
Date:   2019-07-31 15:01:12 +0200

    Update french.xml to 7.7.2

    - Add missing entries.
    - Remove surplus entries.
    - Modify encoding menu entries according to #5951.

    Close #5985

commit 99c8610774a8b0342f4d9bd9cf4060453d62136e
Author: bovirus <1262554+bovirus@users.noreply.github.com>
Date:   2019-07-30 17:38:23 +0200

    Update italian.xml

    Close #5977
```

**Comment by xylographe** [comment]
Oops, my apologies to Scott, with `n` and `m` being adjacent keys, and me being a terrible typist, I inadvertently mangled your name.

**Comment by sasumner** [comment]
> Oops, my apologies to Scott, with `n` and `m` being adjacent keys, and me being a terrible typist, I inadvertently mangled your name.

@xylographe No worries, do you think you are the first ever person to mistake my last name (Sumner) with a season of the year (summer)? :)

**Comment by sasumner** [comment]
@donho said:

>Sorry for the inconvenience.

Well, I'm the one that is sorry for making such a disaster out of my first-ever Notepad++ PR !

@donho / @xylographe : 

I think I've sorted out the confusion.  The issue contains TWO distinct bugs (unfortunate, I'd rather see one bug per issue).

Long ago I agreed with BOTH bugs, but the issue sat and when I retested after Meta Chuh closed it, I wrongly did the "clear all marks" step.  I somehow got it in my head that the step was "clear all bookmarks" on the Search menu, instead of what it really was: a "clear all marks" button press in the Mark window.

Thus I declared that bug # 1 was a no longer an issue and that bug # 2 (the inverse bookmarks one) was the only true problem.  So the inverse bookmarks one was the only thing this PR addressed.

I'll work up a single new PR that fixes BOTH issues, unless I get a reply to this stating that it would be better to create a new issue (and thus a second PR) for the two issues in the original #1948 , like so:

* 1948 : keep case I (clear marks), remove case II (inverse bookmarks)
* a new issue: case II (inverse bookmarks) from 1948

**Pull request closed without merging**
