### PR TITLE
Added some error checking during file saving.

### PR DESCRIPTION
**Pull request by AtlasHackert**
Every once in a while Notepad++ somehow saves a zero byte file, and I have to retrieve the properly saved file from my temp directory. I've added additional error checking in the relevant parts of the code that hopefully will catch this problem.

### CODE REVIEW

**Comment by chcg** [comment]
Appveyor issue seems to be caused by a boost download issue, maybe not be the code change:

Running Install scripts
Invoke-WebRequest -OutFile boost_1_55_0.7z -UserAgent Wget/1.17.1 https://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.7z
7z x boost_1_55_0.7z 2>nul >nul
Command exited with code 2 

Maybe relevant to find the root cause of the crashes for #1835 and #1843

**Comment by donho** [comment]
@AtlasHackert  Could you solve the existing conflict?

**Comment by AtlasHackert** [comment]
How do I see what the conflict is? All I see is some "AppVeyor build failed" error, but as @chcg said that seems to be caused by a failure to download boost, which is out of my control.

**Comment by milipili** [comment]
For AppVeyor, probably a temporary failure. About the conflicts, some changes have already been made. See the [attached diff file](https://github.com/notepad-plus-plus/notepad-plus-plus/files/348862/conflicts.txt)

**Comment by xylographe** [comment]
@AtlasHackert 
```
git fetch --prune upstream master
git rebase upstream/master master
git status
```
Follow instructions from `git status`.
When conflicts are solved,
```
git push --force origin master
```

**Comment by donho** [comment]
There are still some conflicts.
I'll add them manually.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/38ddd32ac51c7a34b6f8f47c9571c45d4dbf9bef

**Pull request closed without merging**
