### PR TITLE
Enlarge your name field size!

### LINKED ISSUE #9849: Rename Current Tab is limited to 20 characters
### Description of the Issue

When using File > Rename... on a yet unsaved file ("Rename Current Tab"), the text input for the new name is limited to 20 characters. There doesn't seem to be a good reason for that, because file names (which serve the same purpose after saving) are not limited to 20 characters. It is often useful to give scratch documents a description that may be longer than 20 characters.

### Steps to Reproduce the Issue

1.  File > New
2.  File > Rename...
3.  Type characters into the New Name text input of the Rename Current Tab dialog

### Expected Behavior
It should be possible to enter more than 20 characters for the new name. A reasonable limit would be 255 characters.

### Actual Behavior
It is not possible to enter more than 20 characters for the new name.

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

### LINKED ISSUE #10961: Rename has a length limit
image

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : D:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1415
Current ANSI codepage : 936
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll

### PR DESCRIPTION
**Pull request by donho**
Rename current tab & Rename User Language name could be up to 63 characters now!
(Before this implementation the limit size is about 20 characters)

Fix #10961, fix #9849

### CODE REVIEW

**Comment by alankilborn** [comment]
If you can give some attention to this feature (e.g. this current PR), how about also the ability to rename under plugin control, e.g. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8916 ?

**Comment by donho** [comment]
@alankilborn 
I don't mind to remove some restrictions which took almost 0 effort and makes a lot of users happy, but I don't add the features which are requested by (very) few users, and the features in question needs a lot of coding effort.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c0989d472cf6523e37b8d3bc9aa1ec0dc0b9a59f

**Comment by alankilborn** [comment]
@donho

> previously to donho: how about also the ability to rename under plugin control

> previously to alankilborn: I don't mind to remove some restrictions which took almost 0 effort and makes a lot of users happy, but I don't add the features which are requested by (very) few users, and the features in question needs a lot of coding effort.

Another user has requested this, see [HERE](https://community.notepad-plus-plus.org/topic/25804/how-to-call-the-api-to-rename-a-new-tab).

**Pull request closed without merging**
