### PR TITLE
Added missing lines for russian.xml (added PluginsAdminDlg)

### PR DESCRIPTION
**Pull request by GOLEM777**

### CODE REVIEW

**Comment by donho** [comment]
@GOLEM777 Could you please update translation in this PR?
Here's the diff of new entries:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5080fdf2d869db0138693965c8f546964917941f#diff-2a8496e2537c34b95cbeca007cd2346b

**Comment by GOLEM777** [comment]
**I have already added everything!**  
 Added all new lines and   **PluginsAdminDlg** too. )))
Mark **_suspended_** not need.  
Everything is ready for release.

**Comment by SinghRajenM** [comment]
@GOLEM777 
You need to translate from 
```<Item id="48503" name="Generate into clipboard"/>``` 
to 
```<Item id="48503" name="Generate from selection into clipboard"/>``` 
as well as per db8b20dd156109c8ab0db6455b6c2b66e02701b4

**Comment by donho** [comment]
@GOLEM777 Oups! Sorry about that!

**Pull request closed without merging**
