### PR TITLE
Update english.xml to v8.3

### PR DESCRIPTION
**Pull request by dfs-**
* add translation for WantToOpenHugeFile as referenced by commit 46011e3
* add previously untranslated drop-down items in Preferences > Print

### CODE REVIEW

**Comment by rddim** [comment]
@dfs- 
Could you check that the `Add` button stop working if you translate for example `Full file name path` to something different please?
I add bulgarian localization for the combo strings, they appear in the menu, but the `Add` button does not work. This make me think that N++ need some code changes to work with translated strings?!

**Comment by GOLEM777** [comment]
@rddim 
You are right, the code stopped working!

**Comment by dfs-** [comment]
Will investigate later. Thought I had this tested, but seems I did not. :/

**Comment by xomx** [comment]
@rddim 
Confirmed for czech.xml, so I am reverting the changes. Thanks.

**Comment by dfs-** [comment]
@rddim @GOLEM777 @xomx

Implemented a fix that is a pull request on its own: #11115

**Comment by dfs-** [comment]
@donho 
I guess you already solved it - thanks for the merge.

**Pull request closed without merging**
