### PR TITLE
update korean 7.9.5

### PR DESCRIPTION
**Pull request by yunbj**
1. add new items

2. remove redundants

3. fix indentation

### CODE REVIEW

**Comment by chcg** [comment]
Build issue is not caused by this PR

**Comment by roc3f** [comment]
> 1. add new items
> 
> 2. remove redundants
> 
> 3. fix indentation

**Comment by roc3f** [comment]
Help

**Comment by donho** [comment]
> fix indentation

It's not acceptable. Please check [contribution rules](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
