### PR TITLE
Fix new document number jumps from "New 1" to "New 3" issue

### LINKED ISSUE #8677: NPP jumps from "New 1" to "New 3" if "Find Results" is displayed
**STR:**
Open NPP (for simplifying the case: no session, `New 1` is open).
Open the Find dialog and press `Find All in Current Document`.
-- The `Find Results` window is displayed.
Open a new file.

**Result:**
`New 3` is opened instead of `New 2`.

(The same happens if you open Python Script console).

**Apparently a minor issue, but https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461 might be related.** 

***
Notepad++ v7.8.9   (32-bit)
Build time : Aug  1 2020 - 16:33:01
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

### LINKED ISSUE #13194: NPP jumps from "new 1" to "new 3" when document map is visible
### Description of the Issue

If the document map is enabled, NPP will not create a "new 2" document but will jump to "new 3".
I believe this is similar to issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8677 that was fixed.

### Steps to Reproduce the Issue

1. Open NPP.
2. Click View > Document Map.
3. Create a new document.

### Expected Behavior

See "new 1" then "new 2" in the tab / document list.

### Actual Behavior

See "new 1" then "new 3" in the tab / document list.

### Debug Information

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2673
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)
    zoomdisabler_x64 (1.2)

The issue no longer occurs when the document map is disabled.
Probably not high priority, just a mild inconvenience for me. I copy paste into 10+ documents at a time from other sources "output1.txt" to "output10.txt" etc, and like to use the document map. It would be easier to align source and destination documents if they were created as "new 1-10" instead of "new 1" then "new 3-11".

### PR DESCRIPTION
**Pull request by donho**
Solution from:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13931#issuecomment-1653523758

Fix #13194, fix #8677

### CODE REVIEW

**Comment by donho** [comment]
@Yaron10
Thank you for your solution.
I will check #11704 later to see what I can do about it.

**Comment by donho** [comment]
@Yaron10 
Please check the latest commit which responds your remark here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13344#issuecomment-1665731435

**Comment by Yaron10** [comment]
@donho,

We might have some misunderstanding here.

1. With the last commit - double-clicking an entry in the Search Results won't jump to a tab named "new".
2. If https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13344#issuecomment-1665619119 is fixed, there's no need to change the first commit.
3. If you agree with @alankilborn's "Maybe it should be given a better title, even if there is no purpose (user wouldn't see it) other than to avoid potential "N++ programmer" confusion at some future point.", how about `std::wstring newTitle = L"newNonMainEditZone ";` _with a space at the end_?

Thank you.

**Comment by donho** [comment]
@Yaron10 
>With the last commit - double-clicking an entry in the Search Results won't jump to a tab named "new".

True! Nice caught!

> If https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13344#issuecomment-1665619119 is fixed, there's no need to change the first commit.

Do you mean the "bug" that allow users to add spaces in front & at the end of the tab name when they try to rename a  tab?

>  how about std::wstring newTitle = L"newNonMainEditZone "; with a space at the end?

Good idea. `newNonMainEditZoneInvisibleTitle ` for ensuring there won't be any collision.

**Comment by Yaron10** [comment]
@donho,

> Do you mean the "bug" that allow users to add spaces in front & at the end of the tab name when they try to rename a tab?

Yes.

`newNonMainEditZoneInvisibleTitle `.

That's better. 👍
How about a short comment explaining the space? 

Thank you again. I appreciate it.

**Comment by Yaron10** [comment]
@donho,

Very nice! 👍 

Thank you.

**Comment by Yaron10** [comment]
@donho,

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6e1b2cab6b42530869f600121443350f0292ad6/PowerEditor/src/WinControls/Window.h#L27

In MS Visual Studio **2017** I need to comment that line or change it to

```cpp
Window(const Window&) = default;
```

Otherwise, I get the `function was explicitly deleted` & `attempting to reference a deleted function` errors.

What do you think?

Thank you.

**Comment by donho** [comment]
@Yaron10 
It doesn't make sense.
By searching ` = delete;` in the project, a lot results are found...
Or the constructor `Window(const Window&)` is really in use? If you can prove it, then this line should be removed.

**Comment by Yaron10** [comment]
@donho,

Thank you for replying.

I know it works for you.
But I have a problem with the following lines:

```cpp
	ScintillaEditView _subEditView = ScintillaEditView(MAIN_EDIT_ZONE);	// only _mainEditView and _subEditView are MAIN_EDIT_ZONE comparing with other Scintilla controls
	ScintillaEditView _mainEditView = ScintillaEditView(MAIN_EDIT_ZONE);	// only _mainEditView and _subEditView are MAIN_EDIT_ZONE comparing with other Scintilla controls
```

תמונה

I'll have to figure it out.

**Comment by donho** [comment]
@Yaron10 
In my opinion, it's one of limitation/bug in MS Visual Studio 2017. 
Couldn't you upgrade your Visual Studio to a more recent version?
By upgrading it, you keep always your MS Visual Studio 2017 for the other projects and you benefit especially all the support of modern C++ syntax of which Notepad++ will use in the future without doubt.

**Comment by Yaron10** [comment]
@donho,

> In my opinion, it's one of limitation/bug in MS Visual Studio 2017.

That was my assumption too.
Thank you for confirming. :+1: 

> Couldn't you upgrade your Visual Studio to a more recent version?

Yes, I should do that.
Currently my Visual Studio is installed on an old Win 7 PC.
I might install the latest version on my Win 10 machine.

**Pull request closed without merging**
