### PR TITLE
Prevent Direct Write being set if user uses RTL

### PR DESCRIPTION
**Pull request by donho**
Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/975d29b30bfd624b6392541b133c2bd32f3212b0#commitcomment-132946815

### CODE REVIEW

**Comment by donho** [comment]
@Yaron10
Please check this PR

**Comment by Yaron10** [comment]
@donho,

1. If you use NPP RTL, the text-direction is RTL on startup (off-topic, this should be configurable IMO).
If you now use "Text Direction RTL", you should get the beep.
Your new block should be under `if (toRTL && !isRTL)`.
2. Even if you fix the previous point - It would be weird that on startup "Text Direction RTL" is OK, but after "Direction **LTR**" & "Direction **RTL**", you get the message.
3. How would you use DirectWrite in NPP RTL? - You disable it on startup.

**Comment by rdipardo** [comment]
@Yaron10 
> 3. How would you use DirectWrite in NPP RTL?

Answer: select `Cascadia Code` or another ligatured font, then enter RTL mode: #11520

**Comment by Yaron10** [comment]
@rdipardo,

Thank you for reminding me of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11520. :)

**Comment by donho** [comment]
@Yaron10 
Just commit a new modification. It should be more coherent.

**Comment by Yaron10** [comment]
@donho,

I suppose that `if (!isWINE && !isTextDirectionRTL())` should be `if (isWINE || isTextDirectionRTL())`.

But we still have a problem: you can't use DirectWrite in NPP RTL.
_And NPP RTL users might want to test DirectWrite_.

How about setting the default to DirectWrite only if !NPP RTL?
if NPP RTL - you can use the (slightly modified) `RTLvsDirectWrite` message on checking `Use DirectWrite` in Preferences.
```
"Text Direction RTL" is not compatible with Direct Write mode.
Continue?
```

**Comment by donho** [comment]
@Yaron10 
> I suppose that if (!isWINE && !isTextDirectionRTL()) should be if (isWINE || isTextDirectionRTL()).

Thank you for correct me the inattentional error.

> How about setting the default to DirectWrite only if !NPP RTL?

What do you mean by "!NPP RTL"?
And "NPP RTL users" ?

**Comment by Yaron10** [comment]
@donho,

I understand the confusion now.

> If RTL localization is not used, but user tries to set Scintilla RTL via menu command "Text Direction RTL", then it's still "NPP RTL" case.

**NPP RTL:** `NppParameters::getInstance().getNativeLangSpeaker()->isRTL()` is `true`.
**Text Direction RTL:** `isTextDirectionRTL()` is `true`.

"Text Direction LTR/RTL" is available whether the localization is LTR or RTL.

If RTL localization is used (**NPP RTL**), how would you use DirectWrite?
I'd like to test it with "**Text Direction LTR**".

**Comment by donho** [comment]
>How about setting the default to DirectWrite only if !NPP RTL?
if NPP RTL - you can use the (slightly modified) RTLvsDirectWrite message on checking Use DirectWrite in Preferences.
```
Text Direction RTL" is not compatible with Direct Write mode.
Continue?
```

@Yaron10 
OK, I think I understand your intention, but I don't see the advantage.
A new user installs Notepad++, the Direct Write Technology is set, and he/she wants to make Scintilla RTL via menu command.
With your suggestion, the following scenario will happen:
1. A Message Box ask the above question, and user clicks Yes.
2. RTL doesn't work.
3. User complains

**Comment by donho** [comment]
@Yaron10 
> If RTL localization is used (NPP RTL), how would you use DirectWrite?

If RTL localization is used, according current PR state, isTextDirectionRTL() will be true. So _writeTechnologyEngine will be affected to the default one - Direct Write won't be set.

Therefore RTL localization will work as expected.

**Comment by Yaron10** [comment]
@donho,

> Therefore RTL localization will work as expected.

That's correct.
But I'd still like to test DirectWrite with "Text Direction **LTR**". And I can't because on startup the direction is **RTL** and you disable it.

```
Text Direction RTL" is not compatible with Direct Write mode.
Continue?
```

I didn't mean this should replace the message you've added in `if (toRTL &&`. That's good whether the localization is LTR or RTL. 
I suggested to _add_ a message on checking `Use DirectWrite` in Preferences if NPP RTL.

> How about setting the default to DirectWrite only if !NPP RTL?

With a new portable NPP, the default interface language is English.
It's getting complex. :)

**Comment by Yaron10** [comment]
@donho,

> OK I see what's your situation (and it can happen to other RTL users) now.

I'd just like to emphasize that `Use DirectWrite` is useless/has-no-effect (if NPP RTL) in the current state of this PR.

***

> How about setting the default to DirectWrite only if !NPP RTL?

In v8.6 the default value of `_writeTechnologyEngine` is `defaultTechnology`. The user can handle that as they wish.
My initial thought was as follows:
If you think it's important to change the default value to `directWriteTechnology`, do it only if NPP layout is LTR.
If NPP RTL, the default value should remain `defaultTechnology`.

But I then realized that in a new setup, the default language is English (-> DirectWrite).
What should happen when the user is switching to Hebrew?  

***

> So the GUI will be RTL, but Scintilla will be LTR.
If editZoneRTL is absent, its default value is "no". What do you think?

1. Do you mean changing the RTL XML localization files?
2. And if the user wants the default text-direction to be RTL (as it is in v8.6)?

***

I don't like it, but you can hide `Use DirectWrite` if NPP layout is RTL.

**Comment by Yaron10** [comment]
Another option.

Add a new setting: `Default Text Direction:` LTR/RTL.
(This can be very useful regardless of DirectWrite: I use NPP RTL, but I want the default text-direction to be LTR.).

Hide `Use DirectWrite` if the new preference is RTL.
Obviously this would require some more thinking & work.

**Comment by donho** [comment]
@Yaron10 
> I'd just like to emphasize that Use DirectWrite is useless/has-no-effect (if NPP RTL) in the current state of this PR.

True. That's why I suggest to make Notepad++ read `editZoneRTL` in the future version. Once it is implemented, the current state of PR can work without changing.


> Do you mean changing the RTL XML localization files?
> And if the user wants the default text-direction to be RTL (as it is in v8.6)?

I might not be clear enough.

In official distribution, all the xml will be kept as they are now.
But user can add `editZoneRTL="no"` in hebrew.xml or any xml for having GUI RTL but Scintilla LTR.
From
```xml
<Native-Langue name="Hebrew" RTL="yes" filename="hebrew.xml">
```
to
```xml
<Native-Langue name="Hebrew" RTL="yes" editZoneRTL="no" filename="hebrew.xml">
```

So in Notepad++ v8.6.1 binary, it finds `RTL="yes"`, then it will try to find `editZoneRTL="???"`. If `editZoneRTL` attribute is absent, then Scintilla follow the `RTL` attribute (normally YES). Otherwise, if `editZoneRTL` value is no, then Scintilla is LTR, even the GUI is RTL.

> Add a new setting: Default Text Direction: LTR/RTL.

I don't like adding options. I guess this policy is clear for the most of community people. 

> Obviously this would require some more thinking & work.

Yes, indeed. Let's think & talk about it for v8.6.1.
But in v8.6, I think Direct Write deserves to be set as default value, at least to try. The old value can always be set to back in the next version.

**Comment by Yaron10** [comment]
@donho,

> But user can add editZoneRTL="no" in hebrew.xml or any xml for having GUI RTL but Scintilla LTR.

It would be easier to switch to English IMO.

> I don't like adding options. I guess this policy is clear for the most of community people.

Nobody is forcing you to do anything!

**Pull request closed without merging**
