### PR TITLE
Fix word spelling in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by donho** [comment]
Sorry I won't take your pr due to the following rule:
*Only bug-fix and feature request will be accepted.*
But it will be fixed. Thank you.

**Comment by frewsxcv** [comment]
> Only bug-fix and feature request will be accepted.

Out of curiosity, why is this a policy? Why should I be discouraged from fixing other issues?

**Comment by ariccio** [comment]
Related: https://visualstudiogallery.msdn.microsoft.com/a23de100-31a1-405c-b4b7-d6be40c3dfff

**Comment by donho** [comment]
@frewsxcv On the contrary, it encourage you to focus on bug-fix or adding of new feature.

**Comment by frewsxcv** [comment]
> On the contrary, it encourage you to focus on bug-fix or adding of new feature.

This doesn't address my question. Wouldn't you want higher quality documentation for the project? If so, you should be accepting these pull requests (or at least cherry-picking the commits).

**Comment by ariccio** [comment]
xref: #225

**Pull request closed without merging**
