### PR TITLE
fix: drop typo

### PR DESCRIPTION
**Pull request by 0o001**

### CODE REVIEW

**Comment by alankilborn** [comment]
Per CONTRIBUTING.md, typos aren't to be fixed via user contributed PR, but rather to be pointed out in an "issue".

**Comment by donho** [comment]
> Your pull requests are welcome; however, they may not be accepted for various reasons. If you want to make some GUI enhancement like renaming some graphic items or fixing typos, please create the issue instead of the pull requests.

Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#pull-requests

**Comment by alankilborn** [comment]
@donho But maybe it is worth correcting the spelling from DRROP... to DROP... here?  Obviously, you could do it in your own commit.

**Comment by donho** [comment]
@alankilborn 
It's done in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3aa9e9280fdd478923bf40914202cac6b537d00c

**Pull request closed without merging**
