### PR TITLE
Fix crash on 64bit build

### PR DESCRIPTION
**Pull request by jh10001**

### CODE REVIEW

**Comment by Rikk** [comment]
Could you please describe when this crash happens and how to reproduce?

**Comment by jh10001** [comment]
2015-09-02 13_59_15-find in files
Click "Find All" button in this dialog.
In 64bit build, if pw's value exceed 32bit, the upper half will be truncated, then cause crash.

**Comment by jh10001** [comment]
Also, assert probably should be in this position.

**Comment by linquize** [comment]
Already fixed by 27787fa062bb3ad411fd2c2cec9963c24cefaccd. You may close this pull request.

**Pull request closed without merging**
