### PR TITLE
Make MinGW gcc build work again

### PR DESCRIPTION
**Pull request by xylographe**
EDIT: Fixes [this MinGW build error](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/53452d96e0bf17f9f5eaaeec9c6beb2424f6d8cd#r36430299).

### CODE REVIEW

**Comment by xylographe** [comment]
@donho
Could you, please, add `#include <memory>` to `PowerEditor/src/WinControls/shortcut/shortcut.cpp`, to fix the AppVeyor mingw build ?

**Comment by donho** [comment]
@xylographe 
Since you have fixed it, why don't we just accept this PR?

**Comment by xylographe** [comment]
@donho 
Commit message updated.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/62622afaebcd87d45813c8dc1bf1be875fc0a0fe

**Pull request closed without merging**
