### PR TITLE
Unify VS project file

### LINKED ISSUE #1523: Unify VS project files
It is possible maintain only one VS project file for both VS2013 and VS2015.

### PR DESCRIPTION
**Pull request by linquize**
Unify VS project file (fixes #1523)

### CODE REVIEW

**Comment by Ede123** [comment]
Popular topic. :wink: 
Please merge!

**Comment by donho** [comment]
error on compiling:
sans titre

**Comment by linquize** [comment]
x86 Build fixed @ 1f45fe3

**Comment by donho** [comment]
sans titre

**Comment by linquize** [comment]
why close?

**Comment by linquize** [comment]
No error for me

**Comment by dail8859** [comment]
Win7, VS2013 Community Edition, both Debug and Release compile fine for me.

**Comment by donho** [comment]
Win10 VS2015 Community edition - error as shown above.

**Comment by linquize** [comment]
I use Win 7 x64 VS2015 Community edition

**Comment by linquize** [comment]
I use Win 7 x64 VS2015 Community edition, without such error.

**Comment by NN---** [comment]
What do you need to merge both projects into one ?
We are here to make one unified vcxproj !

Thanks.

**Comment by NN---** [comment]
Tried now with VS 2015 Update 2 Community , works well.

**Pull request closed without merging**
