### PR TITLE
Update bengali.xml

### PR DESCRIPTION
**Pull request by Oymate**

### CODE REVIEW

**Comment by Oymate** [comment]
The current translations are probably machine translation, some of them are ridiculous, some of these even a machine translation wouldn't mess up.

**Comment by donho** [comment]
@Oymate 
Are you still working on this PR?

**Comment by Oymate** [comment]
Work-in-progress[it's big ya know :)  ]

**Comment by donho** [comment]
Please working locally.
Once it's done, you recreate a new PR.

**Pull request closed without merging**
