### PR TITLE
Display find progress before find in files list creation

### PR DESCRIPTION
**Pull request by pnedev**
Displaying progress percentage is not possible during files list creation but
the currently indexed directory is shown. Cancelling search during this stage is possible as well.

### CODE REVIEW

**Comment by donho** [comment]
The advantage we get from this feature is small, to compare with the price we pay - make simple function more complex.

**Comment by milipili** [comment]
Calculating a progress bar for this kind of feature is usually very time consuming. And it can be quite a disaster on network shares

**Comment by pnedev** [comment]
@donho and @milipili , I made that change because of a user request when N++ was still on SourceForge. The issue the guy had was that he was performing FindInFiles on remote machine (network share) and if there were problems with the network connection the find operation stalled without showing anything. That is because N++ was trying to make the list of the remote files to search and it was waiting for the network timeout but during this search step N++ doesn't show anything (looks like app hang to the user). Only after the list is created the actual search progress appears.

@milipili , The idea is not to show the actual remote files list creation progress - no percentage is shown during this step. During this step the progress window only gives information on the remote directory being checked for files to search (which is the only information the user actually gets about the search status) and it also gives the user a chance to cancel the find operation during this stage (which might be very time consuming if there are network problems).

This is to justify the need from this patch, It's up to you guys to decide whether it's worth merging.

**Comment by milipili** [comment]
Ah oki. Good then.

**Pull request closed without merging**
