### PR TITLE
[xml] Update portuguese.xml

### PR DESCRIPTION
**Pull request by Blackspirits**

### CODE REVIEW

**Comment by hugok79** [comment]
@Blackspirits Let me know every time you make a PR!

**Comment by Blackspirits** [comment]
Ok, sorry.

**Comment by hugok79** [comment]
@Blackspirits 
This is my translation:
[portuguese.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11535080/portuguese.zip)
It's pretty much the same as yours, but it still has some corrections that you didn't make.
You can compare your file with mine. Use Winmerge [https://winmerge.org/?lang=pt_pt](url)

**Comment by hugok79** [comment]
Another thing, you have to put **[xml]** before the title of your PR
For instance: **[xml] Update portuguese.xml**

**Comment by Blackspirits** [comment]
I've already corrected. Thanks hugok79.

**Comment by hugok79** [comment]
> I've already corrected. Thanks hugok79.

Put an @ before mine nickname so I know every time you make a PR
For instance: @hugok79

**Comment by schnurlos** [comment]
@Blackspirits You should add the [xml] in the name of the pull request

**Comment by Blackspirits** [comment]
Done

**Pull request closed without merging**
