### PR TITLE
Connect Scintilla Lexers to npp : SCLEX_ASN1 (Abstract Syntax Notatio…

### PR DESCRIPTION
**Pull request by Cyrillev91**
Connect Scintilla Lexers to npp : SCLEX_ASN1 (Abstract Syntax Notation One), SCLEX_AVS (AviSynth), SCLEX_BLITZBASIC, SCLEX_PUREBASIC, SCLEX_FREEBASIC, SCLEX_CSOUND, SCLEX_ERLANG, SCLEX_ESCRIPT, SCLEX_FORTH, SCLEX_LATEX, SCLEX_MMIXAL, SCLEX_NIMROD, SCLEX_NNCRONTAB, SCLEX_OSCRIPT, SCLEX_REBOL, SCLEX_REGISTRY, SCLEX_RUST, SCLEX_SPICE, SCLEX_TXT2TAGS

Connect Scintilla Lexers to npp : 
- **asn1 (Abstract Syntax Notation One)**       : https://fr.wikipedia.org/wiki/ASN.1#Exemple
- **avs (AviSynth)**       : http://avisynth.nl/index.php/Script_examples
- **blitzbasic** : http://www.blitzbasic.com/bmdocs/command.php?name=Mid&ref=2d_cat
                  http://www.blitzbasic.com/codearcs/codearcs.php?cat=8"
- **csound**     : http://www.csounds.com/manual/html/PrefaceGettingStarted.html
- **erlang**     : http://erlang.org/doc/man/file.html
             http://erlang.org/documentation/doc-5.3.6.13/doc/getting_started/getting_started.html"
- **escript**    : http://erlang.org/doc/man/escript.html
- **forth**      : http://wiki.c2.com/?ExampleForthCode
- **freebasic**  : http://www.freebasic.net/
- **latex**      : http://physics.clarku.edu/sip/tutorials/TeX/intro.html (Sample LaTeX file)
- **mmixal**     : http://mmix.cs.hm.edu/examples/hello.html
- **nimrod**     : http://www.csse.monash.edu.au/~nimrod/nimrodportal/manual/planfileexamples.shtml
- **nncrontab**  : http://www.nncron.ru/help/EN/working/cron-format.htm
- **oscript**    : http://www.oscriptadventures.com/
- **purebasic**  : https://www.purebasic.com/documentation/reference/ide_form.html
- **rebol**      : http://www.rebol.net/cookbook/recipes/0031.html
- **registry**   : windows registry file
- **rust**       : http://rustbyexample.com/std_misc/file/open.html
- **spice**      : http://www.seas.upenn.edu/~jan/spice/spice.overview.html
- **txt2tags**   : https://github.com/txt2tags/txt2tags/blob/master/samples/sample.t2t

**Examples files to validate the addition of lexer :**
[SampleFileForTestLexer.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/587983/SampleFileForTestLexer.zip)

I used **SciTE configuration files** to configure npp (langs.model.xml and stylers.model.xml files)
[SciTE_PropertiesFiles.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/587991/SciTE_PropertiesFiles.zip)

I checked  : color, folding, language menu, status bar, Toggle Single Line Comment, Block Comment, Settings>>Style configurator (style and keywords).

related Issue #1258

### CODE REVIEW

**Comment by donho** [comment]
@Cyrillev91 Nice PR.
Could you solve the conflict so I can merge it into master?

**Comment by Cyrillev91** [comment]
@donho Thank you, PR updated

**Comment by Cyrillev91** [comment]
Sorry I had forgotten to change the size of the tables _langList and _lexerStylerArray (parameters.h)
Since my PR other languages have been added and now we have 81. I put the limitte to 100 (80 previously)
const int MAX_LEXER_STYLE = 100;  // (80 previously)
const int NB_LANG = 100;                // (80 previously)

**Comment by donho** [comment]
@Cyrillev91  In Debug mode (compiled with VS2015) the dialog appeared constantly:
untitled
Any idea about it?

**Comment by Cyrillev91** [comment]
I also have this error without my PR.

The problem comes from the **parseCommandLine()** function of the **winmain.cpp** :

1) Line : TCHAR* commandLine = new TCHAR[lstrlen(cmdLine)];
should be : TCHAR* commandLine = new TCHAR[lstrlen(cmdLine)**+1**];

2) Lines **++commandLine;** modify commandLine value (pointeur adresse)
and line **delete commandLine_save;** FAIL because pointeur value change by ++commandLine

See also : https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b85930314847727ee8070d1417e674afd1bb24ab

Is this problem you encounter?

**Comment by donho** [comment]
@Cyrillev91 Thank you for pointing it out!

**Comment by donho** [comment]
02bdd11700e6fb225157aa59f1f5f1a453865cee

**Comment by dail8859** [comment]
`CSound` is not in the correct place. The "C" menu is no longer sorted.
c

Also the "S" and "V" menus are not sorted. *Note*: this is an existing issue and unrelated to this PR, however if the "C" menu gets fixed, the other 2 might as well.
s
v

**Pull request closed without merging**
