### PR TITLE
Fix [MinGW] Build not work under path with space

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10907. Before test put Notepad++ source code to path with including space. I checked CMD and Git Bash and it works, but some confirmation from others would be advisable.

### CODE REVIEW

**Comment by ArkadiuszMichalski** [comment]
The problem occurs when we run makefile outside it's directory, like appveyor does:
 https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ee884f87bbb66d1431f0d530d0cd25bb7cde6b35/appveyor.yml#L104

Handling this case in line: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ee884f87bbb66d1431f0d530d0cd25bb7cde6b35/PowerEditor/gcc/makefile#L105
it is not very flexible. In the MAKEFILE_LIST variable we have the paths to each processed makefile, but the separator is a space, so if any of them has a space in their path it will be a problem. I have no idea how to get only the path of the current makefile. I'll try to get the value of the `-f` command (if possible).

**Comment by ArkadiuszMichalski** [comment]
Yes, above comment is for this failure.

**Comment by ArkadiuszMichalski** [comment]
@donho 

After this fix spaces in the source path are allowed until we run the `makefile` directly from the `PowerEditor/gcc` folder. Unfortunately outside of this folder will not work (for example when from another folder we specify a `makefile` with the `-f` option). Fixing this would require passing the path to the makefile in an extra variable, and then doing a mass of space conversion to something else (and back it to space again) which will only obfuscate all the code. I just added a short note in `build.md` to avoid spaces in the path for such cases.

**Comment by donho** [comment]
Under both x86 & x64 Native Tool Command Prompt for VS 2022, I've got the same result:

```
C:\tmp\New folder\notepad-plus-plus\PowerEditor\gcc>mingw32-make.exe
* creating BUILD_DIRECTORY bin.i686.build
mingw32-make.exe[1]: *** No rule to make target 'folder/notepad-plus-plus/PowerEditor/gcc/bin.i686.build/libscilexer.a'.  Stop.
mingw32-make.exe: *** [makefile:199: bin.i686.build/libscilexer.a] Error 2
```

I suppose the PR is only for git bash - in this case, I prefer change the Build.md to force users to not put into the folder containing white spaces.

**Comment by ArkadiuszMichalski** [comment]
@donho Can you try directly from CMD running on the system? It looks like you are testing an old makefile or this tool implicitly uses `-f`. On first screenshot I have relative path `../../PowerEditor/gcc/bin.i686.build/libscilexer.a`, and that's why it works because spaces aren't given explicitly. But in your log I can still see absolute path.

image

image

**Comment by donho** [comment]
image

**Comment by donho** [comment]
oups, my bad.
Instead of copying makefile, I copied makefile.rc

**Pull request closed without merging**
