### PR TITLE
Updated swedish translations and fixed indent inconsistencies in all translations.

### PR DESCRIPTION
**Pull request by timint**
Updated swedish translations and fixed indent inconsistencies in all translations. Now using TABs (saving 627 kilobytes wohoo). Good for the planet :)

### CODE REVIEW

**Comment by donho** [comment]
Make your modification compact - don't reformat source code in your request. It makes code review more difficult : 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests
Only swedish translations update from you will be accepted.

**Comment by timint** [comment]
You do as you please. I don't regulary come here so I am not used to your regular rutines for pull requests.

I only edited the whitespace and how in the world would that be done more compact?

The XMLs where a mess of spaces, tabs, linesbreaks here and there. Clean them up and you will free up over half a megabyte. Hey that's a lot of data in a coder's world.

**Comment by chcg** [comment]
@timint Did you use a tool for reformatting the xmls? Maybe it is easier to get donho convinced to rethink about the proposed changes if he could do it on his own and on a regular base.

**Comment by timint** [comment]
@chcg I used the XML Tools plugin for Notepad++ and selected Pretty Print (Text indent). It leaves the line break separations as is but adjusts the leading whitespace for every line.

Here is an example:
image

**Pull request closed without merging**
