### PR TITLE
Refactor code and minor optimization

### PR DESCRIPTION
**Pull request by GermanAizek**
@donho @dail8859

### CODE REVIEW

**Comment by donho** [comment]
> ypo fixing and code refactoring won't be accepted - please create issues with title started with TYPO to request the changing.

ref: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Comment by GermanAizek** [comment]
@donho,
Where exactly is the problem with the style code? I didn't change it, check commit more carefully.

**Comment by donho** [comment]
@GermanAizek 
It's **`code refactoring`** is not accepted. We're trying to focus on bug-fixes or new feature (from issue tracker). Sorry for closing the PR. Hope you understand.

**Comment by mere-human** [comment]
You'll have to create an issue first. Then it can be addressed in a PR. 
For example "Fix warning XXXX reported by PVS Studio in file preference.cpp" But even then, there's a chance a PR won't be accepted due to some other reasons.

**Pull request closed without merging**
