### PR TITLE
Updated Russian translation, russian.xml

### PR DESCRIPTION
**Pull request by arturparkhisenko**
Updated one collocation.

### CODE REVIEW

**Comment by justanotheranonymoususer** [comment]
I approve.

**Comment by arturparkhisenko** [comment]
@donho delicate ping :eyes:

**Comment by arturparkhisenko** [comment]
@donho delicate ping :eyes:

**Comment by arturparkhisenko** [comment]
@donho delicate ping 👀

**Comment by arturparkhisenko** [comment]
@donho delicate ping 👀

**Comment by arturparkhisenko** [comment]
@donho delicate ping 👀

**Pull request closed without merging**
