### PR TITLE
Fix Doc Switcher cut off

### PR DESCRIPTION
**Pull request by ozone10**
fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13053

### CODE REVIEW

**Comment by ozone10** [comment]
`::GetSystemMetrics(SM_CXFRAME)` return different value depending on minimum subsystem version. Windows Vista and newer needs to add `::GetSystemMetrics(SM_CXPADDEDBORDER)` to keep same value as subsystem version for Windows XP.

**Comment by TaleTN** [comment]
FWIW, I would store ::GetSystemMetrics(SM_CXPADDEDBORDER) in a local variable, so it can be reused rather than call it twice i.e.:

`const int paddedBorder = ::GetSystemMetrics(SM_CXPADDEDBORDER);`
`const int leftMarge = (::GetSystemMetrics(SM_CXFRAME) + paddedBorder) * 2 + aSpaceWidth * 4;`
...
`_rc.bottom += (::GetSystemMetrics(SM_CYFRAME) + paddedBorder - 1) * 2;`

**Comment by donho** [comment]
It's indeed a regression - v8.4.8 works fine but not for v8.4.9.

@ozone10 
Do you know where comes from this regression?

**Comment by ozone10** [comment]
image

Previously it was set 5.01 for 32 bit and 5.02 for 64 bit both values for Windows XP. 
Value 6.00 is for Windows Vista.

This setting affect `::GetSystemMetrics(SM_CXFRAME)` as I said in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13054#issuecomment-1418259879

It comes from commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/662b54e28a5ad2787ba198082fc4c23a69849367

**Comment by donho** [comment]
@ozone10 
Thank you for the explanation!

**Pull request closed without merging**
