### PR TITLE
Folder as Workspace: Change folder images after "Expand/Collapse All"

### LINKED ISSUE #8912: Folder as Workspace: folder-images do not change after using "Expand/Collapse All"
**STR:**
Open a folder as Workspace.
Expand the root folder.
Press the **"Collapse All"** button.

**Result:**
The folder-image is "expanded".

תמונה

Just an interesting minor issue.

***
Notepad++ v7.8.9   (32-bit)
Build time : Sep 25 2020 - 21:35:54
Path : C:\---\Notepad++.Win32.Unicode Release.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

### PR DESCRIPTION
**Pull request by mere-human**
Folder images are changed in FileBrowser::notified() when TVN_ITEMEXPANDED
is recieved. This works fine when e.g. expand/collapse using "+" button.
However, when foldAll() or expandAll() are called on a TreeView,
the TVN_ITEMEXPANDED is not sent. The reason is that TVIS_EXPANDEDONCE flag
is set. To reset that flag, it would be needed to pass TVE_COLLAPSERESET
to TreeView_Expand that also removes all child items which is unwanted.

Resolve the problem by notifying TreeView parent manually when recieve
TVM_EXPAND and TVIS_EXPANDEDONCE is set.

Fix #8912

### CODE REVIEW

**Comment by Yaron10** [comment]
The issue still exists with *sub-folders*.
Can you please have a look?

Thank you.

**Comment by mere-human** [comment]
> The issue still exists with _sub-folders_.
> Can you please have a look?
> 
> Thank you.

Should be fine now.

**Comment by Yaron10** [comment]
Great. :+1:

**Comment by donho** [comment]
@mere-human 
I didn't think of treating `TVM_EXPAND` in subclass's procedure. Well played!

**Review by donho — APPROVED** [review]

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ecf44bd085a9d9cb222b5581165e4a6af2384e46

**Pull request closed without merging**
