### PR TITLE
Fix for issue 8617

### PR DESCRIPTION
**Pull request by Roshni-P**
The active index should be updated correctly for the scenario specified in Issue #8617.
Updating the active index ensured that the contents of the New Unsaved file were not lost.

### CODE REVIEW

**Comment by donho** [comment]
Your PR insert a regression : if no file is deleted, the current tab is closed after running "Close All but this" command.

**Comment by sasumner** [comment]
>Your PR insert a regression

Plus, it needs to follow the contributing guidelines better.

**Comment by Yaron10** [comment]
@donho,

> if no file is deleted, the current tab is closed after running "Close All but this" command.

I get the same result with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a82819972a6388668a9ce823738aa24c5572d8f4. Anything I'm missing?

**Comment by Yaron10** [comment]
Fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1eb7d2bef5e7c42c071379154fe11fa30166162a.

**Pull request closed without merging**
