### PR TITLE
Fix exception/crash on Windows Server Core 2022

### LINKED ISSUE #15313: NOTEPAD++ v8.6.8 Crashed and throwing exception when launching on Windows Core Server 2022
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

NOTEPAD++ v8.6.8 crashing and throwing exception on Windows Core Server 2022

Getting error: 
 Exception on WM_CREATE iconList::addicon : Loadicon() function return null

### Steps To Reproduce

1.  Install latest Notepad++ version 8.6.8 x64 on Windows Core 2022 server.
2.  Try to launch Notepad++ application. It crashed.
3.  Dialog box pops up with exception: iconList::addicon : Loadicon() function return null

### Current Behavior

On launching Notepad++ v8.6.8 on Windows Core 2022, it is crashing.
Throwing exception- 
iconList::addicon : Loadicon() function return null

### Expected Behavior

Notepad++ should be launched.

### Debug Information

```shell
Not able to launch Notepad++ after upgrading to v8.6.8 on Windows CORE 2022 Servers.
```

### Anything else?

Notepad++ErrorOnCORE

### PR DESCRIPTION
**Pull request by ozone10**
Make loading icons fail-safe.

Fix #15313

### CODE REVIEW

**Comment by ozone10** [comment]
@donho 
I cannot test is since I am away.

**Comment by xomx** [comment]
@ozone10  @donho 

I do not think this will fix the issue, we probably jumped on that LoadIconWithScaleDown too quickly.

If it is problem with missing/unsupported LoadIconWithScaleDown comctl32 func, the error message will be different (it will originate directly from the OS).

I rather think that there is this code flow:

```
void DPIManagerV2::loadIcon(HINSTANCE hinst, const wchar_t* pszName, int cx, int cy, HICON* phico, UINT fuLoad)
{
	if (::LoadIconWithScaleDown(hinst, pszName, cx, cy, phico) != S_OK) // -> fails but no exception, so it goes to the LoadImage part...
	{
		*phico = static_cast<HICON>(::LoadImage(hinst, pszName, IMAGE_ICON, cx, cy, fuLoad)); // -> this fails too, so hIcon is still NULL...
	}
}
	
if (!hIcon)
	throw std::runtime_error("IconList::addIcon : LoadIcon() function return null"); // -> so it goes here and the message is from the main N++ exception handler...
```

---

I did not have time to search for the comctl32 suport in a Win Core Server but it makes sense to me that it supports that, otherwise it could not run common Win apps...

**Comment by ozone10** [comment]
@xomx 
you might be right, because change to `DPIManagerV2::loadIcon` was already in 8.6.6

**Comment by donho** [comment]
@xomx 
So you think it's failure (problem) from the OS?
If your assumption is true, why did v8.6.7 work?

**Comment by xomx** [comment]
@donho 
> why did v8.6.7 work?

IDK. Maybe the v8.6.8 commits connected to icons somehow?
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cdf32d198b84927539fc0428e3fdbbf09fee85df
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c89033bd8a4bb4505f26377d6a4deae36a505ac0
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c660a71b38ab662f9cf8346c84bc6a39e3d957c

**Comment by donho** [comment]
@xomx 
Let's wait and see the test result from @Pmalhotra2024

**Comment by xomx** [comment]
@donho 

To find out more, create please a new DEBUG PR, with this patch for the DPIManagerV2::loadIcon:

```
#include <format> // TEMP: DEBUG:

void DPIManagerV2::loadIcon(HINSTANCE hinst, const wchar_t* pszName, int cx, int cy, HICON* phico, UINT fuLoad)
{
	HRESULT hr = ::LoadIconWithScaleDown(hinst, pszName, cx, cy, phico);
	if (hr != S_OK)
	{
		std::wstring msg = L"ERROR: LoadIconWithScaleDown WINAPI failed! (HRESULT: ";
		msg += std::format(L"{:#010x}", static_cast<DWORD>(hr)) + L")";
		::MessageBoxW(NULL, msg.c_str(), L"DPIManagerV2::loadIcon", MB_OK | MB_SYSTEMMODAL | MB_ICONERROR); // TEMP: DEBUG:

		*phico = static_cast<HICON>(::LoadImage(hinst, pszName, IMAGE_ICON, cx, cy, fuLoad));
		if (*phico == NULL)
		{
			msg = L"ERROR: LoadImage WINAPI failed! (ErrorCode: ";
			msg += std::to_wstring(::GetLastError()) + L")";
			::MessageBoxW(NULL, msg.c_str(), L"DPIManagerV2::loadIcon", MB_OK | MB_SYSTEMMODAL | MB_ICONERROR); // TEMP: DEBUG:
		}
	}
}
```

**Comment by donho** [comment]
@xomx 

Thank you: done: #15316

**Comment by ozone10** [comment]
issue is due to unsupported ico format

**Comment by ozone10** [comment]
Reuse PR

**Comment by ozone10** [comment]
msys2 failure is due to failure of updating msys2 packages

Maybe using other than transparent icon would be better.

**Comment by donho** [comment]
> Maybe using other than transparent icon would be better.

@ozone10 Why "using other than transparent icon" would make updating msys2 packages better?

**Comment by ozone10** [comment]
@donho 
I have accidentally removed part of text.

"msys2 failure is due to failure of updating msys2 packages", because their site cannot be reached.

Current PR use transparent placeholder. "Maybe using other than transparent icon would be better" for indication.

**Comment by donho** [comment]
The PR is better than https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15331 is, though the dialog needs more clarification. 
I will add more text for it.

**Comment by ozone10** [comment]
@xomx 
that is intended, because all fluent icons now use new ico files with only png images, so it will fail on every toolbar icons.
This will result in blank icons (as seen on tab bar, indicator and close button). 
But because toolbar standard icons use bmp files and these are loaded fine, I use them as some kind of fail-safe solution. User should still switch to standard icons.

**Pull request closed without merging**
