### PR TITLE
Fix: Function list doesnt not work for C# files #3643

### PR DESCRIPTION
**Pull request by uskovboris**
It needs to test this fix compatibility with different languages

### CODE REVIEW

**Comment by MAPJe71** [comment]
Single commit per PR is preferred (especially when they are not directly related) and in its own branch.

**Comment by uskovboris** [comment]
I'm sorry, I'd commit the "fix annoing reload from disk requests" in mistake. I'll recommit "resolve #3643" in the evening

**Comment by aks2161989** [comment]
Hello,

Has this change been incorporated in Notepad++? I am using version 7.8.2 (32 bit) and Function List does NOT work for C#.

Please see [this comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3643#issuecomment-570900692)

**Comment by donho** [comment]
>  It needs to test this fix compatibility with different languages

Other language depends on (and works well with) this core feature, you should fix in `functionList.xml`.

**Pull request closed without merging**
