### PR TITLE
It is rare that one need ordered map, use unordered_map for better pe…

### PR DESCRIPTION
**Pull request by NN---**
…rformance and clear semantic.

### CODE REVIEW

**Comment by ariccio** [comment]
Chandler Carruth dies a tiny bit every time somebody uses a `std::map`

**Comment by donho** [comment]
@NN--- Could you rebase your pull request so I can merge it automatically?

**Comment by NN---** [comment]
I can do it later .
I think merge will have the same effect .

**Comment by NN---** [comment]
Fixed conflict.

**Comment by donho** [comment]
Thank you @NN---

**Comment by NN---** [comment]
You're welcome

**Pull request merged**
