### PR TITLE
Add word-wrap option to find-result window context menu

### PR DESCRIPTION
**Pull request by sasumner**
Implements #8624

### CODE REVIEW

**Comment by sasumner** [comment]
Closing for now as this PR was to build artifacts for @Yaron10 to experiment with.

**Comment by Yaron10** [comment]
@sasumner,

:+1: 
Thank you for a great job!
With really long lines this option is a MUST. 

I couldn't find any faults. :)
The only possible enhancement I can think of is colorizing `Line x`. It's slightly less prominent with `Wrap` ON.

תמונה

But it's probably not worth it.

***
I've tested it with [this](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5044169/extensions.zip) file.
I searched for `id`. The results baffled me and I had to test it with a fresh portable NPP 7.8.9.

תמונה

I don't want to open a new issue if it's already known.

**Comment by sasumner** [comment]
>I've tested it with this file....I don't want to open a new issue if it's already known.

I believe that is a manifestation of the same thing as in #8525
I'm still looking at that one, but it appears the search-result lexer gets confused because there are multi-byte characters in the data.

**Comment by sasumner** [comment]
>only possible enhancement I can think of is colorizing Line x

Well, in theory you can colorize/bold/change-font-size yourself using the _Style Configurator_ settings for `Search result`.
However, because this data screws up the lexer (again, # 8525 ), the results of doing so doesn't look so good:

image

The line-wrapping looks super, though!!
:-)

**Comment by sasumner** [comment]
@Yaron10 
Did you try wrapping with a _Find in these found results..._ search?

**Comment by Yaron10** [comment]
> The line-wrapping looks super, though!!

That's correct. :)

> Did you try wrapping with a Find in these found results... search?

I did and It looked as great. Any issue there?

> Well, in theory you can colorize/bold/change-font-size yourself using the Style Configurator...

:+1: 

***
> I believe that is a manifestation of the same thing as in 8525

I didn't follow all the steps there. In our case wrong characters are highlighted in the Find Results window. 
No need to open a new issue?  

Here's another case:
Paste the following line in a new document.
```
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"_6e1ccc3a-6961-4b99-9455-e04cb868e7c2_-browser-action\",\"_d07ccf11-c0cd-4938-a265-2a4d6ad01236_-browser-action\",\"customizableui-special-separator1\",\"_8883111b-4bc8-4a99-b37f-5672f6cf9834_-browser-action\",\"_4853d046-c5a3-436b-bc36-220fd935ee1d_-browser-action\",\"customizableui-special-separator2\",\"personal-bookmarks\",\"urlbar-container\",\"downloads-button\",\"ublock0_raymondhill_net-browser-action\",\"find-button\",\"_8883111b-4bc8-4a99-b37f-5672f6cf9825_-browser-action\",\"_7773111b-4bc8-4a99-b37f-5672f6cf9825_-browser-action\",\"customizableui-special-separator3\",\"privatebrowsing-button\",\"new-window-button\",\"customizableui-special-separator4\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[]},\"seen\":[\"developer-button\",\"_6e1ccc3a-6961-4b99-9455-e04cb868e7c2_-browser-action\",\"_8883111b-4bc8-4a99-b37f-5672f6cf9825_-browser-action\",\"_8883111b-4bc8-4a99-b37f-5672f6cf9834_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_4853d046-c5a3-436b-bc36-220fd935ee1d_-browser-action\",\"_7773111b-4bc8-4a99-b37f-5672f6cf9825_-browser-action\",\"_d07ccf11-c0cd-4938-a265-2a4d6ad01236_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":16,\"newElementCount\":134}");
```

Search for `browser`.

-- 16 hits. 
-- The search-term `browser` does not appear in the last 7 results.

I think that in such cases NPP should truncate the part *before* the search-term, add `...` and show the search-term.

Known?

**Comment by sasumner** [comment]
>Did you try wrapping with a Find in these found results... search?
>Any issue there?
No issue, I was just wondering if you had a problem with the behavior.
Opening a secondary finder it will use the "wrap" setting from the original finder.
If you open a third finder from the second, it will still use the setting from the original finder, even if you've changed the setting in the second.
It's okay with me. :-)

**Comment by sasumner** [comment]
>...a manifestation of the same thing as in 8525
>No need to open a new issue?

No, not unless something new comes to light.  8525 covers it.

**Comment by sasumner** [comment]
>I think that in such cases NPP should truncate the part before the search-term, add ... and show the search-term.

Wow, with the addition of the "wrap" stuff, this becomes more of a "problem". :-)
Before, if you didn't see the search-term highlighted, you just assumed it was "off to the right somewheres".
With "wrap" on, you fully expect to see it, somewhere...
To implement your suggestion would required a change to the Scintilla part of the code, as it does the lexing for `Search result`.  As I don't fully understand how this lexing works (or I would have already fixed 8525), I don't see changes to this in the future, at least made by me. :-)

>Known?

Well, it is known that long lines (> ~1024) are purposefully truncated in `Find result` window, with perhaps no real reason for it.  See #7723

**Comment by Yaron10** [comment]
> Opening a secondary finder it will use the "wrap" setting from the original finder.
If you open a third finder from the second, it will still use the setting from the original finder, even if you've changed the setting in the second.
...
No, not unless something new comes to light. 8525 covers it.
...
Well, it is known that long lines (> ~1024) are purposefully truncated in Find result window, with perhaps no real reason for it. See 7723

:+1: 

> Wow, with the addition of the "wrap" stuff, this becomes more of a "problem"

Alas, that's true. :)

**Comment by sasumner** [comment]
Reopening this pull request after user acceptance testing and the following nice feedback:

image

Sample 1:  Before wrapping of long lines is turned on:

image

Sample 2:  AFTER wrapping of long lines is turned on:

image

**Comment by donho** [comment]
@sasumner @Yaron10 
Have you ever tried (by applying this PR) searching in a .exe ? There might be some unwanted results.

**Comment by sasumner** [comment]
@donho said:

>Have you ever tried (by applying this PR) searching in a .exe ? 

We advise users on the support forums not to use a text editor for searching non-text (e.g. binary) files.  One reason for this is that NUL ('\0') support in N++ is not complete (yet!).  Searching an .exe is going to cause NULs to appear in the _Find result_ window and this causes several known issues (one is #8270 , there are others, including one I can't find right now regarding copying from the _Find result_ window stops at any '\0' character in a line).

That being said, if you did search an .exe, and the longness of the result bothered you, would you just not right-click and untick "Word wrap long lines"?

I tried some searches on the N++ exe with this feature enabled and did not notice any problems.

>There might be some unwanted results.

What are some other "unwanted results" you are thinking of?

**Comment by donho** [comment]
> What are some other "unwanted results" you are thinking of?

Finally, nothing. :) 
I worried about somethings will never happen.

It looks good this PR, just use "!" instead of "not".

**Comment by sasumner** [comment]
@donho 

>Use the modern operators notation (Use ! instead of not).

OK, will change.
Note that this PR was submitted BEFORE our discussion yesterday in another PR, about preferring usage of `!` instead of `not`.
BTW, isn't `not` more "modern" than `!` ?
BTW, I think you don't like `not` because it is Englishy, and `!` has no language ties. :-)
It's fine, you can like whatever you like.

**Comment by donho** [comment]
@sasumner 
> BTW, isn't not more "modern" than ! ?

Interesting... I thought `not` is like `and` and `or`, which are part of c++98.
If you have any link about this info, please provide it to me.

**Comment by sasumner** [comment]
@donho I did some more research and it appears that `!` actually is more modern than `not`.  So I was wrong.  Perhaps I am thinking about Python where I think it is the other way...or maybe I'm wrong there too.
Anyway, I will use your preference of `!` in Notepad++ code from now on.  (Although a quick search shows a lot of `not`)

**Comment by Yaron10** [comment]
@sasumner,

**STR:**
Search for a relatively long term.
Collapse the Search line.

**Result:**
תמונה

Originally, the underline serves as a separator between segments (search term, file name etc.). 
With "Wrap" enabled, the multiple underlines are slightly confusing.

It's relevant to a wrapped file name as well.
תמונה

I'm not sure it's worth the extra work/code. What do you think?

**Comment by sasumner** [comment]
The underline is an effect from the fold being collapsed, with the first line of the folded "code" being really long.

>I'm not sure it's worth the extra work/code. 

There's no work/code that could be done here --  this is Scintilla at its finest. :-)

>the multiple underlines are slightly confusing

I don't think it is a bad effect.  It's not _ideal_, but...

I say we forget about it and move on. :-)

**Comment by Yaron10** [comment]
Moving on. :)

Thank you.

**Pull request closed without merging**
