### PR TITLE
Update catalan.xml to v7.8.7

### PR DESCRIPTION
**Pull request by Hiro5**
Updated Catalan location for npp 7.8.7.

Sorry I didn't read #7710

Regards

### CODE REVIEW

**Comment by chcg** [comment]
@Hiro5 Could you have a look at #8384 from @xeanhort. Just one updated translation could be used. Maybe you could review your changes and agree how to proceed.

**Comment by xeanhort** [comment]
First contribution here, but at #8384 there's the full description of the changes. I think that the main difference is the sorting.

**Comment by Hiro5** [comment]
> First contribution here, but at #8384 there's the full description of the changes. I think that the main difference is the sorting.

Hi everyone,
The main reason of the catalan.xml order, it's because it's a Visual Order.
If you compare the order of the < Commands> section in english.xml, with the File menu in np++... you will see that some parts are in different order.
While in the catalan.xml it's in the same order as you can see it in the notepad++ app, visually.
Thanks to that, in the past, I was able to see some errors in english.xml file. Like repeated entries, items in the wrong place, and entries that were missing in the english.xml file, but they did exist in the source code, and I just had to add them.

All that said,
I don't mind to change it to the english.xml order, even if it's a big change :)
To me, both ways are OK. And both have their own reason to be that way.

I also can see that you added the comments translated, I removed them because they're not needed, and they were like redundancy: If I see < Menu>< Main>< Entries> ... I don't need a comment to tell me that those are the "< !-- Main Menu Entries -->".

I can see that there are some more differences,
maybe some old entry must be removed, or something else needs to be changed,
I'll check it out.
Thank you, @xeanhort :)

Regards.

**Comment by xeanhort** [comment]
> If you compare the order of the < Commands> section in english.xml, with the File menu in np++... you will see that some parts are in different order.
> While in the catalan.xml it's in the same order as you can see it in the notepad++ app, visually.
> Thanks to that, in the past, I was able to see some errors in english.xml file. Like repeated entries, items in the wrong place, and entries that were missing in the english.xml file, but they did exist in the source code, and I just had to add them.

I've noticed it at the beginning, but I thought that the english version should be the one more updated, so I changed it to be able to detect changes easily comparing files.  I think it's better to keep all sorted the same way to track changes, but you should say it :)

> I also can see that you added the comments translated, I removed them because they're not needed, and they were like redundancy: If I see < Menu>< Main>< Entries> ... I don't need a comment to tell me that those are the "< !-- Main Menu Entries -->".

As I said, I just tried to mimic the format of english.xml to make it easier to compare and maintain 

> I can see that there are some more differences,
> maybe some old entry must be removed, or something else needs to be changed,
> I'll check it out.
👍

**Pull request closed without merging**
