### PR TITLE
[xml] Update Bulgarian localization

### PR DESCRIPTION
**Pull request by rddim**
* Improve GUI for commands for the system tray in Preferences · notepad-plus-plus/notepad-plus-plus@cd45afc
* Avoid user confusion between Global override & Default Styles · notepad-plus-plus/notepad-plus-plus@1890ea6
* Fix Find dialog status bar wrong messaging · notepad-plus-plus/notepad-plus-plus@9010147
* Fix wrong messages for replacement status · notepad-plus-plus/notepad-plus-plus@bfe835e

### CODE REVIEW

**Comment by donho** [comment]
Please consider the following change:
* Add "Close to system tray" in MISC preference (035ef19)
* Improve GUI for commands for the system tray in Preferences (cd45afc)
* Avoid user confusion between Global override & Default Styles (1890ea6)
* Fix Find dialog status bar wrong messaging (9010147)
* Fix wrong messages for replacement status (bfe835e)

**Comment by rddim** [comment]
Hello,
I'm away now. I can do it tomorrow night. 

На 19 октомври 2024 г. 20:44:53 GMT+03:00, Don HO ***@***.***> написа:
>Please consider the following change:
>* Add "Close to system tray" in MISC preference (035ef19)
>* Improve GUI for commands for the system tray in Preferences (cd45afc)
>* Avoid user confusion between Global override & Default Styles (1890ea6)
>* Fix Find dialog status bar wrong messaging (9010147)
>* Fix wrong messages for replacement status (bfe835e)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15694#issuecomment-2424105233
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rddim** [comment]
@donho 
It's done. There is no need of https://github.com/notepad-plus-plus/notepad-plus-plus/commit/035ef19b17ab6cedce7b68d3bc6a3b1108acaf56 because it is removed at https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cd45afc0208f92c21afd286ce3f691f6f32d1989. There is a problem with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1890ea65f98f8d915ac2f4c437b2afd3b2535f8b - the localization does not fit and it is out of the room.

@GOLEM777 could you take a look at https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1890ea65f98f8d915ac2f4c437b2afd3b2535f8b please?

**Comment by GOLEM777** [comment]
> @GOLEM777 could you take a look at [1890ea6](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1890ea65f98f8d915ac2f4c437b2afd3b2535f8b) please?

Hi! What should I see? 
You're doing well!

**Pull request closed without merging**
