### PR TITLE
Powershell installer 2021.03.25

### PR DESCRIPTION
**Pull request by QuantumNovice**

### CODE REVIEW

**Comment by QuantumNovice** [comment]
Improvement of #9693 after reading https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#pull-requests

**Comment by QuantumNovice** [comment]
To see if the QuantumNovice:powershell_installer_2021.03.25 works. Run this one liner

Invoke-Expression -Command (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/QuantumNovice/notepad-plus-plus/powershell_installer_2021.03.25/powershell-install.ps1')

**Comment by QuantumNovice** [comment]
Extension of the issue #9693

**Comment by donho** [comment]
@QuantumNovice 

>Your pull requests are welcome; however, they may not be accepted for various reasons. If you want to make some GUI enhancement like renaming some graphic items or fixing typos, please create the issue instead of the pull requests. ***All Pull Requests, except for translations and user documentation, need to be attached to a issue on GitHub.*** For Pull Requests regarding enhancements and questions, the issue must first be approved by one of project's administrators before being merged into the project. An approved issue will have the label Accepted. For issues that have not been accepted, you may request to be assigned to that issue.
Opening a issue beforehand allows the administrators and the community to discuss bugs and enhancements before work begins, preventing wasted effort.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#pull-requests

**Comment by donho** [comment]
Closed due to absence of reply.

**Pull request closed without merging**
