### PR TITLE
Update japanese.xml to v7.9.3

### PR DESCRIPTION
**Pull request by yasmise**
Follow up to these commits:
* Make find/replace in files progress translatable (d6c941034d6492b89218456f12b138598f37d7e4)
* Improve option for setting save dialog filter to All Types (d5ad02521ed5558ba6a958d5334cfce6f0e8e6fc)

### CODE REVIEW

**Comment by yasmise** [comment]
Force-pushed these changes:
* Make 1 section name of Preferences more explicit (e26199ab51258fa6f743566aa6018eed8fb64b4f)
* Make "Save Folder as Workspace" in Save Session dialog translatable (41c4180b2ef75e963645baca2fcfa0e853f64365)
* Fix spelling inconsistencies

**Comment by donho** [comment]
Please check [v7.9.3 translation diff comparing with v7.9.2](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9455). If nothing is missed, please confirm it with me, so I will include this PR in the next release. Thank you!

**Comment by yasmise** [comment]
I checked your diff and I think this PR is ready.
Your diff says `id="6430"` is removed, but that change was already done by commit aca37f150b565eeadb53b7ae7a94acb4b1b6500f, so I leave it untouched in this PR.
Thanks for your kind attension.

**Comment by donho** [comment]
@yasmise Thank you!

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ad3a86d60f09a10e8c67dbd51dcffbf3dc573911

**Pull request merged**
