### PR TITLE
Enable two more SQL keyword list

### PR DESCRIPTION
**Pull request by xylographe**
KEYWORD2 – data types, highlighted in a different style.
USER1 – user-defined keywords, empty list by default.

Implements #5937. See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5937#issuecomment-514519313 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5937#issuecomment-514572374 in particular.
Adds previously missing SQL keywords as well.

**Before:**

**After:** (with "user1" as a user-defined keyword)

### CODE REVIEW

**Comment by donho** [comment]
Red? Could they be other color than red (for example purple)?
My reason  is red leads ppl think of error.

**Comment by xylographe** [comment]
Purple (#800080) is fine by me. What do you think, @CurbedLarry?

SQL-after

**Comment by donho** [comment]
@xylographe it's perfect to me.
Ping me when you merge your modif in this branch.

**Comment by CurbedLarry** [comment]
> Purple (#800080 [[Purple color codes](https://www.rapidtables.com/web/color/purple-color.html)]) is fine by me. What do you think, @CurbedLarry?

Would only say that some darker themes already use pink/purple for the number style (eg Plastic Code Wrap).  Perhaps in those cases another colour can be default?

**Comment by xylographe** [comment]
@donho
Modifications applied.

Red was used as the KEYWORD2 foregroundcolour in 5 themes:
```
  #FF0000 (Red) ==> #800080 (Purple    )   [Default    ]
  #FF0000 (Red) ==> #600080 (Purple-ish)   [Hello Kitty]
  #FF0000 (Red) ==> #A00090 (Purple-ish)   [Navajo     ]
  #FF0000 (Red) ==> #007FFF (Azure     )   [Obsidian   ]
  #FF0000 (Red) ==> #008060 (Teal-ish  )   [Khaki      ]
```

**Pull request closed without merging**
