### PR TITLE
Do not limit building 32-bit scintilla, so x64 compiler will work

### PR DESCRIPTION
**Pull request by linquize**
Do not limit building 32-bit scintilla, so x64 compiler will work.

Fix regression of 9de1967bf355c982b104c70be23aba6e55d5b88b

### CODE REVIEW

**Comment by linquize** [comment]
ping

**Comment by Croydon** [comment]
:+1:

**Comment by linquize** [comment]
ping

**Comment by milipili** [comment]
@donho : Is this still relevant ?

**Comment by donho** [comment]
Scintilla can be compiled fully in x64

**Pull request closed without merging**
