### PR TITLE
#8483 - Added function to open target file of .Ink file during Drag and Drop

### PR DESCRIPTION
**Pull request by Roshni-P**
#8483 - The new function has not been called from within doOpen() since the fileName parameter is declared constant, hence, cannot be modified.

### CODE REVIEW

**Comment by Yaron10** [comment]
@Roshni-P,

Thank you for this PR. :+1: 

Some comments:
1. Dragging a folder containing a shortcut, the .lnk file is opened (check `Preferences -> Default Directory -> Open all files of folder...`).
2. Opening a shortcut from Folder as Workspace, the .lnk file is opened.
3. It seems that some adjustments are needed for x64.

**Comment by sasumner** [comment]
@Yaron10 

>It seems that some adjustments are needed for x64.

Are you saying that based upon the build failing?
To me it appears that the build failed under mingw.

**Comment by Yaron10** [comment]
@sasumner,

You're right.
I had a quick look at the  AppVeyor page and got confused.

**Comment by Yaron10** [comment]
@Roshni-P,

As @sasumner suggested in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8483#issuecomment-650737577, it's better to call `resolveLinkFile()` in `doOpen()`.

Add
```
	generic_string targetFileName = fileName;
	resolveLinkFile((LPWSTR) targetFileName.c_str());
```
at the beginning and then replace all instances of `fileName` (from there to the end of `doOpen()`)  with `targetFileName`. 

```
void resolveLinkFile(LPWSTR linkFilePath)
{
	HRESULT hres;
	IShellLink* psl;
	WCHAR targetFilePath[MAX_PATH];
	WIN32_FIND_DATA wfd;

	hres = CoInitialize(NULL);
	if (SUCCEEDED(hres))
	{
		hres = CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_INPROC_SERVER, IID_IShellLink, (LPVOID*)&psl);
		if (SUCCEEDED(hres))
		{
			IPersistFile* ppf;
			hres = psl->QueryInterface(IID_IPersistFile, (void**)&ppf);
			if (SUCCEEDED(hres))
			{
				// Load the shortcut.
				hres = ppf->Load(linkFilePath, STGM_READ);
				if (SUCCEEDED(hres))
				{
					// Resolve the link.
					hres = psl->Resolve(NULL, 0);
					if (SUCCEEDED(hres))
					{
						// Get the path to the link target.
						hres = psl->GetPath(targetFilePath, MAX_PATH, (WIN32_FIND_DATA*)&wfd, SLGP_SHORTPATH);
						if (SUCCEEDED(hres))
						{
							wcscpy_s(linkFilePath, MAX_PATH, targetFilePath);
						}
					}
				}
				ppf->Release();
			}
			psl->Release();
		}
		CoUninitialize();
	}
}

BufferID Notepad_plus::doOpen(const generic_string& fileName, bool isRecursive, bool isReadOnly, int encoding, const TCHAR *backupFileName, FILETIME fileNameTimestamp)
{
	const rsize_t longFileNameBufferSize = MAX_PATH; // TODO stop using fixed-size buffer
	if (fileName.size() >= longFileNameBufferSize - 1) // issue with all other sub-routines
		return BUFFER_INVALID;

	generic_string targetFileName = fileName;
	resolveLinkFile((LPWSTR) targetFileName.c_str());

	//If [GetFullPathName] succeeds, the return value is the length, in TCHARs, of the string copied to lpBuffer, not including the terminating null character.
	//If the lpBuffer buffer is too small to contain the path, the return value [of GetFullPathName] is the size, in TCHARs, of the buffer that is required to hold the path and the terminating null character.
	//If [GetFullPathName] fails for any other reason, the return value is zero.

	NppParameters& nppParam = NppParameters::getInstance();
	TCHAR longFileName[longFileNameBufferSize];

	const DWORD getFullPathNameResult = ::GetFullPathName(targetFileName.c_str(), longFileNameBufferSize, longFileName, NULL);
	if (getFullPathNameResult == 0)
	{
		return BUFFER_INVALID;
	}
	if (getFullPathNameResult > longFileNameBufferSize)
	{
		return BUFFER_INVALID;
	}
	assert(_tcslen(longFileName) == getFullPathNameResult);

	if (_tcschr(longFileName, '~'))
	{
		// ignore the returned value of function due to win64 redirection system
		::GetLongPathName(longFileName, longFileName, longFileNameBufferSize);
	}

	bool isSnapshotMode = backupFileName != NULL && PathFileExists(backupFileName);
	if (isSnapshotMode && !PathFileExists(longFileName)) // UNTITLED
	{
		wcscpy_s(longFileName, targetFileName.c_str());
	}
	_lastRecentFileList.remove(longFileName);

	generic_string fileName2Find;
	generic_string gs_fileName{ targetFileName };


	// "fileName" could be:
	// 1. full file path to open or create
	// 2. "new N" or whatever renamed from "new N" to switch to (if user double-clicks the found entries of untitled documents, which is the results of running commands "Find in current doc" & "Find in opened docs")
	// 3. a file name with relative path to open or create

	// Search case 1 & 2 firstly
	BufferID foundBufID = MainFileManager.getBufferFromName(targetFileName.c_str());

	if (foundBufID == BUFFER_INVALID)
		fileName2Find = longFileName;

	// if case 1 & 2 not found, search case 3
	if (foundBufID == BUFFER_INVALID)
		foundBufID = MainFileManager.getBufferFromName(fileName2Find.c_str());

	// If we found the document, then we don't open the existing doc. We return the found buffer ID instead.
	if (foundBufID != BUFFER_INVALID && !isSnapshotMode)
	{
		if (_pTrayIco)
		{
			if (_pTrayIco->isInTray())
			{
				::ShowWindow(_pPublicInterface->getHSelf(), SW_SHOW);
				if (!_pPublicInterface->isPrelaunch())
					_pTrayIco->doTrayIcon(REMOVE);
				::SendMessage(_pPublicInterface->getHSelf(), WM_SIZE, 0, 0);
			}
		}
		return foundBufID;
	}

	if (isFileSession(longFileName) && PathFileExists(longFileName))
	{
		fileLoadSession(longFileName);
		return BUFFER_INVALID;
	}

	if (isFileWorkspace(longFileName) && PathFileExists(longFileName))
	{
		nppParam.setWorkSpaceFilePath(0, longFileName);
		// This line switches to Project Panel 1 while starting up Npp
		// and after dragging a workspace file to Npp:
		launchProjectPanel(IDM_VIEW_PROJECT_PANEL_1, &_pProjectPanel_1, 0);
		return BUFFER_INVALID;
	}

	bool isWow64Off = false;
	if (!PathFileExists(longFileName))
	{
		nppParam.safeWow64EnableWow64FsRedirection(FALSE);
		isWow64Off = true;
	}

	bool globbing = wcsrchr(longFileName, TCHAR('*')) || wcsrchr(longFileName, TCHAR('?'));

	if (!isSnapshotMode) // if not backup mode, or backupfile path is invalid
	{
		if (!PathFileExists(longFileName) && !globbing)
		{
			generic_string longFileDir(longFileName);
			PathRemoveFileSpec(longFileDir);

			bool isCreateFileSuccessful = false;
			if (PathFileExists(longFileDir.c_str()))
			{
				int res = _nativeLangSpeaker.messageBox("CreateNewFileOrNot",
					_pPublicInterface->getHSelf(),
					TEXT("\"$STR_REPLACE$\" doesn't exist. Create it?"),
					TEXT("Create new file"),
					MB_YESNO,
					0,
					longFileName);

				if (res == IDYES)
				{
					bool isOK = MainFileManager.createEmptyFile(longFileName);
					if (isOK)
					{
						isCreateFileSuccessful = true;
					}
					else
					{
						_nativeLangSpeaker.messageBox("CreateNewFileError",
							_pPublicInterface->getHSelf(),
							TEXT("Cannot create the file \"$STR_REPLACE$\"."),
							TEXT("Create new file"),
							MB_OK,
							0,
							longFileName);
					}
				}
			}
			else
			{
				generic_string str2display = TEXT("\"");
				str2display += longFileName;
				str2display += TEXT("\" cannot be opened:\nFolder \"");
				str2display += longFileDir;
				str2display += TEXT("\" doesn't exist.");
				::MessageBox(_pPublicInterface->getHSelf(), str2display.c_str(), TEXT("Cannot open file"), MB_OK);
			}

			if (!isCreateFileSuccessful)
			{
				if (isWow64Off)
				{
					nppParam.safeWow64EnableWow64FsRedirection(TRUE);
					isWow64Off = false;
				}
				return BUFFER_INVALID;
			}
		}
	}

	// Notify plugins that current file is about to load
	// Plugins can should use this notification to filter SCN_MODIFIED
	SCNotification scnN;
	scnN.nmhdr.code = NPPN_FILEBEFORELOAD;
	scnN.nmhdr.hwndFrom = _pPublicInterface->getHSelf();
	scnN.nmhdr.idFrom = NULL;
	_pluginsManager.notify(&scnN);

	if (encoding == -1)
	{
		encoding = getHtmlXmlEncoding(longFileName);
	}

	BufferID buffer;
	if (isSnapshotMode)
	{
		buffer = MainFileManager.loadFile(longFileName, NULL, encoding, backupFileName, fileNameTimestamp);

		if (buffer != BUFFER_INVALID)
		{
			isSnapshotMode = (backupFileName != NULL && ::PathFileExists(backupFileName));
			if (isSnapshotMode)
			{
				// To notify plugins that a snapshot dirty file is loaded on startup
				SCNotification scnN2;
				scnN2.nmhdr.hwndFrom = 0;
				scnN2.nmhdr.idFrom = (uptr_t)buffer;
				scnN2.nmhdr.code = NPPN_SNAPSHOTDIRTYFILELOADED;
				_pluginsManager.notify(&scnN2);

				buffer->setLoadedDirty(true);
			}
		}
	}
	else
	{
		buffer = MainFileManager.loadFile(longFileName, NULL, encoding);
	}

	if (buffer != BUFFER_INVALID)
	{
		_isFileOpening = true;

		Buffer * buf = MainFileManager.getBufferByID(buffer);

		// if file is read only, we set the view read only
		if (isReadOnly)
			buf->setUserReadOnly(true);

		// Notify plugins that current file is about to open
		scnN.nmhdr.code = NPPN_FILEBEFOREOPEN;
		scnN.nmhdr.idFrom = (uptr_t)buffer;
		_pluginsManager.notify(&scnN);


		loadBufferIntoView(buffer, currentView());

		if (_pTrayIco)
		{
			if (_pTrayIco->isInTray())
			{
				::ShowWindow(_pPublicInterface->getHSelf(), SW_SHOW);
				if (!_pPublicInterface->isPrelaunch())
					_pTrayIco->doTrayIcon(REMOVE);
				::SendMessage(_pPublicInterface->getHSelf(), WM_SIZE, 0, 0);
			}
		}
		PathRemoveFileSpec(longFileName);
		_linkTriggered = true;
		_isFileOpening = false;

		// Notify plugins that current file is just opened
		scnN.nmhdr.code = NPPN_FILEOPENED;
		_pluginsManager.notify(&scnN);
		if (_pFileSwitcherPanel)
			_pFileSwitcherPanel->newItem(buf, currentView());
	}
	else
	{
		if (globbing || ::PathIsDirectory(targetFileName.c_str()))
		{
			vector<generic_string> fileNames;
			vector<generic_string> patterns;
			if (globbing)
			{
				const TCHAR * substring = wcsrchr(targetFileName.c_str(), TCHAR('\\'));
				if (substring)
				{
					size_t pos = substring - targetFileName.c_str();

					patterns.push_back(substring + 1);
					generic_string dir(targetFileName.c_str(), pos + 1); // use char * to evoke:
																   // string (const char* s, size_t n);
																   // and avoid to call (if pass string) :
																   // string (const string& str, size_t pos, size_t len = npos);

					getMatchedFileNames(dir.c_str(), patterns, fileNames, isRecursive, false);
				}
			}
			else
			{
				generic_string fileNameStr = targetFileName;
				if (targetFileName[targetFileName.size() - 1] != '\\')
					fileNameStr += TEXT("\\");

				patterns.push_back(TEXT("*"));
				getMatchedFileNames(fileNameStr.c_str(), patterns, fileNames, true, false);
			}

			bool ok2Open = true;
			size_t nbFiles2Open = fileNames.size();

			if (nbFiles2Open > 200)
			{
				ok2Open = IDYES == _nativeLangSpeaker.messageBox("NbFileToOpenImportantWarning",
					_pPublicInterface->getHSelf(),
					TEXT("$INT_REPLACE$ files are about to be opened.\rAre you sure to open them?"),
					TEXT("Amount of files to open is too large"),
					MB_YESNO | MB_APPLMODAL,
					static_cast<int32_t>(nbFiles2Open));
			}

			if (ok2Open)
			{
				for (size_t i = 0; i < nbFiles2Open; ++i)
					doOpen(fileNames[i]);
			}
		}
		else
		{
			_nativeLangSpeaker.messageBox("OpenFileError",
				_pPublicInterface->getHSelf(),
				TEXT("Can not open file \"$STR_REPLACE$\"."),
				TEXT("ERROR"),
				MB_OK,
				0,
				longFileName);

			_isFileOpening = false;

			scnN.nmhdr.code = NPPN_FILELOADFAILED;
			_pluginsManager.notify(&scnN);
		}
	}

	if (isWow64Off)
	{
		nppParam.safeWow64EnableWow64FsRedirection(TRUE);
		//isWow64Off = false;
	}
	return buffer;
}
```

No need to change anything in `Notepad_plus.cpp` nor in `Notepad_plus.h`.
`#include <strsafe.h>` is not needed either.

What do you think?

***

@sasumner,

Can you think of a better implementation?
Removing `const` from `const generic_string& fileName`?

**Comment by Roshni-P** [comment]
I have followed @Yaron10's suggestion.
The only differences are that I have used StringCbCopy instead of wcscpy_s, since it results in 'HEAP CORRUPTION' (Attached exception).  I have included strsafe.h as well.

HeapException

I would have preferred to remove the const from the fileName parameter, since it fails to serve the purpose in the current scenario. This would involve modifying most of this function's references. 
Please share your thoughts... If needed, I can create a new PR so that we can have a new set of clean commits.

**Comment by Yaron10** [comment]
@Roshni-P,

Thank you. :+1: 

> The only differences are that I have used StringCbCopy instead of wcscpy_s, since it results in 'HEAP CORRUPTION' (Attached exception).

I haven't used the Debugger. Did you encounter any problem running the Release version? x86 or x64?

If you add `strsafe.h`, you can make the function return `hres`. It might be useful in the future.

> Please share your thoughts...

I do hope some readers will respond. :)

**Comment by Roshni-P** [comment]
@Yaron10,
I have added the return parameter to the function.

I am having some issues (_Authenticode Check_) setting up the Release version on my system. I need to resolve them and then check.

**Comment by Yaron10** [comment]
And `hres = StringCbCopy(linkFilePath, MAX_PATH, targetFilePath);`. :)

> I am having some issues (Authenticode Check) setting up the Release version on my system. I need to resolve them and then check.

:+1:

**Comment by Yaron10** [comment]
@Roshni-P,

For some reason `psl->Resolve(NULL, 0);` succeeds if the file is *not a shortcut* but empty (size 0).
As a result NPP can not open `Test.txt` if it's empty.

I've added `if (SUCCEEDED(hres) && wfd.nFileSizeLow)` after `GetPath()`.
(Perhaps the size-check can and should be done earlier).

```
HRESULT resolveLinkFile(LPWSTR linkFilePath)
{
	HRESULT hres = CoInitialize(NULL);

	if (SUCCEEDED(hres))
	{
		IShellLink* psl;
		hres = CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_INPROC_SERVER, IID_IShellLink, (LPVOID*)&psl);
		if (SUCCEEDED(hres))
		{
			IPersistFile* ppf;
			hres = psl->QueryInterface(IID_IPersistFile, (void**)&ppf);
			if (SUCCEEDED(hres))
			{
				// Load the shortcut.
				hres = ppf->Load(linkFilePath, STGM_READ);
				if (SUCCEEDED(hres))
				{
					// Resolve the link.
					hres = psl->Resolve(NULL, 0);
					if (SUCCEEDED(hres))
					{
						// Get the path to the link target.
						WCHAR targetFilePath[MAX_PATH];
						WIN32_FIND_DATA wfd;
						hres = psl->GetPath(targetFilePath, MAX_PATH, (WIN32_FIND_DATA*)&wfd, SLGP_SHORTPATH);
						if (SUCCEEDED(hres) && wfd.nFileSizeLow)
						{
							hres = StringCbCopy(linkFilePath, MAX_PATH, targetFilePath);
						}
					}
				}
				ppf->Release();
			}
			psl->Release();
		}
		CoUninitialize();
	}

	return hres;
}
```

***

Another minor issue:
Have `A.lnk` (targeting `A.cpp`) and `B.txt` in `Folder as Workspace`.
Double-click `A.lnk` and then `B.txt`.
-- `A.cpp` and `B.txt` open in the editor.
Activate `A.cpp` in the editor.
Press the `Focus (hunter)` button in `Folder as Workspace`.

Result:
`A.lnk` in `Folder as Workspace` is not selected.

**Comment by Roshni-P** [comment]
@Yaron10 , I'll look into them. Thanks! 👍

**Comment by Roshni-P** [comment]
hres = psl->GetPath(targetFilePath, MAX_PATH, (WIN32_FIND_DATA*)&wfd, SLGP_SHORTPATH); returns S_FALSE.
SUCCEEDED(hres) returns true, since S_FALSE is not an error condition. 
MS (Link - https://docs.microsoft.com/en-us/windows/win32/learnwin32/error-handling-in-com) expects us to specifically check for S_FALSE, if the scenario demands it.  I have added a check, similar to what is mentioned here.

As for the 'Folder as Workspace' issue, I am able to replicate it. I appreciate the testing that you have done and understand that, it pertains to Shortcut files. But wouldn't it be better to have that as a separate issue, rather than club it with the Drag & Drop scenario? ....  :)

**Comment by sasumner** [comment]
>As for the 'Folder as Workspace' issue...wouldn't it be better to have that as a separate issue, rather than club it with the Drag & Drop scenario?

👍 🥇

**Comment by sasumner** [comment]
@Roshni-P If you ever want to have a hope of this PR being accepted, you'd better figure out why the mingw build is failing on your changes.

**Comment by Roshni-P** [comment]
... figure out why the mingw build is failing on your changes.

Thank you @sasumner , let me check on it.

**Comment by Yaron10** [comment]
@Roshni-P,

Well done. Thank you. 
:+1: 

Using `if (SUCCEEDED(hres) && hres != S_FALSE)` after `GetPath()` solves the empty file issue.
May I ask why you've added it in two more places?
Are there any other possible `S_FALSE`s? And what about the three `if (SUCCEEDED(hres))` without ` && hres != S_FALSE`?

***

> As for the 'Folder as Workspace' issue, I am able to replicate it. I appreciate the testing that you have done and understand that, it pertains to Shortcut files. But wouldn't it be better to have that as a separate issue, rather than club it with the Drag & Drop scenario? .... :)

**The issue is caused by this PR.**
Without calling `resolveLinkFile()`, **`A.lnk`** would open in the editor and the `Focus (hunter)` button should work as expected.

Anyway, it's a minor issue and I think it's not worth the extra work/code.

**Comment by Roshni-P** [comment]
> Using `if (SUCCEEDED(hres) && hres != S_FALSE)` after `GetPath()` solves the empty file issue.
> May I ask why you've added it in two more places?
> Are there any other possible `S_FALSE`s? And what about the three `if (SUCCEEDED(hres))` without ` && hres != S_FALSE`?
> 
@Yaron10 ,
I have included S_FALSE at the instances that relate to loading & resolving the shortcut files. This is done to handle any other scenario that might pop-up in the future.
The other 3 instances are omitted, since they pertain to COM initialization (No harm in adding them here, if required).

The mingw build fails since it is unable to recognize IID_IPersistFile & IID_IShellLinkW.
It appears, this occurs due to the absence of ole32.lib. But I have no clue as to how this needs to be added only for the mingw compiler. Nor do I have clear steps to compile Notepad++ using mingw. 
Sorry, I am stuck at this point!

**Comment by sasumner** [comment]
>Nor do I have clear steps to compile Notepad++ using mingw.

Yes.  I can't get good information on that either.  :-(

See #7743

>But I have no clue as to how this needs to be added only for the mingw compiler

I did this "blindly" once.  :-)
See #7951

**Comment by Yaron10** [comment]
@Roshni-P,

> I have included S_FALSE at the instances that relate to loading & resolving the shortcut files.

Thank you. :+1: 

> Sorry, I am stuck at this point!

I hope @sasumner's comment (thanks Scott) should help. :)

**Comment by Roshni-P** [comment]
Thank you @sasumner ! The links were very helpful. The mingw build errors are now resolved.

**Comment by Yaron10** [comment]
@Roshni-P,

:+1: 
Thank you.

**Review by donho — CHANGES_REQUESTED** [review]
Change from `resolveLinkFile(LPWSTR linkFilePath)` to `resolveLinkFile(generic_string& linkFilePath)`.
`linkFilePath` is input & output parameter - it will be modified if needed.

**Comment by Yaron10** [comment]
@donho,

:+1: 
Thank you.

@Roshni-P,

With the requested changes, we're back with `void resolveLinkFile`. :)
And no `#include <strsafe.h>`.

`hres = ppf->Load(linkFilePath.c_str(), STGM_READ);`.
`resolveLinkFile(targetFileName);`.

**Review by sasumner — COMMENTED** [review]
"merge 31 commits" -- not a good idea.  :-)

**Comment by Roshni-P** [comment]
Sorry @sasumner . My actual code changes involve only a few lines. I updated my local branch with the latest from master. The subsequent commit that I made shows all the commits made so far by others. I am unsure how to revert this commit. Should I create a new PR or a new branch?

**Comment by sasumner** [comment]
>I updated my local branch with the latest from master

Probably not a great idea to do that unless it was really necessary.
In your case I would think it was not necessary.
(If necessary then you should do a "rebase")

>I am unsure how to revert this commit. 

Asking a search engine is probably the best route.

>Should I create a new PR or a new branch?

I would attempt to fix what you've already got going.  If you can't get it fixed, and you want to keep going, I suppose you'll have to.

**Comment by donho** [comment]
@Roshni-P  It's so bad:
image

Please create a new PR.

**Pull request closed without merging**
