### PR TITLE
[Hindi] Update Localization

### PR DESCRIPTION
**Pull request by SinghRajenM**
Corrected/updated localization

### CODE REVIEW

**Comment by donho** [comment]
@SinghRajenM  the translation has been changed due to the rolling back of Find/Replace UI: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2593d64fbbc96ec1fc1761e311f0d741b062a9ca
Could you update your PR for this change please?
Sorry for the inconvenience.

**Comment by SinghRajenM** [comment]
@donho, I've already updated the PR. Thank you!

**Comment by SinghRajenM** [comment]
@donho done.

**Comment by donho** [comment]
@SinghRajenM  Thank you!

**Comment by donho** [comment]
6f872ebb7e44ca262e67d9b188a68c7c6a0323f2

**Pull request closed without merging**
