### PR TITLE
[xml] Update Ukrainian translation

### PR DESCRIPTION
**Pull request by a-polivanchuk**
Updating Ukrainian translation based on the latest source file for v8.4.6

### CODE REVIEW

**Review by donho — CHANGES_REQUESTED** [review]
Please update the PR to the latest updated english.xml: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12404

**Comment by donho** [comment]
@a-polivanchuk 
Please add `[xml]` on the beginning of title next time, if the PR is about translation, and only xml file(s) is (are) modified.
Ex: `[xml] Update ukrainian.xml`

**Comment by a-polivanchuk** [comment]
@donho I've just pushed the latest translations in a new commit.

**Comment by donho** [comment]
@a-polivanchuk 
The diff of localization file v8.4.7 vs v8.4.8 is available here: #12649
Please check it and update your localization file, and let me know when this PR is ready to go.
Thank you.

**Comment by a-polivanchuk** [comment]
@donho I've just pulled the English.xml one more time and there's no any diffs with this PR. So it should be ready to go.

**Comment by donho** [comment]
Thank you @a-polivanchuk !

**Review by donho — APPROVED** [review]

**Pull request closed without merging**
