### PR TITLE
FunctionList Update1

### PR DESCRIPTION
**Pull request by MAPJe71**
Several changes to functionList.xml but the main part of the update is the changed order of associations and parsers to follow ascending 'langID' numerical values. This is intended as a normalization phase to make the changes of upcoming updates easier to compare and integrate.

### CODE REVIEW

**Comment by MAPJe71** [comment]
That's more files than intended, was supposed to be functionList.xml only.

**Comment by cmeriaux** [comment]
Hello,
There are two many commits included here. Your PR can't be merged autmatically by gitHub. You may rework it a little bit.

First you better update your master branch without merging : 
`git checkout master`
`git fetch --all`
Récupération de origin
Récupération de upstream
`git reset --hard upstream/master`
HEAD est maintenant à fae21eb Add missing commands in shortcut list

Now rebase your PR on your master.
`git rebase -i master`
git ask you what to do =>
```
pick 98325f3 No need to prefix implicit inline method with <classname>::.
pick e3f528b Included compiled Python script in clean-up.
pick 437db47 Renamed folder ScitillaComponent to ScintillaComponent i.e. added an 'n'.
pick d72d560 Renamed folder ScitillaComponent to ScintillaComponent i.e. added an 'n' (part 2).
pick 625a718 Minor beautification.
pick 6d4df01 FunctionList Update #1 - functionList.xml

```
You should remove the two commits that rename scintilla (you may propose another PR for that)
```
pick 98325f3 No need to prefix implicit inline method with <classname>::.
pick e3f528b Included compiled Python script in clean-up.
d 437db47 Renamed folder ScitillaComponent to ScintillaComponent i.e. added an 'n'.
d d72d560 Renamed folder ScitillaComponent to ScintillaComponent i.e. added an 'n' (part 2).
pick 625a718 Minor beautification.
pick 6d4df01 FunctionList Update #1 - functionList.xml

```

then 
`git rebase --continue`
or 
`git mergetool` if conflicts
and push

I hope it will help you

**Comment by MAPJe71** [comment]
Thanks, will try it!
Is there a way to redo/revoke the PR in GitHub or should I just close it and post a new one?

**Comment by cmeriaux** [comment]
You can push your branch (FunctionList-Update1) with -f (force option), and it will update your PR

**Comment by donho** [comment]
Thank you @MAPJe71 
I'll check it as soon as v7 realese

**Comment by MAPJe71** [comment]
Apparently I messed up the PR :(

**Comment by cmeriaux** [comment]
@MAPJe71  you can use reflog command to check out what happenend  and go back to a previous state [git reflog help](https://git-scm.com/docs/git-reflog)
```
 christophe@Christophe-PC /cygdrive/d/dev/notepad-plus-plus: git reflog

sha1_xxx HEAD@{0}: rebase -i (finish): returning to refs/heads/shortcuts
sha1_xxx HEAD@{1}: rebase -i (pick): Shortcut improvements
sha1_xxx HEAD@{2}: rebase -i (pick): shortcut mapper clear command
sha1_xxx HEAD@{3}: rebase -i (pick): export all shortcut config
sha1_xxx HEAD@{4}: rebase -i (pick): shortcut.xml file saved on modification with comments
sha1_xxx HEAD@{5}: rebase -i (start): checkout master
sha1_xxx HEAD@{6}: checkout: moving from master to shortcuts
sha1_xxx HEAD@{7}: pull: Fast-forward
sha1_xxx HEAD@{8}: checkout: moving from shortcuts to master
sha1_xxx HEAD@{9}: rebase -i (finish): returning to refs/heads/shortcuts

```

then do `reset --hard HEAD@{5}`  to go back 5 step backward.

Isn't git magical ?

**Comment by donho** [comment]
@MAPJe71  Since you close this issue, I suppose that you will do a new PR ?

**Comment by MAPJe71** [comment]
@donho that's my intention yes.
This PR got messed up while adding the #2319 PR and I wasn't able to get it right despite the instructions provided by @cmeriaux. I need to read up on using (Tortoise)Git.

**Pull request closed without merging**
