### PR TITLE
Update Bulgarian localization

### PR DESCRIPTION
**Pull request by rddim**
* follow up ec340000ccde72debc8d0ac721ec376d07dec3e4
* follow up 5080fdf2d869db0138693965c8f546964917941f
* some typo fixes
* follow up 953919c4067c6ccbc3003adaad90074d621b0580

### CODE REVIEW

**Comment by donho** [comment]
@rddim  Could you please update translation in this PR?
Here's the diff of new entries:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5080fdf2d869db0138693965c8f546964917941f#diff-2a8496e2537c34b95cbeca007cd2346b

**Comment by rddim** [comment]
hello and thanks. I'm away from my computer for a week and I hope I will update the localization these weekend. 

На 2 декември 2018 г. 5:15:36 GMT+02:00, Don HO <notifications@github.com> написа:
>@rddim  Could you please update translation in this PR?
>Here's the diff of new entries:
>https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5080fdf2d869db0138693965c8f546964917941f#diff-2a8496e2537c34b95cbeca007cd2346b
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4954#issuecomment-443477511

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chcg** [comment]
@donho Seems your request is done and this could be merged now.

**Comment by rddim** [comment]
Sorry for the flood fixes... it is done, following 953919c4067c6ccbc3003adaad90074d621b0580

**Pull request closed without merging**
