### PR TITLE
Fix EncodingMapper singleton memory leak

### PR DESCRIPTION
**Pull request by wjx0912**
Fix EncodingMapper singleton memory leak

### CODE REVIEW

**Comment by sasumner** [comment]
What issue number does this PR attempt to fix??

**Comment by wjx0912** [comment]
hi, @sasumner 
no issue, just fix a memory leak,
best regards~

**Comment by sasumner** [comment]
The site protocol is to open an issue, THEN create a PR that references that issue.

**Comment by wjx0912** [comment]
issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6031

**Comment by wjx0912** [comment]
#6031

**Comment by donho** [comment]
The singleton lasts the whole life of application so when Notepad++ exits, the OS (Windows) manages to deallocate the allocated memory by application.
OTOH, it's a good practice to instance the singleton only when we need, without allocate in heap zone. Furthermore, the code is more modern (C++11). Hence the acceptation.

**Comment by sasumner** [comment]
>Hence the acceptance

Disappointed to see the acceptance without the analysis and discussion by the author in the "issue"...

**Comment by SinghRajenM** [comment]
When you say singleton, copy and assignment should not be allowed, should it?

**Comment by donho** [comment]
@sasumner 
> Disappointed to see the acceptance without the analysis and discussion by the author in the "issue"

It's indeed a "leak of memory" since in EncodingMapper, a `new` is done but no `delete` (not as the 3 other singletons, see https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3dbb2c4b8ef47fddfd4e78aed086b28108fd036d and https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3643a1875b588e730d132a3e401f099a83b866ef).

**Comment by donho** [comment]
@SinghRajenM 
> When you say singleton, copy and assignment should not be allowed, should it?

You're right about it.
Your enhancement on 4 singletons is welcome.

**Comment by sasumner** [comment]
@donho 

I just like to see PR makers do a nice job with issue creation, before fixing code.  :)

I guess if the absolutely aren't going to do this, and team members quickly see that they are pointing out a real code problem with the PR, then, meh, ..., it's OK.

But I don't think we like it when we see an issueless PR and then have to go guessing at what the heck they are trying to accomplish with it (this is a generalization, maybe doesn't apply this time).

**Pull request closed without merging**
