### PR TITLE
Apply dark mode on color popup

### PR DESCRIPTION
**Pull request by ozone10**
Fix use of dark mode edge color in light mode for color picker button.
Properly redraw disabled color picker button.

fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10269

light mode new style (border)
image
dark mode
image

### CODE REVIEW

**Comment by mere-human** [comment]
Why is the dialog look different in new light mode? It is gray in current build:
image

**Comment by ozone10** [comment]
@mere-human 
> 
> Why is the dialog look different in new light mode? It is gray in current build:

I can look into it, but it is issue? Should I restore the light mode look?

I have changed border style because in dark mode it create white border.

**Comment by donho** [comment]
@mere-human 
My BEFORE & AFTER screenshot under windows 10:

image

Do you think it's an issue?

**Comment by mere-human** [comment]
> Do you think it's an issue?

No, I just wanted to point out it's different.

**Pull request closed without merging**
