### PR TITLE
Update portuguese.xml

### PR DESCRIPTION
**Pull request by Blackspirits**
Small change, I reduced 4 lines, because the text didn't fit all inside the toolbar box

### CODE REVIEW

**Comment by donho** [comment]
@hugok79

Do you validate this change?

**Comment by hugok79** [comment]
@donho Looks good to me. Thanks

**Comment by ozone10** [comment]
@donho 
why not increase width, there is still enough space
image

**Comment by hugok79** [comment]
In version 8.5.2 it was not possible to resize the preferences window.... Meanwhile, with this fix: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13632 
it will not be necessary to apply this submission.

**Comment by hugok79** [comment]
> @donho why not increase width, there is still enough space image

This fix the issue

**Comment by hugok79** [comment]
@donho @ozone10 This PR can be closed.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a1d7db8049ce89bd537d4ca769af8d7f10feee45

**Pull request closed without merging**
