### PR TITLE
Scintilla/Boost build Update - Boostbuild.bat

### PR DESCRIPTION
**Pull request by MAPJe71**
- Improved argument detection and extended usage section accordingly.
- Corrected Boost build tool property for 64-bit builds i.e. using `address-model=64` instead of `architecture=ia64`. The `architecture=ia64`-property is intended for targets with an Itanium processor architecture which no one has (most probably). See also the '64-bit support'-section at http://www.boost.org/build/doc/html/bbv2/reference/tools.html
- Simplified Boost version detection i.e. get it directly from source, `getboostver.*`-files no longer needed.
- Replaced obsolete SourceForge forum link with Community forum link.
- Using for-loop to guess the used build tool set.
- Simplified library path assignment.
- Simplified `boostpath.mak`-file creation.

This PR replaces PR #2319.

### CODE REVIEW

**Comment by donho** [comment]
Does it need to update also:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/README.md#to-build-scilexerdll-with-boost
and 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/README.md#to-build-scilexerdll-without-boost
?

**Comment by MAPJe71** [comment]
Short answer: No
Long answer: BuildBoost.bat's existing interface is still supported, it has just been extended i.e.
options still apply but their sequence is of no importance.

Equivalent examples 1:
`BuildBoost.bat C:\sources\boost_1_55_0 -x64`
`BuildBoost.bat -x64 C:\sources\boost_1_55_0`

Equivalent examples 2:
`BuildBoost.bat --toolset msvc-10.0 -x64 C:\sources\boost_1_55_0`
`BuildBoost.bat -x64 --toolset msvc-10.0 C:\sources\boost_1_55_0`
`BuildBoost.bat -x64 C:\sources\boost_1_55_0 --toolset msvc-10.0`
`BuildBoost.bat --toolset msvc-10.0 C:\sources\boost_1_55_0 -x64`
`BuildBoost.bat C:\sources\boost_1_55_0 --toolset msvc-10.0 -x64`
`BuildBoost.bat C:\sources\boost_1_55_0 -x64 --toolset msvc-10.0`

**Comment by donho** [comment]
No problem for generation of `SciLexer.exe` of 32-bit version.

However, there's a problem while generatig `SciLexer.exe` of 64-bit version : 
boost has been compiled without issue. OTOH when I execute `nmake -f scintilla.mak`, I've got the following error :
```
        link -OPT:REF -LTCG -DEBUG -LIBPATH:c:\sources\boost_1_55_0\bin.v2\libs\regex\build\msvc-12.0\release\address-model-64link-static\runtime-link-static\th
reading-multi -DEF:Scintilla.def -DLL -OUT:..\bin\Scintilla.dll .\AutoComplete.obj .\CallTip.obj .\CaseConvert.obj .\CaseFolder.obj .\CellBuffer.obj .\Character
Category.obj .\CharacterSet.obj .\CharClassify.obj .\ContractionState.obj .\Decoration.obj .\Document.obj .\EditModel.obj .\Editor.obj .\EditView.obj .\Indicato
r.obj .\KeyMap.obj .\LineMarker.obj .\MarginView.obj .\PerLine.obj .\PlatWin.obj .\PositionCache.obj .\PropSetSimple.obj .\RESearch.obj .\RunStyles.obj .\Select
ion.obj .\Style.obj .\UniConversion.obj .\ViewStyle.obj .\XPM.obj .\HanjaDic.obj .\ScintillaBase.obj .\ScintillaWin.obj .\BoostRegexSearch.obj .\UTF8DocumentIte
rator.obj .\ScintRes.res KERNEL32.lib USER32.lib GDI32.lib IMM32.lib OLE32.LIB OLEAUT32.LIB
Microsoft (R) Incremental Linker Version 12.00.40629.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'libboost_regex-vc120-mt-s-1_55.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\link.EXE"' : return code '0x450'
Stop.
```

It's strange that you didn't have such issue.

**Comment by MAPJe71** [comment]
@donho 
I hope you meant Scintilla.**DLL** :)
I'm not able to build the 64-bit version of Scintilla so wasn't able to test/verify that part (I thought that was clear).

Thanks to the link-dump you included finding this problem was easy. The Boost library path 
(`-LIBPATH:c:\sources\boost_1_55_0\bin.v2\libs\regex\build\msvc-12.0\release\address-model-64link-static\runtime-link-static\threading-multi`) is missing a backslash between `64` and `link`.

Didn't squash commits yet but will squash and force into one commit for easy integration once it's issue free, if that's OK with you.

**Comment by cmeriaux** [comment]
@MAPJe71  if you want to save time, when you commit, use the option amend. Then push your branch with force option. Your PR will always have only one commit.

**Comment by chcg** [comment]
See https://www.appveyor.com/docs/installed-software/#languages-libraries-frameworks:

Boost:

    1.62.0 (C:\Libraries\boost_1_62_0)
    1.60.0 (C:\Libraries\boost_1_60_0)
    1.59.0 (C:\Libraries\boost_1_59_0)
    1.58.0 (C:\Libraries\boost_1_58_0)
    1.56.0 (C:\Libraries\boost)

, maybe we could readd the build of scintilla with boost with one of this preinstalled boost versions to appveyor config and don't suffer from the wget issue we saw in the past, also changes to scintilla are quite seldom. But this would enforce an update from currently used boost 1.55.0 to a newer one.

**Comment by chcg** [comment]
Build break probably caused by usage of older appveyor image

image: Visual Studio 2013

which is not updated like the current one Visual Studio 2015

**Comment by MAPJe71** [comment]
@cmeriaux :+1: :smile: 
Yes, I'm aware, it's not the reason the build failed.
Based on all the AppVeyor YAML examples got the impression that YAML required 2 space indentation. **YAML** specifies [**one must not use tabs for indentation**](http://yaml.org/spec/1.2/2009-07-21/spec.html#id2576668) and ...
> Each node must be indented further than its parent node. All sibling nodes must use the exact same indentation level. However the content of each sibling node may be further indented independently.

Working on the issues in a separate branch now, will update soon.

**Comment by MAPJe71** [comment]
FYI:
- Used the following (corrected) `.editorconfig` (w/ EditorConfig plugin) to ensure correct indentation style and size:
``` YAML
root = true
[*] 
indent_style=tab
end_of_line=crlf
[*.yml]
indent_style=space
indent_size=4
```
- Used following commands to update PR: 
``` Bash
git checkout master
git fetch --all
git rebase -i upstream/master
# changed all "pick" to "squash" and used ":quit!" to exit VIm
git push origin master -f
```

**Comment by donho** [comment]
@MAPJe71 
> I'm not able to build the 64-bit version of Scintilla so wasn't able to test/verify that part (I thought that was clear).

So you didn't even compile your PR in 64-bit?!?! That's absurd since you're providing a fix for x64, or am I missing somethings??

**Comment by MAPJe71** [comment]
I posted a question/contemplation in the [Notepad 7 Release Candidate announcement](https://notepad-plus-plus.org/community/topic/12303/notepad-7-release-candidate/21) and was [asked to do a PR that would be checked](https://notepad-plus-plus.org/community/topic/12303/notepad-7-release-candidate/24).

I'm able to build Boost in 64-bit on my development system but I am not able to build or execute 64-bit Scintilla and Notepad++ with my development system i.e. it's a 32-bit system.

The last [commit](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2336/commits/a076fad0656d91f3ba494837296b5adad6155d73) was build utilizing [AppVeyor](https://ci.appveyor.com/project/MAPJe71/notepad-plus-plus) to build 32-bit and 64-bit, both with Boost v1.58.
Copied the 32-bit Release artifacts to my system and didn't notice any problems using them.

**Comment by MAPJe71** [comment]
@chcg Good catch!

**Comment by chcg** [comment]
@donho Any chance to get this resurrected and integrated? Would needs to be done from your point of view? I see:
- cleanup into one commit
- maybe avoid appveyor config changes, but create an appveyor branch build which shows that also the build with boost is ok

Any thoughs about the topics:
- usage of vs2015
- updateboost  from n++ version 1.55 to current 1.63
- update of scintilla, see e.g. https://github.com/cmeriaux/scintilla/commits/npp-3-7-0

**Pull request closed without merging**
