### PR TITLE
[xml][force compile] Fix trim operations for selection

### PR DESCRIPTION
**Pull request by ArkadiuszMichalski**
… line

Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12658

@alankilborn Can you check if it's consistent now?

### CODE REVIEW

**Comment by alankilborn** [comment]
I don't think 12648 is the correct issue for this PR?

**Comment by ArkadiuszMichalski** [comment]
There is a discussion with descriptions of this problem, but I will move it to a new issue later.

**Comment by alankilborn** [comment]
>>Can you check if it's consistent now?

>There is a discussion with descriptions of this problem for trim operations , but I will move it to a new issue later.

Hmm.  Without an issue, I don't know what it is that I'm checking...

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12648#issuecomment-1353755867

**Comment by alankilborn** [comment]
As a user, I would not use "trim" operations on partially-selected lines -- I would select full lines with the mouse using line number margin click+drag.  Or, if I did partially select some group of lines, I would expect "trim" to operate on the full lines touched by selection.  I don't really want to get into the possibly endless debate about how such a thing should work (on partially selected lines), so perhaps @Yaron10 is a better and more thorough tester of this?

**Comment by ArkadiuszMichalski** [comment]
>As a user, I would not use "trim" operations on partially-selected lines -- I would select full lines with the mouse using line number margin click+drag

So you still have a choice, and if that's your workflow, you can always select all. If we do automatic stretching on whole lines, there may be voices like this:
image
Why for above example line 1 and 4 are always include, I didn't mark them at all. Such automatic things done behind your back are better to do only as a last resort (e.g. when sorting, because taking only part of the first/last line is pointless here).

**Comment by alankilborn** [comment]
Right, I was just trying to make the point that I am not the best person to give you the testing on this.

**Comment by Yaron10** [comment]
> As a user, I would not use "trim" operations on partially-selected lines -- I would select full lines with the mouse using line number margin click+drag. Or, if I did partially select some group of lines, I would expect "trim" to operate on the full lines touched by selection.

👍 

> so perhaps @Yaron10 is a better and more thorough tester of this?

I think that removing the selection in the following case is wrong.
תמונה

Leading/Trailing tabs and non-Leading/Trailing tabs are two different "entities".
Let's imagine that Leading/Trailing tabs were represented by a different shape.
For example: ».

Selecting a non-Leading/Trailing tab
תמונה

does not transform it to:
תמונה

***
> Why for above example line 1 and 4 are always include,

Line 4 should not be included.

**Comment by donho** [comment]
@ArkadiuszMichalski 

It's about "Trim **Trailling**" or "Trim **Leading**" operation so it's rather ones of Line Operations.
the selection on left should be considered extended as right:

image

Sorry, for https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bf34ef0dd568b792627813a4445adf649a5c5ba6 I have checked only selection full lines.

**Comment by ArkadiuszMichalski** [comment]
@donho 

It's not that simple, because then appear other borderline cases.

1
image
Cursor is at the beginning on line 4, so the extension should also include line 4, like this or not?

image

2 What in this situation, line 2 should be selected? We start selection before `CRLF` on line 2.
image

3 We start selection before `CRLF` on line 2, and finish with cursor at the beginning on line 3.
image

4 Here I assume that the whole line 4 should be selected (because the first character `A` was selected)?
image

What should be done with the last `CRLF`? Should be a part of this auto-expand selection or not? From the perspective of `doTrim()` it doesn't matter, but this function is also used with `IDM_EDIT_TRIMALL` (as first part), and for this command (named `Remove Unnecessary Blank and EOL`), every `CRLF` is important. In this case the selection will be processed with `doTrim()` first, so it matters more what exactly are we doing with selection here.

I've already seen what problems can arise if we try implement auto-expand selection in: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12580.

That's why I came to the conclusion that it's best if the commands operate on the selection exactly made by us. Then we always have the possibility to select exactly what we need. With auto-expand selection we are forced into default behavior, which may not always meet our expectations.
Maybe a solution would be to make, for example, a separate command `Expand selection to full lines` available from the macro level, and if someone needed it, they could combine the appropriate commands (through macro).

@donho 
But if you want auto-expand selection here then we can try, just write what should happen in the above cases.

**Comment by donho** [comment]
@ArkadiuszMichalski 
No auto-expand selection please. We don't need visual update.
We need only the determination of which lines should apply to trim operation, from the selection. 
For the determination, you can see "Move up/down current line" commands' behaviour with the random selection.

**Comment by ArkadiuszMichalski** [comment]
@donho 

Can you check the last commit is it better?  Now it follows what commands "Move up/down current line" do.

1
image
Selects lines 2 and 3.

2
image
Selects lines 2 and 3.

3
image
Selects lines 2.

4
image
Selects lines 2 and 3 and 4.


We never expand selection to contain the last `CRLF` because another command will not work properly (`IDM_EDIT_TRIMALL`). So:
image
would be:
image
as you suggested earlier https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12655#issuecomment-1356365695.

**Comment by donho** [comment]
@ArkadiuszMichalski 
When multi-selections are present, it takes only the last selection - but I think it's tolerable.

`[xml][force compile]` - it might be a good practice to not consume too much resource for the earlier stage of PR and get quickly the result, but please don't forget to remove it in the latest commit in order to validate the whole set of compiling.

**Comment by ArkadiuszMichalski** [comment]
@donho 
>When multi-selections are present, it takes only the last selection - but I think it's tolerable.

Yes, but that is due to the limitation of `_findReplaceDlg.processAll`. Wherever we use this function only the last selection will be processed. At the moment it may look like this, or we may not support multiselect at all (just return).
Multi-selection seems to be difficult to support because changes in one selection affect the next ones, I don't even know if Scintilla somehow properly saves the selected data in such a situation.

>[xml][force compile] - it might be a good practice to not consume too much resource for the earlier stage of PR and get quickly the result, but please don't forget to remove it in the latest commit in order to validate the whole set of compiling.

I know, even mention something like that here:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#other-available-flags
I was just waiting for you to come back to this PR and check out this new approach, because I don't know if you like it in this form.

image
Now after committing, I will try to adjust these other methods so that they also work on the selection.

**Comment by alankilborn** [comment]
>Multi-selection seems to be difficult to support because changes in one selection affect the next ones, I don't even know if Scintilla somehow properly saves the selected data in such a situation.

What you do for this situation is, for the first change, note how the document length changes, and adjust the location of the intended second change by this amount.  And so on for all the subsequent changes needed.

**Comment by donho** [comment]
As I mentioned, it's tolerable for me. So let's take the simplest solution (the current one).

**Comment by ArkadiuszMichalski** [comment]
>What you do for this situation is, for the first change, note how the document length changes, and adjust the location of the intended second change by this amount. And so on for all the subsequent changes needed.

Right, we can combine in this direction. But I would still expect that `_findReplaceDlg.processAll` support this firstly. It would be less work than doing everything ourselves every time we need this.

**Pull request closed without merging**
