### PR TITLE
update japanese.xml to v7.2.2

### PR DESCRIPTION
**Pull request by yasmise**
Add a new line to catch up with v7.2.2.

### CODE REVIEW

**Comment by cmeriaux** [comment]
You should have a clean commit history. 
Use rebase -i and remove the "merge remote-tracking...." commit

**Comment by yasmise** [comment]
I've just removed "merge remote-tracking" commits. I'm sorry to bother you.

**Comment by donho** [comment]
A newest translation is available: 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

Could you update your PR with the new translation please?

**Comment by yasmise** [comment]
@donho OK, I've updated to v7.3.

**Comment by donho** [comment]
@yasmise Sorry again for the request, but I just add a new feature and several new translation:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6a05bedd05cbfce40106aa464e43448639d1913b#diff-2a8496e2537c34b95cbeca007cd2346b

Could you update the PR again please? (so I can include it in new release)

**Comment by yasmise** [comment]
@donho No problem, just updated to v7.3.1.

**Comment by donho** [comment]
@yasmise Thank you!

**Pull request closed without merging**
