### PR TITLE
Make macro menu organizable with submenu

### LINKED ISSUE #5349: Macro submenus feature request
I have many macros and would like to be able to organise them into sub-menus, rather than scrolling through a single long list. Could this be added to a future version please?

### PR DESCRIPTION
**Pull request by donho**
This PR allows users to add one level of submenu manually for macro command in shortcuts.xml, in order to better organize macro menu commands. For doing it, `FolderName="my menu 1"` attribut should be added in <Macro> node. Only 1 level of submenu is allowed.

For making sub-menu as such:

image

here is an example:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <InternalCommands>
        <Shortcut id="44104" Ctrl="no" Alt="no" Shift="no" Key="0" />
        <Shortcut id="41019" Ctrl="no" Alt="no" Shift="no" Key="0" />
        <Shortcut id="42086" Ctrl="yes" Alt="yes" Shift="no" Key="74" />
        <Shortcut id="42084" Ctrl="yes" Alt="yes" Shift="no" Key="75" />
        <Shortcut id="42085" Ctrl="yes" Alt="yes" Shift="no" Key="81" />
    </InternalCommands>
    <Macros>
        <Macro name="aa" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="A" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="A" />
        </Macro>
        <Macro name="azerty" Ctrl="no" Alt="no" Shift="no" Key="0" FolderName="words">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="a" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="z" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="e" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="t" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="y" />
        </Macro>
        <Macro name="qwerty" Ctrl="no" Alt="no" Shift="no" Key="0" FolderName="words">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="q" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="w" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="e" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="t" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="y" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000D;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000A;" />
        </Macro>
        <Macro name="BB" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000D;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x000A;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="B" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="B" />
        </Macro>
        <Macro name="Trim Trailing Space and Save" Ctrl="no" Alt="yes" Shift="yes" Key="83" FolderName="func">
            <Action type="2" message="0" wParam="42024" lParam="0" sParam="" />
            <Action type="2" message="0" wParam="41006" lParam="0" sParam="" />
        </Macro>
        <Macro name="azerty2" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="a" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="z" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="e" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="t" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="y" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="2" />
        </Macro>
    </Macros>
    <UserDefinedCommands>
        <Command name="Get PHP help" Ctrl="no" Alt="yes" Shift="no" Key="112">https://www.php.net/$(CURRENT_WORD)</Command>
        <Command name="Wikipedia Search" Ctrl="no" Alt="yes" Shift="no" Key="114">https://en.wikipedia.org/wiki/Special:Search?search=$(CURRENT_WORD)</Command>
        <Command name="Open selected file path in new instance" Ctrl="no" Alt="yes" Shift="no" Key="117">$(NPP_FULL_FILE_PATH) $(CURRENT_WORD) -nosession -multiInst</Command>
    </UserDefinedCommands>
    <PluginCommands />
    <ScintillaKeys />
</NotepadPlus>

```

Fix #5349

### CODE REVIEW

**Comment by Patriccollu** [comment]
This change will be great! I'm looking forward to testing it.

**Comment by alankilborn** [comment]
@donho 
I tested this PR and it seemed to work great.
I'm glad you were able to overcome the problem you had with deleting macros via shortcutmapper, before.
It's great that submenuing is coming to Notepad++'s Macro menu.
Thank you for the work.

**Comment by alankilborn** [comment]
>Sometimes the good PR coming needs just time

With code, I call it "gel time", as in "it needs time to gel".  :)

**Comment by alankilborn** [comment]
Is it possible to put a "separator" in the Macro menu (in the region of the menu where the user-created macros are kept)?

**Comment by alankilborn** [comment]
I didn't hear back about my "separator" question, so I thought I'd show a technique for creating a "mock separator":

    <Macro name="--------------------" Ctrl="no" Alt="no" Shift="no" Key="0">
        <Action type="0" message="2172" wParam="0" lParam="0" sParam="comment:  just acting as a SEPARATOR in the menu" />
    </Macro>

will create:

image

-------------------------------------

For a more polished look to the separator:

    <Macro name="&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;&#x2014;" Ctrl="no" Alt="no" Shift="no" Key="0">
        <Action type="0" message="2172" wParam="0" lParam="0" sParam="comment:  just acting as a SEPARATOR in the menu" />
    </Macro>

will create:

image

**Pull request closed without merging**
