### PR TITLE
Make GCC/MinGW build work again and support cross-building under Linux

### LINKED ISSUE #385: Notepad++ cannot be built with GCC/MinGW
This seemed to be possible once because there are already adaptions available including a makefile.

### PR DESCRIPTION
**Pull request by marcows**
Fixes #385.

Only build errors are fixed, compile warnings are left alone. To reduce the number of changes, even the compiler option "-fpermissive" has been used to downgrade several errors to warnings.

### CODE REVIEW

**Comment by sanastasiou** [comment]
I hope this get's merged..

**Comment by slitazcn** [comment]
i like too,waiting

**Comment by marcows** [comment]
If you have access to a Visual Studio installation on Windows, you could test the patches there as I don't have the possibility. This might increase the chance for being merged. Especially for the following two commits I do not know whether they have bad influence:
6eb0ba0c28ff135738063c0caf89799a48f38f2a: Change backslashes to slashes for path names in .rc files
c6fb4883b397d461dd90497c77fa9ef230592090: Convert localizationString.h from little endian UTF-16 to UTF-8

**Comment by sanastasiou** [comment]
I could try building it.. But even then I cannot guarantee it's correctness. Don't forget we are dealing with code here which has 0 tests.

**Comment by marcows** [comment]
All I meant was testing that these two changes do not introduce regressions for the VS build, i.e. after a successful build checking that the menu icons are still existing and the UI language can still be switched.

**Comment by donho** [comment]
@marcows Just compiled under VS2013 without any error.
I have no MiGW package installed and the MinGW-w64 online installer (downloaded from SF) doesn't want to install on my PC (with error message "Cannot download repository.txt[0]"  then quit).

Where I can download MinGW package without the online installer?

**Comment by marcows** [comment]
For testing on Windows I used [i686-5.2.0-release-win32-sjlj-rt_v4-rev1.7z](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.2.0/threads-win32/sjlj/i686-5.2.0-release-win32-sjlj-rt_v4-rev1.7z).
This package only needs to be unzipped and "mingw32\bin" has to be added to PATH environment variable.

Then go to "PowerEditor\gcc" and invoke make from command line:
```
mingw32-make
```
Maybe with e.g. option ```-j4``` for faster build time using parallel jobs.

**Comment by slitazcn** [comment]
use  i686-5.2.0-release-win32-sjlj-rt_v4-rev1.7z.,it can finish build,but run it get std::exception title is exception on WM_CREATE,and it can't finish build use mingw64 64 bits edition,my OS is windows 10 th2,also i use VS 2015 build 64bits is good,also use mingw i suggest static link,then will be more portable,thx for you guys great jobs,notepadpp is a great editor

**Comment by marcows** [comment]
It would have been nice to keep the single steps in the repository history, but thanks anyway, Don! I'm really happy for this being applied now.

**Comment by mzbab88** [comment]
Um, can somebody update makefiles and/or code again? Because mingw failes to build for me. You can see error and details here https://notepad-plus-plus.org/community/topic/11701/how-to-compile-notepad-with-mingw-or-clang

**Comment by marcows** [comment]
@slitazcn I just got the "std::exception" error as well. Reason was the missing SciLexer.dll file. Copy it to the bin/ directory beside NotepadPP.exe.

**Pull request closed without merging**
