### PR TITLE
Update french.xml to 7.7.2

### PR DESCRIPTION
**Pull request by xylographe**
[1] Add missing entries.
[2] Remove surplus entries.

(Also a couple of typo fixes)

### CODE REVIEW

**Comment by donho** [comment]
@xylographe 
Since you're on it. Could you add a commit to modify encoding menu entries :
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5951
?
Only on `french.xml`
I'll do for `english.xml`
Thx

**Comment by xylographe** [comment]
[3] Modify encoding menu entries according to #5951.

(in commit d03caeef702f94fb958f55d091185272604189be)

**Comment by xylographe** [comment]
All commits squashed into one.

**Comment by donho** [comment]
@xylographe  
Use the old branch do the PR make master commit history disaster. Please create a new branch for each PR :
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Pull request closed without merging**
