### PR TITLE
Fixed multi cursor bugs

### PR DESCRIPTION
**Pull request by jmbockhorst**
Thanks a lot to @MetaChuh for testing the multi cursor feature and finding some bugs. I have fixed a few issues:

- Using enter and backspace repeatedly caused the cursors to be incorrect and get jumbled.
- Multi cursors functions did not work with LF (Unix) or CR (Macintosh) line endings.

### CODE REVIEW

**Comment by sasumner** [comment]
I for one am nervous about this now. :)
Why can't we just get the functionality via a Scintilla upgrade?

**Comment by jmbockhorst** [comment]
One thing to note. When there is only one cursor (so for most users), it still uses the default Scintilla functions. So there is no worries about anything breaking for the normal user.
Also, I feel like now (after these fixes), this is working pretty well, and is a useful upgrade for those who could use it. But please test it for yourself if you are still worried about it.

**Comment by MetaChuh** [comment]
@jmbockhorst 
cc @donho as testing report

* [x] all new multi cursor editing bugs i have found, including the crashes, were re-tested and are successfully fixed with this pull. 👍

* [x] i was also not able to find any further issues for now, even when switching live between eol modes when multiple cursors are already set, and even if multi-cursors are shifted left or right across line endings.
(see combined screencast of the fixed version below, tested on both x86 and x64)

Imgur

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1360ff82ba995e0464abb79dc2525b566b8e5921

@sasumner  Yes, Scintilla SHOULD be (and WILL be) updated in short term.

**Pull request closed without merging**
