### PR TITLE
Fix Appveyor artifacts

### LINKED ISSUE #1877: pushing artifact in Appveyor:
Fix a path problem while pushing artifact in Appveyor:
Artifacts in yaml config file (appveyor.yml) is useless.

Rename the binary into notepad++_debug.exe

log of my compil without error :+1: 
https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.22

### PR DESCRIPTION
**Pull request by cmeriaux**
fix #1877

### CODE REVIEW

**Comment by donho** [comment]
Have you test it with your Appveyor account?
If yes, url please?

**Comment by cmeriaux** [comment]
yep. Here is the log : 
https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.22

**Comment by donho** [comment]
please make one commit for Appveyor issue.

**Comment by cmeriaux** [comment]
@donho Don ! 
There was only one commit in this PR !
I did a rebase and submit it again #1937

**Pull request closed without merging**
