### PR TITLE
Add mIRC (mSL) Scripting Language support

### PR DESCRIPTION
**Pull request by westor7**
I hope these helps, feature requested at: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1347

Official Program Website: http://mirc.com
Official XML Style: http://pastebin.com/CfdKyQsk

- Thanks!

### CODE REVIEW

**Comment by Croydon** [comment]
Why did you open three PRs: #1385, #1386?

**Comment by westor7** [comment]
Yeah that was my mistake at begining...

**Comment by Croydon** [comment]
At least close the others if they were a mistake.

**Comment by dail8859** [comment]
This isn't how you add a new language. Plus, just from looking at it, it wouldn't even compile.

**Comment by westor7** [comment]
The other pulls were not error just i did not implent all in one, anyway i tried to add some of them i don't know if all of them are correct, you can fix them better than me.

**Comment by donho** [comment]
@westor7 Just check your PR, and I don't see how could it work.

**Pull request closed without merging**
