### PR TITLE
Fix View menu's Synch H/V Scrolling disabled/enabled bugs

### LINKED ISSUE #5250: "Synchronize ... Scrolling" is disabled on launch with both views shown
### Description of the Issue
In view menu - "Synchronize Vertical Scrolling" / "Synchronize Horizontal Scrolling" items - disabled when opening Notepad++ with both views shown.

### Steps to Reproduce the Issue

1. Open N++ with several documents
2. Transfer one of the documens to other view. In this moment `Synchronize...` items are enabled.
3. Close and open N++ again, `Synchronize...` items are disabled.

### Expected Behavior
`View->Synchronize...` items are enabled.

### Actual Behavior
`View->Synchronize...` items are disabled.

I can see that code for enabling/disabling these items initially is called but it seems to does not work correctly for some reason.

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll DSpellCheck.dll NppConverter.dll PluginManager.dll

### LINKED ISSUE #13071: Synchronize H/V Scrolling commands remain enabled after closing a 2nd view
### Description of the Issue
The _View_ menu's _Synchronize Vertical Scrolling_ and _Synchronize Horizontal Scrolling_ commands are not correctly disabled when a two-view editing environment is reduced to a single view by closure of all files in a second view.

### Steps to Reproduce the Issue
1. Start with a `new 1` tab open (only) in a single view setup
2. Create a new tab with Ctrl+n; `new 2` appears
3. Right-click the tab for `new 2` and choose `Move Document` > `Move to Other View`; you now have one document in each view:
image
4. Observe that _View_ menu's synchronized scrolling commands are enabled:
image
5. Right-click the `new 2` tab and select _Close_ and thus return to only having one view (the remaining view only has `new 1` in it).

### Expected Behavior
When examining the _View_ menu after step 5 has been executed, I expect to see the highlighted menu items from the screenshot in step 4 to be disabled/greyed.

### Actual Behavior
When examining the _View_ menu after step 5 has been executed, the highlighted menu items from the screenshot in step 4 remain enabled.

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : W:\npp.misc\_NoBackup\Releases\npp.8.4.9\npp.8.4.9.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.9 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (2)

### PR DESCRIPTION
**Pull request by alankilborn**
Fix #5250
Fix #13071

### CODE REVIEW

**Comment by Yaron10** [comment]
@alankilborn,

I wasn't by my PC in the last couple of days.
Thank you for working on this issue. 👍 

If you open NPP *without a session*, the commands are wrongly enabled.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0d9b16634d55fe9bee1833c2f6be40921b8fa5a6/PowerEditor/src/Notepad_plus.cpp#L444

Does not work.

@pnedev fixed that in ComparePlus.
https://github.com/pnedev/comparePlus/blob/224a066120d72cbb9e057176afb7d8ffc1bfec57/src/Compare.cpp#L4173

If you close some 100 tabs via Close All, `checkSyncState();` is *needlessly* called many times in `doClose()`.
Wouldn't it be better to call it only after specific Close commands?

**Comment by alankilborn** [comment]
>If you open NPP without a session, the commands are wrongly enabled.

To date, each known situation causing a bug for Synch H/V menu state has had its own issue.
I suppose one should be created for "without a session".

**Comment by alankilborn** [comment]
>If you close some 100 tabs via Close All, checkSyncState(); is needlessly called many times in doClose().
Wouldn't it be better to call it only after specific Close commands?

It probably _would_ be better.  As I didn't consider it, if it doesn't cause a measurable performance problem, I'm inclined to leave it alone, unless Don wants revision.

**Comment by Yaron10** [comment]
@alankilborn,

👍 
Thanks again.

**Pull request closed without merging**
