### PR TITLE
Add option to suppress warning when opening big files

### PR DESCRIPTION
**Pull request by DerivativeOfLog7**
Add an option to suppress the >=2GB file warning. Won't show on a x86 build. This is mostly useful when leaving npp searching inside files unattended as the warning could pop up and halt all progress until acted upon

### CODE REVIEW

**Comment by lorenzo3421** [comment]
Would be useful 👍

**Comment by donho** [comment]
Is there any opened issue about it?

**Comment by DerivativeOfLog7** [comment]
> Is there any opened issue about it?

I don't know, but I added this out of necessity and figured I could make a pull request

**Comment by donho** [comment]
Then please create one and attach this PR to it (ref it) - by doing it doesn't mean that PR will be accepted, but at least we have the full description & information to estimate if the PR is needed.
Ref:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#pull-requests

**Comment by DerivativeOfLog7** [comment]
Done; also had to reopen as #14053

**Pull request closed without merging**
