### PR TITLE
Distinguish between "tab size" and "indent size"

### LINKED ISSUE #3382: Allow separate tab size and indent size
### Description of the Issue
The project I work on has the coding style: 4 column indent for each indented code block, tab size = 8. While Notepad++ is my preferred editor, trying to write code in with this style in Notepad++ is more trouble than it is worth. 

### Requested Enhancement
Provide separate indent size and tab size in language settings.

### PR DESCRIPTION
**Pull request by jwt27**
This patch splits the current "tab size" setting into two separate settings:

* Tab size   : determines the width of the ASCII `TAB` character.
* Indent size: determines the tab stop width.

The first option defaults to 8, the latter to 4.  Additionally, "Replace by spaces" is renamed to "Use only spaces", to better reflect what it actually does.

Pressing the TAB key simply inserts enough space characters to move the cursor to the next tab stop.  But if "Use only spaces" is unchecked, and the cursor column is divisible by the tab character size, those spaces are replaced by tabs.  This doesn't even require any extra code, it is a standard Scintilla feature.

For example, with tab size 8 and indent size 4, pressing the TAB key on an empty line inserts four spaces.  Pressing it again replaces those four spaces with a single `TAB` character.

When tab size and indent size are equal, the behavior is the same as before.

Fixes: #10882, fixes #3382

### CODE REVIEW

**Comment by jwt27** [comment]
Also fixes: #3251 #3382 #3784

**Comment by jwt27** [comment]
Rebased to fix merge conflict - no changes.

**Comment by jwt27** [comment]
Rebased again, and added a commit to upgrade the user's config to the new format, so the change is less disruptive.

**Comment by donho** [comment]
I don't think this feature is demanded by users.
Let's see if there are more similar request coming, then I will consider it.

**Comment by jwt27** [comment]
Okay, that's a bit disappointing.  I hope then that others will see this and chime in.

I wouldn't call this a "feature", though.  It's a bug fix, since the current tab/indent behavior is just wrong.

**Comment by mmoult** [comment]
How many users are required for this to qualify as "demanded"? I think that @jwt27 did a good job in linking several related issues that multiple other people commented on. Furthermore, a similar feature has been implemented in Visual Studio and Visual Studio Code, so that proves that there is interest in it.

I will vouch for my interest. I agree that many current tab/indent behaviors are incorrect. I am not sure how many of them this will fix, but it is a step in the right direction.

**Comment by donho** [comment]
@mmoult 
I do believe @jwt27 has done a good job for this PR, but I think the implemented feature's behaviour in this PR will confuse a lot of users.
When a user hit a TAB, he/she does need a TAB. If a user makes TAB large as 7 char, he/she gets a 7 char width of TAB. If a user want to hit TAB to be ws, he/she enabled "Replace by space" options, then he/she gets 7 ws. It's clear and non-confusion.

**Comment by ArkadiuszMichalski** [comment]
@jwt27 
What is the benefit of inserting at the beginning spaces when expecting tabs? I checked this PR and I don't quite understand its usefulness. When I use tabs as indentation at the beginning, why we should put spaces after pressing tab? What would these spaces do for me?

**Comment by jwt27** [comment]
Strange and rather disappointing to see that this PR got closed so suddenly.

Many text and code files - probably the vast majority - are written with tab size 8 in mind.  But you generally don't want to indent each code block by 8 characters.  Or, the code style simply mandates the use of mixed tabs and spaces (GNU style).  Such files will be all jumbled up when viewed in Notepad++, and any further editing is a *very* painful experience.

I'd like to point out that no functionality is lost by applying this patch.  When tab and indent size are set to the same value, the behavior is unchanged.

Also note that this patch does not add any special code to handle this "feature".  It only uses functionality already present: `SCI_SETTABWIDTH` and `SCI_SETINDENT`.  Clearly this is the way tabs and indents are meant to be handled in Scintilla.

**Comment by jwt27** [comment]
> @mmoult I do believe @jwt27 has done a good job for this PR, but I think the implemented feature's behaviour in this PR will confuse a lot of users. When a user hit a TAB, he/she does need a TAB. If a user makes TAB large as 7 char, he/she gets a 7 char width of TAB. If a user want to hit TAB to be ws, he/she enabled "Replace by space" options, then he/she gets 7 ws. It's clear and non-confusion.

Maybe my explanation was a bit confusing.  I would invite you to try this patch for yourself - I think you'll find that it makes a lot of sense.
It works the same way as in Visual Studio.  Has anyone ever complained that that was too confusing?

**Comment by jwt27** [comment]
> @jwt27 What is the benefit of inserting at the beginning spaces when expecting tabs? I checked this PR and I don't quite understand its usefulness. When I use tabs as indentation at the beginning, why we should put spaces after pressing tab? What would these spaces do for me?

The example I gave is a specific use case for a specific coding style.  You'll know it when you need it.

The more general use case is, if you only indent with 2 or 4 spaces, this patch allows `TAB` characters to still be displayed correctly (8 chars).  Currently you are forced to use the same width for both, and it ruins the layout of most files.

**Comment by jwt27** [comment]
> Just some comments:
> 
> > Many text and code files - probably the vast majority - are written with tab size 8 in mind.
> 
> > ...TAB characters to still be displayed correctly (8 chars)
> 
> Where are these "facts" about `8` coming from? PLEASE tell me the root origins are not because when you fire up Windows' notepad.exe and press TAB, you obtain what appears to be 8 spaces worth of horizontal caret movement.

The use of 8-width `TAB` chars *long* pre-dates notepad.exe and Windows itself.  I wouldn't be surprised if this tradition dates back to UNIX serial terminals, or maybe even the paper teletypes of the 1800's.

I don't have any hard statistics, but I am quite confident in saying that the vast majority of text files, especially those written before the advent of GUI text editors, were meant to be displayed with 8-character-width `TAB`s.  And even then, tab width may be different from the indent size.

> Isn't the modern/accepted way of handling such things, to use "editorconfig"? Notepad++ has a plugin for that and Visual Studio builds in the handling of it, and I'm sure most other power text editors support it as well, either natively or via plugin. I haven't investigated if it can handle all of the desires above (because I'm not personally interested in those scenarios, at all), but at first blush that's what comes to mind for this type of stuff.

I've never heard of "editorconfig" and never seen anyone use it.  I had to look it up, and, as expected, it has separate `tab_width` and `indent_size` options.

As I understand this would involve writing an `.editorconfig` file in each directory where one might want to open a text file with Notepad++.  I don't see why NP++ can't just do the right thing, out of the box.

**Comment by alankilborn** [comment]
>The use of 8-width TAB chars long pre-dates notepad.exe and Windows itself. I wouldn't be surprised if this tradition dates back to UNIX serial terminals, or maybe even the paper teletypes of the 1800's.  I don't have any hard statistics, but I am quite confident in saying that the vast majority of text files, especially those written before the advent of GUI text editors, were meant to be displayed with 8-character-width TABs.

It's always good to remember the past.  Mainly so you don't repeat it.  :-)  I started working in the industry in 1986, and got more heavily into Unix in 1991, thankfully leaving that behind about 5 years later.  While I don't recall a tight tie of tab characters to "8", perhaps I just didn't notice.  My point is that I've been working continuously in the industry for (gasp!) 37 years now, and I don't feel this tight association with tabs and 8.  But ok, you do...  But I think you should be careful with terms like "vast majority" -- it may be your experience, but not everyone's or even the a majority of people's...

> "editorconfig" ..., as expected, it has separate tab_width and indent_size options.

So then its use would "solve" the current issue, I presume.

>As I understand this would involve writing an .editorconfig file in each directory where one might want to open a text file with Notepad++.

Well, you _could_ do that, but the way it is really meant to work is that it looks for `.editorconfig` in the same directory as the file, and if it doesn't find one, it climbs the directory tree, looking for the file in each directory encountered until it reaches the top (i.e. root of the drive).  When it finds one, it stops and uses its settings.

So, in practice, you'd create a master config file at the top level.  If this one meets your need for everything you'll ever do, great, you're done; forget about it, move on.  But if you need refinement in certain projects, you can create an additional `.editorconfig` and place it at the top level for a project, much like git creates a `.git` folder holding settings by project...or VSCode creates a `.vscode` folder in a project...or other similar examples of such things by other tools.

>I don't see why NP++ can't just do the right thing

Notepad++ does do the right thing...but that's always the author's view of what is right.  :-)

>...out of the box

Notepad++ rarely adds any functionality natively that already exists in a plugin.  The philosophy is that that's reinvention, and it is better to focus on new functionality rather than reinvent.  There are exceptions of course, e.g. "change history" went native after existing only in plugins for a long time -- but that was different because that feature came to Scintilla (N++'s underlying editing component and a separate project), and not a lot of work was required in actual N++ code.

**Comment by jwt27** [comment]
> It's always good to remember the past. Mainly so you don't repeat it. :-)

Yeah, I wouldn't use something like GNU style in my own code.  But code in such styles does exist, and sometimes you need to work with it.  Currently that is just impossible in NP++.

> I started working in the industry in 1986, and got more heavily into Unix in 1991, thankfully leaving that behind about 5 years later. While I don't recall a tight tie of tab characters to "8", perhaps I just didn't notice. My point is that I've been working continuously in the industry for (gasp!) 37 years now, and I don't feel this tight association with tabs and 8. But ok, you do... But I think you should be careful with terms like "vast majority" -- it may be your experience, but not everyone's or even the a majority of people's...

Regardless of the specific values, the point of the patch is to make a distinction between the width of an ascii `TAB` character, and how far code blocks or paragraphs are indented (eg. what happens when you press the Tab key, or insert a new line).  There are plenty of files out there where those two settings are not equal, and it should be up to the user to determine them.

> > I don't see why NP++ can't just do the right thing
> 
> Notepad++ does do the right thing...but that's always the author's view of what is right. :-)
> 
> > ...out of the box
> 
> Notepad++ rarely adds any functionality natively that already exists in a plugin. The philosophy is that that's reinvention, and it is better to focus on new functionality rather than reinvent. There are exceptions of course, e.g. "change history" went native after existing only in plugins for a long time -- but that was different because that feature came to Scintilla (N++'s underlying editing component and a separate project), and not a lot of work was required in actual N++ code.

But that is exactly the case here - this patch only exposes functionality that is already present in Scintilla.

**Comment by alankilborn** [comment]
>But that is exactly the case here - this patch only exposes functionality that is already present in Scintilla.

Then I suppose the only hurdle is convincing the N++ author.  Good luck and cheers.

**Comment by jwt27** [comment]
> > But that is exactly the case here - this patch only exposes functionality that is already present in Scintilla.
> 
> Then I suppose the only hurdle is convincing the N++ author. Good luck and cheers.

Thanks.  I do hope he reads this and reconsiders this PR.

**Pull request closed without merging**
