### PR TITLE
Update ukrainian.xml

### PR DESCRIPTION
**Pull request by a-polivanchuk**

### CODE REVIEW

**Comment by donho** [comment]
Thank you @a-polivanchuk .
Sorry for this change. Could you add a new commit for the modification of ffda03c ?

**Comment by donho** [comment]
`<Item id="6213"` should be kept. 
I just fixed it: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3474b8b11ed2aab10bec8e72e277705a66eef141

**Comment by a-polivanchuk** [comment]
Updated based on the latest changes. Please check.

**Comment by donho** [comment]
```
$ git checkout -b a-polivanchuk-patch-2 master
fatal: A branch named 'a-polivanchuk-patch-2' already exists.
```
Please use a unique name instead of "patch-2" - for example the date of PR: 20200418

**Comment by a-polivanchuk** [comment]
Alright! Here is another new PR #8135. I hope there will be no source changes anymore...

**Pull request closed without merging**
