### PR TITLE
About Box improvements

### PR DESCRIPTION
**Pull request by Rikk**
- Make "Build time" field selectable, so users can copy that info.
- Small adjustment to license area.
- Remove ugly border around "OK" button.
- Remove flat style of buttons, because it made them look ugly, were only visible in old Windows Classic Theme and did nothing in modern Windows themes.

Suggestion [Help-Needed]: I think it would be nice to add the Git commit hash to build info, so user know what is the exact source used to build it.

Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/524

### CODE REVIEW

**Comment by donho** [comment]
I like the way it is right now.

**Comment by Rikk** [comment]
I see no drawback with my changes.

**Comment by Rikk** [comment]
At least remove that fugly `BS_FLAT,WS_EX_STATICEDGE`

**Comment by Rikk** [comment]
Btw, the only thing that changed in appearance of "Build time" is the text color (and I added version string to make copy more useful, as requested in mentioned issue). Previously Disabled state made it gray; if you know how to change text color, it would look the same.

**Pull request closed without merging**
