### PR TITLE
Update to scintilla 5.5.0 & Lexilla 5.3.2

### PR DESCRIPTION
**Pull request by chcg**
Sintilla Release 5.5.0 (https://www.scintilla.org/scintilla550.zip)

    Released 23 April 2024.
    Add elements for inactive additional selections SC_ELEMENT_SELECTION_INACTIVE_ADDITIONAL_TEXT and SC_ELEMENT_SELECTION_INACTIVE_ADDITIONAL_BACK. When not set these default to SC_ELEMENT_SELECTION_INACTIVE_TEXT and SC_ELEMENT_SELECTION_INACTIVE_BACK. Bug #2417.
    On Cocoa, avoid use of NSUserDefaults which will soon require justification when used in applications on the App Store.
    Fix Win32 IME crash in windowed mode. Bug #2433.
    Scale reverse arrow cursor for margins to match other cursors when user changes pointer size. Bug #2321.

Lexilla Release 5.3.2 (https://www.scintilla.org/lexilla532.zip)

    Released 23 April 2024.
    COBOL: Stop string literal continuing over line end. Issue #229.
    COBOL: Stop doc comment assigning different styles to \r and \n at line end. Issue #229.
    COBOL: Recognize keywords that start with 'V'. Issue #230.
    COBOL: Recognize comments after tag or that start with '/'. Issue #231.
    HTML: Implement substyles for tags, attributes, and identifiers SCE_H_TAG, SCE_H_ATTRIBUTE, SCE_HJ_WORD, SCE_HJA_WORD, SCE_HB_WORD, SCE_HP_WORD, SCE_HPHP_WORD.
    HTML: Implement context-sensitive attributes. "tag.attribute" matches "attribute" only inside "tag".
    HTML: Match standard handling of comments. Issue #232.
    Lua: Implement substyles for identifiers SCE_LUA_IDENTIFIER.
    Ruby: Allow non-ASCII here-doc delimiters. Issue #234.
    Ruby: Allow modifier if, unless, while and until after heredoc delimiter. Issue #236.
    Rust: Recognize raw identifiers. Issue #239, Pull request #240.

### CODE REVIEW

**Comment by chcg** [comment]
@donho @ArkadiuszMichalski 

With this update all files are opened as language Go. Need to be investigated. Any hint appreciated.

**Comment by chcg** [comment]
Just happens if file is opened via context menu and therefore WM_COPYDATA with COPYDATA_PARAMS is used at Notepad_plus::process()

**Comment by ozone10** [comment]
Maybe related to similar issues with JSON5 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13746 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13042

**Comment by chcg** [comment]
Could be. I'm testing with a portable version 8.5.6 update with this compilation but there is also an installation of N++ 8.5.6 available.

**Comment by donho** [comment]
> With this update all files are opened and autodetected as language Go but could be manually changed to the correct one. Need to be investigated. Any hint appreciated.

It can happen when the arguments are passed by `%ProgramFiles%\Notepad++\notepad++.exe` to (YOUR LAUNCHED) `whereever\notepad++.exe` and both notepad++.exe are not the same version.
Here is the detailed explanation:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13042#issuecomment-1416802964

**Pull request closed without merging**
