### PR TITLE
Update Chinese localization: fix a interface error(missed a "$" symbol)

### LINKED ISSUE #9588: there is a "$INT_REPLACE3" in search overview when you npp is in Chinese(zh_CN) , but English won't
### Description of the Issue

when you are doing some searches , the search overview will show `搜索 "colour" （0个文件中匹配到0次，总计查找$INT_REPLACE3）` to you, the " `$INT_REPLACE3` " is a strange part in this sentence. But when you are using English as your interface language, the search overview will be " `Search "colour" (0 hits in 0 files of 1 searched)` ". I hope that who can fix this issue.
**NOTE:** "Colour" is a random word, this bug will reproduce when searching for any word.
### Steps to Reproduce the Issue

1. Set `Chinese Simplified` as your interface language.
2. Click `Ctrl+F`
3. Input a random word
4. Click `在当前文件中查找（Find All in current Document）` or `查找所有打开文件(Find All in Opened Documents)`

### Expected Behavior

The software will show me the sentence "0个文件中匹配到0次，总计查找了1次"
### Actual Behavior

The software shows me the sentence "0个文件中匹配到0次，总计查找$INT_REPLACE3"
### Debug Information

Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7600.0
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

图片

### PR DESCRIPTION
**Pull request by xiaopangju**
@popcorner Can you help me review this? Thanks!
This PR can fix #9588

### CODE REVIEW

**Review by popcorner — APPROVED** [review]

**Comment by donho** [comment]
Thank you for the update. Could you adapt the diff of english.xml (v7.9.4 vs v7.9.3):
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9613

and confirm me when it's done? Thank you.

**Comment by xiaopangju** [comment]
> Thank you for the update. Could you adapt the diff of english.xml (v7.9.4 vs v7.9.3):
> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9613
> 
> and confirm me when it's done? Thank you.

Hello, I submit this pr only to fix this interface error. I may not have time to translate all the newly added English texts.

**Comment by popcorner** [comment]
> Hello, I submit this pr only to fix this interface error. I may not have time to translate all the newly added English texts.

这样的话那剩下的我来翻译好了^_^可以吧？

**Comment by xiaopangju** [comment]
> > Hello, I submit this pr only to fix this interface error. I may not have time to translate all the newly added English texts.
> 
> 这样的话那剩下的我来翻译好了^_^可以吧？

谢谢大佬!

**Comment by xiaopangju** [comment]
@donho Although I don't have time to translate the newly added English texts, @popcorner is willing to translate all the newly added English texts.

**Comment by xiaopangju** [comment]
> > Hello, I submit this pr only to fix this interface error. I may not have time to translate all the newly added English texts.
> 
> 这样的话那剩下的我来翻译好了^_^可以吧？

我可以邀请你加入我的组织（xiaopangjutranslation），然后直接在我修复界面显示问题的基础上继续翻译吗？

**Comment by xiaopangju** [comment]
> > Hello, I submit this pr only to fix this interface error. I may not have time to translate all the newly added English texts.
> 
> 这样的话那剩下的我来翻译好了^_^可以吧？

作者已经合并了，我收回我说的想要邀请你进我自己创建的github组织一起翻译的话^^
希望您能把这个软件翻译得更好^^

**Pull request closed without merging**
